ParabolInc/parabol

README.md
There's a typo in your README @jordanh :)
=> Fix link to Action's waffle.io board

src/client/client.js, src/server/utils/getCashaySchema.js
@mattkrick see: https://github.com/mattkrick/cashay/pull/67
I couldn't find a good way to put the loader directly into the webpack config in a way that would allow us to sometimes exit, sometimes not. And, I certainly couldn't find a way to accomplish what we wanted without adding a param (unless we had two separate implementations of `getCashaySchema.js`, ick!)
Look ok to you?
=> Uses new cashay-loader signature to stop rethink when we want

package.json, src/client/client.js, webpack/webpack.config.dev.js
- fix for rethinkdb terminating early during `npm run dev`
- reintroduction of -p flag for `npm build:client`
=> Build fixes

package.json, src/server/utils/getCashaySchema.js
@mattkrick: I guess more than a tweak. Note `exitRethink` -> `stopRethink`. Allows build to complete and exit.
Cosmetically, I'd like to reserve the `deploy` command to possibly actually deploy the app one day. Hence, rename to put `client-min` behind `build:`.
=> rename deploy:client -> build:client-min; fix to stop rethink

package.json, src/universal/decorators/loginWithToken/loginWithToken.js, src/universal/modules/landing/containers/Landing/LandingContainer.js, src/universal/modules/notifications/ducks/notifications.js, src/universal/redux/getAuthedUser.js
Problems:
- `loginWithToken` was sending `getCurrentUser` to the server when we wanted it to only look locally
- `notifications` had an impure reducer (`++nid`)
- `LandingContainer` duplicated `loginWithToken` logic
cleaner code, fewer lines, & fixes all 3 problems!
fixes #104
=> Fix for #104

src/universal/modules/invitation/containers/Invitation/Invitation.js
After user testing a bit here at August, found that applying mutation caused
props to update, and invitation to double process. This prevents it.
=> Fix for double accept.

src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js, src/universal/modules/meeting/ducks/__tests__/meetingDuck-tests.js, src/universal/modules/meeting/ducks/meetingDuck.js
This new `RESET` action isn't even _really_ necessary. As the user params change, the subs would change and the `CREATE_MEMBERS` action would overwrite the members array in state. But, the reset action cleans up some global state if we have the opportunity to.
Will close #170.
Also included:
- Cleanup of unused action `SET_LOCAL_PHASE`
- Unit tests!
Note: will be merged back to `team-dash`.
GTG?
=> Added meetingDuck reset state action, cleanup, and unit tests

src/universal/modules/teamDashboard/components/TeamProjectCard/TeamProjectCard.js
Mad props to @atannus for spotting that `redux-form` v6.0.2 was no longer providing the focus action creator as a prop.
Here we're using the action creator from the module.
=> Using action creator, not prop

package.json, src/client/client.js, src/client/makeStore.js, yarn.lock
N.B. still requires raven to be included from a CDN or elsewhere.
Included as an aid for #437 and future issues.
=> Added redux-raven-middleware

src/universal/decorators/requireAuthAndRole/requireAuthAndRole.js, src/universal/modules/admin/containers/Impersonate/Impersonate.js
@mattkrick just a little somethin' somethin' that was bothering me.
I thought we could do without all the toasts when impersonating a user. I added some optional args to the `requireAuthAndRole` decorator.
If you like it, go ahead and merge it.
=> Expanded requireAuthAndRole with optional args

src/universal/containers/EditingStatus/EditingStatusContainer.js, src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js, src/universal/utils/fromNow.js
This PR is meant to address https://github.com/ParabolInc/action/issues/258
What it should do:
The timestamp displayed on the card should update:
- in 30 seconds if it is less than 1 minute old
- in 1 minute if (1 min < age < 1 hour)
- in 1 hour if (1 hour < age < 1 day)
and so on...
@mattkrick @ackernaut @jordanh
=> OutcomeCard timestamp refresh

src/universal/modules/meeting/components/RejoinFacilitatorButton/RejoinFacilitatorButton.js
@jordanh @mattkrick @ackernaut Now the cursor displays as a pointer when you hover over the rejoin facilitator button 👆
=> Rejoin facilitator button cursor is pointer

.babelrc, package.json, src/server/billing/helpers/adjustUserCount.js, src/server/graphql/models/Action/actionQuery.js, src/server/graphql/models/IntranetJobs/intranetJobsQuery.js, src/server/graphql/models/Invitation/inviteTeamMembers/getInviterInfoAndTeamName.js, src/server/graphql/models/Invoice/invoiceQuery.js, src/server/graphql/models/Meeting/meetingSchema.js, src/server/graphql/models/Organization/addOrg/createNewOrg.js, src/server/graphql/models/Organization/organizationMutation.js, src/server/graphql/models/Organization/organizationQuery.js, src/server/graphql/models/Organization/organizationSchema.js, src/server/graphql/models/Organization/rejectOrgApproval/removeOrgApprovalAndNotification.js, src/server/graphql/models/Project/projectQuery.js, src/server/graphql/models/Team/createFirstTeam/addSeedProjects.js, src/server/graphql/models/Team/teamSchema.js, src/server/graphql/models/TeamMember/teamMemberSchema.js, src/server/graphql/models/User/userSchema.js, src/server/utils/authorization.js, src/server/worker.js, yarn.lock
- fixes raven warning on server
- makes sure any call to rethinkdb returns a promise (regression from fixing the unnecessary await lint rule)
- goes back to plain jane babelrc for dev so we can work on safari 9 (i guess the extra work isn't _that_ slow, but it was nice debugging without a new closure for every use of `const` and `await`. someday....)
=> ensure graphql gets a promise back from newly non-awaited calls

src/universal/components/Button/Button.js, src/universal/components/Dashboard/DashHeaderInfo.js, src/universal/components/DashboardAvatars/DashboardAvatars.js, src/universal/components/Editable/Editable.js, src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js, src/universal/modules/teamDashboard/components/EditTeamName/EditTeamName.js, src/universal/modules/teamDashboard/components/Team/Team.js, src/universal/modules/userDashboard/components/SettingsHeader/SettingsHeader.js, src/universal/modules/userDashboard/components/UserDashMain/UserDashMain.js, src/universal/styles/ui.js
- Adds a raised button to *Meeting Lobby*
- New *Team Settings* flat button is over by the team avatars
- Main dash header title is larger
- My Dashboard header, moved the Date and Easter Egg to the far right
[record.it](http://recordit.co/M3lXqqwOVh)
=> Team dash header (Lobby button! Team settings! and more!)

circle.yml
let's force add the build directory instead of ignoring it. this should clean up our git status immensely while working.
=> force add build directory

src/server/database/migrate.js
there was an error that was caused by a lack of regen runtime, which is caused because we transpile to ES5 for prod. until we stop doing that, we either need to include (babel-polyfill) it or ditch async/await. i chose the latter for migrate.js
=> fix staging goof

src/server/graphql/models/Team/createFirstTeam/createFirstTeam.js
testing the broken condition:
with this patch, the delay occurs between step 2 and 3. this makes for a slower welcome wizard, but safer.
=> welcome wizard race condition Fix #914

src/universal/components/DashboardWrapper/DashboardWrapper.js, src/universal/modules/newTeam/components/NewTeamForm/NewTeamForm.js, src/universal/modules/newTeam/containers/NewTeamForm/NewTeamFormContainer.js
it
the first bug was caused by `shouldValidate` (see #1132)
the second bug was likely caused when I got rid of NewTeam.js i think this happened shortly after the new router switch.
=> fix #1131 new team form bugs

src/server/database/migrations/20170714185201-removeEmptyContent.js, src/server/graphql/models/Project/projectMutation.js, src/server/graphql/models/Team/endMeeting/endMeeting.js, src/universal/validation/legitify.js, src/universal/validation/makeProjectSchema.js
This nukes bad records in the DB & makes it so no more bad records can enter the DB.
fixes #1243 fixes #1228
Problem:
The draft-js raw state had an empty block array. So, when you go to retrieve a block like `.first()` it will return undefined instead of an object. We could fix the rehydration function to always give it at least 1 block, but then the state on the client doesn't match what's in the DB, plus we'd have to be careful every time we did a rehydrate.
the simpler solution is to ensure that the blocks array has at least 1 block before writing it to the DB.
=> fix getKey

src/server/graphql/mutations/addGitHubRepo.js, src/server/graphql/types/GitHubIntegration.js
@jordanh 
since we haven't pushed github to master, i'd like to sneak this guy in. very simple, very basic. but if i can get it in now it means i don't have to write a migration later.
=> add an adminUserId to every github integration

.github/ISSUE_TEMPLATE.md
It bothers me to see OSX in locations when it should be macOS for anything modern.
=> Quick update to ISSUE_TEMPLATE.md for OS Naming conventions

src/server/graphql/models/Team/notifySlack/notifySlack.js, src/server/safeMutations/addProviderGitHub.js, src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js
=> Epic6.5 hotfix

src/universal/modules/email/components/QuickStats/QuickStats.js, src/universal/modules/email/components/SummaryEmail/SummaryEmail.js, src/universal/modules/email/components/SummaryHeader/SummaryHeader.js
=> Epic6.5 Summary Email Sprint (TA)

src/universal/components/ProjectIntegrationLink.js, src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js, src/universal/modules/menu/components/MenuItem/MenuItem.js, src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js, src/universal/modules/outcomeCard/components/OutcomeCardFooterButton/OutcomeCardFooterButton.js
This PR addresses: #1198 (tab + enter to open menu instead of advance meeting)
**NOTE**: This is just a patch to slightly improve the experience. There is still a number of menu behaviors that can be improved and this may need deeper refactoring and some more fluency on the menu HOC pattern. _I would save this work for perhaps a Sprint No. 2 or defer as the menu improvements are low priority overall_.
**Does Address**:
- If a user tabs to a card button and instinctively presses `enter` they get a menu instead of advancing the meeting. However, they have to use the mouse for further interaction (see note below).
- A user can tab into the GitHub link of an integrated card. Pressing `enter` will open the link in a new tab.
- A user will skip the avatar when tabbing through an integrated card …
=> Epic 6.5 Menu Sprint #1

src/server/emailSSR.js, src/universal/components/CreateCard/CreateCard.js, src/universal/modules/email/components/ContactUs/ContactUs.js, src/universal/modules/email/components/QuickStats/QuickStats.js, src/universal/modules/email/components/SummaryEmail/SummaryEmail.js, src/universal/modules/email/components/SummaryEmail/index.js, src/universal/modules/email/components/SummaryHeader/SummaryHeader.js, src/universal/modules/meeting/components/AgendaShortcutHint/AgendaShortcutHint.js, src/universal/modules/meeting/components/CheckInControls/CheckInControls.js, src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.js, src/universal/modules/meeting/components/MeetingAgendaFirstCall/MeetingAgendaFirstCall.js, src/universal/modules/meeting/components/MeetingAgendaItems/MeetingAgendaItems.js, src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js, src/universal/modules/meeting/components/MeetingCheckin/MeetingCheckin.js, src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js, src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js, src/universal/modules/meeting/components/Sidebar/Sidebar.js, src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js, src/universal/modules/meeting/helpers/actionMeeting.js, src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js, src/universal/modules/userDashboard/helpers/getRallyLink.js, src/universal/styles/theme/labels.js, src/universal/styles/ui.js, src/universal/utils/constants.js, src/universal/utils/makeCalendarInvites.js
This PR addresses:
Note, the code:
- Uses constants for UI labels in more places.
- Refactors UI labels in some places.
- Cleans up unused constants for UI labels.
_Oh yeah, and Rally added_: [JUST DO IT](https://youtu.be/ZXsQAXx_ao0)
=> Epic 6.5 Meeting Sprint (TA)

src/universal/components/Button/Button.js, src/universal/components/Tooltip/ControlledTooltip.js, src/universal/components/Tooltip/HoverTooltip.js, src/universal/components/Tooltip/Tooltip.js, src/universal/modules/meeting/components/CopyShortLink/CopyShortLink.js, src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js
Alright, this should fix #1378. Following up here from the closed #1381.
I'm about to take a go at changing the feedback mechanism from changing the contents of the button to a tooltip modal. 
Test Plan
=> Epic7 meeting link copier

src/universal/modules/invoice/components/Invoice/Invoice.js, src/universal/modules/userDashboard/components/InvoiceRow/InvoiceRow.js
=> support invoices that are not upcoming or paid

src/universal/modules/meeting/helpers/handleRedirects.js, src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js
fix #490 
while in a meeting, if the facilitator advances with a participant is still typing, the participant advances with the facilitator, losing their work. This is frustrating for the participant.
It is not the job of the facilitator to wait for folks to finish typing.
It is not the job of the participant to alert the facilitator that the are still typing.
The solution is to not advanced with the facilitator if they're still typing.
To detect typing, we see if they have a contenteditable div active.
There are better forms of detection, but for now this works perfectly (ie if i'm adding an agenda item it still advances me).
also fixes an little break in react 16.
=> Interrupting chicken

src/universal/components/Dashboard/DashModal.js, src/universal/components/EditorHelpModal/EditorHelpModal.js, src/universal/components/ProjectColumns/ProjectColumns.js, src/universal/containers/EditorHelpModalContainer/EditorHelpModalContainer.js, src/universal/modules/meeting/components/MeetingAgendaItems/MeetingAgendaItems.js, src/universal/modules/userDashboard/components/UserDashMain/UserDashMain.js
This is a first pass at a help modal for the editor. See: #1343 
**Note**: Based off of `epic7` for latest…but this doesn’t have to ship with Epic 7.
**Behaviors**:
**Contexts (wherever there are editable cards)**:
=> Epic 8 or 8.5: Editor Help Modal v1 (ready to test and ship!)

src/universal/components/ProjectColumns/ProjectColumns.js, src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js, src/universal/modules/teamDashboard/components/ProjectColumn/ProjectColumn.js
=> add projects during updates phase

src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js, src/universal/utils/__tests__/parseEmailAddressList.test.js, src/universal/utils/parseEmailAddressList.js
=> Epic8.5 1504

src/universal/modules/dropdown/components/DropdownInput/DropdownInput.js, src/universal/modules/newTeam/NewTeam.js
=> add tier labels to orgs in new team form

src/universal/modules/meeting/components/HelpTextMyRound.js, src/universal/modules/meeting/components/MeetingUpdatesPrompt/MeetingUpdatesPrompt.js
Fixes #1595 for the following:
=> Solo Updates prompt conditions

src/server/graphql/mutations/moveMeeting.js, src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js, src/universal/mutations/EndMeetingMutation.js
Fixes #1660 and #1651 
To verify:
On `master` (failing) and `fix-agenda-nav-bounce` (passing) attempt the following:
- Run a meeting
- Move to the agenda
- Add several agenda items
- Navigate through all the items out-of-order that they're marked as completed
- Navigate back through the completed items
- Complete the meeting
- On `master`, expect to experience the bouncing. Also expect that once you complete the meeting, you see all the completed agenda items still on the team dashboard.
- On `fix-agenda-nav-bounce`, expect not to experience the bouncing; expect the intuitive behavior. Also expect that once you complete the meeting, the completed agenda items are gone from the team dashboard.
=> Move between completed agenda items without bouncing back

src/universal/components/Dashboard/DashLayout.js, src/universal/modules/meeting/components/MeetingLayout/MeetingLayout.js, src/universal/modules/teamDashboard/components/AgendaInput/AgendaInput.js, src/universal/modules/teamDashboard/components/AgendaInput/AgendaInputField.js, src/universal/modules/teamDashboard/components/AgendaItem/AgendaItem.js, src/universal/modules/teamDashboard/components/AgendaList/AgendaList.js, src/universal/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.js
=> Scroll to active agenda item

src/universal/components/LoadableMenu.js, src/universal/modules/menu/components/MenuItem/MenuItem.js, src/universal/modules/outcomeCard/components/AddSoftTeamMember.js, src/universal/modules/outcomeCard/components/OutcomeCardAssignMenu/OutcomeCardAssignMenu.js, src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js
=> Add label, better a11y to assignment menu

src/server/graphql/mutations/changeTaskTeam.js, src/server/graphql/mutations/createGitHubIssue.js, src/server/graphql/mutations/createTask.js, src/server/graphql/mutations/deleteTask.js, src/server/graphql/mutations/editTask.js, src/server/graphql/mutations/updateTask.js, src/server/graphql/resolvers.js, src/server/graphql/rootMutation.js, src/server/graphql/types/ChangeTaskTeamPayload.js, src/server/graphql/types/Task.js, src/server/graphql/types/TaskSubscriptionPayload.js, src/universal/components/PlainButton/PlainButton.js, src/universal/containers/GitHubReposMenuRoot/GitHubReposMenuRoot.js, src/universal/modules/menu/components/MenuItem/MenuItemWithShortcuts.js, src/universal/modules/outcomeCard/components/AddSoftTeamMember.js, src/universal/modules/outcomeCard/components/OutcomeCardAssignMenu/OutcomeCardAssignMenu.js, src/universal/modules/outcomeCard/components/OutcomeCardAssignMenu/OutcomeCardAssignTeamMenu.js, src/universal/modules/outcomeCard/components/OutcomeCardAssignTeamMenuRoot.js, src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js, src/universal/mutations/ChangeTaskTeamMutation.js, src/universal/mutations/UpdateTaskMutation.js, src/universal/subscriptions/TaskSubscription.js, src/universal/utils/draftjs/removeEntityKeepText.js, src/universal/utils/relay/findConnectionWithNodeId.js, src/universal/utils/relay/findNodeInConn.js, src/universal/utils/relay/getAllConnections.js, src/universal/utils/relay/safeRemoveNodeFromUnknownConn.js
fixes #1474 
BACKGROUND
Sometimes a user creates a card and later realizes it was better suited for another team. For example, taya creates a card during a product meeting, but the task belong in exco. this allows users to do that from the my dashboard view.
TEST
=> Change team menu

src/universal/components/Action/Action.js, src/universal/components/AuthPage/AuthPage.js, src/universal/components/ErrorAlert/ErrorAlert.js, src/universal/components/HorizontalSeparator/HorizontalSeparator.js, src/universal/components/InputField/InputField.js, src/universal/components/PlainButton/PlainButton.js, src/universal/components/ResetPasswordPage/ResetPassword.js, src/universal/components/ResetPasswordPage/ResetPasswordForm.js, src/universal/components/ResetPasswordPage/ResetPasswordPage.js, src/universal/components/SignUpPage/SignUpPage.js, src/universal/utils/constants.js
Fixes #1758.
Note that the "If you try to recover an account associated with 3rd party auth, the page complains at you" acceptance criteria is not currently met, since auth0 happily accepts a request to reset a password for a passwordless account. If we wanted to build this functionality, it would expand the scope of this work.
Testing:
- Check out the `password-recovery` branch locally
- Flip the `newSignIn` release flag to `true`
- Start the dev server
- Log out if you're already logged in
- Follow the link at the bottom of the new sign in page titled "Forgot your password?"
- Enter your email
- Check your email
- Open the email from auth0
- Reset your password using auth0's site
- Go back to your dev server
- Sign in successfully with your new credentials
=> Password recovery

src/server/graphql/queries/activeProOrgCount.js, src/server/graphql/rootQuery.js
Implements #1803 
type this:
```
query {
activeProUserCount
}
```
=> Add activeProOrgCount query, implements #1803

src/universal/modules/teamDashboard/containers/TeamColumns/TeamColumnsContainer.js
=> Make TeamDashboard filter case-insensitive

src/server/graphql/queries/helpers/countTiersForUserId.js
Counts the orgs for only which userId is a billing leader
=> trivial fix to tierProBillingLeaderCount

package.json, src/server/billing/stripeWebhookHandler.js, src/server/graphql/httpGraphQLHandler.js, src/server/integrations/handleGitHubWebhooks.js, src/server/server.js, src/server/socketHandlers/handleMessage.js, src/server/socketHandlers/wsGraphQLHandler.js, src/server/socketHandlers/wsRelaySubscribeHandler.js, src/server/utils/RethinkDataLoader.js, src/server/utils/sendGraphQLErrorResult.js, src/server/utils/sendSentryEvent.js, src/universal/Atmosphere.js, src/universal/utils/jwtFields.js, yarn.lock
Recently, we've been fighting too many fires.
We goof up, and instead of that goof up gracefully landing in sentry, the customer's screen goes white & there are no errors in the console.
This fixes that. Fixes #1774
There were a few things going wrong:
- The dataloader would throw an error if there was a missing foreign key. Albeit if a foreign key doesn't exist, it is 100% our fault, but the penalty for failure was too severe (blank screen of death). Now, we log it and send down the null value to the client. It's then up to the client to handle it gracefully
- The client was not handling errors gracefully for HTTP requests. This was my fault. I now pass whatever values, good or bad, into relay & then we can handle it with onError callbacks if need be.
- The client was not handling errors …
=> Stop the bork - gracefully handle server errors (Error PR 1 of 3)

src/universal/components/NewMeetingWithLocalState.js
Fixes #1918
Test: run `npm NODE_ENV=production WEBPACK_MIN=true webpack --config ./webpack/prod.babel.js` and do NOT see red warning about unexpected `[` token.
=> Fix incorrect flow type import

e2e/lib.js, e2e/scripts/drivers.js, e2e/tests/authentication.test.js, src/universal/components/SignInPage/SignInEmailPasswordForm.js, src/universal/components/SignUpPage/SignUpEmailPasswordForm.js, src/universal/releaseFlags.js, src/universal/utils/auth0Login.js, src/universal/utils/getWebAuth.js
This enables the new signin/signup/password recovery pages.
It also updates the end-to-end tests of those pages.
=> Enable new auth pages

src/server/graphql/mutations/login.js, src/server/graphql/mutations/setOrgUserRole.js, src/universal/redux/__tests__/authDuck.test.js, src/universal/redux/authDuck.js
See #1901.
This changes when we call segment identify to synchronize user traits with some of our integrated services upon each login. See the issue for more information on why we're doing this.
=> Fix segment identify #1901

src/universal/modules/meeting/components/MeetingAgendaFirstCall/MeetingAgendaFirstCall.js, src/universal/modules/meeting/components/MeetingAgendaItems/MeetingAgendaItems.js, src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js, src/universal/modules/meeting/components/MeetingCheckIn/MeetingCheckIn.js, src/universal/modules/meeting/components/MeetingHelpDialog/MeetingHelpDialog.js, src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js, src/universal/modules/meeting/components/MeetingMain/MeetingMain.js, src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js, src/universal/modules/meeting/components/RejoinFacilitatorButton/RejoinFacilitatorButton.js
This was easy enough to shim in (I know we will refactor Action Meetings soon) and have a look at the help content for action meetings. I can submit a separate PR to add to Retro and do it in a smarter way than this using `NewMeeting` and new phase views.
=> Adds help dialogs in action meeting

src/universal/components/MeetingPhaseWrapper.js, src/universal/components/NewMeeting.js, src/universal/components/NewMeetingSidebar.js, src/universal/components/RetroDiscussPhase.js, src/universal/components/RetroGroupPhase.js, src/universal/components/RetroReflectPhase/RetroReflectPhase.js, src/universal/components/RetroSidebarDiscussSection.js, src/universal/components/RetroVotePhase.js, src/universal/components/ScrollableBlock.js, src/universal/modules/teamDashboard/components/AgendaList/AgendaList.js, src/universal/styles/ui.js, src/universal/types/schema.flow.js
This fixes #2013 and improves phase view overflow.
The following Retro UI components can overflow in a small viewport:
- The left nav with many discussion topics
- The reflect phase with many cards
- The group phase with many cards
- The vote phase with many cards
- The reflections and/or the new tasks in the discuss phase
This component abstracts what we did on the team agenda list when it overflows. It adds a box-shadow at the top or bottom depending on where the overflow is with the idea that it helps indicate visually that there is more to scroll to.
We can improve the component to better listen and detect overflow on initial load and on changes, but I think it’s safe to try.
=> Scrollable block indicates overflow in retro meeting UI

src/server/graphql/mutations/endNewMeeting.js, src/server/graphql/mutations/helpers/notifySlack.js, src/server/graphql/mutations/startNewMeeting.js, src/server/graphql/types/RetrospectiveMeeting.js, src/universal/components/NewMeeting.js, src/universal/components/ReflectionCard/ReflectionCard.js, src/universal/components/RetroGroupPhase.js, src/universal/components/RetroReflectPhase/PhaseItemColumn.js, src/universal/components/RetroSidebarVoteSection.js, src/universal/modules/teamDashboard/components/TeamCallsToAction/TeamCallsToAction.js, src/universal/mutations/EndNewMeetingMutation.js, src/universal/mutations/UpdateReflectionLocationMutation.js, src/universal/subscriptions/TeamSubscription.js, src/universal/types/schema.flow.js, src/universal/utils/meetings/findFirstStageInPhase.js, src/universal/utils/meetings/getIsNavigable.js, src/universal/utils/meetings/isForwardProgress.js
=> small retro fixes

src/universal/components/ReflectionGroup/ReflectionGroupTitleEditor.js, src/universal/components/RetroGroupPhase.js, src/universal/components/RetroReflectPhase/RetroReflectPhase.js, src/universal/components/RetroSidebarDiscussSection.js, src/universal/components/RetroVotePhase.js, src/universal/modules/email/components/QuickStats/RetroQuickStats.js, src/universal/modules/email/components/RetroDiscussionTopics/RetroDiscussionTopics.js, src/universal/utils/constants.js, src/universal/utils/meetings/lookups.js, stories/MeetingComponents.stories.js
=> Updating group and topic labels (ready for review)

src/universal/mutations/UpdateTaskMutation.js
=> fix #1659 suppress task involvement notifications in meeting

src/universal/components/SocketHealthMonitor.js, src/universal/containers/Signout/signout.js, src/universal/mutations/toasts/popUpgradeAppToast.js, src/universal/utils/constants.js
TEST
- goto team dash
- change the version in the package.json
- in components/Team/Team.js, change `"Search Team Tasks & Agenda` to `"FOO"`
- save changes
- ctrl + c in the server terminal to stop the server (cannot trust piping!)
- `yarn dev` to restart the server
=> no logout on app upgrade

src/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.js
before this gets too crazy we should just figure out how to SSR the summary route so we don't have to construct megaqueries... but until then,
TEST
- start a retro, add 3 reflections, don't group them, give them all your votes, end the meeting
=> Fix retro email summary votes [BASE: false-no-ws]

src/server/graphql/mutations/helpers/addEntitiesToReflections.js, src/server/graphql/mutations/helpers/autoGroup/addLemmaToEntities.js, src/server/graphql/mutations/helpers/autoGroup/computeDistanceMatrix.js, src/server/graphql/mutations/helpers/autoGroup/getAllLemmasFromReflections.js, src/server/graphql/mutations/helpers/autoGroup/getSyntaxFromText.js, src/server/graphql/mutations/helpers/autoGroup/getTitleFromComputedGroup.js, src/server/graphql/mutations/helpers/autoGroup/groupReflections.js, src/server/graphql/mutations/helpers/autoGroup/sanitizeAnalyzedEntititesResponse.js, src/server/graphql/mutations/helpers/autoGroup/sortGroupedReflections.js, src/server/graphql/mutations/helpers/makeRetroGroupTitle.js, src/server/graphql/types/GoogleAnalyzedEntity.js, src/universal/components/NewMeetingCheckIn.js, src/universal/modules/meeting/components/CheckInControls/CheckInControls.js, src/universal/modules/meeting/components/MeetingCheckIn/MeetingCheckIn.js, src/universal/types/schema.flow.js
This improves grouping by supporting case insensitivity and grouping plurals & singulars.
Fixes #2063
TEST
=> Refine auto group

src/universal/Atmosphere.js
TEST
- open up debugger to websocket frames, navigate to team dash, hit refresh, notice a list of sent subscription requests
=> fix #2053 multiple subscriptions bug

src/universal/modules/email/components/Card/Card.js
fix #2034 
TEST
Honestly, not too sure how to reproduce the problem, but I've seen it crop up from time to time both locally & on sentry.
=> fix #2034 upgrade Card.js

jsconfig.json, package.json, src/universal/components/AnalyticsIdentifierRoot.js, src/universal/components/NewMeetingWithLocalState.js, src/universal/mutations/NavigateMeetingMutation.js, src/universal/utils/isInterruptingChickenPhase.js, src/universal/utils/isViewerTyping.js
TEST
- progress to the discussion phase of a retro meeting
- on 1 device, the non-facilitator start typing a task in the discussion phase
- on another device, the facilitator progresses the meeting
EXTRA (for devs)
=> fix #2100 retro interrupting chicken

src/server/graphql/mutations/helpers/addDefaultGroupTitles.js, src/server/graphql/mutations/setOrgUserRole.js
fixes #2174
- User A creates Org1, Team1, invites User B
- User B joins Team 1, invites User C (does not exist yet)
- User A promotes User B to billing leader in the org.
also fixes the bug mentioned here: https://github.com/ParabolInc/action/pull/2245#issuecomment-403149684
=> 2174 approve on promote [BASE: update-cc-modal]

.storybook/webpack.config.js, package.json, stories/AddReflectionButton.stories.js, stories/components/RelayStub.js, stories/components/StoryContainer.js, yarn.lock
storybook was broken in 3 fun ways:
it didn't support webpack 4
it didn't support our babel config
it didn't support relay
now it does! fixes #2260
TEST
=> add webpack 4 & relay support for storybook

src/server/graphql/mutations/startDraggingReflection.js, src/server/graphql/types/StartDraggingReflectionPayload.js, src/universal/components/PhaseItemMasonry.js, src/universal/components/ReflectionCard/DraggableReflectionCard.js, src/universal/components/ReflectionGroup/ReflectionGroup.js, src/universal/mutations/StartDraggingReflectionMutation.js, src/universal/mutations/UpdateDragLocationMutation.js, src/universal/types/schema.flow.js
TEST
Since this touches the draggable reflection logic, a general test of all dragging is needed. For example, multiple clients dragging in & out of modals.
- Have 3 cards, A is alone. B & C are grouped together. A is on the left: `|A|  |B,C|`
TEST 2
=> Staging dragging fix

src/universal/components/LoadableMenu.js, src/universal/components/Modal.js, src/universal/decorators/withToggledPortal.js, src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js
This is useful in meetings when you want to see if someone is still working on a card.
fixes #2130
TEST
-  [ ] click any menu on a task card (avatar, github octocat, status, due date) & the header changes to "editing". close the menu & it's no longer editing
=> mark card as editing when a menu is open

src/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.js, src/server/graphql/types/RetrospectiveMeetingMember.js
TEST
- run a retro, add a public & a private task card, complete the meeting,
=> hide private cards in meeting summary fixes #2286

src/universal/modules/newTeam/containers/NewTeamForm/NewTeamRoot.js, src/universal/modules/teamDashboard/components/Team/Team.js, src/universal/modules/teamDashboard/containers/TeamArchive/TeamArchiveRoot.js, src/universal/modules/userDashboard/components/UserDashRoot.js
on any route that starts with /team you could see 2 sets of ducks. now you only see 1.
still not perfect, but this'll all change when react 17 comes out, so it's not worth the investment for now
=> remove the double duck flash

package.json, src/client/cdnFallback.js, src/client/client.js, src/server/template.html, webpack/webpack.prod.config.js, yarn.lock
this supports clients that block our CDN.
here's how it works:
- the HTML template includes a fallback script that grabs the failed resource name & prefixes it with our static address
- every script in our generated HTML calls the fallback when it encounters an error
for scripts that are loaded after the initial bundle:
- we add a `catch` clause to the chunk loader. when a chunk fails, we try it again without the CDN.
TEST
=> CDN fallback

src/universal/components/ReflectionCard/ReflectionCard.tsx, src/universal/components/RetroReflectPhase/ChildrenCache.tsx, src/universal/components/RetroReflectPhase/ExpandedReflectionStack.tsx, src/universal/components/RetroReflectPhase/FLIPGrid.tsx
TEST - reflect phase modal
- pressing shift+enter resizes the layout
- resizes the window works
- press enter to blur the card & submit
- tab submits (#2385 says it didn't, but in my tests it does, so maybe i'm missing something)
=> add better resize detection & return handling

src/server/graphql/mutations/createReflection.js, src/universal/modules/email/components/RetroDiscussionTopics/RetroDiscussionTopic.js, src/universal/modules/summary/components/NewMeetingSummary.tsx, src/universal/mutations/EndNewMeetingMutation.js
=> Fixes #2372 prompt footer in summary

src/universal/components/ReflectionCard/DraggableReflectionCard.tsx, src/universal/components/ReflectionCard/ReflectionCard.tsx, src/universal/components/ReflectionFooter.js, src/universal/components/RetroDiscussPhase.tsx, src/universal/utils/multiplayerMasonry/initializeModalGrid.js
this sets the proper height of the cards in the grouping modal.
it also correct the user select & readOnly pieces.
i'm not sure how to test really because it's a little race conditiony. the only way i got it to test was during a hot reload the styles failed. so, i'll just merge
also, fix #2389 footer userSelect
=> fix #2388 grouping modal spacing

src/universal/components/BaseButton.js, src/universal/components/CardButton.js, src/universal/components/CreateAccountPage/CreateAccountEmailPasswordForm.js, src/universal/components/DueDateToggle.js, src/universal/components/FloatingActionButton.js, src/universal/components/MeetingHelp/HelpMenuToggle.js, src/universal/components/NewMeetingLobby.tsx, src/universal/components/PrimaryButton.js, src/universal/components/PrimaryFloatingActionButton.js, src/universal/components/RaisedButton.js, src/universal/components/ResetPasswordPage/ResetPasswordForm.js, src/universal/components/SignInPage/SignInEmailPasswordForm.js, src/universal/components/UpgradeSuccess.js, src/universal/modules/meeting/components/MeetingHelpDialog/MeetingHelpDialog.js, src/universal/modules/meeting/components/RejoinFacilitatorButton/RejoinFacilitatorButton.js, src/universal/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx, src/universal/modules/teamDashboard/components/TeamArchiveSqueeze/TeamArchiveSqueeze.js, src/universal/modules/userDashboard/components/CreditCardModal/UpgradeCreditCardForm.tsx, src/universal/modules/userDashboard/components/OrgPlanSqueeze/OrgPlanSqueeze.js, src/universal/styles/ui.js, src/universal/types/graphql.d.ts
- Fixes #2332 (Button API updated to handle elevation)
- Fixes #2258 (Card buttons updated to be flat)
- Buttons are flat unless an explicit `elevationHovered` and elevationResting` are passed as props
- The value for `elevationHovered` is using the default Material for pressed
- The pressed value is half of the distance between `evelationHovered` and `elevationResting` so that when pressing the button looks like it drops a little on the z axis
- Raised and primary buttons were updated to a consistent elevation
- Floating action buttons and primary floating action buttons were added
- Cards are using flat buttons
=> Button elevation, card buttons

src/server/graphql/queries/invoices.js
there were a couple problems with the paginated list of invoices.
first, stripe can sometimes create 2 invoices (first month + following month) at the exact same timestamp, so we needed another sort to ensure that the sort order is deterministic.
second, we weren't accounting for the upcoming invoice for `hasNextPage`.
TEST
=> fix the last page of invoices listed under org

src/universal/components/EditorHelpModal/EditorHelpModal.js
=> fix #2454 OS-specific keys in task editor help menu

src/server/graphql/mutations/downgradeToPersonal.ts, src/server/graphql/rootMutation.js, src/server/graphql/types/DowngradeToPersonalPayload.ts, src/server/graphql/types/OrganizationSubscriptionPayload.js, src/server/graphql/types/TeamSubscriptionPayload.js, src/server/utils/alreadyMutatedErrors.js, src/universal/types/graphql.d.ts
fixes #2123
you can now run a downgrade mutation from the admin panel.
out of scope, but still necessary:
- allowing users to downgrade themselves
- showing ex-pro users their past invoices
TEST
=> create downgrade mutation

src/universal/components/ReflectionEditorWrapperForEmail.js, src/universal/components/TaskEditor/TruncatedEllipsis.tsx, src/universal/components/TaskEditor/decorators.js, src/universal/modules/email/components/Card/Card.js, src/universal/utils/draftjs/truncateCard.js
TEST
- start a retro, write a long reflection, go to discuss phase, write a long task
fixes #2497
=> fix #2497 add expandable ellipsis to draft-js entities

src/universal/Atmosphere.js, src/universal/components/ReflectionGroup/ReflectionGroup.tsx, src/universal/components/ReflectionGroupVoting.tsx, src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx, src/universal/components/RetroReflectPhase/ReflectionStack.tsx, src/universal/mutations/VoteForReflectionGroupMutation.js
=> clean up completed phases

package.json, src/server/graphql/mutations/login.js, src/universal/components/AnalyticsIdentifier.tsx, src/universal/components/AuthenticationPage.tsx, src/universal/components/OAuthRedirect.tsx, src/universal/mutations/LoginMutation.ts, yarn.lock
TEST
- be logged out, don't use adblockers, run a demo, & create an account from the demo summary
=> add segmentId to login payloads

src/server/database/migrations/20180509162156-addFreeRetros.js, src/universal/components/AuthenticationPage.tsx, src/universal/components/MasonryCSSGrid.tsx, src/universal/components/OAuthRedirect.tsx, src/universal/components/RetroReflectPhase/ExpandedReflectionStack.tsx, src/universal/components/StandardHubUserMenu.js, src/universal/components/TimelineEventJoinedParabol.tsx, src/universal/decorators/requireAuthAndRole/requireAuthAndRole.js, src/universal/modules/userDashboard/components/SettingsHeader/SettingsHeader.js, src/universal/modules/userDashboard/components/UserDashboard/UserDashboard.js, src/universal/modules/userDashboard/components/UserProfile.tsx, src/universal/modules/userDashboard/components/UserProfileRoot.tsx, src/universal/modules/userDashboard/components/UserSettingsWrapper/UserSettingsWrapper.js, src/universal/utils/constants.js, src/universal/utils/getAnonymousId.ts
TEST
- fix analytics.user missing (no need to test)
- turn history.push into history.replace for login routes
- use native ResizeObserver (the only errors happened on Chrome, and Chrome offers a native implementation, so we'll try using that)
fix #2615 
fix #2608
fix #2604
fix #2461
=> rename settings to profile

src/universal/components/PhaseItemMasonry.tsx, src/universal/components/RetroGroupPhase.tsx, src/universal/components/RetroReflectPhase/PhaseItemEditor.tsx, src/universal/components/RetroReflectPhase/RetroReflectPhase.tsx, src/universal/components/RetroVotePhase.tsx
=> fix #2601 improve phase completion logic

src/universal/modules/demo/ClientGraphQLServer.ts
fix #2663
not sure about repro. my guess is the user deleted a task before the bot had a chance to call update on it.
merging immediately due to size & scope.
=> fix #2663 no agendaId for demo bot if human deletes task

src/server/demoEntityHandler.ts, src/server/graphql/mutations/helpers/addEntitiesToReflections.js, src/types/generics.ts, src/universal/utils/promiseAllPartial.ts
=> don't send sentry error when google nlp fails due to unsupported lang

package.json, src/universal/Atmosphere.ts, src/universal/components/DashboardRoot.tsx, src/universal/components/MeetingDashAlert/MeetingDashAlert.js, src/universal/components/QueryRenderer/QueryRenderer.js, yarn.lock
fix #2700
issues found:
- code in the DashAlert would fail if the component unmounted after the store was cleared
- MyTimelineRoot has a ttl but did not have any subscriptions, which caused a queryFetcher to never get disposed of. Fixed by registering all queries with a TTL, subscriptions or not.
additional fixes:
- i brought back aggressive query caching. this means you can navigate around the site & if you go back to a page in a reasonable amount of time (5 minutes) then you won't need to requery (since the subscriptions are still active & populating the new stuff). this should make the site feel a lot faster when clicking around.
TEST
- open devtools>network>websocket frames
- go to timeline, tasks, a team, another team
=> fix registerQuery logic

src/universal/components/TaskEditor/TaskEditor.js
=> submit Task on Enter fix #2684

src/server/graphql/types/Organization.js, src/server/utils/RethinkDataLoader.js
=> support superuser get teams for org fix #2707

src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx, src/universal/styles/paletteV2.ts
=> Fixes #2781 prompt indention, highlight arrow

package.json, src/universal/components/AndroidEditorFallback.tsx, src/universal/components/ReflectionEditorWrapper.js, src/universal/components/RetroReflectPhase/PhaseItemEditor.tsx, src/universal/components/TaskEditor/TaskEditor.js, src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js, src/universal/styles/theme/globalStyles.js, src/universal/utils/draftjs/isAndroid.ts, src/universal/utils/draftjs/isRichDraft.ts, yarn.lock
TEST
tip: edit the return value of `isAndroid.ts` to test
=> add android fallback for draft-js

src/server/graphql/mutations/inviteToTeam.ts, src/universal/modules/email/containers/TeamInvite/TeamInvite.js
- Note: accepting an invite to a team with an active meeting automatically redirects to the meeting, so I kept the condition simple (without any consideration for time e.g. within the last hour). Once we update the redirect logic and work on more async meetings, we can implement the timing aspect of it.
=> #2837 email invite with active meeting copy, CTA

src/server/graphql/isQueryAllowed.ts, src/types/modules.d.ts, src/universal/Atmosphere.ts
this only affects development. everything in production stays the same.
on the client, this sends the full query string instead of a persisted documentId.
on the server, it accepts full length queries.
=> remove need for calling postdeploy in dev

packages/client/components/NullableTask/NullableTask.tsx, packages/client/containers/TaskCard/DraggableTask.tsx, packages/server/graphql/mutations/updateTask.ts, yarn.lock
Added in 3 safety checks:
TEST
EXTRA CREDIT
```
r.db('actionDevelopment').table('Task')
.get('EDiJQdzStc')
.update({content: '{"blocks":[],"entityMap":{}}'})
```
=> Hotfix update task [base: service-worker-for-real]

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx, packages/client/modules/email/components/SummaryEmail/SummaryEmailScheduleCalendar.tsx
Fixes for #2907 probably got lost in a merge somewhere.
=> adds changes from PR #3042

CHANGELOG.md, lerna.json, package.json, packages/cypress/package.json, packages/server/package.json, packages/server/utils/sendToSentry.ts
Only 50 files changed on the server between v3.15.0 and v3.16.0, which is when the memory leak was introduced.
After some research, it looks like sentry is guilty of having a memory leak built in, and v3.16.0 fixed a bug in our sentry implementation to make it correctly load tags.
I'm undoing that bugfix to see if that fixes the problem.
=> Hotfix mem leak

packages/client/components/MeetingContent.tsx, packages/client/components/MeetingHeaderAndPhase.tsx, packages/client/components/PhaseWrapper.tsx, packages/client/modules/demo/initBotScript.ts
there's a bug where the discuss task column doesn't scroll. this fixes that + smoothes out the demo animations during grouping. 
TEST
=> fix group demo animations & discuss overflow

packages/server/billing/helpers/adjustUserCount.ts, packages/server/database/types/InvoiceItemHook.ts, packages/server/graphql/intranetSchema/mutations/stripeUpdateInvoiceItem.ts, packages/server/graphql/types/InvoiceLineItemDetails.ts
fixes #3229 by searching for invoices within 3 seconds of the time that the invoice item was created.
=> add tolerance to matching hooks to user count events

packages/client/components/SwipeableDashSidebar.tsx
Still can't reproduce this, so I'm flying blind, but it would make sense that this would fix #3120  
TEST
=> show body scroll on sidebar unmount

packages/server/graphql/mutations/updateAgendaItem.ts
=> Fix 3276 agenda dnd during retro

packages/client/components/ActionMeetingAgendaItems.tsx, packages/client/components/ActionMeetingFirstCall.tsx, packages/client/components/ActionMeetingLastCall.tsx, packages/client/components/MeetingSubnavItem.tsx, packages/client/components/NewMeetingSidebarPhaseListItem.tsx, packages/client/modules/teamDashboard/components/AgendaInput/AgendaInput.tsx, packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx, packages/client/types/graphql.ts
=> Meeting sidebar updates

packages/client/components/Dashboard/DashModal.tsx, packages/client/components/EditableAvatar/EditableAvatar.tsx, packages/client/components/LoadableModalAbstract.tsx, packages/client/components/MeetingArea.tsx, packages/client/components/MeetingHelp/HelpMenuToggle.tsx, packages/client/components/ReflectionCard/ReflectionCardDeleteButton.tsx, packages/client/components/RetroReflectPhase/ExpandedReflectionStack.tsx, packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx, packages/client/components/RetroReflectPhase/StageTimerDisplayGauge.tsx, packages/client/components/StaticSidebar.tsx, packages/client/components/TeamInvitationMeetingAbstract.tsx, packages/client/components/Tooltip/Tooltip.js, packages/client/hooks/useMenuPortal.tsx, packages/client/hooks/useModalPortal.tsx, packages/client/hooks/useTooltipPortal.tsx, packages/client/modules/meeting/components/MeetingControlBar/MeetingFacilitatorBar.tsx, packages/client/modules/meeting/components/RejoinFacilitatorButton/RejoinFacilitatorButton.tsx, packages/client/modules/teamDashboard/components/AgendaAndTasks/AgendaAndTasks.tsx, packages/client/modules/userDashboard/components/OrgBilling/OrgBillingReassuranceQuote.tsx, packages/client/styles/elevation.ts, packages/client/types/constEnums.ts, yarn.lock
Fixes #3295 
Fixes #2772 
In a few cases there’s a difference between the visual elevation and the necessary z-index of the portal components since they sit on a different plane. Tooltips by spec are an elevation of 0 but must show above sidebars at 16 (invite button tooltip has to be above open agenda sidebar). Menus have a visual elevation of 8 but also must show above sidebars of 16 (user hub menu needs to open above mobile dash nav sidebar, change facilitator menu must show above mobile meeting left nav). Tooltips and menus are at a z-index of 24 like dialogs, but with the correct box-shadow or lack thereof.
~My recommendation is to use a simple formula `MD elevation * 100` to allow for collisions, because it would be confusing to have to override a component and bump it up or down 1 …
=> zIndex scrubbed

packages/client/components/ResetPasswordPage/ResetPasswordPage.tsx
Fix #2857 
- Go to forgot password form
- Submit an email address
- There’s a clear way to get back to the Sign In view
=> Fix 2857 back to sign in

packages/server/graphql/mutations/voteForReflectionGroup.ts
=> fix race condition where the first 2 votes come in too fast

packages/server/utils/authorization.ts
when an auth token is invalid, it's an empty object, not falsy.
live & learn.
TEST
=> fix #3404 - failed to fail on acceptTeamInvite

package.json
Following the [source-code](https://github.com/ParabolInc/action#source-code) docs in README, one would see the following:
```sh
➜  action git:(master) ✗ yarn quickstart                                       
yarn run v1.21.1
error Command "quickstart" not found 
```
This PR adds a top level `quickstart` command that just proxies it to the `packages/server` workspace.
Another option would be to add one extra `cd packages/server` to the docs, but that seems unnecessary.
=> docs(README): add top level quickstart command

packages/client/components/StageTimerControl.tsx, packages/client/components/StageTimerModalEditTimeEnd.tsx, packages/client/components/StageTimerModalEditTimeLimit.tsx, packages/client/components/StageTimerModalEndTime.tsx, packages/client/components/StageTimerModalTimeLimit.tsx, packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationRow.tsx, packages/client/types/constEnums.ts, packages/server/graphql/mutations/setStageTimer.ts
Fixes #3582
- The deadline notification is not being pushed to Slack, see issue #3619. We can fix that here or defer for backlog ranking.
=> Fix #3582 timebox to deadline label

packages/client/components/Action/Action.tsx, packages/client/components/AuthenticationPage.tsx, packages/client/components/DemoMeeting.tsx, packages/client/components/DemoSummary.tsx, packages/client/components/ResetPasswordPage/SetNewPassword.tsx, packages/client/components/VerifyEmail.tsx, packages/client/hooks/useCanonical.ts
fix #3578 
uses a rel=canonical for all public routes. this is useful because some links may point to e.g. /signin?foo=1 and we want the search engine to be sure that it knows /signin is the desired route.
=> use canoncial

packages/client/components/MeetingHelp/ActionMeetingAgendaItemsHelpMenu.tsx, packages/client/components/MeetingHelp/ActionMeetingFirstCallHelpMenu.tsx, packages/client/components/MeetingHelp/ActionMeetingLastCallHelpMenu.tsx, packages/client/components/MeetingHelp/ActionMeetingLobbyHelpMenu.tsx, packages/client/components/MeetingHelp/CheckInHelpMenu.tsx, packages/client/components/MeetingHelp/DiscussHelpMenu.tsx, packages/client/components/MeetingHelp/GroupHelpMenu.tsx, packages/client/components/MeetingHelp/ReflectHelpMenu.tsx, packages/client/components/MeetingHelp/UpdatesHelpMenu.tsx, packages/client/components/MeetingHelp/VoteHelpMenu.tsx, packages/client/components/NewMeetingHowToSteps.tsx, packages/client/modules/email/containers/TeamInvite/TeamInvite.tsx, packages/client/types/constEnums.ts
Fixes #3648 
The Learn More link in the help menu for each phase in a meeting opens to the correct URL and content anchor (e.g. [https://www.parabol.co/resources/retrospective-meetings#vote](https://www.parabol.co/resources/retrospective-meetings#vote))
The Retro and Check-in links work in the Invite email
=> Fix #3648 resource links

README.md, docker-compose.yml
Some people (✋) prefer to run db services in isolated containers to avoid "polluting" their system.
This PR:
- adds a simple `docker-compose.yml` file with `db` (rethinkdb) service 
- adds a comment to README.md with an alternative to run rethinkdb inside a docker container
=> Dockerize rethinkdb

packages/server/createSSR.ts, packages/server/template.html
I want to merge our www.parabol.co and `action-production` instance configurations on Segment in order to eliminate the chance for error/cookie conflict. As part of this, I'd need to deliver GTM via Segment, vs. natively in the Segment template.
@mattkrick can we sneak this into v5.5.0?
=> remove Google Tag Manager

packages/server/utils/serveStatic.ts
This fixes the nondeterministic __dirname bug that occurs during HMR, as found by @NikAiyer!
TEST
=> don't trust __dirname

packages/client/modules/invoice/components/InvoiceLineItem/InvoiceLineItemDetails.tsx, packages/server/billing/helpers/adjustUserCount.ts, packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
We had a couple bugs with invoices. this fixes those.
fix #3803
TEST
=> ignore quantity changes for enterprise orgs

packages/cypress/cypress.json, packages/cypress/integration/demo_discuss.ts, packages/cypress/support/commands.ts
Goals:
- Establish pattern to remove `wait` wherever possible
- Establish pattern to create tests without modifying app code
Root cause:
- The reason the `wait` was required is because cypress was referencing an unmounted DOM node
- When the user clicks "create task", an optimistic task appears immediately so the UI feels snappy. It is then replaced by a persisted task that is editable. This is the cause for the unmount.
- Just like a human, cypress shouldn't know or care about optimistic updating or DOM nodes being unmounted. It should try to act like a human as much as possible
- So, we tell cypress to look for a task with a placeholder that is editable. The gotcha here is that _cypress only retries the last command before the assertion_. See …
=> remove waits from tests

packages/server/email/components/Header/Header.tsx, packages/server/email/components/NotificationSummaryEmail.tsx, packages/server/email/components/notificationSummaryCreator.tsx
=> fixes #3712 notif summary email copy

packages/client/components/DiscussionThreadList.tsx, packages/client/components/ThreadedItem.tsx, packages/client/components/ThreadedRepliesList.tsx, packages/client/modules/demo/getDemoEntities.ts, packages/cypress/cypress.json, packages/cypress/integration/demo_discuss.ts, packages/cypress/support/commands.ts
This PR does the following:
* adds a double click to demo tests to account for bottom control bar progress (will now double click to go to next phase)
* removes index checking from most discussion tests
* fixes the if statement in getDemoEntities to use lookup table when in Cypress mode
=> Fixes for Cypress tests and getDemoEntities

packages/server/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Removed SummaryEmailScheduleCalendar from SummarySheet.tsx
This removes the scheduling section from the end of meeting summary.
=> Removed GCal and Outlink calendar section from the summary email

README.md
When people first cloned the repo, they need to run ``yarn dev -i`` to properly get the DB setup and migration ready. After it's done one time, they don't need to include the ``-i`` option anymore to make it fast.
=> Update README.md to include -i option on "yarn dev"

packages/server/utils/getActiveDomainForOrgId.ts
fixup a bad query that happens whenever folks are added to an org
=> fix bad query in getActiveDomainForOrgId

packages/client/components/AnalyticsPage.tsx, packages/client/types/graphql.ts, packages/server/graphql/mutations/endNewMeeting.ts, packages/server/graphql/types/ActionMeeting.ts, packages/server/graphql/types/RetrospectiveMeeting.ts
=> Segment and Check-in fixes

packages/client/components/NewMeetingActionsCurrentMeetings.tsx
This PR attempts to address issue #3761. It does this by removing the check for meetingType when looking up all the active meetings in a team. 
Steps to check functionality:
=> New Meeting Notifications - Active Meetings

.vscode/launch.json, scripts/webpack/dev.client.config.js
Resolves #3979
These changes enable developers working on Parabol to locally debug client code in VSCode via a Chrome extension.
- makes a small change to client dev webpack
- adds a vscode launch config
=> setup config to enable client code debugging in vscode

scripts/webpack/dev.servers.config.js
Resolves #3958.
This PR changes the webpack configuration for the dev server so that source maps are created with deterministic line number references from target to source. This change enables developers working on Parabol to use the VSCode debugger tool to debug their local server with breakpoints.
~~Developer can debug staging server in VS Code through SSH tunneling~~ (don't need now)
=> fix source maps to enable debugging with breakpoints in vscode

packages/server/database/migrations/20200617000000-addMeetingIdIndexToAgendaItems.ts, packages/server/dataloader/foreignLoaderMakers.ts, packages/server/email/components/SummaryEmail/ExportToCSV.tsx, packages/server/graphql/types/ActionMeeting.ts
Implements #3870 (Add thread comments to CSV export).
*   [ ] After a retro meeting is ended, user can export a CSV summary:
*   [ ] For reflections, author should remain anonymous
*   [ ] Comments and replies are also exported
*   [ ] Replies have `replyTo` column to indicate which comment they are replied to
*   [ ] Supports anonymous comments
*   [ ] Supports anonymous replies 
*   [ ] Replies to tasks are included in the output
*   [ ] A Task that is a Reply has type Task
*   [ ] A Task that is a Reply has the discussionThread content of the threadParentId  
*   [ ] After an action meeting is ended, user can export a CSV summary:
*   [ ] Author status should indicate if the author has attended the meeting or not
*   [ ] Comments and replies are also exported and should correspond to …
=> #3870 Add thread comments to CSV export

packages/server/graphql/intranetSchema/intranetSchema.ts, packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts
This PR resolves issue #3951 
It adds a private schema enableSAMLForDomain.ts, and creates a graphql mutation for it, which adds a record to the SAML table with domain, url, metadata and cert fields.
=> Made a mutation for private schema enableSAMLForDomain

packages/client/lint-staged.config.js, packages/client/types/graphql.ts, packages/server/utils/updateGQLSchema.ts
This fixes #3991 .
@gql2ts/language-typescript has a customized [prettier](https://github.com/amount/gql2ts/blob/master/packages/language-typescript/src/typescriptPrettify.ts#L17-L24) that's different than our configurations. It's [this change](https://github.com/ParabolInc/parabol/commit/610a181a2cfacad1160e30649690448d854057ce#diff-b89bfe1397acd7451f86caf05f468827) that brings the issue. The fix is to overwrite the prettier configuration to match [ours](https://github.com/ParabolInc/parabol/blob/master/.prettierrc). So only intended change will be in the diff.
I made some random addition to the `NewMeeting` type:
then I run `yarn dev` as usual and observed the generated file of `client/types/graphql.ts`:
You can see only the intended diffs are there, as compared before you have diffs …
=> Customize prettier for gql2ts generated .ts file

packages/server/database/migrations/20200715162900-backfillIsActiveForCreatedTeamTimelineEvent.ts, packages/server/database/types/TimelineEventCreatedTeam.ts, packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
We only load [active](https://github.com/ParabolInc/parabol/blob/61b799f2469c2b347f63bf01c623e91ad0fe8d3f/packages/server/graphql/types/User.ts#L256) timeline events for a user. This bug was introduced by omitting the `isActive` field when writing the `TeamCreation` timeline event **directly** to the database.
=> Fix the bug where TeamCreation timeline events were missing

packages/client/components/DiscussPhaseReflectionGrid.tsx, packages/client/components/ReflectionCard/AddReactjiButton.tsx, packages/client/components/RetroDiscussPhase.tsx, packages/client/components/ThreadedCommentHeader.tsx, packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx, packages/client/modules/teamDashboard/components/AgendaInput/AgendaInput.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
I’ve been saving up a batch of patch fixes to correct design intent (styling, alignment, hierarchy, etc.):
=> A round of UI polish

packages/client/components/TimelinePriorityTasks.tsx
Timeline task header is currently sticky. When the user scrolls down, the header moves over the task. This only happens in Chrome, not in Safari. 
Removing the `sticky` position prevents this from happening.
=> Updated timeline task header

packages/client/modules/userDashboard/components/CreditCardModal/CreditCardForm.tsx, packages/client/modules/userDashboard/components/CreditCardModal/CreditCardModal.tsx, packages/client/modules/userDashboard/components/OrgBilling/OrgBilling.tsx, packages/client/modules/userDashboard/components/OrgBilling/OrgBillingCreditCardInfo.tsx, packages/client/modules/userDashboard/components/OrgBilling/OrgBillingUpgrade.tsx
This PR aims to resolved issue #3281.
It does this by turning the createFragmentContainer in OrgBilling.tsx into a createRefetchContainer, refetching the viewer query found in OrgBillingRoot.tsx when CC info is successfully updated/added to the page.
Users can:
=> Update OrgBillingView when CC is updated/added

packages/client/components/DueDateToggle.tsx, packages/client/components/EditingStatus/EditingStatus.tsx, packages/client/components/EditingStatus/EditingStatusText.tsx, packages/client/components/NullableTask/NullableTask.tsx, packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx, packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx, packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx
This PR aims to solve issue #2219: 
It adds disable option to TeamArchive outcome cards so that editing and date selection can be disabled.
To test:
=> Disabled editing and due date selection for archived cards

packages/server/database/types/DiscussStage.ts, packages/server/graphql/types/RetrospectiveMeeting.ts
When a user groups things & then ends the meeting without voting, the summary doesn't show the groups.
it probably should.
fixes the issue here: https://github.com/ParabolInc/parabol/issues/3622#issuecomment-648971359
=> Early end summary fix [base: share-templates]

packages/client/components/BottomControlBarReady.tsx, packages/client/components/BottomNavControl.tsx, packages/client/components/ThreadedCommentBase.tsx
Fixes for issues #3936 and #4046 
- Adjusted the width and added a wrapper so that long links don't cause problems
- Lightened the hover grey for the bottom nav control. The ready button text currently changes from grey to green. I imagine that we don't want to lighten the grey text on a white background so I've lightened the hover colour so that there's more of a contrast between the button, text and the thread. 
I think this helps but it doesn't necessarily make it super obvious that the user has clicked "Ready". Perhaps a green background with white text would be clearer?
Also, it may be difficult to test this branch until this installation error is resolved: #4077
=> Fix for long URL and lightened up the grey

packages/client/components/AnalyticsPage.tsx, packages/server/utils/segmentIo.ts
Closes #4116 
Should emit segment events in the form of:
```javascript
{
// ...
context: {
integrations: {
"Google Analytics": {
clientId: '1a94b8ed-f331-4f96-bd3a-77a3723aba70'
}
}
},
// ...
}
```
=> sets GA clientId to Segment anonymousId

packages/server/database/migrations/20200828161500-samlDomainAsId.ts, packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts
Issue #4031 
This PR converts make `enableSAMLForDomain` to an upsert instead of an insert for a domain.
=> Make enableSAMLForDomain an upsert

packages/server/graphql/intranetSchema/mutations/backupOrganization.ts
fixes bug where the export would include timeline events for teams that were not a part of the requested organization
=> exclude timeline events from uninteresting teams

docker-compose.yml, packages/server/graphql/intranetSchema/mutations/loginSAML.ts, packages/server/graphql/mutations/acceptTeamInvitation.ts, packages/server/graphql/mutations/addOrg.ts, packages/server/graphql/mutations/addTeam.ts, packages/server/graphql/mutations/verifyEmail.ts
This includes 3 fixes:
- If a SAML user logs in without the email attribute in the SAML response, it includes a good error message
- a SAML user may now be a superuser
- the superuser flag persists across token changes so you don't have to occasionally logout/login to get back to graphiql
@tianrunhe mind taking a look to make sure i'm not accidentally giving random folks super powers?
=> persist user rol, rol on SSO

packages/server/graphql/intranetSchema/mutations/connectSocket.ts
@nickoferrall found a good bug where the presence was broken.
this fixes #4143 
TEST
=> fix connect presence logic

.circleci/config.yml, .github/workflows/typecheck.yml, package.json, packages/server/package.json, yarn.lock
=> bump to node v14.10.1 and uWebSockets v17.6

nginx.conf.sigil
Resolve #4114
> /
create-account
signin
retrospective-demo
retrospective-demo/reflect
retrospective-demo/group
retrospective-demo/vote
retrospective-demo/discuss/1
retrospective-demo-summary
Note: I can't verify how good ^^this tester is, but the [official google tester](https://support.google.com/webmasters/answer/6062598?hl=en) requires extra finagling to verify that you own the app you're testing.
=> add robots.txt to nginx config

packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
=> remove trailing slash from intranet graphql url

packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx, packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
=> Fix for toggle timestamp bug

packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/modules/demo/initDB.ts, packages/client/mutations/handlers/handleAddTimelineEvent.ts
Bug fix following #4179.
The retro demo was crashing when the meeting ended as the demo wasn't handling timeline events.
=> Fix demo timeline event bug

nginx.conf.sigil
Fix #4160 
> @tiffanyhan on staging i get this:
User-agent: *
Disallow: /
Allow: /$
Allow: create-account
Allow: /signin
Allow: /retrospective-demo
should create-account have a slash prefix like the rest?
=> prefix /create-account rule

packages/client/components/DueDateToggle.tsx
This PR attempts to resolve issue #2194.
Users can:
* Tab to the due date toggle
* Use the keyboard to open (enter) and close the menu (escape)
=> Added tab access for due date

packages/client/components/Menu.tsx
=> Bug fix for first item in menu

.circleci/config.yml, packages/cypress/package.json
*   [ ] Cypress tests will run on master branch push
*   [ ] Cypress test result report will show on the "TESTS" tab on CircleCI
*   [ ] Cypress test artifacts (screenshots & videos) will show on "ARTIFACTS" tab on CircleCI
Example run: https://app.circleci.com/pipelines/github/ParabolInc/parabol/916/workflows/c214ed62-f0d9-492f-bbfe-f43b8f3f8a71/jobs/9809
=> Enabling Cypress test on master branch and fix Cypress test result report in CircleCI

packages/server/graphql/intranetSchema/mutations/backupOrganization.ts
@nickoferrall found a good bug where suggested actions could possibly include a `teamId` that lives on the personal org, but by protocol we don't always export the personal orgs
this filters out suggested actions that don't match the list of teamIds
=> filter out teamIds in backup Org

packages/server/database/migrations/20200930085630-isStarter.ts, packages/server/database/migrations/20200930135100-addMoreRetroTemplates.ts, packages/server/database/types/MeetingTemplate.ts, packages/server/graphql/queries/helpers/getPublicScoredTemplates.ts
@tianrunhe here's a start to the starter templates work.
since we want these templates to live in on-premise deployments, we probably want to always guarantee that the new templates are added via a migration.
Alternatively, we could have a template master file (e.g. retroTemplates.json) and guarantee that the master file always gets pushed to the DB. but tbh i think that's probably too much for now.
give it a test & if it looks good feel free to merge & then add the additional templates for @avivapinchas in a new migration
=> add isStarter to starter templates

packages/server/graphql/types/User.ts, packages/server/segmentFns/SegmentFnHubspot.js, packages/server/segmentFns/SegmentFnHubspot.ts
fixes #4086 
NOTE: 
after this hits production, we MUST update the lambda function in segment. we can't do it before because the lambda function requires this updated graphql schema or else it'll bork the rest of the request.
=> add meetingCount to user

packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
This PR attempts to solve the following issue: #4240 
If there are no stages present on the current phase, the onClick handler in AgendaItem gets returned with a undefined value, and the completion status gets set to false. Because the other phases do not have stages, when the user is on any other phase, clicking on agenda items becomes disabled and the items themselves are not shown as complete. In order to access the agenda items, you must click on Team Agenda first.
This PR fixes this issue by doing the following:
* adds phases variable to keep track of all phases in meeting, as well as the stages for agendaitems
* uses the stages from the agendaitems phase whenever the current phase is not agendaitems
Users can:
*   add new agenda item at Last Call, and navigate to it
*   see correct …
=> Check-in agenda state

package.json, scripts/codeshift/baseClientMutation.ts, scripts/codeshift/baseMutation.ts, scripts/codeshift/basePayload.ts, scripts/codeshift/codeshiftExplicitGql.ts, scripts/codeshift/newMutation.ts
fixes #3960
creating a new mutation isn't hard, but there's a lot of ugly boilerplate.
we should get paid to solve hard problems, not do mindless junk.
So, I made a CLI to generate the boilerplate.
we've got about 10 mutations to develop for the next sprint, so this should help.
How to use:
- call the CLI: e.g. `yarn newMutation addSmilesToFriends --subscription team`
How it works:
- this will generate a mutation called `addSmilesToFriends` and connect it to the Team subscription
- if this mutation is going to be hooked up to a subscription, you can add that with a `--subscription` (or `-s`) flag
- it will generate a mutation file on the client & server
- it will generate a mutation payload file on the server
- it will update the rootMutation & rootSubscription on the server
- it will …
=> Add CLI to create new mutations

packages/client/components/DropdownToggleV2.tsx, packages/client/components/ExpansionPanelSummary.tsx, packages/client/components/MenuToggleV2Text.tsx, packages/client/components/NewMeeting.tsx, packages/client/components/NewMeetingDropdown.tsx, packages/client/components/NewMeetingSettingsToggleCheckIn.tsx, packages/client/components/NewMeetingTeamPicker.tsx, packages/client/modules/meeting/components/RetroTemplatePicker.tsx
Fixes part of #4237 the other ideas will be on the backlog or iceboxed
=> New meeting view updates

packages/client/package.json, yarn.lock
Resolves #4290 
This one isn't practical to fully reproduce and test. But after fetching the latest patch of mediasoup-client, `https://github.com/ParabolInc/parabol/blob/mediasoup-edge/node_modules/mediasoup-client/lib/handlers/Chrome74.js#L4` should not have any rest parameter syntax in it. This syntax was tripping up edge 18 even though the code wasn't being executed, because the browser wasn't able to parse the syntax when it loaded javascripts. This update brings in a patch that fixes the issue by targeting an older ES version in mediasoup-client's tsconfig file.
**AC**
=> bump mediasoup-client package to ^3.6.21

packages/client/components/EstimatePhaseArea.tsx, packages/client/components/PokerCard.tsx, packages/client/components/PokerCardDeck.tsx, packages/client/hooks/usePokerDeckLeft.ts, packages/client/hooks/usePokerZIndexOverride.ts, packages/client/types/constEnums.ts, packages/client/utils/getBezierTimePercentGivenDistancePercent.ts, packages/client/utils/getColorLuminance.ts
=> Poker Estimate Phase: Card Deck

packages/server/graphql/mutations/addReflectTemplate.ts, packages/server/graphql/mutations/updateTemplateScope.ts
This fixes #4289 .
Root cause: field `isActive` has been deprecated in favor of `removedAt`.
Tests:
*   [ ] When copying an existing template, the prompts were copied over
*   [ ] After a copied template was created, user can add new prompts at will
=> Fix a bug which prevent reflect template to be copied over

packages/server/selfHostedHandler.ts, packages/server/server.dev.ts, packages/server/server.ts
@tiffanyhan here's how i'd handle that case of self-hosted content.
the static server has a lot of sharp edges to prevent folks from doing rude things.
if the customer is gonna be self-hosted, we don't really have to worry about that.
basically, we store everything that they upload in `/self-hosted`.
Then, when they want to retrieve that, we look in `/self-hosted`
If we don't find it, we send em a 404.
If we do, we pipe it to them (this has a slight overhead vs. sending the whole thing at once, but means it can support ver large files, if the need shall arise)
note: untested!
=> add-new-route

packages/client/Atmosphere.ts, packages/client/package.json, packages/server/package.json, yarn.lock
this PR adds a convention to convert nested objects into a file FormData schema.
Nested fields are store as dot separated values (e.g. `{query, 'payload.uploadables.file': File}`)
@tiffanyhan this cleans up a few of the rough edges for file uploads from the client. after migrating to the new uWS we can use this same convention to reconstruct the object on the server
=> support nested formdata pieces

packages/client/components/Facilitator.tsx, packages/client/mutations/RemoveReflectionMutation.ts, packages/client/utils/getTemplateList.ts
In sentry, we found 3 fatal client side bugs that are rooted in objects not existing in the client cache where they are guaranteed to exist. This leads me to believe the bug is in Relay, likely as a race condition in how it garbage collects. It is possible that the Relay team has fixed this bug in a newer version (even if they didn't know they fixed it or it wasn't in the changelog).
For this reason, we should up the priority of bumping the relay version. There will be breaking changes & we'll likely have to re-fork it again with our fixes that won't get accepted to their master branch.
@nickoferrall
=> Fixes fatal client-side bugs found in sentry

packages/server/graphql/httpGraphQLHandler.ts, packages/server/graphql/intranetGraphQLHandler.ts, packages/server/graphql/mutations/addTeam.ts, packages/server/package.json, packages/server/server.dev.ts, packages/server/server.ts, packages/server/socketHandlers/handleOpen.ts, packages/server/socketHandlers/handleUpgrade.ts, packages/server/sse/SSEConnectionHandler.ts, packages/server/utils/makeSentryRequest.ts, packages/server/utils/uwsGetIP.ts, yarn.lock
to handle multipart form data, we need to upgrade uWS.
There are a few breaking changes:
- uWS v18 no longer passes the `request` into the open handler. instead, it introduces an upgrade handler. Once auth has been performed in the upgrade handler, we can pass in the authToken & IP address to the open handler.
- it added a native way to get proxied IP addresses that always returns IPv6, so we use that instead. we'll need to verify this in prod to make sure we don't rate limit folks unfairly
=> upgrade uws

packages/client/components/EstimatePhaseDiscussionDrawer.tsx, packages/client/components/MeetingTopBar.tsx, packages/client/components/PokerActiveVoting.tsx, packages/client/components/PokerEstimateHeaderCardJira.tsx
@nickoferrall I made a few style changes without bothering you with the details. Merge into your `poker-drawer` branch if you accept!
=> Poker drawer styles

packages/client/components/EstimatePhaseArea.tsx, packages/client/components/PokerSidebarEstimateSection.tsx
=> Poker UI clean-up

packages/client/components/TimelineEventCard.tsx, packages/client/components/TimelineEventPokerComplete.tsx, packages/client/hooks/useMakeStageSummaries.ts, packages/client/types/graphql.ts, packages/server/email/components/SummaryEmail/ExportToCSV.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/MeetingMembersWithoutTasks.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/QuickStats.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx, packages/server/email/components/SummaryEmail/MeetingSummaryEmail/makePokerStats.ts, packages/server/graphql/types/JiraIssue.ts, packages/server/graphql/types/Story.ts, packages/server/graphql/types/Task.ts
This adds a summary + svg export for poker meetings.
limited to the first dimension. 
summary follows the same template as the other meetings just so we can get it out the door.
also fixes poker timeline events
=> add summary

packages/client/components/EditableText.tsx, packages/client/hooks/usePortal.tsx, packages/client/modules/meeting/components/PokerTemplateScaleDetails.tsx
=> fix escape handler, reset editingscaleId on exit

packages/client/types/graphql.ts, packages/server/graphql/mutations/addFeatureFlag.ts, packages/server/graphql/types/AddFeatureFlagPayload.ts
in order to facilitate adding a whole bunch of people to sprint poker, i needed to fix up the addFeatureFlag.
It now supports multiple email addresses and/or a single domain.
=> add batch support for feature flags

packages/client/modules/meeting/components/ScaleActions.tsx, packages/client/modules/meeting/components/ScaleDropdownMenuItem.tsx
Resolves #4457 
The bug is that when we clone a scale, we should not use the `teamId` for that scale. For pre-defined the scale, the `teamId` is _aGhostTeam_ so not matching with the viewer from server side, hence the request was rejected. The fix is to use the `teamId` for the dimension.
Tests:
=> Fix a bug where user cannot clone a public scale

packages/client/modules/meeting/components/AddPokerTemplateScaleValue.tsx, packages/client/modules/meeting/components/PokerTemplateScaleDetails.tsx, packages/client/modules/meeting/components/TemplateScaleValueItem.tsx
- The inline action to create items uses the same font-size as items; adds a hover state
- Adds a border to separate editable items from special items
- No hover for special items
- Yanks the HR in the header
=> scale editor ui refinements

packages/client/utils/getSSODomainFromEmail.ts, packages/server/database/migrations/20201222114114-samlDomains.ts, packages/server/database/rethinkDriver.ts, packages/server/database/types/SAML.ts, packages/server/graphql/intranetSchema/mutations/backupOrganization.ts, packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts, packages/server/graphql/intranetSchema/mutations/loginSAML.ts, packages/server/graphql/intranetSchema/types/EnableSAMLForDomainPayload.ts, packages/server/utils/SAMLHandler.ts, packages/server/utils/getSAMLURLFromEmail.ts
we've got a customer who's been waiting for this, so we gotta get this out.
This replaces #4440 
Big picture, this replaces SAML.domain with SAML.domains. It also adds the tld to all domains. that way, a company like "parabol" can have ownership over "prbl.in" and "parabol.co" and folks with either email can still log in via saml.
=> Enable multidomain SAML

packages/client/modules/meeting/components/AddPokerTemplateScaleValue.tsx, packages/client/modules/meeting/components/EditableTemplateScaleValueLabel.tsx, packages/client/modules/meeting/components/PokerTemplateScaleDetails.tsx, packages/client/modules/meeting/components/TemplateScaleValueItem.tsx, packages/client/modules/meeting/components/TemplateScaleValueList.tsx, packages/server/graphql/mutations/updatePokerTemplateScaleValue.ts
=> User can pick the color of special cards in scale editor

packages/client/components/NewMeeting.tsx
=> Do not scroll to the last meeting type in meeting lobby when selected team is changed

packages/server/package.json, scripts/migrate.js, scripts/webpack/toolbox.config.js
pulling from a fresh computer & i noticed `db:migrate` wasn't doing what it was supposed to do.
this fixes that
the problem was that require.main !== module for webpack assets. TBH i'm not sure how this worked before...
the fix was to remove migrate from the toolbox, that way it can be called by CLI & imported.
the DB pool was also not drained. this was because rethinkdb-ts-migrate was using a different version of the driver so we couldn't access that singleton. this was fixed by having that package drain the pool after migrating.
=> Fix migration

packages/client/components/JiraScopingSearchFilterMenu.tsx, packages/client/components/JiraScopingSearchInput.tsx, packages/client/components/JiraScopingSearchResults.tsx
Kinda fixes #4568.
The root cause of that issue is jira's own API sucks for searching.
This PR does the following:
- Adds a placeholder with example JQL when JQL search is turned on
- fixes a bug if someone turns on JQL too fast
- shows the mock loading bars when a search is in progress. this is a little more jerky than ideal, but we need to show folks that a search is pending
=> jira search touchups

packages/client/utils/relay/renderQuery.tsx
PR to help debug issue #4542.
This PR adds an event id to the render query so that the error is sent to Sentry.
I haven't been able to reproduce this bug after:
- Replicating the `AcceptTeamInvitationMutation` and accepting new joiners _many, many_ times
- Using CrossBrowserTesting to test Chrome, Edge and Firefox on Windows. I've tested those same browsers on a Mac as well as Safari and tested Chrome on my iPhone. 
- Throttling the network speed
It looks like the `tags` error that you mentioned Matt has only surfaced in the past [couple of weeks](https://sentry.io/organizations/parabol/discover/results/?environment=server&field=title&field=event.type&field=project&field=user.display&field=timestamp&name=All+Events&project=107196&query=Cannot+read+property+%27tags%27+of+undefined&sort=-tim …
=> Fix Sentry error message in renderQuery

README.md, packages/client/components/GroupingKanbanColumn.tsx
While working on issue #4531, I noticed two UI bugs that this PR resolves:
1. On Windows, removing a reflection from a reflection group can cause `ColumnScrollContainer` to show a vertical scrollbar
2. If a column has two sub columns and you remove all of the reflections from one of the sub columns, the column will automatically minimise. By adding a `minWidth`, the column will only expand or minimise when the user decides.
=> Retro columns fixes

packages/client/components/ViewerNotOnTeam.tsx, packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx
This PR _may_ resolve issue #4542. 
[This](https://sentry.io/organizations/parabol/issues/1641789488/?project=107196&query=level%3Afatal&statsPeriod=14d) and [this](https://sentry.io/organizations/parabol/issues/2109105416/?project=107196&query=level%3Afatal&statsPeriod=14d) Sentry issue suggest that the new joiner can infinitely bounce between the [ViewerNotOnTeam](https://github.com/ParabolInc/parabol/blob/91aff6e5c28bf344521db5701b0113401a2bc1dc/packages/client/components/ViewerNotOnTeam.tsx#L44) and the [MeetingSelector](https://github.com/ParabolInc/parabol/blob/01bfad9f162ef8f69c034a956bfbce9db3b1e9b9/packages/client/components/MeetingSelector.tsx#L35) components.
I haven't been able to reproduce the issue but I suspect that the `teamId` may be added to Relay's `authObj` before the …
=> Fix new joiner infinite loop 

packages/client/components/ReflectionGroup/ReflectionGroup.tsx
This PR fixes the collapsing stack issue where the reflection group doesn't land precisely in the target after collapsing the stack. This will hopefully resolve the remote reflection buggyness outlined in issue #4531.
=> Fix collapsing stack

docker/dev.yml, packages/server/postgres/Dockerfile, packages/server/postgres/extensions/install.sql, packages/server/postgres/extensions/postgres-json-schema/Makefile, packages/server/postgres/extensions/postgres-json-schema/postgres-json-schema--0.1.1.sql, packages/server/postgres/extensions/postgres-json-schema/postgres-json-schema.control
adding a pattern for postgres extensions, if the need should arrive.
jsonb validation might be good to have.
this uses json schema v4, which is pretty old.
so, i'm only setting it up in dev. we may not end up using it.
=> add example pg-json-schema extension in dev

packages/client/components/DiscussionThreadInput.tsx, packages/client/components/DiscussionThreadList.tsx, packages/client/components/TaskEditor/CommentEditor.tsx
=> Thread comments expanded

packages/client/mutations/handlers/handleRemovePokerTemplateDimension.ts, packages/client/mutations/handlers/handleRemoveReflectTemplatePrompt.ts
Fixes support issue reported [here](https://parabol.slack.com/archives/C4JAUUZ9P/p1613668617087100). Notice that the user reported that he could not rename a reflect but that was actually a side effect of not being able to remove it from front end. Hence the "Prompt not found" error. I looked at in our DB, from server side, the prompt was removed already.
Tests:
=> Fix the bug where reflect prompts and dimensions cannot be deleted

packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts
Makes the domain name used in SAML template dynamic.
closes #4679
=> (bug): make SAML Issuer and AssertionConsumerServiceURL dynamic

packages/client/components/ReflectionCard/ReflectionCard.tsx, packages/client/mutations/NavigateMeetingMutation.ts, packages/client/types/graphql.ts, packages/client/utils/constants.ts, packages/client/utils/smartGroup/groupReflections.ts, packages/server/graphql/mutations/helpers/handleCompletedStage.ts, packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts, packages/server/graphql/types/ReflectPhaseCompletePayload.ts
=> Sort the reflection goups on server side after REFLECT phase

packages/client/mutations/NavigateMeetingMutation.ts
`reflectionGroups` is `null` in non-retro meetings
=> Fix broken navigation

packages/client/components/ErrorComponent/ErrorComponent.tsx
This PR resolves issue #4751 
Rather than just showing a message asking the user to upgrade, I thought it'd be helpful to provide a link. 
We could write a bunch of conditionals ([like so](https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser)) to detect the browser and render a link based on the browser they're using. But browsers change, the conditionals may break and we would probably never know if Opera v8 is no longer showing the correct error message.
So I suggest that we show [this link](https://browser-update.org/update-browser.html) which explains why they should upgrade their browser & provides links to popular browsers.
=> Provide feedback for old browser bugs

packages/client/components/StageTimerModalEndTimeDate.tsx
fix #4766 
the first month available in the date picker should be the month of today, not the month of the suggested end time
=> fix end time start month

packages/server/billing/helpers/processInvoiceItemHook.ts, packages/server/graphql/mutations/acceptTeamInvitation.ts, packages/server/graphql/mutations/updatePokerScope.ts, packages/server/utils/RedisLock.ts
fix #4719 
I decided to go with a document lock instead of a nested in-place update.
Reason being, that nested update would have to operate on 1 update at a time, and in the case of a large select-all, it could actually take longer than using a lock.
Also updated the lock API so it's easier to just wait until we have a lock
TEST
=> atomic update poker scope

packages/client/components/DeckActivityAvatars.tsx, packages/client/components/EstimateDimensionColumn.tsx, packages/client/components/EstimatePhaseArea.tsx, packages/client/components/PokerCardDeck.tsx, packages/client/mutations/SetPokerSpectateMutation.ts, packages/client/subscriptions/MeetingSubscription.ts, packages/client/types/graphql.ts, packages/server/database/migrations/20210319135548-pokerSpectate.ts, packages/server/database/rethinkDriver.ts, packages/server/database/types/PokerMeetingMember.ts, packages/server/database/types/TeamMember.ts, packages/server/graphql/executeGraphQL.ts, packages/server/graphql/mutations/joinMeeting.ts, packages/server/graphql/mutations/pokerRevealVotes.ts, packages/server/graphql/mutations/setPokerSpectate.ts, packages/server/graphql/mutations/startSprintPoker.ts, packages/server/graphql/rootMutation.ts, packages/server/graphql/types/MeetingSubscriptionPayload.ts, packages/server/graphql/types/PokerMeetingMember.ts, packages/server/graphql/types/SetPokerSpectatePayload.ts, packages/server/graphql/types/TeamMember.ts
fixes #4571
- Added `isSpectating` to the PokerMeetingMember
- Added `isSpectatingPoker` to the TeamMember (so we remember their preference for future meetings)
TEST
=> add "i dont vote" button

packages/client/components/MeetingSubnavItem.tsx, packages/client/components/PokerSidebarEstimateSection.tsx
¡**Ojo**! This merges into branch `fix-4671` **not** master
=> poker subnav item styles (merge into branch ‘fix-4671’)

packages/server/graphql/mutations/deleteUser.ts
PR to resolve issue #4825 
This PR defines the argument types & checks if `reason` exists so that an error isn't returned when it's not provided.
=> Add type safety to deleteUser

packages/client/hooks/useSlackChannels.ts, packages/client/utils/SlackManager.ts, packages/client/utils/isSlackIMArray.ts, packages/server/graphql/mutations/addSlackAuth.ts, packages/server/graphql/mutations/setDefaultSlackChannel.ts
To send a DM from the `@Parabol` bot, we were using the [conversations.open](https://api.slack.com/methods/conversations.open) method and the [conversations.list](https://api.slack.com/methods/conversations.list) method to get the bot's channel id. Both methods required the IM scope.
The [postMessage](https://api.slack.com/methods/chat.postMessage) method requires a Slack channel id as an argument. However, instead of using `conversations.list` to get the bot's channel id (using the IM scope), the fine print explains that you can pass the user's id as the channel id which will then send a notification from `@Parabol`. 
This PR:
- Uses the user's id as the channel id when using the `@Parabol` bot
- Removes references to IM
In the `Parabol-staging` app, I've removed the IM scopes but I …
=> Remove IM scopes in Slack

packages/client/components/MeetingControlBar.tsx
There's an issue with `MeetingControlBar` width and `fit-content` usage. In this case `width: auto` fixes the issue.
=> Fixed meeting control bar width

packages/client/components/EditingStatus/EditingStatusText.tsx, packages/client/mutations/CreateTaskMutation.ts, packages/client/mutations/EditTaskMutation.ts, packages/client/utils/relay/getOptimisticTaskEditor.js
PR to resolve issue #4829 
Repro the issue:
- Go to team kanban
- filter by another team member (not you)
- add a task
- see that it says "X is editing too..."
The `userId` field in `task` tells us who owns the task but the task owner can be different from the task editor. Using the `viewer` instead of the task `user` resolves this bug.
=> Fix editing too bug

packages/client/components/ViewerNotOnTeam.tsx, packages/client/mutations/InviteToTeamMutation.ts, packages/client/mutations/PushInvitationMutation.ts
PR to resolve issue #4744 
Current problems:
1. If a user tries to join a team, the team members in that team may see a React Hooks error.
2. The `team` and `meeting` queries in `ViewerNotOnTeam` are invalid as `teamId` and `meetingId` can be null.
Solutions:
1. This is being caused by `PushInvitationMutation` breaking the rules of hooks which explains why the bug only happens in development and not production.
2. A bug in the Relay compiler prevented it from detecting the error (if we use a regular query instead of a fragment, it does detect the error). It looks like we don't need to check whether `team` or `meeting` exist in `ViewerNotOnTeam` as [MeetingSelector](https://github.com/ParabolInc/parabol/blob/235b57d1790f74b6170f8c3ebd5acf30839a472c/packages/client/components/MeetingSelector …
=> Fix team invitation

packages/client/hooks/useUpdatedSafeRoute.ts, packages/client/mutations/UpdatePokerScopeMutation.ts, packages/server/graphql/mutations/updatePokerScope.ts
PR to resolve issue #4811 
Steps to reproduce:
- User A, the facilitator, goes to a Story in the Estimate Phase
- User B goes back to the Scope phase and removes the Story that User A is currently on
- User A will be kicked out of the meeting and won't be able to go back to the meeting unless they change the phase in the URL
One solution would be to prevent users from removing Stories that are active in the Estimate Phase but I think users should have that power and we should accommodate.
The solution in this PR doesn't update the `facilitatorStageId`. I think that's OK as the local stage updates and the `facilitatorStageId` will change when the facilitator makes their next move. If that seems problematic, I could update the `facilitatorStageId` in `updatePokerScope`.
=> Fix tator being kicked out of Poker

packages/client/components/AvatarList.tsx, packages/client/components/AvatarListUser.tsx, packages/client/components/MeetingCard.tsx, packages/client/components/PokerActiveVoting.tsx, packages/client/components/PokerVotingRow.tsx, packages/client/components/PokerVotingRowBase.tsx
Having an avatar with a hanging border, and overlapping other avatars, is a challenge on the 8px grid.
- For smaller avatars let’s use a 2px border, for larger (GTE 40px) let’s use 3px. It looks crisp for the larger sizes.
- If we want gutters and edges to fall on the 8px grid we have to offset for the 2 or 3 pixels. So you may see partial padding sizes like 5px (+3) or 4px (+2 +2 vertically)
- To get an avatar of 24 we have to call it 28 (24 + 2 + 2), and for 40 we measure 46 (40 + 3 + 3).
- There’s not a good solution yet for the growing whitespace + any optional vertical gutter so I hard-coded offsets to account for a row of 24px avatars
=> refines avatar group layout

packages/client/Atmosphere.ts, packages/client/components/AnalyticsPage.tsx, packages/client/components/ErrorBoundary.tsx, packages/server/graphql/rootQuery.ts
Logging `authToken` in User query. Some users have been able to login but get a `null` response from the User query. 
This should help us narrow down whether there's a problem with the dataLoader or the token.
This PR also:
- Prevents a network request from being sent to LogRocket
- Sends a custom event to LogRocket so that we can track fatal errors
=> Log authToken in User query

packages/gql-executor/gqlExecutor.ts
**AC:**
- run `yarn build` then `yarn start`
- go to graphiql and do the mutation below, which will trigger a server error
- go to [sentry staging](https://sentry.io/organizations/parabol/issues/?project=107915) and see that the error shows up
```
mutation {
addAgendaItem(newAgendaItem: {
content: "content",
pinned: false,
teamId: "teamid",
teamMemberId: "team member id",
sortOrder: 1,
meetingId: "meeting id"
}) {
error {
title
message
}
}
}
```
=> init sentry in gqlExecutor

packages/client/components/ScopePhaseAreaGitHub.tsx, packages/client/types/constEnums.ts, packages/client/types/graphql.ts, packages/client/utils/GitHubManager.ts, packages/server/graphql/mutations/addGitHubAuth.ts, packages/server/graphql/types/GitHubIntegration.ts, packages/server/postgres/migrations/1621283671444_gh-scope.ts, packages/server/postgres/queries/generated/getGitHubAuthByUserIdTeamIdQuery.ts, packages/server/postgres/queries/generated/upsertGitHubAuthQuery.ts, packages/server/postgres/queries/src/upsertGitHubAuthQuery.sql, packages/server/utils/GitHubServerManager.ts
unblocks #4930, which will need extra github scope to show private repos
fix #4970 
TEST
=> support varying github scopes

packages/client/clientSchema.graphql, packages/client/components/DiscussionThread.tsx, packages/client/components/RetroDiscussPhase.tsx, packages/client/mutations/AddCommentMutation.ts, packages/client/mutations/DeleteCommentMutation.ts, packages/client/mutations/ResetMeetingToStageMutation.ts, packages/client/mutations/connections/getThreadSourceThreadConn.ts, packages/client/mutations/handlers/handleEditCommenting.ts, packages/client/mutations/handlers/handleRemoveTasks.ts, packages/client/mutations/handlers/handleUpsertTasks.ts, packages/client/subscriptions/MeetingSubscription.ts, packages/client/types/graphql.ts, packages/server/graphql/types/AgendaItem.ts, packages/server/graphql/types/RetroReflectionGroup.ts, packages/server/graphql/types/Story.ts, packages/server/graphql/types/Threadable.ts, packages/server/graphql/types/User.ts
fix #4973
This works does 2 things:
- it moves `commentors` from `ThreadSource` to  `ThreadConnection` (unblocks #4965)
- it moves `thread` from `ThreadSource` to `User` (supports future discussions outside of meetings)
TEST
=> refactor commentor to thread conn

packages/client/components/ErrorBoundary.tsx, packages/server/graphql/rootQuery.ts
Sending exceptions to LogRocket as well as Sentry. Also, sending an exception to LogRocket when the `viewerId` is null in the `User` query to help debug https://github.com/ParabolInc/parabol/issues/4802
Merging right away as the change is trivial
=> Send exceptions to LogRocket too

packages/server/postgres/migrations/postDeploy/1621238616230_backfillTier.ts, packages/server/postgres/queries/generated/backfillTierQuery.ts, packages/server/postgres/queries/generated/getTeamsByIdQuery.ts, packages/server/postgres/queries/generated/getUsersByIdQuery.ts, packages/server/postgres/queries/generated/updateUserTiersQuery.ts, packages/server/postgres/queries/src/backfillTierQuery.sql, packages/server/postgres/queries/src/updateUserTiersQuery.sql, packages/server/utils/setUserTierForUserIds.ts
Changes:
1. Update `setUserTierForUserIds` to update the `tier` column to PG. As the `Organization` table has not been migrated to PG, we need to join with RethinkDB today.
2. A backfill script for the `tier` column for `User` table in PG.
Tests:
=> Tier update pg

packages/client/components/NewJiraIssueInput.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryAvatarHeader.tsx
This PR resolves two small issues that I've noticed:
1. The Jira new issue menu width is too wide. This was because the menu ref was attached to a full width button
2. The meeting summary shows each team member as "Present". As we now only show team members that have joined the meeting rather than all team members, perhaps we can remove "Present" from the meeting summary as all team members will always be present?
=> UI fix-ups

scripts/webpack/prod.servers.config.js
Resolves #4908
**AC**
This branch is deployed to dev server. Development also has extra code to trigger sending to sentry from staging or development branches.
This is a sentry error triggered from dev server, with successfully resolved source maps: https://sentry.io/organizations/parabol/issues/2410288689/?project=107915&query=is%3Aunresolved
When this PR is first merged to staging, any errors triggered from staging server won't have resolved source maps. This is bc the default behavior is to send to sentry only on pushes to production. Once this PR is in production, server stack traces in sentry will display correctly.
=> Sentry server stack

packages/server/utils/getVerifiedAuthToken.ts
PR to _possibly_ resolve issue #4802. 
[This Sentry error](https://sentry.io/organizations/parabol/issues/2407373705/events/302584b819ea433681ce0b9cfeb39c97/?project=107196&statsPeriod=14d) shows that the `authToken` is an empty object which could be because the [getVerifiedAuthToken](https://github.com/ParabolInc/parabol/blob/9fd7b20f991e900ca307d5d8913ee15b0c544230/packages/server/utils/getVerifiedAuthToken.ts) fails to verify the jwt. 
This PR adds a 10 second clock tolerance to give us more leeway and adds extra Sentry logging
=> Add clock tolerance to getVerifiedAuthToken

packages/client/components/SlackChannelDropdown.tsx, packages/client/hooks/useSlackChannels.ts, packages/client/utils/SlackManager.ts, packages/server/database/types/MeetingAction.ts, packages/server/database/types/MeetingPoker.ts, packages/server/database/types/MeetingRetrospective.ts, packages/server/graphql/intranetSchema/queries/dailyPulse.ts, packages/server/graphql/mutations/addSlackAuth.ts, packages/server/graphql/mutations/endCheckIn.ts, packages/server/graphql/mutations/endRetrospective.ts, packages/server/graphql/mutations/helpers/makeSlackBlocks.ts, packages/server/graphql/mutations/helpers/notifySlack.ts, packages/server/graphql/mutations/setDefaultSlackChannel.ts, packages/server/graphql/mutations/startCheckIn.ts, packages/server/graphql/mutations/startRetrospective.ts, packages/server/graphql/mutations/startSprintPoker.ts
PR to resolve issue #4911. 
It also resolves an undocumented bug where timer adjustments send new notifications rather than update the previous one. I've commented inline about this. 
A few additional notes:
- The issue mentioned using Slack's default green `#007a5a` but with Slack's blocks, you choose whether it's a primary button, regular or danger button rather than specify the colour. On a dark mode theme, we get the darker button and in a light mode, it's a lighter button
- I haven't come across a good, free tool for creating short links so I've included the regular link without utm params which is still shortish
- I've added a dummy interactivity request URL to the [Slack app](https://api.slack.com/apps/A01EGHDU7PZ/interactive-messages?). Otherwise, a warning sign shows after …
=> Make Slack notifications pretty

.circleci/config.yml
=> update ci backup command to use new breaking interface

packages/client/hooks/useSlackChannels.ts, packages/client/utils/SlackManager.ts, packages/server/graphql/mutations/addSlackAuth.ts, packages/server/graphql/mutations/helpers/notifySlack.ts, packages/server/graphql/mutations/setDefaultSlackChannel.ts
We've got another case of the prod Slack app working differently to the dev Slack app.
There are two differences:
1. In the recent update, to enable upserting Slack messages when the timer changes, I searched through IMs to get the bot app `channelId`. While this worked in dev, it looks like the im:read scope is required in prod. I suspected this might happen after a similar thing happened with private channels so I included a back-up channelId here. However, now after auth'ing Slack, the channel menu doesn't show-up. I suspect [this line](https://github.com/ParabolInc/parabol/blob/cf2fe59da68edd9a44035baa8d02aa3ea279e736/packages/server/graphql/mutations/addSlackAuth.ts#L129) is the issue - it shouldn't be a return statement.
I've reverted the `addSlackAuth` logic back to how it was …
=> Slack im:scope fix 

packages/server/graphql/intranetSchema/mutations/flagOverLimit.ts, packages/server/postgres/migrations/1622701938472_backfillOverLimitCopy.ts, packages/server/postgres/utils/checkEqBase.ts, packages/server/postgres/utils/checkTeamEq.ts, packages/server/postgres/utils/checkUserEq.ts
We have the following "inequality" in the comparison result:
```
“xxxxxxxx”: {
“error”: [
“overLimitCopy”
],
“rethinkRow”: {
“overLimitCopy”: null
},
“pgRow”: {
“overLimitCopy”: “”
}
},
```
Field `overLimitCopy` in RethinkDB is used by sales to pop messages like "hey your team are over free tier limit, please contact XXX". When the team is indeed upgraded, we set its value to `null` in RethinkDB. In other words, `undefined` for this field represents "we never bothered this user at all", non-empty string represents a popup message, `null` represents "user is upgraded hence the pop up message is cleared".
In RethinkDB, we use `undefined` to represent non-existence and explicit `null` to represent emptiness. In PostgreSQL, `null` is equivalent as undefined. Hence I propose:
* `undefined` in …
=> Handle null overLimitCopy in RethinkDB vs. PG

packages/server/postgres/migrations/postDeploy/1623747531144_backfillMissingTeams.ts
Just a quick & dirty backfill script to backfill the ~1,700 teams missed in last round of migrations to PG. I borrowed a lot of code from [1615148741896_backfillTeamTable.ts](https://github.com/ParabolInc/parabol/blob/master/packages/server/postgres/migrations/postDeploy/1615148741896_backfillTeamTable.ts).
=> Backfill script for the missing teams with same createdAt timestamp

packages/server/database/migrations/20210527170505-addAdditionalRetroTemplates.ts, packages/server/database/migrations/20210602120505-addAdditionalRetroTemplates.ts
PR to resolve issue #4069 
After deleting the templates and prompts in the down migration, the templates would still show up in the retro template modal but without any prompts.
I think this is because we grab the prompts with the dataLoader but we get the templates with `db.read` [here](https://github.com/ParabolInc/parabol/blob/a47534ce10f9b18b2568ab2ee9ad4b41354196fa/packages/server/graphql/types/RetrospectiveMeetingSettings.ts#L95) which initially checks Redis. The templates and prompts were successfully deleted but the templates lived on in the cache.
I'm now clearing the Redis cache in the migrations. After running either migration and then restarting the server, zombie templates no longer show up. Not sure if it's strictly necessary as the cache gets cleared when running `yarn dev` …
=> Add retro templates

packages/server/graphql/mutations/helpers/notifySlack.ts
Removing upsert notifications for timer as:
- it's only used when updating the timer and the notification channel is the bot
- it requires the `im:read` scope
- it requires grabbing the bot channel id
=> Remove Slack upsert timer 

packages/client/components/TimelineEventPokerComplete.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/makePokerStats.ts, packages/client/types/graphql.ts, packages/server/database/migrations/20210622170418-addPokerStats.ts, packages/server/database/migrations/20210624120419-addPokerStats.ts, packages/server/database/types/MeetingPoker.ts, packages/server/graphql/mutations/dragDiscussionTopic.ts, packages/server/graphql/mutations/dragEstimatingTask.ts, packages/server/graphql/mutations/endCheckIn.ts, packages/server/graphql/mutations/endRetrospective.ts, packages/server/graphql/mutations/endSprintPoker.ts, packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts, packages/server/graphql/mutations/helpers/notifySlack.ts, packages/server/graphql/mutations/joinMeeting.ts, packages/server/graphql/mutations/pokerAnnounceDeckHover.ts, packages/server/graphql/mutations/pokerResetDimension.ts, packages/server/graphql/mutations/pokerRevealVotes.ts, packages/server/graphql/mutations/pokerSetFinalScore.ts, packages/server/graphql/mutations/setPhaseFocus.ts, packages/server/graphql/mutations/updateAgendaItem.ts, packages/server/graphql/mutations/updateNewCheckInQuestion.ts, packages/server/graphql/mutations/updatePokerScope.ts, packages/server/graphql/mutations/voteForPokerStory.ts, packages/server/graphql/types/PokerMeeting.ts, packages/server/graphql/types/RetrospectiveMeeting.ts, packages/server/graphql/types/TimelineEventPokerComplete.ts, packages/server/utils/getPhase.ts
PR to resolve issue #4983 
This PR saves the story count and comment count to the db when a poker meeting ends. It also adds a migration to update previous meeting stats.
=> Add poker comment & story count

packages/client/components/MockFieldList.tsx, packages/server/dataloader/customLoaderMakers.ts, packages/server/graphql/mutations/updateJiraDimensionField.ts
Related issue: https://github.com/ParabolInc/parabol/issues/5028 
The reason it doesn't work is that `UpdateJiraDimensionField` mutation fails when `As Comment` or `Do Not Update` is selected. See the screenshot below. 
@mattkrick I went through the commit history and I can't find any changes that could break that functionality. Before this fix, `UpdateJiraDimensionField` just iterates through Jira fields and throws an error if the field is not found. As `As Comment` or `Do Not Update` aren't normal Jira fields they can't be found in the list of standard Jira fields. This PR checks if any of these custom fields is selected and then just skips the Jira field array search. Otherwise, it just works as before.
=> Jira stories, can’t add points as a comment

packages/client/mutations/UpdateAgendaItemMutation.ts, packages/client/mutations/handlers/handleRemoveAgendaItems.ts, packages/server/graphql/mutations/removeAgendaItem.ts
Related issue: https://github.com/ParabolInc/parabol/issues/5056 
Agenda items related relay store updaters were broken because they were reading non-exsiting `agendaItemId` property from `AgendaItemsStage`. 
Now, both sorting and deletion work without any issues (currently, on prod sorting and deletion are broken).
=> Fixed agenda items sorting and deleting

packages/client/Atmosphere.ts, packages/client/components/ErrorComponent/ErrorComponent.tsx, packages/client/hooks/useServiceWorkerUpdater.ts, packages/client/hooks/useTrebuchetEvents.ts
PR to resolve issue #4691. I'm having difficulty comparing the app version and the server version in the error component but I've implemented a possible solution, written up my understanding of how things are working and left a couple of questions.
I can see that the `__APP_VERSION__` is set in the webpack config [here](https://github.com/ParabolInc/parabol/blob/0ea032bfa3d57a52212278d47cee0bbe3d1972e2/scripts/webpack/prod.client.config.js#L127) and that it looks at the package json file for the latest version.
Using service workers, we create a cache in [sw.ts](https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/serviceWorker/sw.ts) with `__APP_VERSION__` as the suffix.
In [useTrebuchetEvents](https://github.com/ParabolInc/parabol/blob/8c68b …
=> Update new version snackbar

packages/server/postgres/migrations/1625576993064_sortJiraDimensionFields.ts, packages/server/tsconfig.json
Migration script to:
* Sort `jiraDimensionFields` array field in RethinkDB
* Sort `jiraDimensionFields` array field in PG
@mattkrick I got the error: `Module '"fast-json-stable-stringify"' can only be default-imported using the 'esModuleInterop' flag` if I don't enable the `esModuleInterop` option in tsconfig. Not sure what's a better solution.
=> Add a new migration script to sort jiraDimensionFields for both RethinkDB & PG

packages/client/types/graphql.ts, packages/server/database/migrations/20210708185500-removePromptTitle.ts, packages/server/database/types/RetrospectivePrompt.ts, packages/server/graphql/mutations/helpers/makeRetroTemplates.ts, packages/server/graphql/types/ReflectPrompt.ts
PR to resolve issue #5009 
I know that [we sometimes](https://github.com/ParabolInc/parabol/blob/db45e3b5a4c27e917dcc267d33175bae8a04970b/packages/server/graphql/types/RetroReflectionGroup.ts#L32) keep the field with a deprecation reason. I assume we do this when deprecating a previously important field and we want to be careful in case we break something? The prompt title isn't being used anywhere so I assume it's safe to remove it entirely.
=> Deprecate prompt title

packages/server/dataloader/foreignLoaderMakers.ts, packages/server/graphql/mutations/startSprintPoker.ts
Resolves https://github.com/ParabolInc/parabol/issues/5126
**AC:**
=> templateDimension dataloader should only return non removed dimensions

packages/server/graphql/mutations/addAtlassianAuth.ts, packages/server/postgres/migrations/1624862201216_addAtlassianAuthTable.ts
After merging https://github.com/ParabolInc/parabol/pull/4880 `scope` is no longer kept as a string but as an array of strings to allow easier manipulation. This PR fixes the migration which assumed it was a string. 
I've also added an improvement to existing functionality: https://github.com/ParabolInc/parabol/issues/5134
=> Fixed atlassian auth migration

packages/client/components/Dashboard/DashSidebar.tsx, packages/client/components/TimelineRightDrawer.tsx, packages/client/modules/teamDashboard/components/AgendaAndTasks/AgendaAndTasks.tsx
PR to resolve issue: #5117 
Issue was caused by removing `position: fixed` [here](https://github.com/ParabolInc/parabol/blob/c8d057bc6861eaa9d102e8a53966fb79e55a3272/packages/client/components/Dashboard/DashSidebar.tsx#L23) in #4975. 
However, it looks like the [DashMain](https://github.com/ParabolInc/parabol/blob/bdbb60c65d52f48698268aed46f9e095947ee3f3/packages/client/components/Dashboard.tsx#L114) div previously included the nav sidebar on large screens and we adjusted the content of `DashMain` with padding. 
Instead, by removing `position: fixed` and removing the extra padding, we can correctly centre the dashboards and the `DashMain` div won't include the sidebar.
=> Fix dashboard padding

packages/server/graphql/intranetSchema/mutations/updateWatchlist.ts, packages/server/graphql/types/UpdateWatchlistPayload.ts
PR to implement Matt's suggestion here: https://github.com/ParabolInc/parabol/pull/5127#discussion_r670037068
With this update, super users can add a list of emails or a domain that they want to start/stop recording in LogRocket.
=> Add emails and domain to updateWatchlist

packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx, packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx, packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx, packages/client/types/graphql.ts, packages/server/graphql/types/RetroDiscussStage.ts
Related issue: https://github.com/ParabolInc/parabol/issues/5099
I've noticed one more thing though. If the meeting ends before going to the discussion phase, the reflections fetched in the meeting summary will be an empty array. I'm investigating this but if someone has any quick fixes for that, please let me know! For now, I've added a check for empty data in CSV export to prevent it from crashing.
AC:
* Meeting summary works when there's no discussion
=> Fixed summary review not working properly

packages/server/database/migrations/20210719161718-deletedUserEmailBackfill.ts
Deleted users in PG have their emails look like this:
```
parabol-saas=> SELECT "email" FROM "User" WHERE "email" LIKE 'DELETED%' LIMIT 5;
email
-----------------------------------------------------------
DELETED:google-oauth2|110945899376117816083:1626360264029
DELETED:google-oauth2|116562409957802979935:1626360264029
DELETED:local|4myp2jiFe:1626360264029
DELETED:google-oauth2|104006359267253995684:1626360264029
DELETED:local|ZCVtnN3APd:1626360264029
(5 rows)
```
There are 1,275 deleted users:
```
parabol-saas=> SELECT COUNT(1) FROM "User" WHERE "email" LIKE 'DELETED%';
count
-------
1275
(1 row)
```
We need to backfill RethinkDB to match with the format so the equality checker won't complain.
=> Backfill email field for deleted users in RethinkDB to match with PG

packages/client/components/MeetingCard.tsx
In efforts to slowly improve accessibility @enriquesanchez and I have identified a small element on the meeting view cards where colour contrast could be improved. 
- MeetingTypeLabel: 11px -> 12px
- Name: GRAPE_700 -> GRAPE_800; 20px -> 22px
- Meta: GRAPE_600 -> GRAPE_700
Left: updates | Right: Original
=> updating meeting cards styles for improved contrast and HTML semantics

packages/server/dataloader/atlassianLoaders.ts, packages/server/graphql/mutations/pokerSetFinalScore.ts, packages/server/graphql/types/Task.ts
nothing to test yet since we don't show estimates on tasks.
when we build the frontend, the story points you see on a task are guaranteed to be the same value as it exists in jira.
fix #5165
=> keep parabol estimates synced with jira

packages/server/graphql/types/Team.ts
Resolves https://github.com/ParabolInc/parabol/issues/5169
**AC:**
=> make sort team members query case insensitive

packages/server/graphql/handleGraphQLTrebuchetRequest.ts, packages/server/utils/PubSubPromise.ts
PR to resolve issue #5189 
With these changes, the app shows the loading icon rather than crashes when the GQL Executor doesn't respond within the timeout limit.
=> Handle slow responding gql executor

packages/client/components/MeetingCard.tsx
This tiny little PR adds an empty `alt` property (`alt=''`) to the meeting card images in the meeting view. This is important for folks using assistive technology, such as screen readers, as it tells the software to ignore the image.
I've chosen to ignore the images because they are purely decorative and don't provide any critical meaning to the user. For a screen reader user, the meeting type is already indicated by the meeting type label in the meeting card.
Credit also goes to @acressall for the help 🙌
=> Adds empty alt property to meeting card images for a11y

packages/client/components/RetroReflectPhase/ReflectWrapperDesktop.tsx
PR to resolve issue #5263 
This PR center aligns the kanban columns on Safari to be consistent with Chrome.
@enriquesanchez mind reviewing this one? It's a tiny change so if you're happy it, I think we can merge it without a second code review
=> Center align kanban columns on safari

packages/client/types/graphql.ts, packages/server/database/migrations/20210726140543-estimate-stage-tasks.ts, packages/server/graphql/types/EstimateStage.ts, scripts/dev.js
fix #5161
For all new poker meetings, a task is created for imported stories.
This migrates all old meetings to guarantee that each imported story has a linked task.
It also turns the stage's finalScore into a TaskEstimate so we can reference the task's story points outside of the meeting
TEST
=> turn existing jira stages into tasks and estimates

packages/client/components/StageTimerDisplay.tsx, packages/client/components/UndoableGroupPhaseControl.tsx, packages/client/components/UndoableGroupPhaseDialog.tsx, packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts, packages/client/subscriptions/MeetingSubscription.ts, packages/client/types/graphql.ts, packages/server/graphql/mutations/resetMeetingToStage.ts, packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts, packages/server/graphql/rootMutation.ts, packages/server/graphql/types/MeetingSubscriptionPayload.ts, packages/server/graphql/types/ResetRetroMeetingToGroupStagePayload.ts
Fixes #5249
1. Updates existing `resetMeetingToStage` to only works for resetting to group stage for a retro meeting. This is to ensure that we don't need to create dummy phases/stages for the meeting beforehand, hence we no longer rely on the `meetingSettings` which could change during the meeting period. See discussion in #5249 and [this thread](https://parabol.slack.com/archives/C836NA350/p1628885677080400?thread_ts=1628639020.029800&cid=C836NA350).
2. Due to the above changes, rename the mutation to `resetRetroMeetingToGroupStage` across the board, to avoid confusion.
=> Reset retro meeting to group phase without creating all the new phases

packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/types/graphql.ts, packages/server/database/migrations/20210817223727-removePromptTemplateId.ts, packages/server/database/types/ReflectPhase.ts, packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts, packages/server/graphql/mutations/startRetrospective.ts, packages/server/graphql/mutations/startSprintPoker.ts, packages/server/graphql/types/ReflectPhase.ts
Remove the field from the meeting stage. The template is now not
connected to the stage anymore so update the template timestamp where it
is used when starting the meeting.
Resolves: #3949
=> Remove promptTemplateId field from reflect stage

CHANGELOG.md, lerna.json, package.json, packages/client/package.json, packages/client/utils/getMassInvitationUrl.ts, packages/cypress/package.json, packages/gql-executor/package.json, packages/server/createSSR.ts, packages/server/package.json, packages/server/utils/getReqAuth.ts, packages/sfu/package.json
fix #5282 
- Removes logRocket from the client keys, disabling it entirely (I think we'll probably want to move to datadog client in the future...)
- uses http proto when the invitation link starts with localhost
- server checks for a reverse proxy (x-forwarded-for header) and if not present uses x-application-authorization header
=> support prod build locally

packages/client/Atmosphere.ts
the client shouldn't have to be aware of a reverse proxy that swaps out headers. 
fixed the server handling in #5284
now the client can be dumb
=> x-app-auth always on client

packages/server/graphql/intranetSchema/mutations/autopauseUsers.ts, packages/server/postgres/queries/generated/getUserIdsToPauseQuery.ts, packages/server/postgres/queries/getUserIdsToPause.ts, packages/server/postgres/queries/src/getUserIdsToPauseQuery.sql
First step to replace User reads from RethinkDB with reads from Postgres.
This is a separate PR as it's independent and easy to test.
Relates-To: #4867
=> Read autopauseUsers user from PG

packages/client/components/ActionSidebarPhaseListItemChildren.tsx, packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
Fixes #5307 
We [previously checked](https://github.com/ParabolInc/parabol/blob/8c68bf771a350b31c7948e6bd11c5c110e30c977/packages/client/components/ActionSidebarPhaseListItemChildren.tsx#L27) whether the `localPhase` type equaled the `phaseType` before rendering the component.
We now need to always render the `MeetingSidebarTeamMemberStageItems` component during the check-in and updates phases so that the sidebar transition can work.
Checking whether `localPhase` exists in `MeetingSidebarTeamMemberStageItems` does the trick as the `useAnimatedPhaseListChildren` will return a height of 0 if it doesn't exist.
While the `sidebarPhase` should always exist, I've removed the bang operator and added additional checks, just to be extra cautious. 
I'm not sure why the `localPhase` can be null, …
=> Fix undefined phaseType bug

packages/server/graphql/intranetSchema/mutations/draftEnterpriseInvoice.ts, packages/server/graphql/intranetSchema/mutations/loginSAML.ts, packages/server/graphql/intranetSchema/mutations/updateEmail.ts, packages/server/graphql/intranetSchema/mutations/updateWatchlist.ts, packages/server/graphql/intranetSchema/queries/dailyPulse.ts, packages/server/graphql/intranetSchema/queries/user.ts, packages/server/graphql/mutations/deleteUser.ts, packages/server/graphql/mutations/emailPasswordReset.ts, packages/server/graphql/mutations/helpers/attemptLogin.ts, packages/server/graphql/mutations/inviteToTeam.ts, packages/server/graphql/mutations/loginWithGoogle.ts, packages/server/graphql/mutations/resetPassword.ts, packages/server/graphql/mutations/verifyEmail.ts, packages/server/graphql/queries/verifiedInvitation.ts, packages/server/hubspot/backfillHubSpot.ts, packages/server/postgres/queries/generated/getUserIdsToPauseQuery.ts, packages/server/postgres/queries/generated/getUsersByEmailsQuery.ts, packages/server/postgres/queries/getUsersByEmails.ts, packages/server/postgres/queries/src/getUsersByEmailsQuery.sql
Fetch users by email from Postgres. Split query into two versions (1 user, multiple users) to avoid accidentally indexing the promise due to wrong parenthesis since it happened to me multiple times.
Resolves: #5373
=> Fetch user by email from PG

packages/server/graphql/mutations/updatePokerScope.ts, packages/server/utils/RedisLockQueue.ts
#5268
In this PR I add `RedisLockQueue` which is a lock that put tasks in a queue and execute them in serial in the order that they were queued.
**It works as follows:**
- Instead of setting a single key, we use a LIST to push a request UID into it.
- Each request periodically checks if it is the first in the LIST. And if so, it is executed.
- After successful execution, the request calls `unlock` function which removes its UID from the LIST.
- Now, another request is able to find its UID in the LIST and execute
**Handling errors:**
It is theoretically possible that some of the events are failed and stuck in a queue. To handle this situations we use the following approach:
- When event starts, we append a timestamp to its UID. Each process checks if timestamp of the first event in a queue …
=> Implement RedisLockQueue

packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
Fixes #5191 .
Test:
Starts a retro meeting, fill in some reflections. End the meeting before discussion phase. Verify:
*   [x] reflection cards are shown in meeting summary page, and within correct reflection groups is there are any
*   [x] export to CSV button works and reflection texts are in the CSV file
=> Fix bug where reflections missing if meeting not advance to discuss phase

packages/server/database/migrations/20211025134235-estimateStageTaskIdBackfill.ts
Resolves #5558
When this migration runs in staging or production, the user from #5424 and any others similarly affected should be able to access their ended meetings on the timeline with no errors.
Solves the following silent error from rethinkdb, which was surfaced during development using `returnChanges`.
```
{
changes: [],
deleted: 0,
errors: 1,
first_error: 'No attribute `taskId` in object:\n' +
'{\n' +
'\t"endAt":\t{\n' +
'\t\t"$reql_type$":\t"TIME",\n' +
'\t\t"epoch_time":\t1632431013.443,\n' +
'\t\t"timezone":\t"+00:00"\n' +
'\t},\n' +
'\t"finalScore":\tnull,\n' +
'\t"id":\t"4E7aaI8kec",\n' +
'\t"isComplete":\ttrue,\n' +
'\t"isNavigable":\ttrue,\n' +
'\t"isNavigableByFacilitator":\ttrue,\n' +
'\t"isVoting":\ttrue,\n' +
'\t"phaseType":\t"ESTIMATE",\n' +
'\t"readyToAdvance":\t[],\n' …
```
=> fix migration from silent rethinkdb fail when stage has no taskId

packages/client/utils/getMeetingPhase.ts, packages/server/graphql/mutations/endCheckIn.ts, packages/server/graphql/mutations/endRetrospective.ts, packages/server/graphql/mutations/endSprintPoker.ts
With the right sequence of events it is possible to end up with a
complete (no open phases) meeting which did not end yet. This should not
throw.
Relates-To: #5243
=> Fix ending meeting without open phases

.prettierrc, docker/dev.yml, scripts/dev.js
redis & rethinkdb don't have M1 architectures yet so we have to emulate them.
Also noticed some deprecation warnings on node v16.9.1, so fixed that up.
an explicit x86_64 should work just fine for intel architectures, too.
=> support new m1 pro architecture

.vscode/settings.json
i noticed some PRs coming in that don't have a newline at the end of the file.
this should be something that we don't have to think about, so this turns it on by default for vscode users
=> add final newline on save vscode

packages/client/components/SpotlightModal.tsx, packages/client/hooks/useGroupMatrix.ts, packages/client/hooks/useSpotlightSimulatedDrag.tsx, packages/client/mutations/handlers/handleUpdateSpotlightResults.ts
Fix https://github.com/ParabolInc/parabol/issues/5625 and https://github.com/ParabolInc/parabol/issues/5622
=> Fix source returning to kanban & 2 column error

packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx
Fix https://github.com/ParabolInc/parabol/issues/5623
When a reflection group is ungrouped, a new `reflectionGroupId` is created for the ungrouped reflection. When this happens, the new reflection group is added to the Spotlight [here](https://github.com/ParabolInc/parabol/blob/378944330900be841e7cc903974c0afc9a1c17f8/packages/client/mutations/handlers/handleUpdateSpotlightResults.ts#L47). However, momentarily, before the new reflection group is added to the Spotlight, the `reflectionGroupId` doesn't exist in the `resultGroupIdsInSpotlight` meaning `!isReflectionGroupIdInSpotlight` and therefore [isPriorityCard](https://github.com/ParabolInc/parabol/blob/45cae6676c2bf6051cd8042962e5bee243c04419/packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx#L151) are briefly true …
=> Fix collapsed reflections 

packages/server/graphql/mutations/endDraggingReflection.ts, packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts, packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
In dev, relay would print some errors saying the same object in the same payload had different properties.
specifically, `reflection.reflectionGroupId` was different from `reflectionGroup.reflection.reflectionGroupId` in the endDragging payload.
the root cause was a dataloader with stale data.
@nickoferrall you might be interested in this
=> fix relay error on drag end

packages/client/components/ReflectionGroup/ReflectionGroup.tsx, packages/client/components/ReflectionGroup/useSpotlightReflectionGroup.ts
The property was missing from the `ReflectionGroup`s fragment. Also
moved the hook in the `ReflectionGroup` subdirectory as it's tightly
coupled to `ReflectionGroup`
=> Fix missing `isSpotlight` in `useSpotlightReflectionGroup`

package.json
If we run this command we want to see all errors, so don't stop lerna
run when the first package fails.
=> Show all packages errors on `yarn typecheck`

packages/client/package.json, packages/server/package.json, yarn.lock
ever since the last round of dep bumps i've been getting
```
[Error - 3:25:07 PM] Error: Error while loading rule '@typescript-eslint/no-loss-of-precision': @typescript-eslint/no-loss-of-precision requires at least ESLint v7.1.0
```
so i figured we should bump this, too
=> bump eslint to v8

packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
Sometimes the tooltip for the agenda item pins can be a little sticky. `onMouseOver` & `onMouseOut` fire more frequently as they execute when the cursor leaves the child element as well as the current element. Matt mentioned the issue and solution here: https://github.com/ParabolInc/parabol/pull/5550#discussion_r739439423
Hey @tianrunhe, would you mind reviewing this one, please?
=> Fix sticky tooltip in agenda item pins

packages/client/components/AddTeamMemberModal.tsx, packages/client/components/AddTeamMemberModalDemo.tsx, packages/client/components/CreditCardIcon.tsx, packages/client/components/NewMeeting.tsx, packages/client/components/NewMeetingIllustration.tsx, packages/client/components/ReflectionCard/AddReactjiButton.tsx, packages/client/components/UpgradeLater.tsx, packages/client/components/UpgradeSuccess.tsx, packages/client/modules/userDashboard/components/CreditCardModal/CreditCardErrorLine.tsx, packages/client/types/modules.d.ts, packages/client/utils/StripeClientManager.ts, packages/server/types/modules.d.ts, scripts/webpack/dev.client.config.js, scripts/webpack/prod.client.config.js
our build should be totally self-contained.
__STATIC_IMAGES__ is not. it is a link to a directory on our S3 server.
by removing it, all required assets are put into the webpack build.
this should make deploying to private instances easier.
TEST
=> remove __STATIC_IMAGES__

.eslintrc.js, packages/client/.eslintrc.js, packages/server/.eslintrc.js
now our child .eslintrc files are a little more verbose, but they work without fallback flags :tada:
=> support eslint v7+

.husky/post-commit, .husky/pre-commit, package.json, packages/client/package.json, packages/server/package.json, yarn.lock
Recently we updated `husky` from version `^3.0.1` to version `^7.0.4` ([commit](https://github.com/ParabolInc/parabol/commit/6086f859533faf087f1fcf840ea8f6a4470ee0b8#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519))
Looks like a new version of husky is no longer store hooks in `.git/hooks`, now it requires another approach.
From the README https://github.com/typicode/husky:
```
Edit package.json > prepare script and run it once:
npm set-script prepare "husky install"
npm run prepare
Add a hook:
npx husky add .husky/pre-commit "npm test"
git add .husky/pre-commit
```
- Ideally, make a fresh clone of the repo, run `yarn`
- Be on `master`
- Make a commit and see it run without errors, but no hooks were executed
- Checkout to this branch — `fix-husky`
- …
=> Fix husky hooks

packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx, packages/client/components/ReflectionGroup/ReflectionGroup.tsx, packages/client/components/ResultsRoot.tsx, packages/client/components/SpotlightGroups.tsx, packages/client/components/SpotlightModal.tsx
=> Fix remotely ungrouped results position in Spotlight

packages/client/types/graphql.ts, packages/server/graphql/types/UserFeatureFlags.ts, packages/server/graphql/types/UserFlagEnum.ts
Fix #5753 
I haven't added a cheat code for standups yet as:
1. I imagine it should be added to the `NewMeeting` file, but I'm not sure yet as we haven't started building it
2. It's not in the AC
3. We need to use the `AddFeatureFlagMutation` which is added in #5699. I'd prefer to keep the PRs separate
4. Adding the cheat code is trivial once #5699 is merged
@BartoszJarocki could you review this one, please?
=> Add standups feature flag

packages/client/components/IntegratedTaskContent.tsx
#5247
How to test:
- Create a task in parabol and push to jira
- Edit task on jira and add images to description with different aspect ratios (vertical, horizontal)
- Go back to paraobl, see images are displayed correctly
=> Fix image scaling in task description

CHANGELOG.md, packages/client/hooks/useDraggableFixture.ts, packages/client/hooks/useDraggableReflectionCard.tsx
Fix #5806 
`TouchEvent` can be undefined on Firefox ([see here](https://bugzilla.mozilla.org/show_bug.cgi?id=1693172)). Reverting back to the previous implementation. 
I had committed the Changelog update to `master`, which is why this PR includes the Changelog update. I think it's fine to still include that here.
=> Remove instanceof TouchEvent

packages/client/components/Dashboard.tsx
This PR adds a skip link to the app's dashboard views. It mainly consists of two changes:
1. Creates an `a` tag that is visually hidden unless it receives keyboard focus
2. Replaces a `div` with a `main` tag for the main content area. This is so the skip link can point to the main area.
In short, this makes the first interactive item in the Web page a link to the beginning of the main content.
**Related WCAG criteria:**
[2.4.1 Bypass Blocks](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1#qr-navigation-mechanisms-skip)
_A mechanism is available to bypass blocks of content that are repeated on multiple Web pages._
This is a common a11y feature and there are many examples and best practices. For reference, check out [gov.uk](https://www.gov.uk/) and …
=> Adds skip link to dashboard

.vscode/settings.json
This is subjective and shouldn't be forced on everyone.
=> Remove editor.wordWrap from workspace settings

packages/server/graphql/mutations/inactivateUser.ts
Fixes #5832.
Notes on testing: please create a fresh new user, team and org locally. An existing user might be in the Parabol org that was restored from production DB, depends on your local setup. Since for local development we use the test Stripe key, it won't work if there are subscriptions initially created in production with a prod Stripe key.
Tests:
*   [ ] Go to organization page for a pro org, go to the Members tab. Toggle an active user to inactive, the toggle should stay greyed. In DB, this user should:
*    [ ]  have `inactive` property as true in `User` table
*   [ ] have `inactive` property as true for the `userId` & `orgId` pair in `OrganizationUser` table
=> Update dataLoader cache in inactivateUser mutation

packages/client/components/DashTopBar.tsx
This PR fixes the alignment of the logo in the dashboard's top bar, after the introduction of focus styles (#5607). The logo was pushed 8px to the right to allow for enough padding around:
Top was before, bottom is now.
Tested to make sure focus styles still work well and no issues are present on mobile views.
=> Fix alignment of logo

packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/modules/demo/initDB.ts
Fix retro demo task integrate menu, issue reported in #5826
For demo user we do not set assigneeTeamMember/viewerTeamMember and return here:
https://github.com/ParabolInc/parabol/blob/1766b647c835e7ac4ce1bda2bf0a8844441c01c3/packages/client/components/TaskFooterIntegrateMenu.tsx#L72
This PR adds  assigneeTeamMember and viewerTeamMember in TaskFooterIntegrateMenuRootQuery
- Ran reproduction steps in #5826
=> Fix retro demo task integrate menu

packages/server/package.json, yarn.lock
New version has upgraded dependencies which fix CVE-2021-33623.
Relates to https://github.com/ParabolInc/parabol/security/dependabot/yarn.lock/trim-newlines/open
=> Upgrade rethink-ts-migrate

packages/client/components/MeetingHelp/CheckInHelpMenu.tsx, packages/client/modules/email/components/TeamInvite.tsx
Resolves #5641
The problem existed only for poker meeting.
Also, fixed Icebreaker->Tips->Lean more link for poker meeting
* Create a new team
* Create a poker meeting
* Send an email invite
* See no `undefined` in email text
* Go to icebreaker step of a poker meeting on mobile view
* Click on Tips at the bottom menu
* Click Lear more
* See the link opened correctly
=> Fix undefined in team invitation email

packages/client/components/DashboardAvatars/DashboardAvatar.tsx
Fixed [Issue 5553](https://github.com/ParabolInc/parabol/issues/5553)
Had to change the PropType interface for `DashboardAvatar_teamMember` since the graphQL data structure could not be changed.
@jordanh
=> Fix empty name on tooltip when onboarding new member

packages/client/utils/AtlassianManager.ts
Partially fixes #5705. 
There are 2 issues there, actually. This PR fixes only the first one.
1. Time tracking fields require different body format when calling Jira API
2. When field isn't on the issue screen, our mechanism for automatically fixing that for user will fail, because `timeoriginalestimate` and `timeestimate` fields depend on the `timetracking` field being added to the issue screen. Interestin part is, when `timetracking` isn't added, but `timeoriginalestimate` is, it can't be updated via REST API, even though it can be, via Jira UI. 
More context: https://github.com/ParabolInc/parabol/issues/5705#issuecomment-1007501068 
This PR fixes 1, the second issue [has its own ticket.](https://github.com/ParabolInc/parabol/issues/5868)
Tests:
1. Make sure time tracking and original …
=> Fix Original Estimate field can not be updated in Sprint Poker

packages/client/components/AddTaskButton.tsx
This super tiny PR fixes the center alignment of the `Add task` button in `Discussions`. It removes a  `4px` left margin on the icon.
**Before**
**After**
=> Fix alignment of Add task button in discussions

packages/client/components/AddPollButton.tsx
Another tiny PR that removes a `4px` left margin from the icon of the `Add a poll` button. See #5876 for additional context
=> Remove 4px  left margin from Add Poll button

packages/server/database/migrations/20220112175838-addMissingPlainTextContentToTask.ts
#5438
How to test
1. If needed, remove some `plaintextContent`
```
r.db('actionDevelopment').table('Task').filter({
"meetingId": "put_your_own_value"
}).replace(r.row.without('plaintextContent'))
```
2. Run migration `yarn db:migrate`
3. Check that all tasks have `plaintextContent`
```
r.db('actionDevelopment').table('Task').filter(function (row) {
return row.hasFields({ plaintextContent: true }).not()
})
```
=> Add migration to fill missing plaintextContent for tasks

packages/server/graphql/httpGraphQLHandler.ts
In https://github.com/ParabolInc/parabol/pull/5830, I checked whether `connectionContext` was of type `ConnectionContext`, which is the type that `handleGraphQLTrebuchetRequest` is expecting. 
This broke the login & signup functionality as `connectionContext` can be of type `StatelessContext`. I've reverted the change. I haven't updated `handleGraphQLTrebuchetRequest` to expect `ConnectionContext | StatelessContext` yet as this will require many subsequent changes to the gql logic, which can be done in a separate PR.
I'll merge this PR right away as master is broken and this should fix it.
=> Reverted connectionContext type check

packages/client/components/Facilitator.tsx, packages/client/components/FacilitatorMenu.tsx
Implements #5531 .
Notice the implementation is a little bit different than the issue description as I feel like this is a less intrusive change that's safe to try: no new visual changes, just adding one more item to the existing menu.
Tests:
=> Implement choosing random person as facilitator

packages/server/graphql/mutations/inviteToTeam.ts
primisify returns any, thus a typo in `toString` was not caught.
Resolves: #5912
=> Fix type error in inviteToTeam

packages/server/pipeStreamOverResponse.ts, packages/server/safetyPatchRes.ts, packages/server/socketHandlers/handleUpgrade.ts
this guarantees that we no longer attempt to access responses that have already been disposed of.
it'll still emit a console log, but we can turn those off later & it'd be AOK.
instead of turning them off, i'm thinking we track both `done` and `aborted` booleans & only log if it is done but not aborted. that way we'll still get log statements when the handler isn't doing it right
=> monkeypatch uWS res.cork

package.json, packages/server/package.json, yarn.lock
"Medium security findings: jsdom: ^16.6.0, node-gyp: ^8.4.1"
Bumping jsdom to ^16.6.0 also fixed a high finding for `request` as 16.6.0 removed the request dependency
=> 6.44.0 ironbank fixes

packages/server/graphql/mutations/promoteToTeamLead.ts
Promoting someone who was previously removed from a team did not always work. 50% of the time, it worked all the time.
This fixes that.
TEST
=> promoteToTeamLead filters on isNotRemoved

packages/client/mutations/AcceptTeamInvitationMutation.ts
Follow up to https://github.com/ParabolInc/parabol/pull/5683#issuecomment-983006254
* open two browsers with 2 parabol accounts Alice and Bob
* send an invite from Alice to Bob
* Bob accepts invite
* Without refresh Alice can see that Bobs avatar appears in the upper right panel and on hovering Bobs name is shown
=> Make dependency from DasboardAvatar to AcceptTeamInvitation explicit

packages/client/components/PokerDimensionValueControl.tsx, packages/client/components/PokerDiscussVoting.tsx, packages/client/components/useSetTaskEstimate.ts
This should fix both: #5508 #5846
How to test:
- Create poker meeting
- Add Jira integration
- Go to https://parabol-2.atlassian.net/secure/admin/ConfigureFieldScreen.jspa?id=10065 and remove `Story Points` field
- Add the following task https://parabol-2.atlassian.net/browse/FIXCOMP-1
- Enter any estimation, select `Story points` field, click `update` link, see fix field dialog appeared, see the field fixed correctly
- Go to https://parabol-2.atlassian.net/secure/admin/ConfigureFieldScreen.jspa?id=10065 and remove `Story Points` field again
- Estimate the above task again, but now click on mini card to update the score.
- See fix field dialog appeared, see the field fixed correctly
=> Fix missing jira field dialog on mini card click

packages/client/hooks/useScrollIntoVIew.ts, packages/client/modules/meeting/components/ReflectTemplateItem.tsx, packages/client/modules/meeting/components/ReflectTemplateList.tsx
fix for #5920
TEST
loom here: https://www.loom.com/share/69ecc2234fe64a3fbef064a064ffc457
=> fix retro template scrolling

packages/client/components/SAMLRedirect.tsx
One of our customers is using google apps which is opening parabol with a `window.opener` which is a huge vulnerability to them trusting that we won't send any phishing attacks their way. There's no risk to us, but it does cause a bug with logging in because we assume that if something opened up the login page in a popup, we should close that popup.
This fix addresses that problem & makes sure that the thing that opened the login page is from the same origin.
AC
```html
<html>
<body>
<button onclick="NewTab()">Parabol</button>
<script>
function NewTab() {
window.open(
"http://localhost:3000/saml-redirect?token=badToken"
);
}
</script>
</body>
</html>
```
=> ensure window.opener is same-origin

packages/client/mutations/AddAgendaItemMutation.ts, yarn.lock
Fixes #5400.
This was a fun one. I went through the whole process of team subscriptions, updating the relay store, checking how `isInterruptingChickenPhase` works to find out that `AddAgendaItemMutation` does not fetch data needed to check if stage `isNavigable`. As a result, `navigateMeetingTeamUpdater` was updating the relay store with data that wasn't enough to handle navigation in some cases.
=> Added needed data dependencies to add agenda item mutation result

packages/client/components/EmptyDropdownMenuItemLabel.ts, packages/client/components/GitHubScopingSearchFilterMenu.tsx, packages/client/components/GitHubScopingSearchHistoryMenu.tsx, packages/client/components/JiraScopingSearchFilterMenu.tsx, packages/client/components/JiraScopingSearchHistoryMenu.tsx, packages/client/components/NewGitHubIssueMenu.tsx, packages/client/components/NewJiraIssueMenu.tsx, packages/client/components/SearchMenuItem.tsx, packages/client/components/TaskFooterIntegrateMenuList.tsx, packages/client/components/TeamDashTeamMemberMenu.tsx, packages/client/components/UserDashTeamMemberMenu.tsx, packages/client/components/UserDashTeamMenu.tsx, packages/client/hooks/useSearchFilter.ts, packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterTeamAssigneeMenu.tsx, packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx
fixes https://github.com/ParabolInc/parabol/issues/5777.
Adds search functionality to the team / team member filter dropdowns.  This is done by creating a couple of new things:
* A `SearchMenuItem` component - a styled menu label that accepts text input
* A `useSearchFilter` hook - A hook that takes in an array of items and a function for getting a string value of those items, and returns:
* An `onQueryChange` handler - Takes a query string.  Pass this as `SearchMenuItem`'s `onChange` handler, or any other text input.
* `filteredItems` - An array of items that match the query string
* `query` - The last query passed to `onQueryChange`.
These patterns are based on the [filtering logic](https://github.com/ParabolInc/parabol/blob/2d134896d2da154b34fc80a5025022a63cd35a4b/packages/client/compon …
=> Add string filtering to team / team member filter dropdowns

packages/client/components/GroupingKanban.tsx
There is nothing obvious causing this issue and I couldn't reproduce it. Handle the error for now so the client is not affected but still track the error in Sentry so we can eventually find the root cause.
Resolves: #5902
=> Workaround for null reflections in GroupingKanban

packages/client/components/ErrorBoundary.tsx, packages/client/components/ErrorComponent/ErrorComponent.tsx, packages/client/utils/isOldBrowserError.ts
Fix #5995 
Once we have an idea of the expected number of fatal bugs per 1,000 sessions, we could send a notification to Slack when there's a sudden sharp increase.
I created a chart in amplitude to track this: https://analytics.amplitude.com/parabol/chart/8m2qx3s
- add the segment env vars
- add a fatal bug, e.g. add an undefined variable to the `TimelineEventCard` component, and then visit the Timeline page at `/me`
- search for your `userId` in amplitude and see that the `Fatal Error` event has been tracked
=> Track fatal bugs per 1,000 sessions

packages/client/Atmosphere.ts, packages/client/components/AnalyticsPage.tsx
This PR adds logic to identify users with Datadog, so we can easily see their IDs in the Datadog UI. Here's an example of me running this code locally:
=> feat(dd-rum): identify user on Datadog session

packages/client/modules/userDashboard/components/CreditCardModal/CreditCardForm.tsx, packages/server/graphql/mutations/updateCreditCard.ts, yarn.lock
Fix #5905
Updating credit cards did not show an error message
TEST
=> send CC error message to client

CHANGELOG.md, packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx, packages/client/mutations/PromoteToTeamLeadMutation.ts, packages/server/graphql/mutations/promoteToTeamLead.ts
when a user accepts a team invite we don't request their email, which means calls `promoteToTeamLead` has email == null.
we could either request their email, or use the userId of the person we want to join.
Since the userId is always requested, seems like that is a little more robust than having to remember to always request the email any time a new TeamMember object is created in the app.
fixes issues discovered in https://github.com/ParabolInc/parabol/issues/6074#issuecomment-1042367499
=> replace email with userId as ID for promoteTeamMember

packages/client/components/PokerEstimateHeaderCardJira.tsx, packages/client/components/ThreadedCommentBase.tsx, packages/client/components/ThreadedCommentHeader.tsx, packages/server/dataloader/customLoaderMakers.ts, packages/server/graphql/rootSchema.ts, packages/server/graphql/types/Task.ts, packages/server/package.json, yarn.lock
Fix #6024
Fix #6015 
Fix #6023
Our big poker meeting shined the light on some big bugs!
- If 2 fragments have a field with the same name but a different type, then 1 or both must be aliased. `_xGitHubIssue.url` is a `_xGitHubURI` whereas `JiraIssue.url` is a `string`. Since we use graphql-jit, our server technically doesn't perform this validation so we could keep getting away with it, but while debugging I like to remove graphql-jit to get better stack traces so I figured it was a good time to fix it. The same goes for a nullable vs. non-null type, as see in  `createdByUser` (since that can be null for a comment but non-null for a poll or task)
- The above bug showed me that nest-graphql-endpoint couldn't handle client-aliased fields. The workaround is to edit the default resolver for …
=> fix unresponsive github poker meeting

packages/server/graphql/traceGraphQL.ts
Errors thrown in resolvers were swallowed silently when tracing is
enabled.
=> Rethrow exceptions in traceGraphQL

packages/client/components/GitLabScopingSearchResults.tsx, packages/client/components/GitLabScopingSearchResultsRoot.tsx, packages/client/components/ScopePhaseAreaGitLab.tsx, packages/client/components/ScopePhaseAreaGitLabScoping.tsx
Fix https://github.com/ParabolInc/parabol/issues/6034
This PR grabs the issues from GitLab and renders them in a list. The fancy stuff will be handled in https://github.com/ParabolInc/parabol/issues/6088
This PR includes a lot of commented out code which will be needed in #6088 and beyond. 
- Integrate with GitLab (you may need to add the feature flag if you can't see GitLab in the integration provider row)
- Make sure you're part of the GitLab team Parabol1
- Create a Sprint Poker meeting, go to the Scope phase, and click the GitLab icon
- See the GitLab issue titles in a list
=> Display GitLab issues in Sprint Poker

packages/server/jest.config.js, packages/server/package.json, yarn.lock
@igorlesnenko ran into some issues on his PR (#6092) where `jest` was throwing this error in [CI](https://app.circleci.com/pipelines/github/ParabolInc/parabol/4405/workflows/c60f5290-e766-485c-a1eb-e0cf00d53f7d/jobs/13207):
```console
FAIL  dataloader/__tests__/usersCustomRedisQueries.test.ts
● Test suite failed to run
Cannot find module '~/shared/gqlIds/JiraProjectId' from 'integrations/JiraTaskIntegrationManager.ts'
Require stack:
integrations/JiraTaskIntegrationManager.ts
integrations/TaskIntegrationManagerFactory.ts
dataloader/jiraServerLoaders.ts
dataloader/RootDataLoader.ts
graphql/getDataLoader.ts
dataloader/__tests__/usersCustomRedisQueries.test.ts
1 | import makeCreateJiraTaskComment from '../utils/makeCreateJiraTaskComment'
> 2 | import JiraProjectId from …
```
=> build(server): fix jest transforms

CHANGELOG.md, lerna.json, package.json, packages/gql-executor/package.json, packages/integration-tests/package.json, packages/server/package.json, yarn.lock
This hotfixes the issue where github poker meetings with 2+ dimensions don't load the issues from github
=> bump nest-graphql-endpoint

packages/server/database/migrations/20220222141104-updateThreeLittlePigsPromptColors.ts
Fixes #4703 
Test steps:
1.  Pull down the branch and run `yarn dev`
2.  Migration should run: \[migrate-rethinkdb\]  ↑  up  ↑  20220222141104 updateThreeLittlePigsPromptColors
3.  In the template picker for retro meeting, select Three Little Pigs from Public templates, see the correct color should be present.
=> Add migration to update prompt colors for Three Little Pigs template

packages/client/components/PokerSidebarEstimateSection.tsx, packages/client/components/RetroSidebarDiscussSection.tsx, packages/client/components/TimelinePriorityTasks.tsx, packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/modules/demo/LocalAtmosphere.ts, packages/client/modules/meeting/components/TemplateDimensionList.tsx, packages/client/modules/meeting/components/TemplatePromptList.tsx, packages/client/modules/meeting/components/TemplateScaleValueList.tsx, packages/client/modules/teamDashboard/components/AgendaList/AgendaList.tsx, packages/client/utils/constants.ts
Fixes #6029.
The issue is that when an item is dropped to its original position or somewhere invalid, the `destination` will be `null`. See this [discussion](https://github.com/atlassian/react-beautiful-dnd/issues/558#issuecomment-399205587).
Tests:
=> Fix a bug where dragging item to original position cause an error

packages/client/hooks/useMakeStageSummaries.ts, packages/client/mutations/UpdatePokerScopeMutation.ts, packages/server/graphql/mutations/updatePokerScope.ts, packages/server/graphql/types/UpdatePokerScopePayload.ts
fix #6043
Before, every add/remove to the poker scope would trigger a refetch of all stages, including the task for that stage, which included the integration associated with that task. That means if I had 50 stages & removed one, it'd reach out to jira or github 49 times just to remove the stage!
Now, it only reaches out to integrations for new stages, which makes sense because it needs to grab the title, description, etc. 
For removals, it doesn't reach out to any integrations.
TEST
=> fix #6043 only fetch new tasks

packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts
fix #5985
SAMLRequest isn't required by all IdPs, but it does not harm to include it for all, so that's what this does.
Note this does NOT adjust the SAML records that have already been created. If some are broken there, we'll have to manually update them.
TEST
=> always create samlrequest

packages/server/dataloader/atlassianLoaders.ts, packages/server/utils/atlassian/jiraFields.ts
Fix #5864
This removes the aggregated fields from the dropdown. Those fields are calculated & read-only, anyways.
TEST
- Look at the screenshot. no fields start wtih a big sigma
=> fix(jira): remove calculated fields from dropdown

packages/server/graphql/mutations/addTeam.ts, packages/server/graphql/mutations/createReflection.ts, packages/server/graphql/mutations/updateTaskDueDate.ts, packages/server/graphql/mutations/updateTeamName.ts, packages/server/graphql/types/CreateReflectionInput.ts, packages/server/graphql/types/NewTeamInput.ts, packages/server/graphql/types/UpdatedTeamInput.ts
=> Fix type mismatch GraphQL

packages/client/components/MeetingSelector.tsx, packages/client/components/TeamPromptMeeting.tsx
Fixes #5932, #5933 
This PR adds an empty implementation of `TeamPromptMeeting` component and handling of a new meeting type in the `MeetingSelector`. Not much to review here, as the main purpose is to unblock the work on the UI of standups while the backend is still in progress.
=> feat(standups): Added empty team prompt meeting component

packages/client/types/constEnums.ts, packages/client/utils/constants.ts
Added comments on future direction of how we handle string constants, const enums, enums, etc.
In the bad old days, we didn't use typescript, so string constants were a nice way to avoid typos.
They're still good for naming hard-to-name things like color hex values.
Typescript enums are not equivalent to their string counterparts. For example, if something expects a string union, you can't pass in an enum, even if the underlying values are the same! So, they're not as useful as we once thought.
So as a rule of thumb:
- if the value comes from the server, try to reference it from that instead of making a second source of truth on the client
- If a value can be a string union, try to do that
Still not sure about all the best practices, but it's a start 🤷
=> chore(comments): future of constants on client

packages/server/postgres/migrations/1647259140753_dropMattermostAuthTable.ts
The table was unused since #5829.
https://github.com/ParabolInc/parabol/blob/eb295331feba7e2534c48012d252c2a52b802905/packages/server/postgres/migrations/1640229261909_mattermostToIntegrationsTables.ts#L72
Now is later.
=> chore: Drop unused MattermostAuth table

packages/server/dataloader/customLoaderMakers.ts, packages/server/graphql/intranetSchema/mutations/draftEnterpriseInvoice.ts, packages/server/graphql/queries/organization.ts, packages/server/graphql/types/User.ts, packages/server/utils/authorization.ts
I realized i couldn't get the name of an organization from graphiql, now i can.
TEST
```gql
viewer {
organization(orgId: "foo") {
name
}
}
```
=> feat(analytics): support querying organization for superusers

packages/server/database/migrations/20170516165400-backfillInvoices.js
Migration is many years old and the used stripe manager was deleted in
PR #6161.
=> chore: Remove backfilling invoices logic from migration

.circleci/config.yml, docker-compose.yml, packages/server/postgres/Dockerfile
I noticed today that CircleCI started badging our builds with this warning about using deprecated images ([link from screenshot](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034)).
We just needed to switch over to using the official postgres image vs. the `circle/` prefixed one.
=> ci: use official postgres image & sync with digital ocean version

.husky/post-commit, package.json
This PR removes the `postcommit` hook to call `git update-index` because it slows down git operations like `rebase`. According to @mattkrick - this used to be required by JetBrains IDEs, but we don't need it anymore.
=> chore: remove postcommit git command

packages/server/graphql/mutations/setOrgUserRole.ts
This change will allow admin users to set org billing users using the following mutation
```
mutation {
setOrgUserRole(orgId: "orgId", userId: "local|botpRdWlzi", role: "BILLING_LEADER") {
updatedOrgMember {
user {
email
}
}
}
}
```
context: https://parabol.slack.com/archives/C4JAUUZ9P/p1646147430342679
=> Allow admins to call set org user role mutation

packages/server/graphql/InMemoryRateLimiter.ts, packages/server/graphql/__tests__/InMemoryRateLimiter.test.ts, packages/server/graphql/getRateLimiter.ts, packages/server/graphql/graphql.ts, packages/server/graphql/rateLimit.ts
This PR supersedes #6063. Instead of choosing between a StubRateLimiter and an InMemoryRateLimiter, we just disable it when `NODE_ENV` is `test`. See https://github.com/ParabolInc/parabol/pull/6063/files#r814362740 for details.
Relates to https://github.com/ParabolInc/parabol/issues/6018
=> feat: disable rate limiter in test

.github/workflows/validate_pr_title.yml
This PR adds a GitHub Actions workflow to enforce conventional commit-style PR titles. See [the governance doc (🔒)](https://www.notion.so/parabol/conventional-commit-style-Pull-Request-titles-b70e585fcf084e0f8f9f22e74594f70c) for details on this decision.
=> chore: enforce conventional commit PR titles

packages/server/email/ServerEnvironment.ts, packages/server/graphql/mutations/helpers/softDeleteUser.ts, packages/server/graphql/private/rootSchema.ts, packages/server/graphql/resolveTypesForMutationPayloads.ts, packages/server/utils/updateHubspot.ts
root cause fix #6268
This bug was caused because graphql couldn't figure out if a mutation returned an error or a success.
TEST
```gql
mutation {
enableSAMLForDomain(name:"foo", domains:["foo.co"], metadata: "as") {
__typename
... on ErrorPayload {
error {
message
}
}
}
}
```
=> fix(sdl): Default resolveType on mutation payloads

docs/serviceDiagram.md
I created a diagram to help me understand how we're using the different
redis channels to connect the server with the GQL executor.
Relates to: #5910
=> Add flow diagram for services

packages/server/graphql/mutations/pokerResetDimension.ts, packages/server/postgres/queries/generated/removeMeetingTaskEstimatesQuery.ts, packages/server/postgres/queries/removeMeetingTaskEstimates.ts, packages/server/postgres/queries/src/removeMeetingTaskEstimatesQuery.sql
Fixes #6243
Currently, the `removeMeetingTaskEstimates` query called by the `pokerResetDimension` mutation performs a deletion on any task estimate in the meeting, not just the task estimate in the meeting for the current stage.
Modify the `removeMeetingTaskEstimates` to take a `stageId` param and only delete rows with that stage.
Test:
* Perform the setup steps in #6243 up to revoting on the third task
* Click revote, confirm that the current estimation is reset
* Refresh the page, confirm the current estimation is reset, and confirm that the first two tasks are still scored
* Score the third task, refresh the page, and confirm that the first two tasks are still scored, and the third task has the new score
* End the meeting, and confirm that all tasks are correctly scored in the summary
=> fix(sprint-poker): Only reset current estimation stage on revote

packages/client/components/ScopePhaseArea.tsx
debugging poker scoping issues sucks when you have to keep clicking a tab after refresh.
TEST
=> feat(integrations): save favorite integration to local storage

packages/client/components/GitLabScopingSearchResults.tsx, packages/server/graphql/public/rootSchema.ts, packages/server/graphql/public/types/_xGitLabProject.ts, packages/server/graphql/public/types/_xGitLabQuery.ts
This fixes that problem where fullPath was required on the client side.
adding fullPath to the client didn't actually fix the problem, it just masked it.
full loom here: https://www.loom.com/share/79e4d705572c40bdba449b12bc3250b7
=> fix(gitlab): add proper client-side alias handling

docs/serviceDiagram.md, packages/client/shared/gqlIds/GQLExecutorChannelId.ts, packages/client/shared/gqlIds/SocketServerChannelId.ts, packages/client/shared/gqlIds/SocketServerId.ts, packages/client/types/constEnums.ts, packages/gql-executor/README.md, packages/gql-executor/gqlExecutor.ts, packages/server/graphql/ResponseStream.ts, packages/server/utils/PubSubPromise.ts, packages/server/utils/getGraphQLExecutor.ts, packages/server/utils/publish.ts
before, a graphql executor would send the response payload to a fixed server (because the channel name was static).
now, it sends it to the server that requested it.
I also renamed `serverChannel` to `executorChannel` since that could get ambiguous.
=> feat(scale): give a pubsub channel to each socket server

tsconfig.base.json
This setting influences truncation from TSServer in hover and error
messages.
=> chore(dx): Don't truncate TypeScript types

packages/server/graphql/mutations/createTask.ts
At the moment we do not know how many users use the "Add issue" fab in
Poker meetings to create new tasks in their integration. Add the
integration field in the segment message to track it.
=> chore: Track integrations in createTask

packages/client/components/NullableTask/NullableTask.tsx, packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx, packages/client/package.json, yarn.lock
successor: #6282 
fixes:  #1450
Always display a "no more items" message (for simplicity and UX consistency) when the user reaches the end of the archive, even if there is no scroll in the archive (few cards).
few cards
many cards
=> feat: Display a message when there are no more items to paginate

packages/client/components/MeetingTopBar.tsx, packages/client/components/TeamPrompt/TeamPromptOptions.tsx, packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx, packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
fixes https://github.com/ParabolInc/parabol/issues/6199
Current behavior is to end the meeting, but stay on the meeting page.  After meeting is ended, "End Meeting" button is still present, but disabled.
(commits https://github.com/ParabolInc/parabol/commit/f0635559c344aacda1bdbcc76763b97095c56f4b and later are the relevant ones; the diff against https://github.com/ParabolInc/parabol/pull/6336's branch is inaccurate due to the merge from `master`)
Needs rebase after https://github.com/ParabolInc/parabol/pull/6336 is merged.
https://www.loom.com/share/b1871e6f2f29435f84e83e570e2db457
=> feat(standups): Options menu - end meeting

packages/client/components/ScopePhaseArea.tsx
Fix https://github.com/ParabolInc/parabol/issues/6440
In a previous PR, I used the non-null assertion to fix the eslint complaint that we could return null before a hook. Matt mentioned that we could ignore the eslint complaint and return null if `viewerMeetingMember` is undefined. 
Unfortunately, while I made the change in that PR, a subsequent PR built off of that branch must have still included the change. This PR reverts that change. 
I'd like to get this PR merged into master before the ship on Wednesday. As the change is trivial and the urgency is high, I'll request a review from a Maintainer.
https://www.loom.com/share/3fdd2fbb01ef42a9a7691f9c1132a276
=> fix: viewerMeetingMember can be undefined

packages/server/postgres/utils/__tests__/checkEqBase.test.ts, packages/server/postgres/utils/checkEqBase.ts
unlock: #6239 
`checkRethinkPgEquality` should handle cases where the fields are an array with different element order.
=> fix: ignore comparison order for equality

packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/components/promptResponse/PromptResponseEditor.tsx
fixes https://github.com/ParabolInc/parabol/issues/6202
~**Do not merge until https://github.com/ParabolInc/parabol/pull/6353 lands**~ ✅ 
Basic response cards.
A couple things left out of scope because the backend isn't yet implemented:
* Hooking cards up to responses from the backend (just the team member associated with the stage) - this should be easy once the data loading implemented in https://github.com/ParabolInc/parabol/pull/6333 lands.
* Showing when the response was last updated - this data isn't actually included on the response object as-is.  Maybe we pull this into its own issue?
Blank responses for viewer + other member:
Filled response for other member:
Filled response for viewer:
https://www.loom.com/share/4e5919b191db469ebe1ba4619cf6b22d
=> feat(standups): Response Cards

packages/client/clientSchema.graphql, packages/client/components/ActionMeetingAgendaItems.tsx, packages/client/components/DiscussionThread.tsx, packages/client/components/DiscussionThreadList.tsx, packages/client/components/DiscussionThreadRoot.tsx, packages/client/components/EstimatePhaseDiscussionDrawer.tsx, packages/client/components/RetroDiscussPhase.tsx, packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/server/graphql/mutations/addComment.ts
fixes https://github.com/ParabolInc/parabol/issues/5796
Mobile design impl is the same as the reduced space case per [this discussion](https://parabol.slack.com/archives/C039L3XG6BH/p1649356110824849) (vs. the mobile design impl in Figma)
https://www.loom.com/share/5282c3ac078d4bfba9b8f8ca74bb4065
Test:
* Discussion drawer opens when placeholder icon is clicked
* User can interact with the discussion thread
* Add comments
* Add task
* React to comments
* Reply to comments
* Drawer closes when the top right close icon is clicked
* Drawer overlays the rest of the meeting space when space is limited
=> feat(standups): Discussion Drawer

packages/server/graphql/graphQLSubscriptionType.ts
When a subscription union is extended via SDL, it wasn't resolved
properly. Query the schema for non-abstract object types and return
those directly solves it for this use case.
=> fix(SDL): Resolve subscription payload type

packages/integration-tests/playwright.config.ts, packages/integration-tests/tests/config.ts
This PR allows us to run the integration test suite against a different HOST (other than `localhost`). See inline comments for details.
=> fix(integration-tests): support running integration tests against another env

packages/server/package.json, yarn.lock
this bumps some dependencies in rethinkdb-ts-migrate to get rid of the dependabot errors.
we couldn't merge the dependabot fixes because our versions were too old
=> chore(deps): bump rethinkdb-ts-migrate

packages/server/graphql/types/Company.ts
Fixes #6225 
Test steps:
1.  Create a new org and 2 new teams under it
2.  In RethinkDB, manually update the org's domain to something else: `r.db('actionDevelopment').table('Organization').get('xxx').update({activeDomain: "abcd.com"})`
3.  Run a meeting in one of the new team
4.  Run GraphQL query in admin console and observe the count should be 1 (in `master` branch this will return 2):
```graphql
query {
company(domain: "abcd.com") {
activeTeamCount
}
}
```
=> fix(metrics): activeTeamCount resolver in Company GraphQL type should not count inactive teams

package.json, packages/client/package.json, packages/gql-executor/package.json, packages/server/__tests__/globalSetup.ts, packages/server/graphql/private/mutations/enableSAMLForDomain.ts, packages/server/graphql/private/typeDefs/_legacy.graphql, packages/server/graphql/private/typeDefs/enableSAMLForDomain.graphql, packages/server/package.json, packages/server/tsconfig.json, yarn.lock
fix #6327
fix #6409
enableSAMLForDomain had some bugs in it:
- you could register a domain for multiple different clients
- you couldn't just update the domains without also including the metadata, or vice versa
Fixing this also exposed a bug in typescript not employing strictNullChecks, so that's fixed here, too.
TEST
=> feat(enableSAMLforDomain): support updates

packages/server/database/types/GenericMeetingStage.ts, packages/server/graphql/mutations/helpers/removeUserFromMeetingStages.ts, packages/server/graphql/types/NewMeetingStage.ts
`readyToAdvance` field of `GenericMeetingStage` can be undefined. This
was already checked in multiple parts of the codebase. Fixed the type
accordingly and `removeUserFromMeetingStages`.
I'm not perfectly clear how the `readyToAdvance` field gets lost, but we have such data in Rethink, thus it's better to have the code prepared for it.
=> fix: hardDeleteUser failed because readyToAdvance is undefined

packages/client/modules/email/components/TeamInvite.tsx
Fixes #6498 
Tests:
1. Invite a user via email
2. Click the links in the invitation email and verify the URL contains `?utm_source=invite+email&utm_medium=email&utm_campaign=invitations`
=> fix(metrics): add UTM parameters to URLs in team invitation emails

docs/codeReview.md
This PR is a result of code review brainstorming sessions with @nickoferrall and @Dschoordsch.
The changes introduced here add more explicit statements about what's ok when doing the code review or when submitting a PR etc. I believe it's beneficial to have things written down explicitly. 
Let's discuss!
=> docs: Added general rules to code review policy

docs/codeReview.md
This PR is a result of code review brainstorming sessions with @nickoferrall and @Dschoordsch.
The proposal comes from the tension that we're not iterating fast enough, especially when working on the new features. We spend a lot of time making our code perfect not even knowing if the feature we're working on will be useful to anyone. When things are not related to architecture or existing client-facing functionality we should be more comfortable with shipping not perfect code in exchange for being able to validate ideas/features faster. 
Let's discuss!
=> docs: Added code review experiment proposal

.github/workflows/labeler.yml
As we agreed here it'd be good to add size labels to our PRs. This PR adds usage of [Pull Request size labeler workflow](https://github.com/marketplace/actions/pull-request-size-labeler). Feel free to comment on the config, ie. what we consider a big PR etc. thank you!
=> chore: added PR labeler workflow

packages/server/postgres/utils/checkTeamEq.ts
As part of #6239 struggle, we encountered the fact that Postgres & RethinkDB store "Team" records with `updatedAt` that differ by about a year. 
This appears to be because the system does not always update the `updatedAt` field of Postgres or RethinkDB in some cases. This will be fixed in a separate PR.
Therefore, we can skip checking the `updateAt` field for the time being when comparing records.
https://github.com/ParabolInc/parabol/pull/6239#discussion_r863572037
=> fix: ignore updateAt field in checkTableEq for Teams

packages/client/components/ArchiveTaskRoot.tsx, packages/client/components/ArchiveTaskUserRoot.tsx
By default, the system loads only the first 10 archived tasks, which is quite small even for the first screen without scrolling (related to #6536).
<a href="https://www.loom.com/share/25d04129fbc44d16b899b29c15d3a551">
<p>Archived tasks- 13 May 2022 - Watch Video</p>
</a>
=> fix: increase initial page size for archived tasks

packages/client/components/DueDatePicker.tsx
Resolves:
* #6580 
Once the due date was advanced to a certain month, it could not be set
to a previous one again, see
https://react-day-picker.js.org/api/interfaces/DayPickerProps#frommonth
for reference.
=> fix: Due date month could sometimes not be set to the current month

packages/client/components/TopBarSearch.tsx
This is a first steps to fix: #6536 
Case: the search control disappears on the page for archived tasks, but still applies to them...
<a href="https://www.loom.com/share/f617869b1ab347d2ab8907c61538599d">
<p>Disappearance of search control 🔍 - Watch Video</p>
</a>
=> fix: display search on archived tasks page

.github/pull_request_template.md
Path wasn't adapted after the template was moved.
=> docs: Fix code policy link in PR template

.github/workflows/labeler.yml
This is an attempt to fix our workflow for labeling PR sizes automatically. 
I'm not sure if it'll fix the problem but 🤞
=> fix: added write permission to pull request labeler workflow

packages/server/utils/AzureDevOpsServerManager.ts
Fixes #[6509]
Modifies the AzureDevOpsServerManager to send html formatted comments to Azure DevOps instead of markdown.  This has a better user experience in Azure DevOps.
- Import any Azure DevOps work item
- Add a story point estimate value
- Set the dropdown to a "Comment" to push the value of the story point to the work item's comment section in Azure DevOps
- Navigate to the work item in Azure DevOps and open it.  Make sure that a comment was created from the Parabol client in html format.
=> feat(Azure DevOps):  Correctly format Sprint Poker comments as HTML

packages/server/postgres/utils/checkTeamEq.ts
Partially Fixes #6239  / Part of #6239
See https://github.com/ParabolInc/parabol/pull/6239#issuecomment-1130326877
- Run an equality check on the production database.
- Team records with the default value of `isOnboardTeam` should be successfully compared.
=> refactor: handle default value for isOnboardTeam in checkTeamEq

packages/client/components/AzureDevOpsSVG.tsx
```
Warning: Invalid DOM property `stop-color`. Did you mean `stopColor`?
```
Happens in both Sprint Poker view and Teams->Integrations when one has Azure DevOps enabled.
=> fix: stop-color warning in SVG

packages/client/components/TeamPrompt/TeamPromptOptions.tsx, packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Fixes #6583 
Widest breakpoint
Medium breakpoint
Mobile
=> feat(standups): Display active users and invite button in standup meeting

packages/client/mutations/UpdatePokerScopeMutation.ts, packages/server/graphql/mutations/updatePokerScope.ts
Fixes #6334 
Minified exception occured on production because all exception messages are stripped out. When adding and removing issues in fast succession, it could happen that the optimistic updater throws an error because the store is in a weird state. This fix just works around this particular case but does not fix the root cause.
This is how I was able to reproduce it before the fix:
https://www.loom.com/share/f2990f1feab448bca0d50190e67a16d5
I needed to repeat this a couple of times, it was not easily reproducible.
I tested with Jira as GitHub was probably bottlenecked by the server which resulted in different server side errors.
- Add and remove tasks in quick succession
- No error is shown
- Add remove more than 5 items in 10s (individual operations)
- The server will not print an …
=> fix(Sprint Poker): An exception could occur when modifying the scope in fast succession

packages/client/components/TeamPrompt/TeamPromptOptions.tsx
Fixes #6616 
Changes:
1. Added support for `active` and `focus` styles so it's easier to navigate using the keyboard
2. Changed the styles to match the back button used in the top bar 
3. Increased icon size
Note: I didn't add any breakpoints for icon size as I wanted to make it work the same way as the existing back button. The size of the icon was increased, IMO it looks good on both mobile and desktop. 
https://user-images.githubusercontent.com/1017620/170276983-c6b9e653-13cc-4295-b370-be91255d1de1.mp4
=> feat(standups): Improved standups options button size

codegen.json, packages/client/components/TeamPromptMeeting.tsx, packages/client/mutations/UpdateMeetingPromptMutation.ts, packages/client/subscriptions/MeetingSubscription.ts, packages/server/database/migrations/20220524131406-addPromptToTeamPrompt.ts, packages/server/database/types/MeetingTeamPrompt.ts, packages/server/graphql/mutations/startTeamPrompt.ts, packages/server/graphql/public/mutations/updateMeetingPrompt.ts, packages/server/graphql/public/typeDefs/updateMeetingPrompt.graphql, packages/server/graphql/public/types/UpdateMeetingPromptSuccess.ts, packages/server/graphql/types/TeamPromptMeeting.ts
refs https://github.com/ParabolInc/parabol/issues/6584
Full "update prompt" mutation w/ basic UI.  The proper UI (full modal w/ static suggestions) will come in a follow-on PR.
In an effort to get this feature partially landed by the next release, and because this is still behind a feature flag, anything related to a "good" UI is outside the scope of this PR.  As a result, while the non-facilitator view should be unchanged, the facilitator's view of the prompt may seem a bit janky.  Additionally, most (all?) of the changes to `packages/client/components/TeamPromptMeeting.tsx` will be short-lived (only until the UI PR lands).
See https://github.com/ParabolInc/parabol/pull/6625/commits/993d027785be822e39b41a506fd61878e2d73e1f and later commits for context on how the UI will change to match …
=> feat(standups): Basic editable prompt

packages/client/components/TeamPrompt/TeamPromptLastUpdatedTime.tsx
=> feat(standups): Update relative `createdAt` automatically

packages/client/mutations/UpdatePokerScopeMutation.ts
Fixes #6231 
The bug itself was caused by meeting subscription updating the relay store with no fully populated data. `UpdatePokerScopeMutation` didn't include data needed for `useInitialSafeRoute` and `useUpdatedSafeRoute` hooks to work. `facilitatorStageId` was undefined after the update and as a result, the facilitator was kicked off the meeting. 
https://user-images.githubusercontent.com/1017620/171653362-24ce2b37-cc41-4028-b9cd-4bfa97568678.mp4
Doesn't really matter what integration is used, the scenario described in #6231 was true for all existing integrations.
=> fix(sprint-poker): Prevent kicking facilitator off the meeting while modifying the scope

packages/server/database/migrations/20210602120505-addAdditionalRetroTemplates.ts, packages/server/database/migrations/20220124600507-addMoreRetroTemplates.ts, packages/server/database/migrations/20220602164119-fixRetroTemplates.ts
Fixes #6666
Some prompts were missing because of an `id` clash with existing
prompts because the `id` was purely generated from the question itself.
Changed it to be generated including the `templateId`.
New meeting dialog, choose Retro and switch template. "SaMoLo" and "Keep, Problem, Try" have 3 prompts each matching their name.
=> fix(Retro Templates): Added missing prompts

packages/client/utils/AtlassianManager.ts, packages/server/graphql/mutations/addMissingJiraField.ts
Fixes #6675
In this PR:
- I increased number of screens we fetching to 2000 as it is not possible to filter them by `projectId` using API
- I'm trying to fix only screens with high probability, to avoid possible timeout errors while iterating everything
- I request screen tabs as we go, to reduce potential number of API requests. 
- I assume that required screen will be fixed first in most cases, otherwise I suggest it is better to show a meaningful error instead of timeout
- Added more logging
How to test:
- Create a new company-managed project in Jira
- Try to estimate any issue with Story points
- See that Fix field dialog works fine and fixes the field
=> fix(jira): Handle a case with a huge number of Jira projects and avoid timeout error when trying to fix Jira field automatically

packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
Partially Fixes `Standups: Improve mobile experience #6601`
The issue is caused by mobile browser not taking into account the top/bottom bars of their UI into calculating units like `vh`.
The quickest fix is to use `lvh` on mobile as it fixes exactly that problem.  More info: https://css-tricks.com/the-large-small-and-dynamic-viewports/. The support isn't great right now but it works on the new mobile browsers. For everything else, the behavior will stay as it is now. 
Before
After
=> fix(standups): Discussion thread drawer is cut off on mobile

docs/codeReview.md
Today, our sprint board implicitly couples 1 issue to 1 PR.
For example, we might see an issue in the "reviewer review" column.
It's not actually the _issue_ that is under review, rather it is the PR that fixes that issue.
This is important because 1 PR might resolve multiple issues.
if a PR resolves 3 issues, would all 3 issues have to go under "reviewer review"? If it fails to resolve 1 of the issues, does that single issue get moved back to "In Progress" after the PR is merged?
What if 2 PRs are required to resolve 1 issue? Would we merge the PR & move that issue back to "In Progress"? That's not an accurate representation of the work that's being accomplished.
By making sure only PRs go in the "Review" columns, we know 1 card = 1 review needed.
=> docs(codeReview): Decouple PRs from Issues

CHANGELOG.md, lerna.json, packages/gql-executor/package.json, packages/server/database/migrations/20220610093935-fixRetroPromptIds.ts, packages/server/package.json
Fixes #6714 
The updated reflection prompts got a new id which was not updated in the
reflections themselves. Also there is some filtering happening based on
the template creation date which messed up pre-release retrospectives.
Without this PR on master do
* create a meeting before running the migration `packages/server/database/migrations/20220602164119-fixRetroTemplates.ts`
This can be done by clearing the db, running all up migrations and then one down migration
```
yarn db:stop
docker volume rm docker_postgres-data docker_rethink-data
yarn db:start
yarn dev
#stop after migrations ran
yarn db:migrate down
```
* Make sure you're not running up migrations when starting the server by commenting out
https://github.com/ParabolInc/parabol/blob/8fa20a5509c889b86da2de4a059478b76899af51/scripts …
=> fix(Retrospective): Fix refleciton prompts

codegen.json, packages/server/graphql/graphql.ts, packages/server/graphql/mutations/emailPasswordReset.ts, packages/server/graphql/mutations/helpers/processEmailPasswordReset.ts, packages/server/graphql/private/mutations/removeAuthIdentity.ts, packages/server/graphql/private/typeDefs/removeAuthIdentity.graphql, packages/server/graphql/private/types/RemoveAuthIdentitySuccess.ts
Fix https://github.com/ParabolInc/parabol/issues/6709
```gql
mutation {
removeAuthIdentity(domain: "parabol.co", identityType: GOOGLE, addLocal: true){
... on RemoveAuthIdentitySuccess {
users {
email
identities {
isEmailVerified
type
}
}
}
}
}
```
=> feat: remove auth identity

.github/ISSUE_TEMPLATE/release_test.md
Some serious bug missed (#6714) while doing release testing, because tested only new accounts and meetings.
- Added a note to not forget to check existing data not broken
- Added GitLab and JiraServer to the checklist
=> chore: update release_test.md

packages/client/components/PokerDimensionValueControl.tsx
Fixes #6710
How to test:
- Try to estimate Parabol tasks in poker meeting
- See no additional label controls appeared
=> fix(poker): Fix wrong controls when estimating Parabol tasks

packages/client/components/StartMeetingFAB.tsx, packages/client/components/TopBarStartMeetingButton.tsx
=> fix: Center add/start meeting button content

packages/client/components/MeetingsDash.tsx, packages/client/components/MeetingsDashTutorialModal.tsx, packages/client/components/TutorialMeetingCard.tsx
Fixes #6652 
Add a video tutorial link to the empty meetings dash experience.
TODO: Final links are missing
Open meeting dash without any active meetings, click the tutorial card.
=> feat(Onboarding): Added video tutorial to empty meetings dash

package.json, yarn.lock
To avoid Dev Server always prompting warnings like this,
Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
`npx browserslist@latest --update-db` updates `caniuse-lite` version
in your npm, yarn or pnpm lock file. This update will bring data about
new browsers to polyfills tools like Autoprefixer or Babel and reduce
already unnecessary polyfills.
You need to do it regularly for three reasons:
1. To use the latest browser’s versions and statistics in queries like
`last 2 versions` or `>1%`. For example, if you created your project
2 years ago and did not update your dependencies, `last 1 version`
will return 2 year old browsers.
2. Actual browsers data will lead to using less polyfills. It will reduce
size of JS and CSS files and improve …
=> fix: updates caniuse-lite version in yarn lock file

packages/server/postgres/generatedMigrationHelpers.ts, packages/server/postgres/utils/checkTeamEq.ts
Fixes #6761 
The migration still used generated postgres queries. Added getTeamsByIds
to the static queries for migrations and changed `checkTeamEq` to use
it.
no demo
CI passes
=> chore: fix delete team migration

packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
Fixes https://github.com/ParabolInc/parabol/issues/6624
Move the response + reactjis to the header of the discussion thread, which is in the discussion scrollview.
=> feat(standups): Make response in discussion drawer scrollable

packages/client/components/promptResponse/PromptResponseEditor.tsx
=> fix(standups): Reduced list padding in standups response

packages/client/components/AnalyticsPage.tsx
Fixes #6718 
HubSpot matches the URL to decide which chat to show. For SPAs it needs
manual refreshing on page change.
https://www.loom.com/share/21d239c305fa4791b4d130dc4bd96333
- Add Hubspot to your local [devTemplate.html](https://github.com/ParabolInc/parabol/blob/4f1c9d807d01ca027f9f300af114a67a2f2992af/devTemplate.html#L7)
(see #6718)
- Remove non-production return from Analytics page
https://github.com/ParabolInc/parabol/blob/4f1c9d807d01ca027f9f300af114a67a2f2992af/packages/client/components/AnalyticsPage.tsx#L83-L85
=> chore: Refresh HubSpot chat widget on page changes

packages/client/components/EstimatePhaseDiscussionDrawer.tsx, packages/client/components/PokerEstimatePhase.tsx, packages/client/components/mediaQueryforPoker.tsx, packages/client/types/constEnums.ts
fix #6433 Remove the padding in the discussion Drawer
:star_struck: My first Open-Source Contribution
Before
After
=> fix(Sprint Poker): Remove padding in Discussion Drawer

packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
Currently, the add reactji mutation often doesn't happen when attempted immediately after the viewer submits their response.  The current workaround is to just refresh the page, but that's annoying.
=> fix(standups): Allow reactjis to be added after initial response submission

packages/client/mutations/AcceptTeamInvitationMutation.ts
Fix https://github.com/ParabolInc/parabol/issues/6793
- In prod/master, copy the team invitation link
- Go to a new window and create a new account
- Paste the invitation link into the URL and see that you're successfully added to the team 
- Now paste the URL for a second time and see the loading screen (see screenshot in issue)
- Checkout this branch and see that you can use the same invitation link as many times as you wish
=> fix: reuse invite link

packages/client/mutations/AcceptTeamInvitationMutation.ts, packages/server/graphql/private/mutations/enableSAMLForDomain.ts
I introduced this bug during the Org Approvals PR.
It wrote to the wrong field & typescript didn't catch it.
I still haven't figured out why typescript didn't catch it.
=> fix(saml): write to url field

packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx, packages/client/components/promptResponse/PromptResponseEditor.tsx
Fixes https://github.com/ParabolInc/parabol/issues/6688
Update the UX for response submission from onBlur to explicit "submit"/"update", and allow users to undo any in-progress edits with a "cancel" button.
Recommend reviewer sets "ignore whitespace" for the change in `packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx`
https://www.loom.com/share/8f09c3adb3ec42089de0b05831cc984f
(check that this matches designs for each step)
=> feat(standups): Response submission UX redesign

packages/client/components/Insights.tsx, packages/client/components/InsightsDomainNudge.tsx, packages/server/graphql/types/SegmentEventTrackOptions.ts
Fix https://github.com/ParabolInc/parabol/issues/6681
This PR sends an event to Segment when the viewer visits the /usage page and when they click the domain stats CTA.
I got a bunch of bad merge conflicts in https://github.com/ParabolInc/parabol/pull/6764 after https://github.com/ParabolInc/parabol/issues/6681 was merged to master, so I closed that PR and created a fresh one as there aren't too many changes.
=> feat(insights): usage stats analytics

packages/client/components/Dashboard.tsx, packages/client/components/NewMeeting.tsx, packages/client/hooks/useUsageSnackNag.ts
Fix https://github.com/ParabolInc/parabol/issues/6762
This PR shows a nagging snackbar to users who have the `insights` feature flag turned on and whose `tier` is less than their `suggestedTier`, e.g. `tier` is `personal` and `suggestedTier` is `pro`.
Note: if you refresh the page or dismiss the snackbar and proceed to the meeting selector, it'll show up right away rather than after 3 minutes. I could add some logic to prevent this, but as [the idea](https://github.com/ParabolInc/parabol/issues/6762#issuecomment-1157976095) is for the snackbar to be essentially persistent, I think that logic would be unnecessary.
=> feat(insights): usage snack nag

packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
Fixes: #6792 
This should help with onboarding new users. The hint appears after a timeout (same which is used for typing notifications) or after blurring the input.
- Start Retrospective and go to reflect phase
=> feat(Retrospective): Add more prominent enter to submit hint

packages/client/components/ReflectionGroupVoting.tsx, packages/client/components/VoteSettingsMenu.tsx, packages/client/components/VoteSettingsStepper.tsx, packages/integration-tests/tests/retrospective-demo/step3-vote.test.ts
Fixes #6750 
Replace thumbs up/thumbs down with + and - buttons for voting so it's less confusing.
* Start a Retrospective, create some reflections and at least 1 group
* vote + and - on single reflections
* vote + and - on opened reflection group
=> feat(Retrospective): Updated voting buttons to be clearer

packages/client/clientSchema.graphql, packages/client/components/TypeAheadLabel.tsx, packages/client/modules/meeting/components/ReflectTemplateItem.tsx, packages/client/modules/meeting/components/ReflectTemplateList.tsx, packages/client/modules/meeting/components/ReflectTemplateListOrg.tsx, packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx, packages/client/modules/meeting/components/ReflectTemplateListTeam.tsx, packages/client/modules/meeting/components/ReflectTemplateModal.tsx, packages/client/modules/meeting/components/ReflectTemplateSearchBar.tsx
Fix https://github.com/ParabolInc/parabol/issues/6791
This PR implements a search filter so users can quickly find the template they're looking for. The UI does not sparkle on mobile as there are existing template UI bugs as outlined in: https://github.com/ParabolInc/parabol/issues/5978
<details>
</details>
=> feat: retro template search filter

yarn.lock
I noticed we lost our security fixes in our yarn lockfilie.
I'm not sure what PR did this, but I assume it was mine #6799.
Not sure how this happened as I didn't blow away the lockfile & when I regenerated it on my computer it included the right changes.
The security tab in GitHub does not say there are 12 security holes anymore, 8 of which were already previously patched
=> fix(lockfile): re-add security fixes

packages/client/components/DemoMeetingCard.tsx
Fixes #6833 
- Create a new user
- Click the demo meeting card
- Verify the event was emitted in Segment
=> feat(metrics): Add Segment event to track when onboarding user clicks the Demo Meeting Card

packages/client/components/promptResponse/PromptResponseEditor.tsx
This PR improves list styles in standups response editor by decreasing top/bottom margins a little.
**Before**
**After**
=> feat(standups): Decrease top/bottom list margins in standup response editor

package.json, packages/client/package.json, packages/gql-executor/package.json, packages/integration-tests/package.json, packages/server/package.json, yarn.lock
This should fix 3 of the CWEs identified by dependabot that it is not able to automatically fix.
Being vague here because security.
Of note-- now that lerna is deprecated, vulns are getting found & not fixed, so we should increase priority to move to non-lerna.
=> fix(security): package bumps for dependabot fixes

packages/gql-executor/gqlExecutor.ts, packages/server/server.ts
`process.env.DD_TRACE_ENABLED`  is now the only way to set enabled for dd-trace.
this PR fixes the typescript error, but no change to runtime.
this happened when i bumped dd-trace to fix a security vuln
=> fix(dd-trace): enabled comes from env var

packages/client/utils/meetings/lookups.ts
This PR changes the label shown on the meeting card for standups. Instead of `Started` now, we'll display `Active`
=> feat(standups): Display standups as active instead of started

packages/client/components/GitHubScopingSearchResults.tsx, packages/client/components/TaskFooterIntegrateMenu.tsx, packages/server/graphql/queries/repoIntegrations.ts, packages/server/graphql/types/TeamMember.ts
Fix: https://github.com/ParabolInc/parabol/issues/6880
=> fix: access more than 10 Jira projects in task footer

packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
Currently, you need to hover over the "Mattermost Webhook" text to see the tooltip which explains how to get the webhook URL:
In this PR, I'm adding an info icon to make it clearer for users that there's a tooltip with instructions:
=> feat: mattermost info icon

packages/server/dataloader/azureDevOpsLoaders.ts, packages/server/utils/AzureDevOpsServerManager.ts
Fixes #6891
Changes include:
1. Adding the $expand property to the Azure DevOps Rest API to return hypermedia links
2. Changing the mapping function of the returned work item to retrieve html url
When you are in a sprint poker meeting and are in the process of providing estimates, after importing the work item, you will see
If you click on the link of the work item at the top of the screen (in this case the #3 link), you will currently be linked incorrectly to the JSON representation and see something like:
This change fixes that issue by providing the html url.  You will now see:
- Import the work items that you want to estimate into a sprint poker meeting
- During the estimate phase, click on the link at the top of the screen and verify it takes you to the Azure DevOps SaaS instance and …
=> feat(Azure DevOps): Add SaaS url to sprint poker estimation

packages/client/components/Snackbar.tsx, packages/client/components/SnackbarMessage.tsx, packages/client/components/SnackbarMessageAction.tsx
fixes #6218
Try to generate different snackbar messages and verify the dismiss button and its functionality.
=> fix: Added dismiss button to snackbar messages

packages/client/components/AuthenticationPage.tsx, packages/client/components/Dashboard.tsx, packages/client/components/FlatPrimaryButton.tsx, packages/client/components/NewMeeting.tsx, packages/client/components/NewMeetingActions.tsx, packages/client/components/NewMeetingActionsCurrentMeetings.tsx, packages/client/components/NewMeetingHowTo.tsx, packages/client/components/NewMeetingHowToSteps.tsx, packages/client/components/NewMeetingIllustration.tsx, packages/client/components/NewMeetingMeetingSelector.tsx, packages/client/components/NewMeetingRoot.tsx, packages/client/components/NewMeetingTeamPicker.tsx, packages/client/components/PrivateRoutes.tsx, packages/client/components/StartMeetingFAB.tsx, packages/client/components/TopBarStartMeetingButton.tsx, packages/client/hooks/useModalPortal.tsx, packages/client/hooks/usePortal.tsx, packages/client/modules/meeting/components/PokerTemplatePicker.tsx, packages/client/modules/meeting/components/RetroTemplatePicker.tsx
Fixes #5602 
This is the first step in redesigning the dialog. The dialog still uses
the same route as before. If the route is hit directly, the meetings
dashboard is rendered in the background. If it's reached by pressing the
"Add meeting" button, then the current page is put into the location
state to be rendered as background.
https://www.loom.com/share/eba28320ed6f4c67806042a440ac1b9f
* Create at least 2 teams
* team 1 with some active meetings
* team 2 with no active meetings
=> feat: New meeting dialog is now a modal

packages/server/graphql/mutations/addComment.ts, packages/server/graphql/mutations/addReactjiToReactable.ts, packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts, packages/server/utils/analytics/analytics.ts
Implements #6902 
Comment Added:
Response Added:
Reactji Interacted:
=> feat(metrics): Add more Segment events to Standups

packages/client/components/TeamPrompt/TeamPromptTopBar.tsx, packages/client/components/TeamPromptMeeting.tsx
Fixes https://github.com/ParabolInc/parabol/issues/6899
Adds a beta badge to the standups meeting
Appears on desktop
Does not appear on mobile (since the top bar doesn't have enough real estate)
=> feat(standups): Beta badge within meeting

packages/client/components/AnalyticsPage.tsx, packages/client/components/Icon.tsx
Relates to: #6062
When translating the app in Chrome it would break all the material ui font icons. To fix this the CSS class 'notranslate' was added to the `Icon` component.
Before (page translated to German by Chromium):
After:
Load the app in Chrome and translate to a non-English language.
=> chore: Fix browser translation

packages/server/utils/updateHubspot.ts
Partially Fixes #6982 
1. This solution is not perfect but workable for now.
2. Adding more fields will NOT increase API call volume to HubSpot as we update all properties for a company in one call.
=> fix(metrics): update activeUserCount & activeTeamCount for companies in HubSpot more often

packages/client/components/NewMeetingCarousel.tsx
Fixes #6937. 
Important: the dimensions of carousel elements are different in the application than in the designs so I couldn't make it pixel perfect as I had to scale the badge down a bit to make it look nice.
=> feat(standups): Added beta badge to standups on new meeting view

packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts, packages/server/database/types/DiscussStage.ts
Fixes #6631
In this PR I make it possible to move to the discussion phase without voting.
Previous discussion here: #6886
How to test:
- Create a new retro meeting
- Advance to the voting phase but do not case any votes
- Click next, see the button works and advances to the discussion phase
=> fix: allow to go to the discuss phase without voting

packages/client/components/NewMeeting.tsx, packages/client/modules/demo/DemoUser.ts, packages/server/__tests__/addFeatureFlag.test.ts, packages/server/graphql/public/types/UserFeatureFlags.ts, packages/server/graphql/types/UserFlagEnum.ts
This PR removes the standups feature flag and is meant to finish the https://github.com/ParabolInc/parabol/milestone/129 milestone.
=> feat(standups): Removed standups feature flag

packages/client/components/MeetingCard.tsx, packages/client/components/NewMeetingCarousel.tsx, packages/client/modules/email/components/TeamInvite.tsx, packages/server/database/types/MeetingTeamPrompt.ts, packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
Fixes https://github.com/ParabolInc/parabol/issues/6987
=> feat(standups): Rename Async standup -> standup

docs/codeReview.md
We've [made a decision](https://parabol.slack.com/archives/C836NA350/p1658847963962769) to make `One Review Required` part of our `Code Review Policy`. This PR removes the part saying it was an experiment. 
Please let me know if you'd like to see any additional clarification on that, thank you!
=> chore: Added one review required to code review policy

packages/client/mutations/AcceptTeamInvitationMutation.ts, packages/client/types/constEnums.ts, packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts, packages/server/graphql/public/mutations/acceptTeamInvitation.ts, packages/server/graphql/public/mutations/helpers/getIsAnyViewerTeamLocked.ts
Fix https://github.com/ParabolInc/parabol/issues/6897
This PR prevents a user from creating a meeting if any of the members of that team belong to a locked team. It largely uses the logic shared [here](https://github.com/ParabolInc/parabol/issues/6378#issuecomment-1185777575), with a few changes. I've added comments where the logic was changed to help with the CR.
=> feat: increase locking restrictions

packages/server/graphql/private/mutations/loginSAML.ts, packages/server/graphql/public/mutations/loginWithGoogle.ts
fix #6668
fix #6930
Users can add a `preferredName` attribute to their SAML response payload & that will become their new `preferredName` _for new users_. This will not update the name for existing users.
Also, if a user signed up using Google OAuth2 and then their domain upgraded to SSO, we now force them to login with SSO. If they try logging in via Google OAuth2, they get an error telling them to login via SSO.
=> feat(saml): support preferredName, enforce SAML over oauth

packages/server/billing/helpers/adjustUserCount.ts, packages/server/graphql/private/mutations/connectSocket.ts, packages/server/graphql/public/mutations/addFeatureFlag.ts
Partially Fixes #6952. As a first step, I added `isActive` and `featureFlags` because the infomation is available upon socket connection. Any other properties suggested in the issue are expensive to calculate. For example, `isTeamLead`, we could call `identify` on `promoteToTeamLead` but that would only work for **new** team lead. To "backfill" existing team leads, we have to `identify` them on login, but it seems expensive to calculate if the user is a team lead on all the logins for every user? I need to think about the performance impact more hence not including them in this PR.
=> feat(metrics): Add `isActive` and `featureFlags` as new User Properties for Segment identify calls

packages/server/graphql/private/mutations/connectSocket.ts
Before we only identify user's `highestTier` [upon tier changes](https://github.com/ParabolInc/parabol/blob/master/packages/server/utils/setUserTierForUserIds.ts#L70). This causes [majority of our users in Segment/Amplitude has `none` highestTier](https://analytics.amplitude.com/parabol/chart/mknrler?source=redirect%3A%20chart%20saved).
=> feat(metrics): identify user's tier upon login

packages/client/components/NewMeeting.tsx
fixes #7025
Just restored previous dialog width that was changed for some reason
=> fix: fix truncated sprint poker description in new meeting dialog

packages/client/components/DemoMeetingCard.tsx, packages/client/components/ErrorBoundary.tsx, packages/client/components/GitLabScopingSearchFilterMenu.tsx, packages/client/components/ScopingSearchInput.tsx, packages/client/components/SpotlightSearchBar.tsx, packages/client/components/TutorialMeetingCard.tsx, packages/client/hooks/useAnimatedSpotlightSource.ts, packages/client/hooks/useDraggableReflectionCard.tsx, packages/client/hooks/useSpotlightSimulatedDrag.tsx, packages/client/modules/teamDashboard/components/ProviderRow/JiraServerProviderRow.tsx, packages/client/mutations/SendClientSegmentEventMutation.ts, packages/client/mutations/UpdatePokerScopeMutation.ts, packages/client/utils/getSearchQueryFromMeeting.ts, packages/server/graphql/types/SegmentEventTrackOptions.ts
Fixes #6996 
`viewerId` is an unnecessary property for Segment events we published because:
1. [Each event is already associated with the `userId`](https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/mutations/segmentEventTrack.ts#L81)
2. We grabbed the `viewerId` [from `authToken`](https://github.com/ParabolInc/parabol/blob/master/packages/server/graphql/mutations/segmentEventTrack.ts#L58)
This PR:
1. removed `viewerId` from `SegmentEventTrackOptions`
2. made `SendClientSegmentEventMutation`'s `options` arg strong typed with `SegmentEventTrackOptions`
3. removed all unnecessary `viewerId` arg in various places `SendClientSegmentEventMutation` is called
=> fix(metrics): remove duplicate viewerId in various Segment events

packages/client/components/InsightsCharts.tsx, packages/server/graphql/public/types/Company.ts, packages/server/postgres/pgtypedConfig.js
Fix #6932
Also dedupes users (undocumented bug)
A loom would contain PPI, so you'll just have to trust me :cry: 
- To test with staging data, connect to the staging database. See the readme in https://github.com/ParabolInc/action-devops
- impersonate this [user](https://app.hubspot.com/contacts/3888472/contact/15521551)
- see that the org count is ~42 & the user count is deduped
=> fix: bug that set org count to 0

packages/server/utils/updateHubspot.ts
Fixes #6958 
**Note**: 
1. Our access token is [here](https://app.hubspot.com/private-apps/3888472/). I'll update the [`HUBSPOT_API_KEY`](https://github.com/ParabolInc/action-devops/blob/4aa09acb2ddc8376aaabd11bfc5bcfd7380b9bf8/environments/production#L69) after this PR is merged.
2. Example on how to call HubSpot with Private Apps access token is [here](https://developers.hubspot.com/docs/api/private-apps#make-api-calls-with-your-app-s-access-token)
Unfortunately there's no good way to test it locally, as we only have 1 production access token. For each of the API calls though, I've tested with CURL command and verified the responses:
```shell
curl "https://api.hubapi.com/contacts/v1/contact/email/tianrunhe@gmail.com/profile" \
-H 'Authorization: Bearer ${hapiKey}' \
-H 'Content-Type: …
```
=> feat(metrics): Use HubSpot Private apps access token for HubSpot calls

packages/server/graphql/mutations/startCheckIn.ts, packages/server/graphql/mutations/startRetrospective.ts, packages/server/graphql/mutations/startSprintPoker.ts, packages/server/graphql/mutations/startTeamPrompt.ts
Fixes #7028 
- Starts a team prompt meeting
- Verify the `lastMeetingType` for the team is updated to `teamPrompt`
=> fix(standups): Update 'lastMeetingType' after a team prompt meeting starts

CHANGELOG.md, lerna.json, package.json, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx, packages/client/package.json, packages/gql-executor/package.json, packages/server/package.json
Fixes production issue - email summaries not being sent.  Caused by standup-specific client-side-only code being imported for server-side rending of non-standup meeting summaries.
Go through a retro, end meeting, and confirm summary email is sent
=> fix: Don't import team prompt summary for SSR

packages/server/graphql/public/mutations/acceptTeamInvitation.ts, packages/server/utils/analytics/analytics.ts
Fixes #6973 
- Inviter invites someone to the team
- Invitee accepts the invitation
- Verify the `inviterId` in the `Invite Accepted` event is the `userId` of the inviter
=> feat(metrics): add 'inviterId' to Invite Accepted events

packages/server/graphql/mutations/navigateMeeting.ts, packages/server/graphql/mutations/promoteNewMeetingFacilitator.ts, packages/server/graphql/mutations/updateNewCheckInQuestion.ts, packages/server/graphql/public/types/Company.ts
Fixes #7054
An active team was defined by the team having a meeting.updatedAt being less than 30 days old. updatedAt is now replaced with endedAt/createdAt.
Also, updated applied fixes to stop meeting.updatedAt from updating after the meeting has ended.
Test:
=> fix(usageStats): active teams definition

packages/client/components/RetroDiscussPhase.tsx
We have 2 scrollbar containers.
Note, this isn't visible on macOS or windows, but it's there! it'll be noticeable as you use your scrollwheel on all platforms.
Specifically, when the outer container is scrolled, the cards will sit on top of the "12 Reflections" header.
[ ] - create a retro with a bunch of reflections in a group. you can scroll them just fine
=> fix: remove double scrollbar on discuss phase

packages/client/components/TaskIntegrationMenuItem.tsx
Fixes #7084
The reason it didn't work is the fact the lookup object used non-safe casting and didn't include required properties.
=> fix(integrations): Not working integrate task menu

packages/client/components/NewMeetingTeamPickerAvatars.tsx
Fixes: #7072
How to test:
- Create a team with 4 members, see that team lead is always shown first, other members are shuffled
- Create a team with more than 4 members, see that you are excluded from the preview if you are not the team lead
=> fix: show the team lead first in the preview of team selector

packages/server/billing/helpers/adjustUserCount.ts
Following up with https://github.com/ParabolInc/parabol/pull/6997. I noticed the method might exit early on [this line](https://github.com/ParabolInc/parabol/blob/master/packages/server/billing/helpers/adjustUserCount.ts#L161) without calling `identify`. This change just move the call to near the `track` call so it's easier & cleaner.
1. Manually set a few user's `lastSeenAt` timestamp to 30 days ago
2. Run the `autopauseUsers` mutation
3. Check Segment and verify identify calls were emitted
=> fix(metrics): Move identify inactive up to within changePause()

packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
Fix https://github.com/ParabolInc/parabol/issues/6975
https://www.loom.com/share/3cb5f3c909474f95be24fa92ab299281
=> fix: hyperlink default focus

packages/client/components/ThreadedCommentHeader.tsx, packages/client/modules/demo/commentLookup.ts, packages/client/modules/demo/initDB.ts, packages/integration-tests/tests/retrospective-demo/step4-discuss.test.ts
Fix https://github.com/ParabolInc/parabol/issues/6905
I've also updated the comment text to mention standups. 
Currently, in prod:
This PR:
- Can add comments to a thread in the demo and see the author (yourself)
- When the bot adds a comment, it says the author's name
- Can add anonymous comments
- Can add comments & anonymous comments in the Retro & Poker discussion thread
=> fix: demo comments are always anonymous

.vscode/settings.json, .vscode/tips.md
Add relative import preference. Currently, importing server files often incorrectly begins with `server/`. Now they'll import using the relative path, e.g. `'../../database/types/User'`
=> chore: update vscode import settings

packages/client/components/TopBarHelpMenu.tsx
Fixes/Partially Fixes #[7055](https://github.com/ParabolInc/parabol/issues/7055)
- Step 1
Ensure "Teamwork Resource" was changed to Documentation and points to Support page
-  Step 2
Ensure "Give Feedback" is changed to "Get Help" and links to Contact Form
=> fix: support documentation easier to find in-app

packages/client/components/EmojiMenu.tsx, packages/client/components/TaskEditor/EmojiMenuContainer.tsx, packages/client/components/TaskEditor/useEmojis.tsx, packages/client/components/TaskEditor/withEmojis.tsx, packages/client/components/promptResponse/EmojiMenuTipTap.tsx, packages/client/components/promptResponse/PromptResponseEditor.tsx, packages/client/components/promptResponse/tiptapConfig.ts, packages/client/package.json, yarn.lock
Fixes https://github.com/ParabolInc/parabol/issues/6883
Add emoji support by typing `:`.  Reuse the emoji menu used in our Draft.js editor to show emojis in TipTap.
Changes:
* Refactor existing emoji menu to decouple the menu from the draft.js editor
* Add a new tiptap emoji component that uses the [Suggestion](https://github.com/ueberdosis/tiptap/tree/main/packages/suggestion) tiptap utility to render the emoji menu.
This uses a pattern used by many TipTap React components in which the component is rendered by simply passing in the editor - no added configuration in the config (see the [React Bubble Menu](https://github.com/ueberdosis/tiptap/blob/9a254bf9daf6d839bd02c968e14837098b903b38/packages/react/src/BubbleMenu.tsx)).
**note**: one test case this fails is when the cursor is part-way …
=> feat(tiptap): Emoji Support

.circleci/config.yml, scripts/webpack/prod.client.config.js, scripts/webpack/prod.servers.config.js
- datadog-ci sourcemap upload at build time, however, the cli requires the .js file and .js.map file to have the same root name. As currently built, the name is different between .js and .js.map file. e.g.name]_[contenthash].js.map and [name]_[contenthash].js' This PR changes contenthash to hash to resolve the datadog-ci issue.
- reverts changes that only used staging .env for deployment, thus all deployments were going to staging with build assets since v6.56.0
Note, I chose to add datadog-ci node module at the time it was needed vs having it placed into the build as it's not a runtime dep, only used for uploading sourcemaps.
resolves #6731
=> feat(dd sourcemaps): add source maps to deploy. fix(deploy): using staging .env, reverted code to

packages/client/components/promptResponse/PromptResponseEditor.tsx
Fixes #7099 by increasing the line-height of text in responses to `20px`.
With various formatting applied:
=> fix: increased the line-height of text in Standup responses

packages/server/dataloader/azureDevOpsLoaders.ts
Fix https://github.com/ParabolInc/parabol/issues/7006
When refreshing the token, Azure returned the error `invalid_grant`. The error description said: 
`The refresh token was issued to a single page app (SPA), and therefore has a fixed, limited lifetime of 1.00:00:00, which cannot be extended. It is now expired and a new sign in request must be sent by the SPA to the sign in page`
This issue https://github.com/AzureAD/microsoft-authentication-library-for-js/issues/4104 and this [Azure doc](https://docs.microsoft.com/en-us/azure/active-directory/develop/refresh-tokens#refresh-token-lifetime) confirm that the user needs to re-auth after 24 hours. 
In this PR, I'm removing the user's stale auth if the refresh token error message is `invalid_grant`. In Sprint Poker, the user will now see …
=> fix: azure refresh auth

packages/client/components/AuthenticationPage.tsx
Fixes #7126 
Changed the copy on the /create-account page to:
_92% of users agreed that Parabol improves the efficiency of their meetings._
=> fix: Changed copy on /create-account page

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts, packages/server/graphql/mutations/helpers/isPatientZero.ts, packages/server/graphql/mutations/helpers/updateUserProfile.ts, packages/server/graphql/private/mutations/connectSocket.ts, packages/server/graphql/types/User.ts, packages/server/postgres/queries/getPatientZeroByDomain.ts, packages/server/postgres/queries/src/getPatientZeroByDomainQuery.sql
Fixes #7128 
1. Log in
2. Verify in Segment the `isPatient0` property is included in the `identify` call
=> feat(metrics): identify if user is patient 0 upon login

packages/client/components/Insights.tsx, packages/client/components/InsightsCharts.tsx, packages/client/components/InsightsDomainPanel.tsx
Fix https://github.com/ParabolInc/parabol/issues/7037
This PR:
- Changes "Meetings" to "Total Meetings"
- Adds tooltips to all domain panel terms
- Adds a subtitle to the charts to explain the terms. Chart js requires a string as a title rather than a React element and it has support for subtitles so I felt that worked well
- Increased the width of the domain panels to accounts for tooltips
- Updated domain panel on mobile
- Removes "Usage" title and adds it to the domain panel
=> feat: usage stats clarity improvements

scripts/codeshift/convertToUseFragment.ts
Automate the migration from `createFragmentContainer` to `useFragment` for a particular file.
Please also review the [guide](https://www.notion.so/parabol/How-to-Migrate-createFragmentContainer-useFragment-with-codeshift-d534e7d0b8674089a2075f2835544558).
Usage:
```
jscodeshift --extensions=tsx --parser=tsx -t ./scripts/codeshift/convertToUseFragment.ts ./packages/client/components/TeamArchived.tsx
```
Doesn't work in all cases, but should work in most.
Partially Fixes https://github.com/ParabolInc/parabol/issues/6283
See https://github.com/ParabolInc/parabol/pull/7136
Run on a few different files and confirm that this does the right thing. This is expected to fail in a lot of ways, so in this case, the "right thing" is:
* Works most of the time
* When it doesn't work, spits out an error …
=> feat(dx): createFragmentContainer -> useFragment codeshift automation

packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Increases the font size of the standup meeting title from `16px` to `18px`. This improves hierarchy and visual balance.
Before and after:
=> style: increase font size of standup meeting title

.github/workflows/stats.yml
According to the [Cycle Time](https://en.wikipedia.org/wiki/Cycle_time_(software)) statistics from [LinearB](https://linearb.io/), we're spending a longer time indeed in the Review phase, so let's figure out how to speed it up, and the first step might be to show more detailed Review data:
This PR adds usage of [pull-request-stats workflow](https://github.com/flowwer-dev/pull-request-stats), use this Github Action to print relevant stats about Pull Request reviewers. Let's continuously measure and do more improvements!
The objective of this action is to:
- Reduce the time taken to review the pull requests.
- Encourage quality on reviews.
- Help deciding which people to assign as reviewers.
Please feel free to comment, let's just see how it works in this PR, please let me know what you …
=> chore: add pull-request-stats github workflow

.circleci/config.yml
Fixes error during pipeline execution deploying to Staging.
```
remote:        2022-09-06T10:57:57: PM2 log: App name:GQL Executor id:2 disconnected        
remote:        2022-09-06T10:57:57: PM2 log: App [GQL Executor:2] exited with code [0] via signal [SIGINT]        
remote:        2022-09-06T10:57:57: PM2 log: App [GQL Executor:2] starting in -cluster mode-        
remote:        2022-09-06T10:57:57: PM2 log: App [GQL Executor:2] online        
remote:        Error:         
remote:        Something went wrong installing the "sharp" module        
remote:        node-loader:        
remote:        Error: libvips-cpp.so.42: cannot open shared object file: No such file or directory        
remote:        Possible solutions:        
remote:        - Install with verbose logging and look …
```
=> fix(pipeline): fix CircleCI error during Commit Deployment stage (missing dependency for sharp module)

packages/client/components/BeginDemoModal.tsx, packages/client/components/BottomControlBarTips.tsx, packages/client/hooks/useDemoMeeting.tsx, packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/modules/demo/initDB.ts
Fixes/Partially Fixes #6946 
prevent demo meeting auto start after page refresh
https://www.loom.com/share/c032b342f9ed4762b76642d8b135a279
- Refresh Page
- Click "Start Demo" button
- Bots start adding reflections
- Click "Start Demo" button
- Refresh Page
- Everything continues
=> fix(demo): prevent demo meeting auto-start after page refresh

.github/reviewers.yml, .github/workflows/assign_reviewers.yml
Try to automatically add reviewers for external contributers and migration changes for now.
Fixes #6969
- Step 1
- Step 2...
- Step 1
- Step 2....
=> chore: Automatically add reviewers

packages/client/components/BottomControlBarTips.tsx
Fixes/Partially Fixes #6946 
in https://github.com/ParabolInc/parabol/pull/7131, moved `clientGraphQLServer.db._started` out of the useEffect, which broke all retro meetings (not demo meeting).
=> fix: only check clientGraphQLServer for isDemoRoute

packages/server/graphql/mutations/setTaskEstimate.ts
I noticed after https://github.com/ParabolInc/parabol/pull/7117 is merged, task estimates for Parabol task (i.e., tasks that were not integrated with any services) were not written in the `TaskEstimate` table. This PR fixes it.
After the fix, in Segment we see that an event with `success = true` is published:
Also in DB we can see the corresponding row:
- Start a poker meeting
- Scope or create a Parabol task
- Vote and set an estimate for the task
- In Segment, verify an event with `success = true` is published
- In `TaskEstimate` table in Postgres, verify a new row is added
=> fix(poker): fix an bug where task estimate is not written to DB when it's a Parabol task

packages/server/graphql/mutations/setMeetingSettings.ts, packages/server/utils/analytics/analytics.ts, packages/server/utils/analytics/helpers.ts
Fixes #7163 
New property `disableAnonymity` included in Meeting related events:
New event `Meeting Settings Changed` published to Segment:
- Start/Join/Complete a meeting
- Verify `disableAnonymity` is included in the relevant events in Segment
- Go to meeting selector modal
- Toggle the `Anonymous reflections` setting
- Verify a new `Meeting Settings Changed` event was published and the `disableAnonymity` property is expected
=> feat(metrics): Add metrics about `disableAnonymity` in retro meetings

.github/workflows/assign_reviewers.yml
Fixes/Partially Fixes #6969
the `Auto Request Review` GitHub workflow looks like it's still [a failure for external contributors](https://github.com/ParabolInc/parabol/actions/runs/3077044304/jobs/4971620538):
```shell
Matched no reviewers
Falling back to the default reviewers
Randomly picking reviewers if the number of reviewers is set
Requesting review to jmtaber[12](https://github.com/ParabolInc/parabol/actions/runs/3077044304/jobs/4971620538#step:2:13)9
Error: HttpError: Resource not accessible by integration
```
This `HttpError: Resource not accessible by integration`  error happens as soon as the person creating the PR does not have permission to the repository. [looking into this issue](https://github.com/actions/first-interaction/issues/10), there's a potential solution mentioned …
=> ci: setting write permissions to the PR for external contributor

.github/ISSUE_TEMPLATE/release_test.md
While doing Release Testing, I realized that we're now missing a release check for the new Standup meeting type. btw I renamed the `Action` to `Team Check-in` meeting to keep consistent with the new-meeting dialog.
https://github.com/ParabolInc/parabol/issues/new?assignees=&labels=&template=release_test.md&title=Release+test+v
=> chore: add Standup smoke test into the testing basics

.github/workflows/stats.yml, scripts/reviewStats.ts
Let's run review stats on a regular basis. The previously used review stats package had 2 major disadvantages:
1) it calculated time to review wrong
2) it requires monthly sponsorship to be able to post to Slack
Grep the PR timeline for PRs merged in the last 7 days and calculate the time to review etc. from those.
* create GitHub personal access token with `public_repo` right
* if you want to check Slack, you need to create a bot with a webhook, otherwise stats will be printed on console but pushing to slack will fail
* export following environment variables
```
GITHUB_TOKEN=<your personal access token>
TIME_DIFF=<defaults to 7d if not set>
SLACK_WEBHOOK=<your channel webhook>
REPO=ParabolInc/parabol
```
* run `yarn ts-node scripts/reviewStats.ts`
=> chore: Weekly review stats in Slack

packages/server/graphql/mutations/voteForPokerStory.ts
Fixes/Partially Fixes #7191 #6755 #6890
Check if the voting is enabled in the below scenarios:
=> fix: 'Estimate phase is already complete' error message

package.json
Fixes/Partially Fixes #6212 
Nx, unlike Lerna, will run NPM scripts (here is `precommit`) in parallel by default
and lint-staged actually cannot be executed in parallel, so it throws this error, https://github.com/okonet/lint-staged/issues/896
The precommit script under each package should be run serially
```shell
yarn precommit
```
=> fix: disable the Nx parallel run precommit

.github/workflows/assign_reviewers.yml
External contributors don't have the correct permissions to assign reviewers, thus use a separate token for this
=> chore: Use separate PAT for auto assigning reviewers

packages/client/modules/email/components/NotificationSummaryEmail.tsx
We currently don't track UTM parameters for notification summary emails.
Add these UTM params
=> fix(notifications): UTM params on notification email link

.github/workflows/stats.yml
Try to match other reminders, taking into account the runtime of the job. This hopefully reduces distraction for everyone.
=> chore: Tweak review stats schedule to match other reminders

packages/server/graphql/mutations/inviteToTeam.ts
See this Slack thread for further context: https://parabol.slack.com/archives/C4JAUUZ9P/p1663860269145519
A user would like to be added to a team that doesn't have any team members. We would like to be able to execute the `inviteToTeam` mutation, but can't do it because it requires the viewer to be on the team.
This PR enables super users to access the mutation.
=> feat: let super users invite to team

packages/client/components/CopyLink.tsx, packages/client/components/MassInvitationTokenLink.tsx, packages/client/components/MeetingCardOptionsMenu.tsx, packages/client/modules/meeting/components/CopyShortLink/CopyShortLink.tsx
Send a "Copied Invite Link" event to segment when a user clicks the invite link in the "Invite to team" modal.
=> feat(analytics): 'Copied Invite Link' event

packages/server/utils/analytics/analytics.ts
Fixes https://github.com/ParabolInc/parabol/issues/7059
Event for when a user's invite was accepted by a different user. Can be used to answer questions like "What's the conversion rate from 'User creates account' to 'Another user accepts the user's invite'?" within Amplitude.
=> feat(analytics): 'Sent invite accepted' event

packages/gql-executor/gqlExecutor.ts, packages/server/listenHandler.ts
- Adds the Server ID to the boot message of the Web Server.
- Changes where the Server ID is shown in the GQL Executor boot message.
There are no particular test scenarios. The application has been launched locally and it runs, showing the expected message.
=> chore: boot message changed to include Server ID and task. 

packages/client/components/TopBarNotifications.tsx, packages/client/modules/email/components/NotificationSummaryEmail.tsx, packages/client/utils/makeAppURL.ts
Our current notifications simply go to the user's tasks page with no additional information.
Instead, include a query param on notification summary email links, and when this parameter is present, auto-open the notifications menu after some delay.
~I'd like to hold off on merging this until after the next release, so we can first get some baseline data from the [UTM parameters](https://github.com/ParabolInc/parabol/pull/7224)~ the release with updated UTM parameters has been deployed.
https://www.loom.com/share/0b150be30ad04f9d89ea73e6a36d11dd
=> feat(notifications): Auto-open notifications from email

packages/client/components/DiscussionThreadInput.tsx
=> fix: Text without spaces breaks the UI in discussion

scripts/reviewStats.ts
Comment only events were not counted towards the total comment count.
Comments from the author are not counted.
* Set following environment variables
```
export GITHUB_TOKEN=<a PAT with publicRepo right>
export TIME_DIFF=7d
export REPO=ParabolInc/parabol
```
* run `yarn ts-node scripts/reviewStats.ts --debug`
* compare some of the comment counts with the ones from the PR
=> chore(Review stats): Count IssueComment events towards comment count

docs/codeReview.md
In this PR I propose an update to the code review policy in an attempt to reduce PR turnaround time.
- Added more focus on reviewing PR within 24 hours
- Added a suggestion to start working day from doing PR reviews
- Made "One review required" definition broader
- Added suggestion of requesting a review from a group of people or from everyone 
- Copied some info we have in notion to store everything in a single place
Please let me know what you think
=> chore: update code review policy

packages/client/components/ReflectionCard/ReflectionCard.tsx, packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
Fixes #7107
Check if the screen readers read `edit this reflection` for non-editable reflections in different phases and different scenarios (for ex: when a phase is completed)
=> fix: Aria-label “edit this reflection” should not exist when the reflection is no longer editable

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts, packages/server/graphql/mutations/helpers/isPatientZero.ts, packages/server/utils/analytics/analytics.ts
Fixes #7182 
- Create an account with a new domain
- In Segment verify the value for label `isPatient0` is 1
- Create an account with an existing domain
- In Segment verify the value for label `isPatient0` is 0
=> feat(metrics): Send isPatient0 property to Google Analytics

packages/client/components/DiscussionThreadInput.tsx, packages/client/components/TaskEditor/CommentEditor.tsx
Fixes #7268
Reverts #7238 
- on device 1 (facilitator) moves to item 2
- on device 2 (participant) see that you do not advance forward
=> fix: participants follow facilitator

packages/client/components/ReflectionCard/EmojiUsersReaction.tsx
Fix https://github.com/ParabolInc/parabol/issues/7249
=> feat: show you in emoji list instead of viewer name

packages/client/components/AvatarList.tsx, packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatarGroup.tsx
Fixes/Partially Fixes [issue](https://github.com/ParabolInc/parabol/issues/6060)
If there are too many meeting member avatars to fit in the meeting card, the meeting member count avatar can float away from the card.
[loom video](https://www.loom.com/share/852d745e358b4501adceed7b1d43beae)
=> fix: AdjustMeetingMemberCountPosition

packages/server/database/migrations/20221012142324-fixDakiMigration.ts
Fix https://github.com/ParabolInc/parabol/issues/7221
To test:
- Run the up migration, open the retro template menu, see that the DAKI template includes the "Keep" prompt
- Running the down migration removes the prompt
I'm not really sure why/how the prompt doesn't exist in the db when it was included here https://github.com/ParabolInc/parabol/blob/ec1cc40f177b02a0a5f37b8e7cd7b422b3f7961e/packages/server/database/migrations/20210602120505-addAdditionalRetroTemplates.ts#L80 and the other three prompts are all there 🤔
=> fix: missing daki prompt

packages/client/modules/email/components/NotificationSummaryEmail.tsx, packages/server/graphql/private/mutations/sendBatchNotificationEmails.ts
Fixes #7270 
Update which users receive notification batch emails according to the [spec](https://www.notion.so/parabol/Spec-Batch-Notification-Email-Enhancements-f5a99dd9509a4aff93b6ec6568a969ae#94a8626afe26472c8247f84ec018c2bb).
I decided not to make the optional changes listed in the AC, since those will be easier to implement when we update this query to support the new emails.
=> feat(notifications): Batch notification emails - improve who gets emails

.github/workflows/assign_reviewers.yml
Triggering on pull_request_target rather than pull_request will run the workflow from the base branch (i.e. master) rather than from the fork. This allows to use secrets as the running code is managed by us.
This will hopefully allow to auto-assign reviewers for external PRs.
No demo. Because of the nature of this change, it can only run after being merged.
- Step 1
- Step 2...
- Step 1
- Step 2....
=> chore: Run auto assign reviewer workflow on pull request target

packages/client/hooks/useDraggableReflectionCard.tsx
Fixes: #7297
Dragged reflection cards are cloned elements outside of the usual component tree. In #6910 we changed the timing slightly when the clone was created, which caused this issue: The clone was created after the component tree was modified and the original disappeared already.
- create a reflection group
- drag one card out of the expanded reflection group
=> fix(Retro): a card dragged from an expanded group disappeared

packages/client/components/MeetingCardOptionsMenu.tsx
Fix https://github.com/ParabolInc/parabol/issues/7301
https://www.loom.com/share/f2c8aaab283c4d2d9d9a90d05b1bc132
=> feat: end meeting from meetings view

packages/server/createSSR.ts
Our PPMIs are showing up in google search results. See https://parabol.slack.com/archives/C4JAUUZ9P/p1666368289967199.
There are 2 ways to noindex them:
- Send a noindex header
- Add a noindex meta tag
Creating different rules for different hosts isn't great. it means staging !== production, but for a case like this, it's the only way.
I opted for using a meta tag for 2 reasons:
- our app is pretty stable (our infrastructure is about to change big time)
- we already do some noindexing for certain pages like invitation links. Nice to keep it all together
- At time of release, when the new version is up on the staging server, change the env var HOST from action-staging.parabol.co to action.parabol.co this will trigger a server restart.
- goto the app & see that the meta tag exists. 
I'm …
=> fix: add noindex for ppmis

packages/server/database/migrations/20221021163318-rename-christmas-template.ts
This PR renames the Christmas template following this request: https://parabol.slack.com/archives/C836NA350/p1666361083087839
The id of meeting templates is based on the template name, which isn't ideal. I've updated the template name which means its id is out of sync with the name. I think that's OK, but an alternative solution could be removing the template from the db and inserting a new template with the updated name & id.
=> feat: rename christmas template

packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
Fixes #7088
The changes in #7078 were conflicting with the initial fix in #7089. We cannot trim the link title for the dialog so it doesn't match the selection anymore.
https://www.loom.com/share/9fc2d4a4576445739e65e5fbb4ec02b0
- press <Ctrl> + K to open link dialog and enter link
=> chore: Fix whitespace in links

packages/server/graphql/types/EstimateStage.ts
Hotfix
The `serviceField` field is non-null and will break the meeting when `null` is returned. Instead default to "Do not update". This breaks existing Sprint Poker meetings for some users.
No demo, Sprint Poker with Jira issue can be opened normally.
This bug occured when trying to open a Sprint Poker meeting with a Jira issue which cannot be fetched anymore. Not sure how to reproduce this exactly.
=> fix: EstimateStage was broken for Jira if the issue could not be fetched

packages/client/modules/demo/ClientGraphQLServer.ts, packages/client/modules/demo/initDB.ts
@MindEvo discovered a bug in the demo where you couldn't push tasks to integrations (see Rafa's message in Slack [here](https://parabol.slack.com/archives/C836NA350/p1666857871119549?thread_ts=1666780209.440339&cid=C836NA350)). 
This was because https://github.com/ParabolInc/parabol/pull/7234 added `TaskFooterIntegrateMenuListLocalQuery` which wasn't added to the demo. 
The same PR also requested the `service` field from the repoIntegration, which wasn't being returned in the `DemoJiraRemoteProject` demo class.
=> fix: task integration demo bug

packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx, packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx, packages/client/components/TeamPrompt/TeamPromptTopBar.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/components/promptResponse/tiptapConfig.ts, packages/client/mutations/EndTeamPromptMutation.ts, packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
=> feat(standups): Added ended meeting view

packages/client/components/PokerCardDeck.tsx
Hopefully Fixes #6247
I assume the bug is caused by an untimely suspense on the part of relay (technically react, but :shrug:).
I can't reproduce the bug, this is just a shot in the dark. :space_invader: :gun: 
We'll keep tracking this bug & if the frequency drops we'll know it worked!
=> fix: use fallback values for PokerCardDeck

packages/client/components/StageTimerMinutePicker.tsx
It allows to have 10 minutes in the timer, instead of having to select 9mins then 1min to add up to 10 minutes
- Open a timer
- Select 10 Minutes
=> feat(timer picker): add 10 minutes option

packages/server/dataloader/atlassianLoaders.ts
Fixes #7353
The issue happens because there is sometimes no field name exists `issueRes.names[fieldId]`
How to test:
- Simulate undefined field name `issueRes.names[fieldId]`
- Make sure poker meeting with jira work as expected
=> fix: Jira issues sometimes are not loading in poker meeting sidebar

packages/server/package.json, yarn.lock
Fixes: #7280 
The package is obsolete with the current ioredis version.
No demo, nothing changed.
- typecheck passes
=> chore: Remove @types/ioredis package

packages/client/components/AzureDevOpsScopingSearchResults.tsx
Adding ADO work items to Sprint Poker resulted in tasks which had an invalid issueKey and integrationHash because tenant and project were prepended twice.
https://www.loom.com/share/a899f356ac8a45a7bdb8adcafc34d0de
=> fix(Azure DevOps): fix adding issues to Sprint Poker

packages/client/modules/teamDashboard/components/LeaveTeamModal/LeaveTeamModal.tsx, packages/client/modules/teamDashboard/components/ManageTeam/ManageTeamMember.tsx, packages/client/mutations/RemoveTeamMemberMutation.ts
Fixes #6061 https://github.com/ParabolInc/parabol/issues/7291 https://github.com/ParabolInc/parabol/issues/7311
This issue occurs when leaving the team. When cleaning up the member's task list, an error occurs. So add compatible logic here, not let the error terminate subsequent mutation operations when tasks is `null`.
Before: https://www.loom.com/share/a8d96b8141734f499dc74311a64aa5ac
After: https://www.loom.com/share/de2c205926d24440811486ae02203a5f
In the meantime, fixing a style issue with a name that was too long
Before|After
----|----
- leave the team
- check the nav team list
=> fix(Team): leave team does not work until refresh

packages/server/postgres/migrations/1666387804873_userPatient0.ts
The previous migration was too slow to run on production data and timed out. Solving this by creating a temporary table to read the patient 0 values from.
Previous version timed out after > 30 min while current version runs in < 2min on staging.
- Run migration on staging data
=> chore: Fix isPatient0 migration runtime

packages/client/components/EditorHelpModal/EditorHelpModal.tsx
Changed Header name from `Task Card Formatting` to ` Formatting Text `
Fixes/Partially Fixes #7245
Link to issue - https://github.com/ParabolInc/parabol/issues/7245
=> fix:  header name should be more general

.circleci/config.yml
Splits the backup from the regular workflow to allow manually running backups and manually deploying to production.
=> chore(CircleCI): split backup from deployment

packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeam.tsx, packages/client/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.tsx
Fixes #6424
> I noticed that when I try to delete a team, it looks like nothing happens. But once I refresh the page the team is gone.
The 'delete team' feature should work, but the user interaction just makes it confusing, because: 
1. **The delete operation takes time**, but there is no indicator, like a loading effect when deleting. Only after deleted, there's a snackbar message "team has been archived"
2. **The confirmation button is not clear**, we use the text hint to confirm using the `Enter`, but using a red delete confirmation button like GitHub does might be clearer.
This PR added improvements for adding a **confirmation red button with the updated copy text and the waiting effect when deleting in progress**.
Before|After
----|----
<video …
=> fix: add delete confirmation button and waiting effect

packages/client/mutations/AddAtlassianAuthMutation.ts, packages/server/graphql/mutations/addAtlassianAuth.ts
Fix #7430 when a jira tenant is unpaid, don't fail silently
Typically, errors should be propagated to an error message line that usually lives in a span below the input. This is nice because it shows _where_ the error hapened.
In this case, there are 4 instances where a user can add atlassian auth. 2 of those are in menus. showing error messages in menus is a bit ugly, so i opted to use the snackbar pattern everywhere.
- create a new team, start a poker meeting & integrate with jira using an unpaid tenant. see a snack pop up
=> fix: snack on jira auth error

package.json
`yarn clean` will fail if certain expected files are missing due to the use of the `&&` operator. Instead, use `;`, which will run all commands regardless of the result of the preceding commands.
Run `yarn clean`, then running `yarn clean` again and see that all commands are still executed.
=> fix(dx): Run all yarn clean commands, even if one fails

packages/server/database/types/Organization.ts, packages/server/graphql/public/typeDefs/Organization.graphql, packages/server/graphql/types/Organization.ts
Closes #7385
How to test:
Set flags on any org
http://localhost:8080/#dataexplorer
```
r.db('actionDevelopment').table('Organization').filter({
id: 'ijVADO81eo'
}).update({
tierLimitExceededAt: new Date('2021-01-01'),
scheduledLockAt: new Date('2021-02-02') ,
lockedAt: new Date('2021-03-03') 
})
```
Run query http://localhost:3000/admin/graphql
```
{
viewer {
organization(orgId: "ijVADO81eo") {
tierLimitExceededAt
scheduledLockAt
lockedAt
}
}
}
```
=> feat(teams-limit): add limit exceeded and locking flags

packages/client/components/TypeAheadLabel.tsx, packages/client/package.json, yarn.lock
We're currently doing `dangerouslySetInnerHTML` with strings that may be user provided.
Add [`dompurify`](https://www.npmjs.com/package/dompurify) and sanitize the HTML before dangerously setting.
See https://parabol.slack.com/archives/C836NA350/p1669242962403119 for details.
Confirm that the XSS attack described in the slack thread no longer works.
=> fix(xss): Fix XSS Attack in template

packages/server/graphql/mutations/addPokerTemplate.ts, packages/server/graphql/mutations/addReflectTemplate.ts
Fix https://github.com/ParabolInc/parabol/issues/7487
=> feat: prevent creating new templates from server

packages/client/utils/GitHubClientManager.ts, packages/client/utils/SlackClientManager.ts, packages/server/utils/SlackServerManager.ts
Reverts slack redirect strategy until slack approves our app.
also fixes the callback url for github oauth2.
=> fix: revert slack change until approval

packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx
Removing the scrollbar that exist on the task page header
- Open app on a Mobile devices or web
- Navigate to task page
- scroll the navbar on the page
[loom](https://www.loom.com/share/136b5e73f30747288a170dedb1e8ad11)
[Ticket Link](https://developers.gitstart.com/ticket/PARA-7456)
Gitstart issues link https://github.com/GitStartHQ/client-parabolinc-parabol/issues/31
Pull from https://github.com/ParabolInc/parabol/issues/7456
=> fix: There should be no scroll bar on task header

packages/client/modules/email/components/EmailNotifications/EmailNotificationPicker.tsx, packages/client/modules/email/components/EmailNotifications/EmailPaymentRejected.tsx, packages/client/modules/email/components/EmailNotifications/EmailTaskInvolves.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailTaskCard.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7284
Implements the remaining email notifications:
* Task involves (user is mentioned in a task)
* Promoted to billing leader (included in original PR, but not linked to the picker 🙃 )
* Payment rejected
Trigger each of the notification types, trigger a notification email, and examine email.
"Payment rejected" can be manually created in the rethink data explorer with:
```
r.db('actionDevelopment')
.table('Notification')
// Only include notifications which occurred within the last day
.insert({
id: 'iQwJn2dxmg',
status: 'UNREAD',
createdAt: new Date(),
type: 'PAYMENT_REJECTED',
userId: 'local|eXBU1biSzK',
orgId: 'ePchTFCMDe',
last4: '1234',
brand: 'Amex'
})
```
(note that `last4` and `brand` come from the org, and will not appear in the …
=> feat(notifications): Remaining email notifications

packages/client/components/TeamPrompt/Recurrence/TimeLeftBadge.tsx, packages/client/components/TeamPrompt/TeamPromptBadge.tsx, packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx, packages/client/components/TeamPrompt/TeamPromptMeetingStatus.tsx, packages/client/components/TeamPrompt/TeamPromptTopBar.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/utils/date/relativeDate.ts, packages/server/graphql/public/mutations/startRecurrence.ts
=> feat(recurrence): Added standups time left indicator

packages/server/billing/helpers/adjustUserCount.ts, packages/server/graphql/mutations/helpers/removeFromOrg.ts, packages/server/graphql/mutations/helpers/updateUserProfile.ts, packages/server/graphql/mutations/moveTeamToOrg.ts, packages/server/graphql/private/mutations/autopauseUsers.ts, packages/server/graphql/private/mutations/connectSocket.ts, packages/server/graphql/private/mutations/disconnectSocket.ts, packages/server/graphql/public/mutations/addFeatureFlag.ts, packages/server/safeMutations/acceptTeamInvitation.ts, packages/server/utils/analytics/analytics.ts, packages/server/utils/setUserTierForUserIds.ts
While investigating Segment <-> HubSpot integration, I saw this error pop out from Segment that complains `email` is missing from identify calls:
=> fix(metrics): Always include email in traits for identify calls

packages/client/components/ResponseMentioned.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/modules/email/components/EmailNotifications/EmailResponseMentioned.tsx, packages/client/utils/makeAppURL.ts
If a `responseId` query param is present when the Team Prompt Meeting is initially rendered, try to find the corresponding response card, and open its discussion.
Update the in-app and email notifications for standup mentions to include this query param.
In the future, we could use this to enable share-ability by either adding "copy link" buttons to response cards and/or keeping the query param in-sync with open discussion drawers.
Marking this as one review required because this general pattern has already been approved by maintainers in https://github.com/ParabolInc/parabol/pull/7225
In-app - https://www.loom.com/share/45eb8249c162428faceb75f42f6351c6
From email link - https://www.loom.com/share/399f00c8e8a047c4819411ca4d69f85d
=> feat(standups): Auto-open response discussion based on query param

packages/client/components/AnalyticsPage.tsx
After my last [PR](https://github.com/ParabolInc/parabol/pull/7356) deployed to production I found no `page_view` events sent to GA4. Turns out `send_page_view` [is disabled by default  in react-ga4](https://github.com/PriceRunner/react-ga4/blob/master/src/ga4.js#L190). This PR overrides the default config value.
**Production**
`send_page_view` is false:
**Local**
`send_page_view` is set to true after initialization:
=> fix(metrics): enable send_page_view on ReactGA initialization

packages/client/components/ActionMeeting.tsx, packages/client/components/ActionMeetingLastCall.tsx, packages/client/components/MeetingLockedOverlay.tsx, packages/client/components/PokerMeeting.tsx, packages/client/components/RetroMeeting.tsx, packages/client/components/RetroMeetingSidebar.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/modules/summary/components/NewMeetingSummary.tsx, packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx, packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx, packages/client/utils/meetings/isPhaseComplete.ts, packages/client/utils/relay/updateLocalStage.ts, packages/server/graphql/types/NewMeeting.ts
Fixes #7373 
When a locked meeting or its summary is accessed using a direct link, an overlay and an upgrade modal is shown. When the user is not in the organization anymore, the modal has no CTA, otherwise it will lead to the billing page. All phases are returned non-navigable, however spoofing of the network traffic currently would reveal all data.
https://www.loom.com/share/0a04af90726646368dd8368fdd6c96e2
Easiest way to get to the locked meetings is replacing `locked` with `false` in those places:
* https://github.com/ParabolInc/parabol/blob/dc139a292dd739cd121d18aed0b1b686bb4e40b4/packages/client/components/TimelineEventCompletedRetroMeeting.tsx#L79
* https://github.com/ParabolInc/parabol/blob/dc139a292dd739cd121d18aed0b1b686bb4e40b4/packages/client/components/TimelineEventCompletedAc …
=> chore: limit direct access to locked meetings

packages/client/utils/AtlassianManager.ts, packages/server/graphql/public/mutations/updateJiraDimensionField.ts
Relates to: #7560
It seems there is an issue where we've stored the wrong field id for "Story Points". One potential place where this could happen is when finding the field id matching the field name, so escalate this to sentry.
=> chore(Jira): Add logging for some error cases

packages/server/createSSR.ts
Ahrefs continuously flags a minor error where our product signup and demo pages are confused as the same link. There is currently no canonical link set. 
Fixes #7125
However, the following URLs are flagged as duplicate content and we should set https://action.parabol.co/retrospective-demo as the canonical link for them.
1. https://action.parabol.co/retrospective-demo/reflect 
2. https://action.parabol.co/retrospective-demo/vote 
3. https://action.parabol.co/retrospective-demo/group
=> fix: Retrospective demo canonical link

packages/client/components/TeamPrompt/Recurrence/TimeLeftBadge.tsx, packages/client/components/TeamPrompt/TeamPromptBadge.tsx, packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx, packages/client/components/TeamPrompt/TeamPromptMeetingStatus.tsx, packages/client/hooks/useAnimatedCard.ts, packages/client/hooks/useTransition.ts, packages/client/mutations/EndTeamPromptMutation.ts, packages/client/mutations/StartTeamPromptMutation.ts, packages/client/subscriptions/TeamSubscription.ts, packages/client/utils/date/relativeDate.ts, packages/server/dataloader/customLoaderMakers.ts, packages/server/graphql/private/mutations/processRecurrence.ts
Fixes #7500 #7498 
This scenario requires some manual db tweaking as there's no direct way to create meeting in the meeting series
-  create two standups meetings, start recurrence in one of them
-  manually update the second meeting with `meetingSeriesId` associated with the one that has recurrence started
-  now, end one of the meetings and check the ended meeting badge, there should be a link to the current meeting
- create standup meeting, enable recurrence, end the meeting and go back to the meeting view
=> feat(recurrence): Added current meeting link to ended meeting badge in standups

packages/client/package.json, packages/server/package.json
Fixes a security hole allowing for XSS via SVG upload.
The way we use it today, you'd only be able to XSS yourself, meaning the attacker would have to get the victim to upload a nefarious profile picture.
Not gonna publish too much about this until it is in prod :sweat_smile:
=> fix: bump sanitize-svg version

packages/server/graphql/types/NewMeeting.ts, packages/server/graphql/types/helpers/isMeetingLocked.ts
Relates-To #7373 
The check if a meeting is locked did not check for `null | undefined` `endedAt` values, i.e. open meetings.
https://www.loom.com/share/ab15d5f8ece3404dbf98e99cafc84c63
- Create and join a meeting with a free tier team
=> fix: new meetings were locked with the history limit

packages/client/components/FacilitatorMenu.tsx
At the moment, picking a new facilitator is not truly random because the current facilitator is always excluded. 
It seems more intuitive (and fair) to pick from all meeting members.
-> Add current facilitator to facilitator candidates.
- 
-
=> fix: Change facilitator randomization to include current facilitator

packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Fix https://github.com/ParabolInc/parabol/issues/7593
Demo: https://www.loom.com/share/c0702add99d249ceb40c227d7faf5b39
=> fix: access custom template

packages/client/components/MeetingLockedOverlay.tsx, packages/client/components/TimelineEventCompletedActionMeeting.tsx, packages/client/components/TimelineEventCompletedRetroMeeting.tsx, packages/client/components/TimelineEventPokerComplete.tsx, packages/client/components/TimelineEventTeamPromptComplete.tsx, packages/client/components/TimelineHistoryLockedCard.tsx, packages/server/graphql/types/UpgradeCTALocationEnum.ts
=> chore(metrics): change upgrade CTA events to standard definitions

.github/reviewers.yml
I missed @nickoferrall's introduction of the `Upgrade CTA Clicked` event, which caused some event naming rework in #7592.  I'd like to add the data team as reviewers for any changes to the analytics files, so we can keep a closer eye on new Segment event definitions.
=> chore: add data team as reviewers for analytics changes

packages/client/validation/Legitity.ts, packages/server/graphql/mutations/helpers/validateScaleValue.ts
Fix: https://github.com/ParabolInc/parabol/issues/7577
Demo: https://www.loom.com/share/e50282aaa8294da28070bb530ea31df3
=> fix: emoji length check

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
Non-retro summary pages are broken on `master` (not yet in prod) due to a retro-only meeting fragment that could refer to a non-retro meetings.
Update the fragment, and check the meeting type in the component.
Pre-fix:
Go through any non-retro/non-standup meeting to the summary, and get a `Cannot read properties of undefined (reading 'some')` error.
Post-fix:
Go through any non-retro/non-standup meeting to the summary, and see the summary without error.
Go through a retro with AI summaries and see the summaries on the summary page.
=> fix: Broken summary pages

packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
Fixes/Partially Fixes #7169
- How to reproduce
- join a check-in with Hilde and Olga
- advance to solo update from Hilde with 2 tasks visible
- Hilde changes the due date of task 1 and moves the mouse to task 2
Olga sees task 1 highlighted and then task 2
Actual behaviour
Olga sees task 1 still highlighted when Hilde moves to task 2, so both tasks are highlighted
[loom](https://www.loom.com/share/366055c8688b4ac69918ae6b0822abe9)
=> fix: task highlight sticks when adding a due date

packages/client/components/JiraFieldDimensionDropdown.tsx, packages/client/components/JiraFieldMenu.tsx, packages/client/mutations/UpdateJiraDimensionFieldMutation.ts, packages/client/utils/AtlassianManager.ts, packages/server/dataloader/atlassianLoaders.ts, packages/server/graphql/mutations/setTaskEstimate.ts, packages/server/graphql/private/typeDefs/_legacy.graphql, packages/server/graphql/public/mutations/updateJiraDimensionField.ts, packages/server/graphql/public/typeDefs/JiraIssue.graphql, packages/server/graphql/public/typeDefs/_legacy.graphql, packages/server/graphql/public/typeDefs/updateJiraDimensionField.graphql, packages/server/graphql/types/AtlassianIntegration.ts, packages/server/graphql/types/EstimateStage.ts
Resolves: #7560 
Jira allows to have multiple fields with the same name in a project, even on the same issue. While this does not make sense from a usability standpoint, this backfired for us, because we were selecting fields based on their name and could end up selecting fields which belonged to a different issue type altogether. Now even multiple fields called "Story Points" on one issue are allowed and work.
https://www.loom.com/share/b56ce436c22b4eeb870957e3d3592a94
See demo
- Create at least 2 fields with the name "Story Points" in a Jira project
- Assign 1 field to the issue type "Bug" and the other one to the issue type "Story"
=> fix(Jira): fix Sprint Poker voting for projects with duplicate fields

packages/client/modules/email/components/EmailFooter/EmailFooter.tsx, packages/client/modules/email/components/ResetPasswordEmail.tsx, packages/client/modules/email/styles.ts, packages/client/modules/invoice/components/InvoiceFooter/InvoiceFooter.tsx
We've had reports that emails land in spam.
Digging into it, I tracked it down to poor color contrast in our emails. Spam filters thought were were trying to hide invisible text in the emails. The 2 problem areas were the link colors & footer colors.
I also saw some spam filters look for a physical address & phone number, so I added those to the footer. 
- [  ] Make sure the screenshots look OK!
=> fix: emails landing in spam

.husky/post-checkout
Fixes: #6286 
When switching branches where the target branch is missing some migrations, print a warning with the migration files which will not be present there and steps to run the down migration. The down migrations are not run automatically.
https://www.loom.com/share/f05d16bb86ee432984e4a86d6591759d
See demo
=> chore(DX): Show a warning on switching branch with migrations

.github/workflows/assign_mentioned.yml
If a user is mentioned in a PR or issue, then the author/current assignee probably needs something from them. In order to not loose track add the users as reviewer/assignee.
=> chore: Add reviewer for PRs and assignee for issues on mention

packages/client/jest.config.js, packages/client/package.json, packages/client/utils/__tests__/parseEmailAddressList.test.ts, packages/client/validation/Legitity.ts, packages/client/validation/__tests__/Legitity.test.ts
Fixes: #7622 
Legitity has a separate `required` test which checks for non-undefined, thus all other checks need to be able to cope with undefined values.
Added tests to simplify verification of the fix.
- in a Check-In meeting
- run client tests
- `yarn workspace parabol-client test`
=> fix: Legitity min/max failed on undefined value

packages/client/utils/SlackClientManager.ts, packages/server/utils/SlackServerManager.ts
Uses our cloudflare worker to handle Oauth2 redirects for slack.
This was blocked behind slack approving our app again.
This is the latest in the saga. For the previous PR, see #7514
- set `OAUTH2_REDIRECT='https://oauth2redirect.parabol.co'` in your .env
- Add Slack as an integration :tada: 
This was already tested in #7446, so I don't think it needs testing again.
=> feat: slack uses oatuh2 redirect

packages/client/components/NotificationPicker.tsx, packages/client/components/TeamPromptMeeting.tsx, packages/client/mutations/toasts/mapResponseMentionedToToast.ts, packages/client/mutations/toasts/mapResponseRepliedToToast.ts, packages/client/mutations/toasts/popNotificationToast.ts, packages/client/subscriptions/NotificationSubscription.ts
Fixes https://github.com/ParabolInc/parabol/issues/7559
This does a couple things:
* Brings the generalized `AddedNotification` pattern into our toasts, such that a new notification simply needs to map the notification fragment to toast's `Snack` object, and add the fragment to the `popNotificationToast` fragment
* This automatically marks the notification as `CLICKED` when the user clicks into the notification via the action button (similar to a subset of existing toasts).
* Implement the mapping for a few of the new notifications:
* Standup response replied-to toasts
* Standup response mentioned toasts
Once either this PR or https://github.com/ParabolInc/parabol/pull/7596 lands, we'll want to incorporate relevant changes into the not-merged PR.
=> feat(standups/notifications): Generalized notification toasts + new toasts

.circleci/config.yml, package.json, packages/client/package.json
Add client unit tests to the build job. There are few tests, so let's see how much it slows the job down. We might want to split the job in the future.
Check if the tests were run on this PR
Check if the tests were run on this PR
=> chore: Add client unit tests to CircleCi

packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/7615
After following suggestion number 2 in this article (https://help.openai.com/en/articles/6654000-best-practices-for-prompt-engineering-with-openai-api), I'm getting better results from the summary.
Here is a comparison of the most recent Squad retro in prod vs the summaries with this new prompt. The first image is from prod and the second with the new prompt:
Example 1:
Example 2:
Example 3:
=> chore(ai-summary): improve prompt

packages/client/components/ThreadedCommentBase.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryLoading.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx, packages/server/graphql/mutations/addReactjiToReactable.ts, packages/server/graphql/types/SegmentEventTrackOptions.ts, packages/server/utils/analytics/analytics.ts
Fix https://github.com/ParabolInc/parabol/issues/7467
=> chore(ai-summary): track when the summaries are viewed

packages/server/dataloader/customLoaderMakers.ts, packages/server/dataloader/rethinkForeignKeyLoaderMakers.ts, packages/server/graphql/mutations/endRetrospective.ts
Fix https://github.com/ParabolInc/parabol/issues/7647
=> fix(ai-summary): remove AI comment from comment count

packages/client/components/AnalyticsPage.tsx, packages/client/components/SAMLRedirect.tsx, packages/client/mutations/LoginWithGoogleMutation.ts, packages/client/mutations/SignUpWithPasswordMutation.ts, packages/server/graphql/private/mutations/loginSAML.ts, packages/server/graphql/private/typeDefs/_legacy.graphql, packages/server/graphql/public/mutations/loginWithGoogle.ts, packages/server/graphql/public/typeDefs/loginWithGoogle.graphql, packages/server/graphql/public/types/LoginWithGooglePayload.ts, packages/server/utils/SAMLHandler.ts
Today, we sent `sign_up` events from Segment to GA4. However, due to limitation of Segment, these events have no session information (or any info):
As a result, `sign_up` events cannot be attributed to previous `page_view` events in GA4:
Basically no useful analysis can be performed...😢
This PR emits `sign_up` events directly from GA4 client side. This way all relevant info (session, geo, ...) are automatically populated.
The GA4 client side emitted `sign_up` events look like these in BigQuery:
Attribution seems to work afterwards:
- Verify a `sign_up` event is emitted to GA4
- Verify a `sign_up` event is emitted to GA4
- Verify **NO** `sign_up` event is emitted to GA4
=> chore(metrics): emit sign_up events from GA4 client side

packages/client/components/Action/Action.tsx
This PR moves global styles creation outside of `Action` component render cycle. As this component rerenders on every route update, the performance gain for each render is around ~50%. Without that fix, the initial render time of `Action` component varies between 1.5 ms to 3 ms (calculated ~40 times). With the fix, it's not more than 1 ms - 1.1 ms (same number of calculations). See the example screenshots from React profiler below. This was tested on M1 Max, so I'd assume the time difference will be higher for an average machine. 
~Before:
~After:
=> perf: Moved global style creation outside of the React render cycle

packages/server/postgres/migrations/1673613407246_updateAIUserPic.ts
I added a new image to S3 which is the same as the old favicon but with more padding: https://s3.console.aws.amazon.com/s3/object/action-files.parabol.co?region=us-east-1&prefix=static/favicon-with-more-padding.jpeg
This PR includes a migration to update the Parabol AI user's picture.
Old avatar: 
New avatar:
=> fix(ai-summary): update Parabol AI picture

packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
Related to https://github.com/ParabolInc/parabol/issues/7655
I'm not sure why the topic summary wasn't generated in the meeting shared in the issue, but either the `summary` wasn't generated or there were no `reflectionGroups`. 
This PR adds two `sendToSentry` functions which should help with debugging if it happens again.
=> chore: sendToSentry if unable to create topic summary

packages/client/components/DashNavList/DashNavList.tsx, packages/client/components/NewMeetingActions.tsx, packages/client/modules/teamDashboard/components/Team/Team.tsx, packages/client/modules/teamDashboard/components/UnpaidTeamModal/UnpaidTeamModal.tsx, packages/client/mutations/UpgradeToTeamTierMutation.ts, packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts, packages/server/graphql/types/UpgradeCTALocationEnum.ts
Fixes #7638
Billing leader:
Non billing leader:
Meeting creation error:
How to test
- Set `lockedAt` value on organization 
- See that all teams locked and modal is shown
- See that modal is different for billing leader and non billing leader user
- See that you can't create a new meeting
- See that you can still create a meeting on non-locked teams
- See that after upgrading org the lock is gone
=> feat(teams-limit): implement organization locked modal

packages/server/graphql/mutations/endRetrospective.ts, packages/server/postgres/migrations/1674074684762_deleteEmptyGroups.ts
Fixes #7669 frees up ~800MB
Running this on staging the read query took about 80 seconds. When done in batches, it took ~7 seconds for 10k records, so i figured a single query is probably better.
=> fix: delete empty reflection groups

packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx
[From our UI refinement backlog 🔒](https://www.notion.so/parabol/UI-System-7860fc91e5024379a2d49e000458a914?p=dec72adfa88c45e290d2a577bb32f2ad&pm=s)
This PR increases the scale value used on the colored dot so it cover more area both in desktop and mobile sizes.
=> fix: prompt highlight color does not cover the full-height of the column

packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx, packages/client/components/promptResponse/PromptResponseEditor.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummary.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx, packages/client/package.json, packages/server/email/newMeetingSummaryEmailCreator.tsx, packages/server/graphql/mutations/endTeamPrompt.ts, packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts, packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts, packages/server/graphql/private/mutations/processRecurrence.ts, yarn.lock
Fixes https://github.com/ParabolInc/parabol/issues/7640
Makes standup summaries compatible with SSR + email styling.
Note that tiptap styling in emails doesn't work currently - I investigated how to apply the desired styling to the rendered HTML from tiptap, but couldn't figure it out in a reasonable amount of time. If reviewers don't have any immediate leads on how to resolve this, I'll create a follow-up issue for this.
In-app
In email
=> feat(standups): Email Summaries

packages/server/database/migrations/20230116165620-fixStarfishTemplate.ts
Fix https://github.com/ParabolInc/parabol/issues/7466
It looks like the Starfish template had missing prompts because it was using the duplicated prompt id [here](https://github.com/ParabolInc/parabol/issues/7466). It was inserted at the same time as the DAKI template, which also had the same bug. I've checked the other templates that were added, Lean Coffee and What Went Well, and those are working as expected.
=> fix: missing prompts in starfish retro template

packages/client/components/MeetingsDash.tsx, packages/client/components/MeetingsDashEmpty.tsx, packages/client/components/TopBarSearch.tsx, packages/client/types/constEnums.ts
Add a search bar in meeting view
- Type a query word in the search bar
- Meeting cards only show matched ones
- Remove everything from the search bar
- Meeting view show all active meetings
=> feat(search): add search ability to meeting view

packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
The "Go to the next activity" link actually goes to the current activity (which is the correct behavior). Change the copy to read "Go to the current activity".
https://parabol.slack.com/archives/C043AHXNB32/p1675097875327929
N/A
=> fix(standups): 'next activity' -> 'current activity'

packages/client/components/SAMLRedirect.tsx, packages/client/mutations/LoginWithGoogleMutation.ts, packages/client/mutations/SignUpWithPasswordMutation.ts, packages/server/graphql/private/mutations/loginSAML.ts, packages/server/graphql/private/typeDefs/_legacy.graphql
In GA4 we would like to separate apart patient 0 sign up for attribution reports.
- Sign up as a patient 0
- Check GA4 dashboard
- Sign up using an email with existing domain
- Check GA4 dashboard
=> chore(metrics): Add `isPatient0` property to `sign_up` events emitted by GA4

packages/client/mutations/EndRetrospectiveMutation.ts
We want to add the HubSpot chatbot to meeting summaries that have the AI Summary. To do that, we can update the URL so HubSpot knows when it has an AI Summary.
Related to https://github.com/ParabolInc/parabol/issues/7474
=> chore(ai-summary): update meeting summary url

packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts, packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/7738
This PR updates the OpenAI prompt with the location. This makes it more likely that the summary refers to the meeting or discussion thread rather than "the text".
To test, I went through some of the examples in the issue, copying and pasting the discussion thread comments & tasks. The results seem to be better:
=> fix(ai-summary): summary references "the text"

packages/server/graphql/public/typeDefs/addFeatureFlag.graphql, packages/server/graphql/public/types/UserFeatureFlags.ts, packages/server/graphql/types/UserFlagEnum.ts, packages/server/graphql/types/helpers/isMeetingLocked.ts
Fixes #7666 
Limit is enabled by default now.
=> chore: Invert meetingHistoryLimit feature flag

packages/server/graphql/public/mutations/addFeatureFlag.ts
We have been doing a lot of experiments recently, which involves adding feature flags for a lot of users. We have noticed that `.identify()` on Segment will:
1. [Increase our MTU](https://parabol.slack.com/archives/C03C3J42WDU/p1673544145767659) so economically that's unsustainable 
2. Mess up downstream metrics like [GA4](https://parabol.slack.com/archives/C03C3J42WDU/p1673544145767659), where they think we do have that many of active users, but that's not the truth
This PR simply removes the `.identify()` calls from the `addFeatureFlag` mutation resolver. The only place we are using the user property is in Amplitude analysis and today we are feeding it with Segment ETL, which queries BigQuery and then update Amplitude periodically so it would continue to work.
=> chore(metrics): Do not call identify() on feature flag changes

packages/client/components/MeetingCard.tsx, packages/client/components/MeetingsDash.tsx, packages/client/styles/paletteV3.ts
Fixes https://github.com/ParabolInc/parabol/issues/7702
~Needs rebase once https://github.com/ParabolInc/parabol/pull/7707 lands~. Rebase complete
Recommend reviewers to set `?w=1` to avoid whitespace-only diffs.
Updates meeting cards for recurring meetings according to designs:
* Recurring label
* Recurring meetings shown before non-recurring meetings on dash
* Meeting series title instead of meeting name
* Meeting card stack
* Links to meeting series (link will need to be updated once stable link is changed in https://github.com/ParabolInc/parabol/pull/7707)
When a meeting changes from one-time to recurring and back:
https://www.loom.com/share/1226748129da4c3885a83f74dd6e43c8
=> feat(recurrence): Recurrence-specific meeting card

packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts, packages/server/graphql/private/mutations/processRecurrence.ts
Fixes https://github.com/ParabolInc/parabol/issues/7735
When a team is archived, we don't close any meetings or meeting series (presumably to make undoing that action possible by Parabol employees for support cases). This has a negligible impact for one-off meetings, but because we don't check if a team is active when processing recurrence, recurring meetings on archived teams will continue to recur.
=> fix(recurrence): Don't restart meetings on archived teams

packages/client/components/NewMeetingCarousel.tsx, packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
After shipping advanced recurrence we decided to remove standups beta badge. This PR does that.
No demo
=> chore(standups): removed beta badge from standups

packages/server/graphql/mutations/endCheckIn.ts, packages/server/graphql/mutations/endRetrospective.ts, packages/server/graphql/mutations/endSprintPoker.ts
Fixes #7763 
`isKill` is defined as being a non-nullable boolean which was sometimes set to null. Fix it by evaluating null to false.
- Step 1
- Step 2...
- Step 1
- Step 2....
=> fix: sometimes meetings could not be closed

packages/server/graphql/mutations/helpers/notifications/getSummaryText.ts
Related to https://github.com/ParabolInc/parabol/issues/7674
If there's an AI Summary and there are no meeting stats, send an error to Sentry.
This will let us know how often it's happening and provide more info about the bug.
=> chore(ai-summary): track no stats in Slack summary

packages/server/postgres/migrations/1676299334703_addSeasonalTemplates.ts
Fix https://github.com/ParabolInc/parabol/issues/7434
Changes I've made from the issue:
- Capitalised retrospective to be consistent with the others, so `Holi Retrospective` instead of `Holi retrospective`
- Capitalise question titles, so `Easter Eggs` instead of `Easter eggs`
- Move the emoji to the end of the question title as the formatting can look strange on 
@garethaledavies do those changes work for you and would you mind reviewing the PR to make sure the copy is correct?
Here's a screenshot of one of them:
=> feat: add seasonal retros

packages/client/mutations/AcceptTeamInvitationMutation.ts, packages/server/graphql/types/AcceptTeamInvitationPayload.ts
Fixes #7771
How to test:
- create a new team
- create an invite link from the team dashboard
- follow the invite link with a different user
=> fix: Fix server error when joining a team by invitation link

packages/client/components/MeetingCardOptionsMenu.tsx, packages/client/components/MenuItemLabel.tsx, packages/client/components/TeamPrompt/TeamPromptOptions.tsx, packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7703
Allow copying a meeting series' permalink from either the meeting card or the in-meeting options menu.
https://www.loom.com/share/6f5e01dca25f4ae982c3320b66a58c4f
For both meeting card and in-meeting options menu, including previous meeting in a series:
=> feat(recurrence): Copy meeting series permalink

packages/client/components/EditingStatus/EditingStatusText.tsx
Fixes #7761
Removes an unwanted `font-size: 18px` declaration for the task editing status label.
**Before:**
**After:**
- Edit a task on any team
- When one user is editing the task, impersonate another team member and check the font size of the editing status label.
-
=> fix: remove font-size 18px declaration on tasks editing status label

packages/client/components/MeetingCard.tsx
Fixes issue in [slack](https://parabol.slack.com/archives/C836NA350/p1676561100303009) 🔒 
After recent changes to the component structure of meeting cards, shadows take up the height of the tallest card in the row, instead of the height of the actual card. This leads to weird effects like this:
This PR fixes that issue.
Meeting series card shadow:
One-off meeting card shadow:
=> fix(dashboard): Meeting card shadow doesn't match card

packages/client/components/DiscussionThreadInput.tsx, packages/client/components/TaskEditor/CommentEditor.tsx
Fixes https://github.com/ParabolInc/parabol/issues/6873
Autofocus discussion drawer input in standup meetings.
This was previously fixed, but reverted because the autofocus was applied to _all_ meetings (not just standups), which broke facilitator-following in other activities. This PR specifically limits the autofocus to standup meetings.
Also migrates `DiscussionThreadInput` to `useFragment` via the [codeshift](https://github.com/ParabolInc/parabol/pull/7135)
https://www.loom.com/share/5cfe7f8a464f418690b32ed7e54942e1
=> fix(standups): Autofocus the input in the discussion drawer when opened

docker/dev.yml
fix #7785 
All dev containers run on the architecture as the host machine. no rosetta required.
On an M1:
```sh
yarn db:stop
docker image rm redis && docker image rm rethinkdb && docker image rm rediscommander/redis-commander
yarn db:start
```
check docker desktop, see all images are ARM.
=> chore: select best platform for the job

packages/server/package.json, yarn.lock
With some recent package upgrades, mailgun requests will fail with `from parameter is missing`, even though `from` is definitely present.
This issue seems to be fixed with `v7.0.4`, so upgrade to that version.
I took a look through the [changelog](https://github.com/mailgun/mailgun.js/blob/master/CHANGELOG.md) to see if we may be impacted by the breaking changes + smoke tested emails, and there don't seem to be any issues, but I encourage reviewer to also take a look.
Smoke test emails
=> fix(emails): Upgrade mailgun to 7.0.4

packages/client/components/ActivityLibrary/ActivityLibrary.tsx, packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx, packages/client/components/Dashboard.tsx, packages/client/components/PrivateRoutes.tsx, packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql, packages/server/graphql/public/types/UserFeatureFlags.ts
This PR adds `retrosInDisguise` feature flag and an empty frontend component for activity library. Empty component is accessible under `/activity-library` route, if the `retrosInDisguise` feature flag was set. If not, it'll redirect to 404.
Component names, route urls and everything else are TDB and intention of this PR is only add stub components so we can start working on the details. 
No demo
=> chore(retros-in-disguise): Added retros in disguise feature flag and empty route

docker/dev.yml
Using fixed versions of RethinkDB, Redis and PostgreSQL would assure that all developers have the same workstation setup. Currently, everyone might be using a different version of the databases in their workstation, and those version might be different than the ones in staging and production.
If an upgrade is performed for any of the databases, the developer would need to modify the `docker/dev.yml` and the code and libraries, pushing then all in the same PR, which will force the upgrade for all developers once is merged to master.
=> chore(docker): Redis and RethinkDB database versions fixed for the development docker-compose

docker-compose.yml, docker/dev.yml
RethinkDB 2.3.7 wasn't available for arm64. We agreed on using 2.4.2 locally as there weren't breaking changes between 2.3.7 and 2.4.2 (the version in staging and production). We should upgrade RethinkDB in the future to 2.4.2.
docker-compose.yml file wasn't modified on the last PR and thus the database versions weren't fixed there. They are now.
We are aware that the Dockerfile.prod might not work anymore and we will address that in another PR.
Before testing, it is probably better to remove volumes that can be in a newer version of Redis or RethinkDB with `yarn db:stop && docker volume rm docker_redis-data docker_rethink-data`
- First scenario: run `yarn db:start` and then `yarn dev` to test the application locally.
- Run `docker-compose -f docker-compose.yml -f …
=> chore(docker-compose): RethinkDB fixed to v2.4.2 and Redis fixed to v6 for local development and self-hosted deployment

scripts/codeshift/convertToUseFragment.ts
Fixes an issue where JSX that looks like
```
<NewMeetingAvatarGroup meetingRef={meeting} />
```
would cause the script to fail when checking for conflicts with the `meetingRef` identifier.
N/A
=> chore(relay): Fix convertToUseFragment naming conflict bug

packages/client/components/MeetingsDash.tsx, packages/client/components/TopBarSearch.tsx
No issue, it's just a small UI improvement to visually align search bar and meeting cards. See the conversation [🔒 here.](https://parabol.slack.com/archives/C02438U0VJ4/p1677246806926119)
Before
After
=> fix: align search bar with meeting cards

packages/client/modules/email/components/LimitsEmails/SevenDayWarningEmail.tsx
How to test:
- Trigger teams limit and runScheduledJobs
- See that link from the above screenshot is now clickable
=> fix(teams-limit): add missing billing link to 7 days warning email

packages/client/validation/__tests__/Legitity.test.ts
Test `min`/`max` edge case behaviour.
no
CI runs these: https://app.circleci.com/pipelines/github/ParabolInc/parabol/8508/workflows/d7487f11-dcd8-47de-aa8a-b8192b4938d1/jobs/17305/parallel-runs/0/steps/0-116
=> chore: Add some more Legitity tests

packages/client/components/InsightsDomainNudge.tsx
Fixes #7838
When the time is up, instead of the countdown timer show another message
- Set scheduledLockAt on the org = new Date()
- See the message from the screenshot above
=> fix(teams-limit): fix locked message in usage stats

packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
Show a "Stop recurrence" button when recurrence is enabled.
See [slack](https://parabol.slack.com/archives/C03THUWKVQ8/p1676996230969539) 🔒 
[Figma](https://www.figma.com/file/2tpJMKUScCyvSA9YJwmM0a/Standups-Recurrence?node-id=452%3A23909&t=jQOEj7HiE49QSNjl-4) 
https://www.loom.com/share/7ea7a2bac48f4fca9c480de4138ba824
=> feat(recurrence): Stop Recurrence button

.circleci/config.yml
RethinkDB and PostgreSQL backups were done from our workstation, as well as the wipe-out and restore done in Staging before each release. With this PR, the process is 100% done from CircleCI.
This PR depends on one from our private repository for DevOps scripts to add one option to our [postgres|rethinkdb]-restore.sh allowing to skip the prompt question for non production environments.
=> chore(pipeline): Databases backup and restore from CircleCI pipeline

packages/client/components/InsightsDomainNudge.tsx, packages/client/components/LimitExceededWarning.tsx, packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Fix https://github.com/ParabolInc/parabol/issues/7692
In this PR, I'm using the UI that we have in Insights as I think we should be consistent with the UI & messaging.
Org with the `scheduledToLock`:
Org with the `lockedAt`:
=> feat(checkout-flow): add teams limit warning

codegen.json, packages/client/components/ActivityLibrary/ActivityLibrary.tsx, packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx, packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx, packages/client/components/ActivityLibrary/ActivityLibrarySideBar.tsx, packages/client/components/PrivateRoutes.tsx, packages/server/graphql/public/typeDefs/_legacy.graphql, packages/server/graphql/public/types/User.ts, packages/server/graphql/queries/helpers/connectionFromTemplateArray.ts, packages/server/graphql/queries/helpers/getScoredTemplates.ts, packages/server/graphql/types/PokerMeetingSettings.ts, packages/server/graphql/types/RetrospectiveMeetingSettings.ts, packages/server/utils/getTemplateScore.ts
Create the basic layout for the activity library + stubbed activity "cards".
From here, we can implement activity card designs in parallel with categories + search (which effectively just filter the activity cards shown).
Fixes https://github.com/ParabolInc/parabol/issues/7832
=> feat(retros-in-disguise): Base activity library + stubbed cards

packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Inspired by https://github.com/ParabolInc/parabol/pull/7799/files/8a3661137fc2fe70623ca490280625a38f3855cc#r1124136458
I couldn't resist making this cleaner 😅
=> chore: simplify org plans button logic

packages/client/components/AnalyticsPage.tsx, packages/client/components/SAMLRedirect.tsx, packages/client/mutations/LoginWithGoogleMutation.ts, packages/client/mutations/SignUpWithPasswordMutation.ts
Fixes https://github.com/ParabolInc/parabol-data-sanctum/issues/564
TLDR: previously we emit `isPatient0` as event-scoped dimension. We should make it user-scoped dimension.
* Page view:
* Sign up:
- Sign in as a user
- View a couple of pages
- Verify in Analytics Debugger that `page_view` events have user properties with `is_patient_0` set up
- From `/create-account`, sign up 
- Verify in Analytics Debugger that `sign_up` events have user properties with `is_patient_0` set up
=> chore(metrics): emit `is_patient_0` as user properties for GA4

packages/client/components/TopBarIcon.tsx
Fixes #7816
- Standby
- Focus state
- Standby
- Focus state
-
=> fix: position of notification bell badge

packages/client/components/ActivityLibrary/ActivityLibrary.tsx, packages/client/components/ActivityLibrary/SearchBar.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7834
Implement search functionality in activity library:
* Search bar
* Search query filters templates that are rendered by the template name
* Empty state when no templates match the query
Note that the matching is pretty basic - just the basic string match that `useSearchFilter`. Anything more complex is out of scope for RiD v0.
Also note that the "create custom activity" card is excluded from the empty state with a TODO, since we'll likely want to reuse styles+components implemented as part of https://github.com/ParabolInc/parabol/issues/7833. I'll create a new task for that once this PR lands.
https://www.loom.com/share/1ae5db6ca2444b289797d8fb7a25c1f6
=> feat(rid): Basic activity library search

packages/client/mutations/RemoveOrgUserMutation.ts, packages/client/subscriptions/NotificationSubscription.ts
Fixes #7381 
No demo
- user A is an org billing leader, user B is a user in the user's A org
- start a check in meeting
- from a different browser window, join with user B, set a stage to user's B update
- as a user A, go to org settings and remove user B from org
- user B should be redirected to the dashboard
- user B has no tasks
- user A is an org billing leader
- user A removes user B
- users B app doesn't crash
=> fix: do not run removeOrgUserTaskUpdater for undefined tasks

packages/client/components/EditableOrgName.tsx, packages/client/components/SuggestedActionCreateNewTeam.tsx, packages/client/components/SuggestedActionTryActionMeeting.tsx, packages/client/components/SuggestedActionTryRetroMeeting.tsx, packages/client/components/SuggestedActionTryTheDemo.tsx, packages/client/components/TaskFooterIntegrateMenuRoot.tsx, packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx, packages/client/modules/meeting/components/AddTemplatePrompt.tsx, packages/client/modules/meeting/components/EditableTemplateDimension.tsx, packages/client/modules/meeting/components/EditableTemplatePrompt.tsx, packages/client/modules/teamDashboard/components/EditTeamName/EditableTeamName.tsx
refs https://github.com/ParabolInc/parabol/issues/6283
Converted using the process described in https://www.notion.so/parabol/How-to-Migrate-createFragmentContainer-useFragment-with-codeshift-d534e7d0b8674089a2075f2835544558 🔒 
Note that this contains some non-automated changes (e.g. consolidating prop restructurings), so reviewers may wish to look at the code a bit more carefully, but most of these diffs were still automated with the script.
Once this + https://github.com/ParabolInc/parabol/pull/7874 lands, we should be able to quickly finish off https://github.com/ParabolInc/parabol/issues/6283 by removing occurrences of `UNSTABLE_renderPolicy: 'full'`.
=> chore(relay): createFragmentContainer -> useFragment 7/7

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Fix https://github.com/ParabolInc/parabol/issues/7712
=> chore(template-limits): add template limit flag to p0 domains

packages/client/modules/meeting/components/ReflectTemplateList.tsx, packages/client/modules/meeting/components/ReflectTemplateListTeam.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7900
See [slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1678371595957819) 🔒 
Attempting to click "create new template" for retros currently throws an error due to weirdness manifesting as a result of the `createFragmentContainer` -> `useFragment` migration in `ReflectTemplateItem`.
Fix this by changing the fragments to the same structure that Poker uses, which doesn't contain this bug.
N/A
=> fix(templates): Fix 'Create new template' button error for retros

.github/reviewers.yml
The `assign_reviewers.yml` GitHub action will assign a developer to any PRs from outside contributors, effectively denoted as "anyone not in one of the four groups in `reviewers.yml`".
A few Parabol engineers are currently missing from this list, so their PRs are auto-requesting review. Add them to the list so this stops happening
N/A
N/A
=> chore(dx): Add Parabol employees to reviewers to prevent auto-request-review

packages/client/components/ActionMeetingUpdatesPrompt.tsx
Fixes #7878 
- Removed width css
- Updating it to max-width (there's a horizontal scroll without)
- Moved the CSS to the HTML, with new Tailwind format
https://www.loom.com/share/29ebf1a158d8439a9f127c5c3529997e
- Review with a long name to ensure it wraps correctly
- Review with a large attendee list to make sure it doesn't wrap too soon
=> fix: changing width to max-width in tailwind format

packages/client/components/TeamsLimitExceededNotification.tsx, packages/client/mutations/toasts/mapTeamsLimitExceededToToast.ts, packages/client/mutations/toasts/mapTeamsLimitReminderToToast.ts
Fixes #7856
- Added a close button to each teams limit snackbar
- Changed "Your account is on roll" message. Made it similar to the second warning message. See the bottom snackbar:
**How to test**
- Trigger teams limit
- Run `runScheduledJobs` to see the second snackbar too
=> chore(teams-limit): change first warning notification text

packages/client/tailwindTheme.ts
Currently, there are a lot of warnings in local dev that look like:
```
warn - As of Tailwind CSS v2.2, `lightBlue` has been renamed to `sky`
warn - Update your configuration file to silence this warning.
```
This is because we're currently pulling in all default colors in `tailwindcss/colors`, which includes a few colors that have been renamed.
To fix this, just pull in the colors we're actually using.
N/A
=> chore(tailwind): Fix rename warning

packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx, packages/client/components/promptResponse/PromptResponseEditor.tsx
Fixes https://github.com/ParabolInc/parabol/issues/6871
[miniRFC](https://www.notion.so/parabol/miniRFC-Persist-draft-standup-responses-ee2d82b79055447992aea5e3601c4c90)
Currently, if a user drafts a response in a standup meeting, then navigates away or refreshes the page without submitting, their entire draft response will be lost. This has led to things like "WIP" notes at the top of responses as individuals draft a response that they don't want to lose.
To solve this, persist draft responses to localstorage upon an update to the edited response. Then, when the editor loads, check localstorage for the presence of draft content that differs from the content provided by the GQL layer.
Note that almost the entire diff is included as part of `PromptResponseEditor` - I considered doing the …
=> feat(standups): Persist draft responses to localstorage

packages/server/graphql/mutations/endRetrospective.ts
Related to: https://github.com/ParabolInc/parabol/issues/7674
I won't be able to dig into this issue properly before the retreat (I fly tomorrow), but this PR _might_ help.
Previously, we were using `Promise.all` when adding the meeting stats. If `generateWholeMeetingSummary` were to throw an error, the meeting object wouldn't be updated with the commentCount, taskCount, etc.
Perhaps `generateWholeMeetingSummary` could throw an error if OpenAI took a long time to respond, but in the linked issue, the user doesn't have the OpenAI env vars set-up, so it would just return null right away. 
The linked issue also suggests that there aren't any stats in Slack, but the meeting summary does have the correct stats, suggesting the rethinkdb query in the Promise.all has been executed successfully.
I …
=> fix: slack stats
