circle.yml
package.json
src/server/__tests__/mock-tests.js

i think this is all we need, we'll see

get circleCI up & running

---

package.json
webpack/webpack.config.prod.js
webpack/webpack.config.server.js

Hey @mattkrick. Now using a plugin! 😁
We could integrate this more tightly via a custom plugin, but I'll take this incremental improvement.
Whachu think?

now using WebpackShellPlugin to build theme

---

src/universal/redux/AuthEngine.js
src/universal/redux/__tests__/AuthEngine-tests.js
src/universal/redux/__tests__/authDuck-tests.js
src/universal/redux/authDuck.js

Minor refactor authDuck, AuthEngine; adds unit tests

---

README.md

fixes #92 
changelog table is also added to parabol team/action/changelog in google drive (pasting from a spreadsheet makes converting to .md pretty easy)
Let's push a `v0.3.0` tag to master after accepted

add 0.3.0 to readme

---

package.json
src/universal/modules/teamDashboard/containers/Team/Team.js
src/universal/redux/getAuthedUser.js

in lieu of #107, i propose something a little simpler. I suspect @jordanh already tried this approach & got some bizarre errors in cashay, so now that the bug is fixed, this pattern is 💰 .
Does not address the `requireTeam` for the `/me` route, I'll keep that separate.

fixes #106

---

src/universal/components/LabeledFieldArray/LabeledFieldArray.js

A simple solution for autofocus

---

src/universal/modules/teamDashboard/containers/Team/Team.js
src/universal/modules/userDashboard/containers/Me/Me.js
src/universal/modules/userDashboard/containers/MeSettings/MeSettings.js
src/universal/modules/userDashboard/helpers/getUserAndMemberships.js
src/universal/modules/welcome/containers/Welcome/Welcome.js

Fix for #146

---

docs/epics/0001_Action_Epic_MVTP.md
src/server/graphql/models/Task/taskMutation.js
src/server/graphql/models/Task/taskSchema.js
src/universal/components/OutcomeCard/OutcomeCard.js
src/universal/components/OutcomeCard/OutcomeCardAssignMenu.js
src/universal/components/OutcomeCard/OutcomeCardFooter.js
src/universal/components/OutcomeCard/OutcomeCardStatusMenu.js
src/universal/components/OutcomeCard/OutcomeCardTextarea.js
src/universal/modules/teamDashboard/components/TeamCard/TeamCard.js
src/universal/styles/theme/labels.js
src/universal/subscriptions/subscriptions.js

Wired up status and ownership assignment.
Updated epic status.
Added editingBy to show who's editing a project, needs refactor.

Team dash 2

---

src/universal/modules/landing/components/Landing/Landing.js
src/universal/modules/landing/containers/Landing/LandingContainer.js

Closes #123
Also updated loginWithToken injected params

Added "or Log in" onButtonClick handler

---

src/server/graphql/models/TeamMember/teamMemberMutation.js

Original implementation had a 'few' things wrong about it 😉

Fix for acceptInvitation mega-query

---

package.json
src/client/makeStore.js
src/server/graphql/models/Team/teamMutation.js
src/universal/utils/clientOptions.js
src/universal/utils/constants.js

Adds client application versioning

---

src/universal/utils/makeCheckinGreeting.js

New check-in prompts

---

src/universal/components/Action/Action.js
src/universal/modules/teamDashboard/components/AgendaAndProjects/AgendaAndProjects.js
src/universal/modules/teamDashboard/components/AgendaHeader/AgendaHeader.js
src/universal/modules/teamDashboard/components/AgendaInput/AgendaInput.js
src/universal/modules/teamDashboard/components/AgendaInput/AgendaInputField.js
src/universal/modules/teamDashboard/components/AgendaItem/AgendaItem.js
src/universal/styles/helpers/index.js
src/universal/styles/helpers/makePlaceholderStyles.js

Fixes #234 
Fixes #226 
See: [http://g.recordit.co/1WkzP4bZ0B.gif](Screen recording GIF)

Agenda list updates

---

src/universal/components/OutcomeCard/OutcomeCardTextarea.js

Fixes #285 
See: http://recordit.co/BJT4NXGjJS
See: http://recordit.co/yngc1LONmd

Card textarea autoresize, subtle state styles

---

src/universal/components/Avatar/Avatar.js
src/universal/modules/meeting/components/MeetingAgendaItems/MeetingAgendaItems.js
src/universal/modules/meeting/components/MeetingCheckin/MeetingCheckin.js
src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js

- Fixes link to Agenda overflow issue for Updates phase
- Updates label text for meeting links
- Removes the annoying `console.log` on Avatar hover

Label updates for meeting, clean-up for avatar

---

src/universal/components/OutcomeCard/OutcomeCardFooter.js
src/universal/components/OutcomeCard/OutcomeCardTextarea.js

- Fixes the disabled state for the textarea of an archived project card
- Fixes the disabled state for the user avatar of an archived project card

Archived card disabled states - Fixes 347

---

src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js

Card footer team name outline removed

---

src/server/graphql/models/Team/teamMutation.js
src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js
src/universal/modules/meeting/components/Sidebar/Sidebar.js
src/universal/modules/meeting/containers/MeetingAgendaLastCall/MeetingAgendaLastCallContainer.js
src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js
src/universal/utils/shuffle.js
static/css/graphiql.css

- remove killMeeting
- add endMeeting
- add hotkey to endMeeting
- remove click to killMeeting

End meeting mini (fix #372)

---

src/universal/modules/welcome/components/Welcome/Welcome.js
src/universal/modules/welcome/containers/Welcome/Welcome.js

Logout in welcome (merge after the summary PR)

---

package.json
src/server/graphql/models/Meeting/meetingSchema.js
src/server/graphql/models/Team/teamMutation.js
src/server/server.js
src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js
webpack/webpack.config.prod.js

created my own npm package: manifest-assets-webpack-plugin
made it throw in case any more private variables get changed around

Fix uglify

---

src/server/graphql/models/Meeting/meetingSchema.js
src/server/graphql/models/Team/teamMutation.js
src/server/server.js
src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js

this adds `present` boolean to each teamMember in the MeetingSummaryContainer.
also fixes an undocumented bug where a Meeting wouldn't have all the required fields unless the meeting had at least 1 agenda item.

Add meeting attendance

---

src/universal/components/NotificationBar/NotificationBar.js
src/universal/utils/plural.js

No need to go hogwild & add in i18n just yet, but a nice plural function could do us some good in the interim.

create plural module fix #415

---

src/universal/components/NullCard/NullCard.js
src/universal/modules/email/components/Card/Card.js
src/universal/modules/email/components/SummaryEmail/SummaryEmail.js

fixes #445 #443 and NullCard article grammar

UI bug patch

---

src/universal/redux/reduxSocketOptions.js

Reducing reduxSocketOptions timeout value

---

src/universal/components/Avatar/Avatar.js
src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js
src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js
src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js

Meeting facilitator UI updates

---

src/universal/containers/ProjectCard/ProjectCardContainer.js
src/universal/modules/teamDashboard/components/ProjectColumn/ProjectColumn.js
src/universal/modules/teamDashboard/components/Team/Team.js
src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js
src/universal/modules/teamDashboard/containers/TeamSettings/TeamSettingsContainer.js
src/universal/routes/teamDashMain.js

This should fix the openArea bug. I applied the fix as high up the tree as possible. This is based off the assumption that the `form` value isn't found because `@cached` will return an empty string for the `id` field if it isn't immediately available, which is possible due to server latency. If this doesn't fix it, it's still a good idea to implement it like this, anyways. 
PS merge after #475

Open area fix #379 fix #437

---

src/universal/components/Avatar/Avatar.js
src/universal/modules/meeting/components/AvatarGroup/AvatarGroup.js
src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js
src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js

- Restores a default box shadow, with the option for border styling
- Makes lobby and last call primary buttons more prominent

Avatar style patch

---

src/universal/components/Dashboard/DashModal.js
src/universal/modules/email/components/SummaryHeader/SummaryHeader.js
src/universal/modules/meeting/components/MeetingAgendaLastCall/MeetingAgendaLastCall.js

- DashModal has updated border styling
- SummaryHeader has button-styled link to team dashboard
- LastCall pulls success expression from array

Minor UI updates

---

src/universal/components/CreateCard/CreateCard.js
src/universal/components/CreateCard/CreateCardRootStyles.js

[new CreateCards in action](http://g.recordit.co/EvmErj0n3V.gif)
Also, fixes the maxWidth of the CreateCard to be uniform with UI const.

fixes #514

---

src/universal/validation/templates.js

fix email validation

---

src/universal/modules/teamDashboard/components/NewTeamForm/NewTeamForm.js

Add 'New Team' event.

---

COPYING
LICENSE
README.md

@tayamueller, @mattkrick, @ackernaut: we'll talk about this mañana

Proposal for new dual-licensing disposition

---

CONTRIBUTING.md

We think it's more explicit, and just plain easier to understand.

Rolled 10-point bonus into score.

---

package.json
src/universal/components/Avatar/Avatar.js
src/universal/components/AvatarBadge/AvatarBadge.js
src/universal/components/DashboardAvatars/DashboardAvatars.js
src/universal/modules/teamDashboard/containers/Team/TeamContainer.js
webpack/webpack.config.dev.js
webpack/webpack.config.prod.js
webpack/webpack.config.server.js
yarn.lock

i don't want add-orgs to ge too crazy big, so i'm starting a PR on top of it.
- add dash presence
- update webpack

Add dash presence

---

package.json
src/server/graphql/models/Team/teamMutation.js
src/server/graphql/models/User/userMutation.js
src/server/segmentIo.js
src/server/worker.js
src/universal/redux/authDuck.js
yarn.lock

Segment meeting number server side

---

README.md

Update readme to use yarn, fix a typo :)
@jordanh @mattkrick @ackernaut

Update readme to use yarn, fix typo

---

README.md

@mattkrick @jordanh @ackernaut

Update node version in readme to 7.6.0

---

src/server/graphql/models/Action/actionQuery.js
src/server/graphql/models/Action/actionSubscription.js
src/server/graphql/models/Invoice/invoiceQuery.js
src/server/graphql/models/Organization/organizationQuery.js
src/server/graphql/models/Organization/organizationSubscription.js
src/server/graphql/rootQuery.js
src/universal/modules/newTeam/containers/NewTeamForm/NewTeamFormContainer.js
src/universal/modules/userDashboard/components/OrgBilling/OrgBilling.js
src/universal/modules/userDashboard/components/UserActionList/UserActionList.js
src/universal/modules/userDashboard/containers/CreditCardModal/CreditCardModalContainer.js
src/universal/modules/userDashboard/containers/OrgBilling/OrgBillingContainer.js
src/universal/modules/userDashboard/containers/UserActionList/UserActionListContainer.js

Epic 2 hotfixes

---

src/server/__tests__/utils/expectAsyncToThrow.js
src/server/billing/helpers/generateInvoice.js

also fix jest tests for thrown errors

fix upcoming vs pending

---

src/server/__tests__/MockOrg1BillingCurrent-tests.js
src/server/graphql/models/Invitation/inviteTeamMembers/createPendingApprovals.js
src/server/graphql/models/Invitation/inviteTeamMembers/inviteTeamMembers.js
src/server/graphql/models/Organization/addBilling/__tests__/__snapshots__/addBilling.test.js.snap
src/server/graphql/models/Organization/rejectOrgApproval/rejectOrgApproval.js
src/server/graphql/models/User/userSubscription.js
src/server/utils/authorization.js
src/universal/modules/notifications/components/PromoteToBillingLeader/PromoteToBillingLeader.js
src/universal/modules/userDashboard/components/LeaveOrgModal/LeaveOrgModal.js
src/universal/modules/userDashboard/components/OrgMembers/OrgMembers.js
src/universal/modules/userDashboard/components/OrgUserRow/OrgUserRow.js
src/universal/utils/constants.js

Capitalize Billing Leader everywhere

---

src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js

Added raven message to infiniteLoop watchdog

---

src/universal/redux/authDuck.js
src/universal/redux/segmentActions.js

Heh. Ok. This ought to do it better.

Add identify calls to client authDuck

---

src/universal/components/Auth0ShowLock/signinAndUpdateToken.js
src/universal/containers/Signout/signout.js
src/universal/redux/__tests__/AuthEngine.test.js
src/universal/redux/__tests__/authDuck.test.js
src/universal/redux/authDuck.js
src/universal/redux/getAuthedUser.js
src/universal/redux/segmentActions.js

Re-adds user traits to context.

Redux segment fix 3

---

.babelrc
webpack/webpack.config.dev.js

@ackernaut please test locally & if it works feel free to merge

fix babel regen _this4 error

---

src/server/graphql/models/Organization/addBilling/addBilling.js
src/server/graphql/models/Team/endMeeting/endMeeting.js
src/server/utils/authorization.js
src/universal/modules/summary/containers/MeetingSummary/MeetingSummaryContainer.js
src/universal/redux/segmentActions.js

@mattkrick this what I think we'll have to do to get all the events in the way we want.
What do you think?

Segment profile props everywhere

---

src/server/graphql/models/Action/createAction/createActionValidation.js
src/server/graphql/models/Action/updateAction/updateActionValidation.js
src/universal/containers/DashLayoutContainer/DashLayoutContainer.js
src/universal/modules/email/components/SummaryEmail/index.js
src/universal/modules/meeting/components/MeetingLobby/MeetingLobby.js
src/universal/modules/outcomeCard/components/OutcomeCardTextarea/OutcomeCardTextarea.js
src/universal/utils/constants.js
src/universal/validation/makeProjectSchema.js
src/universal/validation/templates.js

** woops, the copy-edits was based off of this branch**
* fix #839 max chars for projects
* fix #716
* fix #643 summary email subject line
* lint
* fix #857 mystery notification
* Minor layout updates to Meeting Lobby

Copy edits (#855)

---

src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js
src/universal/modules/meeting/helpers/handleRedirects.js

fix #859 infinite redirect loop when deleting the last phaseItem

---

src/server/graphql/models/Organization/extendTrial/extendTrial.js
src/server/graphql/models/Organization/organizationMutation.js

check out graphiql & call the mutation extendTrial. I think this should be user friendly enough for now

Extend trial

---

src/universal/modules/landing/containers/Landing/LandingContainer.js
src/universal/modules/meeting/containers/MeetingContainer/MeetingContainer.js
src/universal/modules/newTeam/components/NewTeam/NewTeam.js
src/universal/modules/teamDashboard/containers/Team/TeamContainer.js
src/universal/modules/userDashboard/components/UserDashboard/UserDashboard.js

Fixes #768 (page title improvements)

---

package.json
src/server/graphql/models/Team/endMeeting/__tests__/__snapshots__/endMeeting.test.js.snap
src/server/graphql/models/Team/endMeeting/__tests__/__snapshots__/resetMeeting.test.js.snap

chances are we got some failed tests that the CI wasn't telling us about

jest bail again

---

src/universal/modules/invoice/components/Invoice/Invoice.js
src/universal/modules/landing/components/Landing/Landing.js
src/universal/utils/makeSuccessCopy.js

- Updates copy on Landing
- Fixes padding on Invoice
- Corrects typo on Success Copy

Patch updates landing, invoice, success copy

---

circle.yml
src/server/graphql/models/IntranetJobs/intranetJobsQuery.js

Fix intranet query for un-ended meetings

---

src/server/graphql/models/Team/endMeeting/endMeeting.js
src/universal/containers/Action/ActionContainer.js
src/universal/modules/newTeam/containers/NewTeamForm/NewTeamFormContainer.js
src/universal/modules/teamDashboard/containers/ArchiveTeamContainer/ArchiveTeamContainer.js

Also:
* Adds `Archive Team` event
* Adds params to page tracking events (which will contain teamId)
Fixes #903

adds teamId to segment events

---

src/universal/decorators/loginWithToken/loginWithToken.js

this fixed it when building & running locally, let's see if it works on staging

attempt to fix staging branch

---

src/universal/components/Row/Row.js
src/universal/modules/integrations/components/IntegrateSlack/IntegrateSlack.js
src/universal/modules/integrations/components/IntegrationRows/IntegrationRows.js
src/universal/modules/integrations/components/ServiceRow/ServiceRow.js
src/universal/modules/integrations/containers/Integrations/IntegrationsContainer.js
src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js

This satisfies needs described by #1007

Team Settings > Integrations UI

---

src/server/graphql/models/IntranetJobs/intranetJobsQuery.js

This was a fun one to track down. See #1074 and #1070 (added for kicks).
@mattkrick this is ready for your eyes. I tested it locally fairly extensively. Will deploy to staging and give it some airtime before we push to prod.
This bug was also the root cause of the strange "mystery meeting endings" segment events we were getting for a bit.

Hotfix #1074

---

src/universal/modules/userDashboard/helpers/getRallyLink.js

added a gorilla breakdancing to Maniac

---

src/universal/components/OutcomeOrNullCard/OutcomeOrNullCard.js
src/universal/components/ProjectEditor/ProjectEditor.js
src/universal/modules/menu/components/AsyncMenu/AsyncMenu.js
src/universal/modules/outcomeCard/components/OutcomeCard/OutcomeCard.js
src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js
src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js

already accidentally pushed this to prod. if only i could protect a branch from pushes so you must PR into it....

fix #1252, notice the menus can't be selected

---

src/universal/modules/outcomeCard/components/OutcomeCard/OutcomeCard.js
src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js

Fix for #1260 – return of team names on My Dashboard

---

src/server/utils/sendSegmentEvent.js

In GQL terms, the shape looks like this:
```
{
userId
event
properties {
teamId
orgId
traits {
avatar
createdAt
email
name
... on Invitation {
inviteeCount
}
... on BillingChange {
quantity
}
... on MeetingCompleted {
meetingNumber
}
}
}
}
```

fix segment shape

---

src/universal/components/ProjectEditor/withLinks.js
src/universal/mutations/SendClientSegmentEventMutation.js

it
(also removed a stray console.log)

fix infinite loop on LinkChanger

---

src/universal/utils/draftjs/__tests__/truncateCard.test.js
src/universal/utils/draftjs/truncateCard.js

no end-to-end tests. 
we've got unit tests!

fix #1312 getLength on truncateCard

---

package.json
webpack/webpack.config.prod.js
yarn.lock

@mattkrick these are some additional changes I had to make to get the build passing – look ok to you?
In the meantime, I'm going to push this to the dev server...

Node v8.4.0

---

src/universal/components/EditorLinkChanger/EditorLinkChanger.js
src/universal/components/EditorLinkViewer/EditorLinkViewer.js
src/universal/components/ProjectEditor/ProjectEditor.js
src/universal/components/ProjectEditor/withLinks.js
src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js
src/universal/modules/outcomeCard/components/OutcomeCardFooterButton/OutcomeCardFooterButton.js
src/universal/styles/ui.js

Epic 6.5 Card Updates [WIP]

---

src/server/database/migrations/20170921170700-fixInvitationExpiry.js
src/server/graphql/models/Team/createFirstTeam/addSeedProjects.js
src/server/graphql/mutations/createGitHubIssue.js
src/universal/components/EditorLinkChanger/EditorLinkChanger.js
src/universal/components/ProjectEditor/withLinks.js
src/universal/subscriptions/helpers/notificationHandler.js
src/universal/validation/makeProjectSchema.js

Project Card
Seed Projects fixed
Migrations

Epic6.5 closeout mk

---

src/server/graphql/mutations/addProvider.js
src/server/graphql/mutations/githubAddAssignee.js
src/server/graphql/mutations/githubAddMember.js
src/server/graphql/mutations/githubRemoveMember.js
src/universal/components/ErrorComponent/ErrorComponent.js
src/universal/components/Tooltip/Tooltip.js
src/universal/components/Tooltip/TooltipModal.js
src/universal/containers/GitHubReposMenuRoot/GitHubReposMenuRoot.js
src/universal/decorators/withCoords.js
src/universal/modules/menu/components/AsyncMenu/AsyncMenu.js
src/universal/modules/menu/containers/AsyncMenu/AsyncMenu.js
src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js
src/universal/styles/ui.js
src/universal/subscriptions/helpers/notificationHandler.js
yarn.lock

add tooltips fix #272 #1354 [Epic 7 PR 1]

---

src/universal/components/Button/Button.js

🤦‍♂️ this should the regression in #1383 @mattkrick

Epic7 fix button icon styles

---

.eslintrc
.eslintrc.js

https://eslint.org/docs/user-guide/configuring#configuration-file-formats

eslintrc is deprecated use JS, YAML or JSON file format

---

CHANGELOG.md
package.json
src/server/graphql/models/User/userMutation.js
src/server/utils/__tests__/tmsSignToken.test.js
src/server/utils/auth0Helpers.js
src/server/utils/tmsSignToken.js

Team invite hotfix

---

src/universal/components/Tag/Tag.js
src/universal/components/Tag/TagPro.js
src/universal/components/Tag/tagBase.js
src/universal/modules/userDashboard/components/OrgBilling/OrgBilling.js
src/universal/modules/userDashboard/components/OrgPlanBadge/OrgPlanBadge.js
src/universal/modules/userDashboard/components/OrgPlanSqueeze/OrgPlanSqueeze.js
src/universal/modules/userDashboard/components/Organization/Organization.js
src/universal/modules/userDashboard/components/OrganizationRow/OrganizationRow.js
src/universal/modules/userDashboard/components/Organizations/Organizations.js
src/universal/styles/ui.js

This is a WIP for #1368 updating the organization billing views.
To be merged after invoice pagination and fixes.
Test Plan TBD

Epic 7 Billing - update OrgBilling views

---

package.json
src/server/graphql/mutations/upgradeToPro.js
src/server/graphql/types/UpgradeToProPayload.js
src/universal/modules/userDashboard/components/OrgBilling/OrgBilling.js
src/universal/modules/userDashboard/components/OrgPlanBadge/OrgPlanBadge.js
src/universal/modules/userDashboard/components/OrgPlanSqueeze/OrgPlanSqueeze.js
src/universal/modules/userDashboard/components/Organization/Organization.js
src/universal/modules/userDashboard/components/OrganizationRow/OrganizationRow.js
src/universal/modules/userDashboard/components/Organizations/Organizations.js
src/universal/modules/userDashboard/components/StackedIcon.js
src/universal/modules/userDashboard/containers/Organizations/OrganizationsContainer.js
src/universal/mutations/UpgradeToProMutation.js
src/universal/subscriptions/subscriptions.js
yarn.lock

Epic7 billing - refactor part 1 & wire it up

---

src/universal/components/SocketRoute/SocketRoute.js

@mattkrick - this is a quick-n-dirty suspected fix for the issue. can provide more details out-of-band.

Possible SocketRoute `render` hotfix

---

src/server/__tests__/utils/channelsToSerialize.js
src/server/graphql/models/Team/archiveTeam/__tests__/__snapshots__/archiveTeam.test.js.snap
src/server/graphql/models/Team/archiveTeam/__tests__/archiveTeam.test.js
src/server/graphql/models/Team/archiveTeam/archiveTeam.js
src/server/graphql/models/TeamMember/removeTeamMember/removeAllTeamMembers.js
src/server/graphql/types/NotifyAddedToTeam.js
src/server/graphql/types/NotifyKickedOut.js
src/server/safeMutations/__tests__/acceptTeamInvite.test.js
src/server/safeMutations/acceptTeamInvite.js
src/server/safeMutations/helpers/__tests__/__snapshots__/makeReactivationNotifications.test.js.snap
src/server/safeMutations/helpers/__tests__/makeReactivationNotifications.test.js
src/server/safeMutations/helpers/makeReactivationNotifications.js
src/server/safeMutations/reactivateTeamMembersAndMakeNotifications.js
src/server/socketHandlers/scRelaySubscribeHandler.js
src/server/utils/handleGraphQLResult.js
src/universal/components/ErrorComponent/ErrorComponent.js
src/universal/modules/userDashboard/components/OrgBilling/OrgBilling.js
src/universal/modules/userDashboard/components/OrgMembers/OrgMembers.js
src/universal/modules/userDashboard/components/OrgPlanSqueeze/OrgPlanSqueeze.js
src/universal/modules/userDashboard/components/OrganizationRow/OrganizationRow.js
src/universal/subscriptions/NotificationsAddedSubscription.js

fixes #1412 auth token channel
#1391

Epic 7 - Auth via auth channel

---

CHANGELOG.md
package.json

Adds updates to the CHANGELOG for `v0.22.0`, increments version in `package.json`, and git tag added.
FYI @mattkrick

Epic7 docs

---

src/universal/subscriptions/ProjectUpdatedSubscription.js

Fix TypeError in ProjectUpdatedSubscription

---

package.json
src/server/database/migrations/20171026160540-removeBillingFromPersonalTeams.js

@mattkrick this should address 1/2 of #1452

Add migration removing billing data from personal teams

---

src/universal/subscriptions/helpers/notificationHandler.js

[ let’s start sprinting! ]
[ Test Plan TBD ]

Epic 8: Assignment Notifications

---

CHANGELOG.md
package.json
src/server/database/migrations/20171026160540-removeBillingFromPersonalTeams.js

This re-implements the commits for v0.22.2 that got lost in the reset

Redo 1455 - Dan's migrations

---

src/server/graphql/types/NotifyInvitation.js
src/universal/components/SocketRoute/SocketRoute.js
src/universal/modules/notifications/components/RequestNewUser/RequestNewUser.js
src/universal/subscriptions/NotificationsAddedSubscription.js

Request notif, show money matters for PRO only

---

src/server/graphql/mutations/helpers/publishChangeNotifications.js
src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js

Fix private mentions

---

src/universal/styles/ui.js

- improves font-stack for emails

Epic 8 patch TA (WIP)

---

src/server/graphql/mutations/updateProject.js
src/universal/components/Panel/Panel.js
src/universal/modules/notifications/components/Notifications/Notifications.js
src/universal/modules/notifications/containers/Notifications/NotificationsContainer.js
src/universal/styles/ui.js

fix in-meeting notifications, notifications bug from email

---

src/server/graphql/mutations/createProject.js
src/server/graphql/mutations/helpers/publishChangeNotifications.js
src/server/graphql/mutations/updateProject.js
src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.js
src/universal/modules/outcomeCard/components/OutcomeCardAssignMenu/OutcomeCardAssignMenu.js
src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js
src/universal/modules/outcomeCard/components/OutcomeCardStatusMenu/OutcomeCardStatusMenu.js
src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js
src/universal/mutations/CreateProjectMutation.js
src/universal/subscriptions/helpers/notificationHandler.js

@ackernaut - Here's the PR for the last remaining blocker.

Notify without toast during meetings

---

src/server/graphql/mutations/createProject.js
src/server/graphql/mutations/helpers/publishChangeNotifications.js
src/server/graphql/mutations/updateProject.js
src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.js
src/universal/modules/outcomeCard/components/OutcomeCardAssignMenu/OutcomeCardAssignMenu.js
src/universal/modules/outcomeCard/components/OutcomeCardFooter/OutcomeCardFooter.js
src/universal/modules/outcomeCard/components/OutcomeCardStatusMenu/OutcomeCardStatusMenu.js
src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js
src/universal/mutations/CreateProjectMutation.js

Re-enables the "no assignment/mention notifications can be generated from a meeting" behavior

---

src/server/graphql/mutations/createProject.js
src/server/graphql/mutations/helpers/publishChangeNotifications.js

Mentioning absent users from within meetings works

---

.flowconfig
package.json
src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeam.js
src/universal/modules/teamDashboard/components/ArchiveTeam/ArchiveTeamForm.js
yarn.lock

Fix delete team validation

---

src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js

This fixes a regression introduced in https://github.com/ParabolInc/action/commit/de5b9caa2b39aa8a543cb40b32e6a065ad0c05bd

Un-bork MeetingUpdates component

---

src/server/graphql/models/User/userMutation.js
src/universal/modules/userDashboard/containers/UserSettings/UserSettingsContainer.js
src/universal/modules/welcome/components/Step1PreferredName/Step1PreferredName.js

`updateUserProfile` now uses the userId provided by the authToken.

fix welcome wizard step 1 regression

---

src/universal/modules/notifications/components/ProjectInvolves.js

Fix #1577 - absent notification author name

---

src/universal/dnd/sortOrderBetween.js
src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.js
src/universal/modules/meeting/components/MeetingAgendaItems/MeetingAgendaItems.js

Fixes #1570 
To verify:
- run a meeting with an agenda item
- during the agenda phase, add some cards
- note that as you add cards they get appended - rather than prepended - to the list, as they used to

Append - don't prepend - cards during agenda

---

src/client/Root.js
src/client/client.js
src/server/graphql/mutations/endMeeting.js
src/server/graphql/types/NotifyNewTeamMember.js
src/server/safeMutations/helpers/makeReactivationNotifications.js
src/universal/components/AtmosphereProvider/AtmosphereProvider.js
src/universal/containers/Signout/signout.js
src/universal/modules/meeting/components/MeetingRoot.js
src/universal/mutations/EndMeetingMutation.js
src/universal/subscriptions/NotificationsAddedSubscription.js

Fixup team bugs

---

src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js
src/universal/modules/teamDashboard/containers/TeamColumns/TeamColumnsContainer.js
src/universal/modules/userDashboard/containers/UserColumns/UserColumnsContainer.js
src/universal/utils/getProjectById.js

Fix drag-and-drop on Meeting Updates

---

src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js
src/universal/modules/teamDashboard/containers/TeamColumns/TeamColumnsContainer.js
src/universal/modules/userDashboard/containers/UserColumns/UserColumnsContainer.js
src/universal/utils/getProjectById.js

Re-addressing #1627, this time into `master` :)

Fix drag-and-drop on Meeting Updates (take 2)

---

src/universal/modules/teamDashboard/components/ProjectColumn/ProjectColumn.js

Fix unresponsive Add Project button on My Dashboard

---

src/universal/releaseFlags.js

Just updates a comment for accuracy.

Fix comment in releaseFlags module

---

package.json
src/server/socketHandlers/scRelaySubscribeHandler.js
src/server/worker.js
src/universal/modules/teamDashboard/components/TeamSettings/TeamSettings.js
src/universal/modules/userDashboard/containers/UserSettings/UserSettingsContainer.js
src/universal/mutations/RemoveTeamMemberMutation.js

fix team member kickout from team settings #1664
fix webpack hmr for ubuntu 16.04
fix UserSettings redirect for new users (undocumented)

Fix team member kickout sub error #1664

---

package.json
src/server/graphql/mutations/__tests__/__snapshots__/endMeeting.test.js.snap
src/server/graphql/mutations/__tests__/__snapshots__/removeTeamMember.test.js.snap
src/server/graphql/mutations/__tests__/__snapshots__/updateProject.test.js.snap
src/server/graphql/mutations/addGitHubRepo.js
src/server/graphql/mutations/addSlackChannel.js
src/server/graphql/mutations/createGitHubIssue.js
src/server/graphql/mutations/helpers/notifySlack.js
src/server/integrations/tokenCanAccessRepo.js
src/server/safeMutations/maybeJoinRepos.js
src/universal/components/AddProjectButton/AddProjectButton.js
src/universal/modules/meeting/components/MeetingUpdates/MeetingUpdates.js
src/universal/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.js
src/universal/utils/getDraftCoords.js
yarn.lock

fix privacy, vanishing links, integration regression

---

.eslintrc.js
src/universal/components/Action/Action.js
src/universal/components/DynamicHome/DynamicHome.js
src/universal/components/SignIn/SignIn.js
src/universal/releaseFlags.js

Fixes #1755.
This is one of the first steps for the new signin flow. It's hidden behind a release flag.

Add <DynamicHome /> (behind a release flag)

---

CHANGELOG.md
package.json
src/server/socketHandlers/handleMessage.js
src/server/socketHandlers/wsRelaySubscribeHandler.js
src/server/socketHandlers/wssConnectionHandler.js
src/server/socketHelpers/keepAlive.js
src/universal/Atmosphere.js
src/universal/utils/SafeSubscriptionClient.js
src/universal/utils/constants.js

fixes #1775 fixes #1770 fixes #1771. Full details in #1775
TEST (local)
RUN THE FOLLOWING USING THE PRODUCTION BRANCH
RERUN TEST USING THIS BRANCH 
Note: Testing locally is easier than testing on a server because this error only exists if the client reconnects. To test on a server, just kill your wifi instead of exiting the server.

Fix con bug

---

flow-typed/globals.js
src/universal/components/Action/Action.js
src/universal/components/RetroRoot/RetroRoot.js
src/universal/modules/teamDashboard/components/Team/Team.js
src/universal/modules/teamDashboard/components/TeamCallsToAction/TeamCallsToAction.js
src/universal/releaseFlags.js

Add Retro CTA button to team dashboard

---

src/server/graphql/mutations/changeTaskTeam.js

my last commit push got rejected yesterday so this never landed. just gonna push to master

final touches to change team PR

---

package.json
src/server/graphql/queries/activeProUserCount.js
src/server/graphql/rootQuery.js
yarn.lock

fixes #1752 
TEST
type this:
```
query {
activeProUserCount
}
```

Count pro users

---

src/server/graphql/mutations/__tests__/__snapshots__/updateCreditCard.test.js.snap
src/server/graphql/mutations/__tests__/updateCreditCard.test.js
src/server/graphql/mutations/updateCreditCard.js
src/universal/components/Dashboard/DashNavTeam.js

TEST
note-- this is NOT in real time. we could make it that way, but that'd take a few more minutes

fix updateCreditCard & missing unpaid invoice warning icon [BASE: STAGING]

---

CHANGELOG.md
package.json
src/universal/components/AtmosphereProvider/AtmosphereProvider.js
src/universal/mutations/AcceptTeamInviteEmailMutation.js
src/universal/mutations/AcceptTeamInviteMutation.js
src/universal/subscriptions/TeamSubscription.js

HOTFIX: No logout for bad invite

---

src/server/graphql/intranetSchema/intranetSchema.js
src/server/graphql/intranetSchema/queries/pingActionTick.js

lot of errors showing up in the server logs, this will remove a few
TEST

fix borked intranet graphql ping

---

circle.yml

Speed up development server deployments

---

src/universal/components/Dashboard/DashSearchControl.js
src/universal/modules/teamDashboard/components/Team/Team.js
src/universal/releaseFlags.js
src/universal/styles/ui.js

- Adds an icon
- Improves placeholder styles for default, focus/active
- Fixes layout of team name
**Note**: the IA of the team/my dash is not final. Both the heading and the search component will probably be positioned in different locations. Just wanted to get a little more common style affordance here.

Patch styles for search filter

---

src/universal/modules/meeting/components/Sidebar/Sidebar.js
src/universal/modules/teamDashboard/components/AgendaItem/AgendaItem.js

- Make full URL for copy meeting control
- Fix aesthetics on agenda item states

Patches for staging (TA)

---

CHANGELOG.md
src/universal/modules/meeting/components/CheckInControls/CheckInControls.js

now folks can be marked as absent. yay!
Note: base is set to staging.

fix click absent

---

src/universal/components/AuthHeader/AuthHeader.js
src/universal/components/AuthPage/AuthPage.js
src/universal/components/AuthPage/Header.js
src/universal/components/FieldLabel/FieldLabel.js
src/universal/components/HorizontalSeparator/HorizontalSeparator.js
src/universal/components/InputField/InputField.js
src/universal/components/LogoBlock/LogoBlock.js
src/universal/components/ResetPasswordPage/ResetPassword.js
src/universal/components/ResetPasswordPage/ResetPasswordForm.js
src/universal/components/ResetPasswordPage/ResetPasswordPage.js
src/universal/components/SignInPage/SignIn.js
src/universal/components/SignInPage/SignInEmailPasswordForm.js
src/universal/components/SignInPage/SignInPage.js
src/universal/components/SignUpPage/SignUp.js
src/universal/components/SignUpPage/SignUpEmailPasswordForm.js
src/universal/components/SignUpPage/SignUpPage.js
src/universal/components/ThirdPartyAuthButton/ThirdPartyAuthButton.js
src/universal/components/index.js
src/universal/releaseFlags.js
src/universal/styles/ui.js

Auth view aesthetic updates

---

src/server/graphql/types/Invitation.js
src/universal/components/FieldArrayRow/FieldArrayRow.js
src/universal/containers/LabeledFieldArray/LabeledFieldArrayContainer.js
src/universal/modules/welcome/components/Step3InviteeList/Step3InviteeList.js
src/universal/modules/welcome/containers/Welcome/Welcome.js
yarn.lock

No priorities no problems

---

src/universal/modules/menu/components/Menu/Menu.js
src/universal/modules/teamDashboard/components/TeamCallsToAction/LoadableTeamCallsToActionMenu.js
src/universal/modules/teamDashboard/components/TeamCallsToAction/TeamCallsToAction.js
src/universal/modules/teamDashboard/components/TeamCallsToAction/TeamCallsToActionMenu.js

Addresses #1857 “Build the Meeting Button” and fixes #1856

“Start Meeting” button for both types

---

.flowconfig
.gitignore
circle.yml
package.json
src/server/graphql/mutations/createReflectionGroup.js
src/server/graphql/mutations/helpers/makeRetroGroupTitle.js
src/server/graphql/mutations/updateReflectionGroupTitle.js
src/server/graphql/mutations/updateReflectionLocation.js
src/server/graphql/resolvers.js
src/server/graphql/rootMutation.js
src/server/graphql/types/CreateReflectionGroupPayload.js
src/server/graphql/types/RetroReflection.js
src/server/graphql/types/RetroReflectionGroup.js
src/server/graphql/types/TeamSubscriptionPayload.js
src/server/graphql/types/UpdateReflectionGroupTitlePayload.js
src/server/graphql/types/UpdateReflectionLocationPayload.js
src/server/utils/RethinkDataLoader.js
src/server/utils/__tests__/validationErrors.js
src/server/utils/docNotFoundErrors.js
src/universal/utils/draftjs/extractTextFromDraftString.js
src/universal/utils/relay/ContentFilterHandler.js
yarn.lock

Adds the following mutations:
- createReflectionGroup (puts 1 or more cards into a group)
- updateReflectionGroupTitle
- augments updateReflectionLocation to support add/remove reflectionGroupId
not much to test until we get to that part of the meeting though. (at least not easily, unless you wanna hunt for IDs in the database!)

1744 group backend

---

e2e/tests/authentication.test.js

tests fail on local for me, this fixes it
@dan-f

fix for node v9.9

---

src/universal/components/Auth0ShowLock/Auth0ShowLock.js
src/universal/containers/Action/ActionContainer.js
src/universal/modules/landing/containers/Landing/LandingContainer.js
src/universal/styles/helpers/makePlaceholderStyles.js
src/universal/styles/hepha.js
src/universal/styles/theme/globalStyles.js
stories/components/StoryContainer.js

Fixes #1946 
To verify:
- run `yarn build && yarn start` on master
- see the error in the console when visiting the `/signin` page
- checkout `fix-css-insertrule-error`
- run `yarn build && yarn start` again
- don't see the error in the console when visiting the `/signin` page

Fix css insertRule error

---

package.json

Do not delete production branch

Merge production back to master

---

CHANGELOG.md
package.json
src/universal/components/TaskEditor/TaskEditor.js

Draft hotfix

---

src/universal/components/NewMeetingLobby.js
src/universal/utils/meetings/helpLookups.js

Adding a batch of solid edits from @tayamueller

Meeting help content updates

---

CHANGELOG.md
package.json
src/server/graphql/mutations/login.js
src/server/utils/authorizationErrors.js
src/server/utils/sendAuthRaven.js
src/server/utils/sendSentryEvent.js

making an explicit PR for the purpose of keeping a history.

Signup hotifx (part 1 of 2)

---

CHANGELOG.md
package.json
src/server/graphql/mutations/login.js

identified failing data in rethinkdb insert. Still not sure what it was receiving.

Signup hotifx

---

src/server/graphql/queries/__tests__/suOrgCount.test.js
src/server/graphql/queries/__tests__/suUserCount.test.js
src/server/graphql/queries/suOrgCount.js
src/server/graphql/queries/suUserCount.js
src/server/graphql/types/SuProOrgInfo.js

suOrgCount: added ignoreEmailRegex, minOrgSize params
suUserCount: added ignoreEmailRegex
SuProOrgInfo type: removed unecessary count

Enhanced su queries with ignoreEmailRegex, &c

---

package.json
src/universal/components/NullableTask/NullableTask.js
src/universal/modules/outcomeCard/components/OutcomeCardFooterButton/OutcomeCardFooterButton.js
src/universal/modules/teamDashboard/components/TeamArchive/TeamArchive.js
src/universal/types/schema.flow.js
yarn.lock

Fix archive

---

src/server/graphql/mutations/startMeeting.js
src/universal/utils/makeCheckinGreeting.js

fix #1578 better checkin question rotation

---

src/client/clientSchema.graphql
src/universal/modules/teamDashboard/containers/TeamColumns/TeamColumnsContainer.js
src/universal/modules/userDashboard/components/UserDashMain/UserDashMain.js
src/universal/modules/userDashboard/components/UserDashRoot.js
src/universal/modules/userDashboard/components/UserDashSearch/UserDashSearch.js
src/universal/modules/userDashboard/containers/UserColumns/UserColumnsContainer.js
src/universal/releaseFlags.js

This is meant to add the filter search to My Dash in similar pattern to Team Dash views.

Filter search on My Dash

---

src/universal/components/TaskEditor/withKeyboardShortcuts.js

Added fix for strikethrough when user press _shift + command + x_

Fix for strikethrough shortcut

---

src/universal/components/BounceBlock/BounceBlock.js
src/universal/components/NewMeetingCheckIn.js
src/universal/modules/meeting/components/CheckInControls/CheckInControls.js

TEST
- start a meeting with 2 members
- wait on the first member's check in stage for 30 seconds
- go to next member's stage

fix #2099 fix bounce [BASE: remove-welcome]

---

src/server/graphql/mutations/helpers/addSeedTasks.js

Fixes 1067, updates seed cards

---

package.json
webpack/webpack.config.dll.js
webpack/webpack.dev.config.js
webpack/webpack.prod.config.js
yarn.lock

fix graphiql

---

src/server/safeMutations/emailTeamInvitations.js

Here's a simple email destination blacklist. Creating this PR for historical purposes.

added simple email domain blacklist

---

src/client/clientSchema.graphql
src/universal/components/ReflectionCard/ReflectionCard.js

TEST
follow test found in #2280

fix #2280 by caching in-progress reflection state

---

src/client/clientSchema.graphql
src/server/graphql/mutations/endDraggingReflection.js
src/server/graphql/types/EndDraggingReflectionPayload.js
src/universal/components/PhaseItemMasonry.js
src/universal/components/ReflectionCard/DraggableReflectionCard.js
src/universal/components/ReflectionCard/ReflectionCard.js
src/universal/components/Tooltip/Tooltip.js
src/universal/mutations/EndDraggingReflectionMutation.js
src/universal/types/schema.flow.js

This is an incremental improvement to the group grid.
it fixes case 1 of #2279
it's not ideal, but it's a lot better than what is in production today

Fix group race

---

package.json
webpack/webpack.prod.config.js
yarn.lock

fix #2269 uglification of codemirror gone wrong

---

src/client/clientSchema.graphql
src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx
src/universal/components/RetroReflectPhase/RetroReflectPhase.tsx

re-add active editor chits

---

src/server/graphql/httpGraphQLHandler.js

@ackernaut and I have been using a [GraphQL CLI client](https://github.com/graphql-cli/graphql-cli) to collect metrics (especially when graphiql gets borked). I dug in a bit this morning and found that the refactor to trebuchet was the breaking change that made our clients stop working.
Included is a rather trivial fix. Question is, do we want to fix it this way or should we create a vanilla GraphQL over HTTP endpoint? I'm fine with either...

Add fallback to regular GraphQL/HTTP when trebuchet not detected

---

src/universal/components/DueDatePicker.tsx

- click a card that has a due date older than 1 month ago.

fix fromMonth

---

src/server/graphql/intranetGraphQLHandler.js
src/server/graphql/intranetSchema/mutations/endOldMeetings.js
src/server/graphql/mutations/endMeeting.js
src/server/graphql/mutations/endNewMeeting.js

testing this isn't easy to do locally, so we'll just hope it works. it's already broken, so it can't be more broken.

attempt to fix endOldMeetings

---

src/server/graphql/mutations/autoGroupReflections.js
src/server/graphql/mutations/helpers/autoGroup/groupReflections.js
src/server/graphql/mutations/helpers/handleCompletedStage.js
src/universal/components/RetroGroupPhase.tsx
src/universal/mutations/AutoGroupReflectionsMutation.js

TEST
- create a list of 10 reflections: people, man, cakes and pies, men, how now, women, pie, Now now, person, cake
* there's still a chance it doesn't work, a race condition still exists somewhere, but it's better than being broken 100% of the time.

fixed removed groups filter

---

src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx
src/universal/components/Tooltip/Tooltip.js
src/universal/types/graphql.d.ts

fixes 2412 prompt highlight hint

---

src/universal/components/BottomNavControl.tsx
src/universal/components/FloatingActionButton.js
src/universal/components/MeetingHelp/DemoDiscussHelpMenu.tsx
src/universal/components/MeetingHelp/DemoGroupHelpMenu.tsx
src/universal/components/MeetingHelp/DemoReflectHelpMenu.tsx
src/universal/components/MeetingHelp/DemoVoteHelpMenu.tsx
src/universal/components/MeetingHelp/DiscussHelpMenu.js
src/universal/components/MeetingHelp/GroupHelpMenu.js
src/universal/components/MeetingHelp/HelpMenuToggle.js
src/universal/components/MeetingHelp/ReflectHelpMenu.js
src/universal/components/MeetingHelp/withDemoHelpMenu.tsx
src/universal/components/MeetingHelp/withHelpMenu.js
src/universal/components/NewMeeting.tsx
src/universal/components/NewMeetingSidebar.tsx
src/universal/components/RetroDiscussPhase.tsx
src/universal/components/RetroGroupPhase.tsx
src/universal/components/RetroReflectPhase/RetroReflectPhase.tsx
src/universal/components/RetroVotePhase.tsx
src/universal/modules/demo/ClientGraphQLServer.ts
src/universal/modules/demo/handleCompletedDemoStage.ts
src/universal/mutations/EndNewMeetingMutation.js

fixes #2462
there are still some broken states when HMR kicks in, but i haven't seen those states with just a refresh, we'll need to refresh on different views to tests for that though.

Demo polish

---

src/universal/modules/demo/handleCompletedDemoStage.ts
src/universal/modules/demo/initBotScript.ts

Demo timing (base: demo-polish)

---

src/universal/components/ReflectionCard/DraggableReflectionCard.tsx
src/universal/modules/demo/ClientGraphQLServer.ts
src/universal/modules/email/components/CreateAccountSection/CreateAccountSection.js
src/universal/mutations/EndDraggingReflectionMutation.ts

fix small demo bugs

---

src/universal/components/MasonryCSSGrid.tsx
src/universal/components/RetroDiscussPhase.tsx
src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.tsx

fix #2432 resize grid when tasks update

---

src/universal/components/RetroReflectPhase/ExpandedReflectionStack.tsx
src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx
src/universal/components/RetroReflectPhase/ReflectionStack.tsx

fix #2400 completed reflect phase is read only [BASE: fix-2432]

---

src/server/graphql/mutations/updateTeamName.js

fix #2397 team rename

---

src/universal/components/MeetingHelp/DelayedCopy.tsx
src/universal/components/MeetingHelp/DemoDiscussHelpMenu.tsx
src/universal/components/MeetingHelp/DemoGroupHelpMenu.tsx
src/universal/components/MeetingHelp/DemoReflectHelpMenu.tsx
src/universal/components/MeetingHelp/DemoVoteHelpMenu.tsx
src/universal/components/MeetingHelp/HelpMenuContent.js
src/universal/components/MeetingHelp/TypingIndicator.tsx
src/universal/components/MeetingHelp/withHelpMenu.js
src/universal/components/MeetingHelp/withStaggerShow.tsx

clean up demo help menu animations

---

src/universal/components/MasonryCSSGrid.tsx
src/universal/components/ReflectionCard/DraggableReflectionCard.tsx
src/universal/components/ReflectionCard/ReflectionCard.tsx
src/universal/components/ReflectionGroup/ReflectionGroup.tsx
src/universal/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
src/universal/components/ReflectionGroupHeader.js
src/universal/components/ReflectionGroupVoting.tsx
src/universal/components/RetroDiscussPhase.tsx
src/universal/components/RetroReflectPhase/ChildrenCache.tsx
src/universal/components/RetroReflectPhase/ExpandedReflectionStack.tsx
src/universal/components/RetroReflectPhase/FLIPGrid.tsx
src/universal/components/RetroReflectPhase/FLIPModal.tsx
src/universal/components/RetroReflectPhase/PhaseItemColumn.tsx
src/universal/components/RetroReflectPhase/ReflectionStack.tsx
src/universal/components/RetroReflectPhase/ReflectionStackPlaceholder.tsx
src/universal/components/Tag/Tag.js
src/universal/modules/meeting/components/MeetingAgendaCards/MeetingAgendaCards.tsx
src/universal/styles/cards.js
src/universal/styles/meeting.js
src/universal/styles/ui.js

@ackernaut here's the branch with the funny looking stacks. to reproduce: in the group phase, group 3+ cards & have 2+ rows of cards, then drag the top one of the group off. while the top one is being drug, the other 2 cards touch the row below em

Fix ref anim

---

src/universal/components/PendingApprovalRow.tsx

HOTFIX: fix hidden org approvals

---

src/universal/modules/email/components/SummaryEmail/ExportToCSV.tsx

avoid minification error in csv parser

---

src/server/graphql/mutations/autoGroupReflections.js
src/universal/components/LoadableServiceDropdown.js
src/universal/components/ServiceDropdown.tsx
src/universal/modules/teamDashboard/AddGitHubRepo/AddGitHubRepo.tsx
src/universal/modules/teamDashboard/components/GitHubIntegrations/GitHubIntegrations.js
src/universal/mutations/AddGitHubRepoMutation.ts

HOTFIX fix #2347 select GH repo

---

src/universal/components/AnalyticsIdentifier.tsx
src/universal/components/AnalyticsIdentifierRoot.tsx
src/universal/components/Ellipsis/Ellipsis.js

this lets us capture page events for folks using the demo without being logged in
TEST

support page events for non-users

---

src/server/graphql/mutations/updateNewCheckInQuestion.js
src/universal/modules/meeting/components/MeetingCheckInPrompt/CheckInQuestion.js
src/universal/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.js
src/universal/subscriptions/TeamSubscription.js

fix #2548 check in questions

---

src/server/template.html
src/universal/components/DemoMeeting.tsx

Fix meta tag

---

src/universal/components/NullableTask/NullableTask.js
src/universal/components/TimelineNoTasks.tsx
src/universal/components/TimelinePriorityTasks.tsx
src/universal/components/TimelineRightDrawer.tsx
src/universal/containers/TaskCard/DraggableTask.tsx

**DO NOT MERGE UNTIL BASE BRANCH IS MASTER**
This is PR 5/5. It goes like this:
- PR 1: Suggested Actions
- PR 2: Remove welcome wizard
- PR 3: Timeline
- PR 4: what's new
- PR 5: **tasks shortlist**
TEST

add active tasks to timeline

---

package.json
src/server/graphql/types/TeamMember.js
src/universal/components/DashboardAvatars/DashboardAvatar.tsx
src/universal/components/DashboardAvatars/TeamMemberAvatarMenu.tsx
src/universal/components/NewMeeting.tsx
src/universal/components/SocketHealthMonitor.js
src/universal/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatar.tsx
src/universal/mutations/fragments/CompleteTeamMemberFrag.js
src/universal/types/graphql.d.ts
yarn.lock

TEST
fixes #2555
Note: I didn't touch the logic in action meetings since it's old, difficult, and works differently. we'll get this functionality for free when we refactor it to the new meeting format

fix #2555 fix #2533 incorrect connection state

---

src/universal/modules/demo/initDB.ts
src/universal/utils/relay/isTempId.js
src/universal/utils/relay/isTempId.ts

fix delete reflection in demo

---

src/server/graphql/types/NavigateMeetingPayload.js

gracefully handle an error payload for navigateMeetingPayload

---

src/server/graphql/types/User.js
src/server/utils/authorization.ts

pushing direct to staging, will test there

hotfix: show meeting summaries for archived teams

---

src/universal/components/AuthenticationPage.tsx
src/universal/components/TeamInvitationGoogleCreateAccount.tsx
src/universal/components/TeamInvitationGoogleSignin.tsx

if the user so much as freakin closes the OAuth window i wanna know about it.

log login errors

---

src/server/graphql/types/User.js
src/universal/containers/Signout/signout.js

fix #2697 impersonate

---

src/server/graphql/mutations/endNewMeeting.js

fix #2650
this provides a better error message when endNewMeeting is called twice very quickly.
if we see this new error message pop up frequently, we'll want to revisit when the client sends that message

add FK meetingId check on team document

---

src/universal/components/EditorInputWrapper.js
src/universal/components/ReflectionEditorWrapper.js
src/universal/components/TaskEditor/TaskEditor.js

add spellcheck for tasks, reflections, and check-in question

---

src/universal/components/Tooltip/Tooltip.js
src/universal/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.js

lock checkin question to facilitator

---

src/server/graphql/mutations/moveMeeting.js
src/universal/modules/meeting/helpers/handleRedirects.js
yarn.lock

this will get us by until we refactor the action meeting to the new format
TEST

fix inf loop crash in action meeting

---

src/universal/components/SocketHealthMonitor.tsx

pop toast on new version

---

package.json
src/universal/components/LoadableModalAbstract.tsx
src/universal/components/VideoControls.tsx
src/universal/components/WebcamDeniedPermissions.tsx
src/universal/components/WebcamPermissionsModal.tsx
src/universal/components/WebcamPromptPermissions.tsx
src/universal/hooks/useSwarm.tsx
src/universal/modules/meeting/components/ReflectTemplateModal.tsx
src/universal/utils/swarm/MediaSwarm.ts
src/universal/utils/swarm/joinSwarm.ts
src/universal/utils/swarm/reducerSwarm.ts
yarn.lock

Video beta

---

src/server/graphql/mutations/endNewMeeting.js
src/server/graphql/mutations/login.js
src/server/graphql/queries/helpers/countTiersForUserId.js
src/server/utils/sendSegmentEvent.js

Send hubspot more identity info fix #2795

---

src/universal/components/NewMeetingCheckIn.tsx

Fixes #2764 Check-In CTA update

---

CHANGELOG.md
package.json
src/server/graphql/mutations/endMeeting.js
src/server/graphql/mutations/helpers/removeTeamMember.ts
src/server/safeMutations/archiveTasksForDB.js

i'm a little confused as to why the linter didn't pick this one up, but it's a showstopper

remove call to missing primeStandardLoader

---

src/universal/components/AuthenticationPage.tsx
src/universal/components/EmailPasswordAuthForm.tsx
src/universal/utils/relay/withForm.tsx

fix forgot password link

---

src/universal/components/AddTeamMemberAvatarButton.tsx
src/universal/hooks/usePortal.tsx
src/universal/hooks/useTooltip.ts
src/universal/hooks/useTooltipPortal.tsx

adds a delay option to useTooltip

Use tooltip delay

---

CHANGELOG.md
package.json
src/universal/components/ErrorBoundary.tsx
src/universal/hooks/useBreakpoint.ts

Probably should be a hotfix. @ackernaut can you test with safari?

support breakpoints on safari

---

package.json
src/universal/components/VideoControls.tsx
yarn.lock

handle browsers without permissions API

---

CHANGELOG.md
src/server/graphql/mutations/endNewMeeting.ts

Capitalize seg event

---

src/server/graphql/resolvers.js

- Create UserA
- Create UserB, give `rol: 'su'` to this user
- Upgrade UserA to Pro
```graphql
query {
user(email: "userA@foo.bar") {
id
preferredName
email
organizations {
id
name
stripeSubscriptionId
}
}
}
```

added SU permission to resolveForBillingLeaders()

---

src/universal/components/RetroGroupPhase.tsx
src/universal/components/RetroReflectPhase/RetroReflectPhase.tsx
src/universal/hooks/usePortal.tsx
src/universal/modules/teamDashboard/components/AgendaInput/AgendaInput.tsx
src/universal/mutations/PromoteNewMeetingFacilitatorMutation.ts

see commits for fixes. all small & not really worthy of testing IMO.

Timer fixes [base: single-card-titles]

---

src/universal/components/TeamInvitationErrorAccepted.tsx

pushing to master since this is a pretty nasty one & it'd be good to get this to prod asap

fix #2988 join meeting from already accepted invitation

---

src/server/graphql/mutations/setStageTimer.ts

See #2998 
Sign into Segment, see debugger for dev source:
- isAsync,
- newScheduledEndTime,
- phaseType,
- previousScheduledEndTime
- stageStartAt
- timeRemaining
- viewCount
**Note**: stopping a timer or a timebox will both return `isAsync: null` so I’m not sure this is clearly distinguishable (pondering how to change)

Timer Segment events

---

src/server/graphql/mutations/acceptTeamInvitation.ts
src/server/graphql/mutations/inviteToTeam.ts
src/universal/components/AddTeamMemberModal.tsx

Segment events for invites

---

packages/client/components/AddTeamMemberModal.tsx
packages/server/graphql/mutations/acceptTeamInvitation.ts
packages/server/graphql/mutations/inviteToTeam.ts

These changes probably got lost in a merge commit somewhere:
See Segment debugger

changes from PR #3040

---

packages/client/utils/makeCheckinGreeting.js

3066 adds new check-in questions

---

CHANGELOG.md
lerna.json
packages/client/components/SAMLRedirect.tsx
packages/client/package.json
packages/cypress/package.json
packages/server/graphql/intranetSchema/mutations/loginSSO.ts
packages/server/package.json

no good way to test this now that it's already live in prod since a redirect would bork current users workflow. pushing at hotfix since worst case scenario, it's still broken.
if it doesn't work, we'll just have to redir during off hours.

Idp inititated SSO

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/cypress/package.json
packages/server/graphql/mutations/login.ts
packages/server/package.json

hotfix for login
also fixes lint-staged, that was really bugging me since it wasn't linting before committing.
TEST

Hotfix login error

---

packages/server/graphql/mutations/startNewMeeting.ts

add rollback for duplicate start meeting

---

packages/client/components/RetroReflectPhase/RetroReflectPhase.tsx
packages/server/billing/helpers/generateInvoice.ts
packages/server/database/types/Coupon.ts
packages/server/database/types/Organization.ts
packages/server/graphql/types/Coupon.ts
packages/server/utils/RethinkDataLoader.ts

guarantee reflectPrompts fix #3195

---

packages/client/subscriptions/TeamSubscription.ts
packages/client/types/graphql.ts
yarn.lock

fixes #3222 subscription to update name

---

packages/client/components/Facilitator.tsx
packages/client/components/StageTimerControl.tsx
packages/client/modules/demo/initDB.ts
packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatarGroup.tsx
packages/client/mutations/fragments/CompleteTeamMemberFrag.js
packages/client/subscriptions/NotificationSubscription.ts
packages/client/types/graphql.ts
packages/server/graphql/types/TeamMember.ts

@ackernaut little fixups for the PR.
I think a nice addition would be to add animations when people connect/disconnect. we can copy the code from the atlassian domain icons. the overflow number could roll up when incremented & down when decremented.

Meeting top bar avatars mk

---

packages/client/components/MenuHelpToggle.tsx
packages/client/modules/demo/initDB.ts

fix #3225 demo menu help doesn't open

---

packages/client/components/ReflectionGroup/RemoteReflection.tsx

fix #3224 fatal error on quick nav from group to vote

---

CHANGELOG.md
packages/server/graphql/mutations/endNewMeeting.ts
yarn.lock

Fix checkin order [base: new-rethinkdb-driver]

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/cypress/package.json
packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
packages/server/package.json
packages/server/safeMutations/acceptTeamInvitation.ts

New driver doesn't handle nested promises i guess.
this would cause teamMember to be an empty object. when this happened mid meeting, the teamMemberId for the CheckInRound would be null, causing the entire NewMeeting object to be null.

Hotfix invite

---

packages/client/components/AnalyticsPage.tsx
packages/server/server.ts

fix #3247 without sacrificing capability or paying.

add server/client envs for sentry

---

packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/modules/demo/getDemoEntities.ts
yarn.lock

fix #3279 create reflection in demo

---

packages/client/hooks/useFlipDeal.ts

test is in #3293
this should make collapse/expand animations look a little cleaner

fix #3293 janky expand reflection group animation

---

packages/client/components/ReflectionGroup/ReflectionGroup.tsx
packages/client/components/RetroDiscussPhase.tsx
packages/client/components/RetroReflectPhase/ExpandedReflection.tsx
packages/client/mutations/PromoteToTeamLeadMutation.ts
packages/client/types/graphql.ts
packages/client/utils/Auth0ClientManager.ts
packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
packages/server/graphql/queries/newMeeting.ts
packages/server/graphql/types/EditTaskPayload.ts
packages/server/graphql/types/EndDraggingReflectionPayload.ts
packages/server/sse/SSEConnectionHandler.ts

A few fatals, but they're really edge cases.
This fixes just about all the sentry errors that we've seen come in over the past 24 hours

Small sentry bugfixes

---

CONTRIBUTING.md

Doing this as a consent proposal.
I'd like to update this E4E policy to support the additional exposure we'll get during hiring. While I don't expect many (if any) to take us up on it, I'd rather make incremental progress here rather than nuke it all together.
* ~Action~ --> Parabol
* The percentage of fully-diluted equity has been halved to reflect the change in risk
* It's been made clear that we need to qualify you before we can accept your bid (i.e. we'll put some legal paper between you and us)

Updated E4E policy

---

packages/server/database/migrations/20161105214300-invitation.js
packages/server/database/migrations/20180206135107-renameProjectToTask.js
packages/server/database/migrations/20190509165854-legacyMeetingEvents.js
packages/server/database/migrations/20190912093945-remove-legacy-tables.ts
packages/server/utils/s3.js

3e4700f and 63d8afb fix blocking issues I ran into when building the repo from scratch.
1fdae78 and 018bcc4 fix non-blocking migration errors.

Fix errors encountered when building from scratch

---

.circleci/config.yml
CHANGELOG.md
lerna.json
package.json
packages/server/graphql/intranetSchema/mutations/dumpHeap.ts
packages/server/package.json
yarn.lock

hotfix to fix unhandledRejection handling in node 12
removes all binaries that don't support the latest node build

Bump node version

---

packages/client/components/DropdownToggleV2.tsx
packages/client/components/MenuToggleV2Text.tsx
packages/client/components/NewMeeting.tsx
packages/client/components/NewMeetingActions.tsx
packages/client/components/NewMeetingSettingsToggleCheckIn.tsx

Fix #3462 meeting lobby polish

---

packages/client/components/DueDateToggle.tsx
packages/client/components/EditingStatus/EditingStatus.tsx
packages/client/components/IconLabel.tsx
packages/client/components/VerifyEmail.tsx
packages/client/hooks/TooltipBackground.tsx
packages/client/hooks/useTooltip.ts
packages/client/hooks/useTooltipPortal.tsx
packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterIntegrateToggle.tsx
packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterTagMenuToggle.tsx
packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterTeamAssignee.tsx
packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterUserAssignee.tsx

Tooltip tasks

---

packages/client/Atmosphere.ts
packages/client/modules/userDashboard/components/UserProfile.tsx
packages/client/mutations/NavigateMeetingMutation.ts
packages/server/graphql/mutations/updateUserProfile.ts
packages/server/graphql/types/RemoveTeamMemberPayload.ts
packages/server/safetyPatchRes.ts

small fixes, extra logs, removed logs to clean up the sentry reports.
biggest fix is kicking out a team member correctly in real time. no big tension around it, but could upgrade to hotfix if we wanted.

fix minor sentry bugs

---

packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx

Added Prompt column with reflection topic for reflection and blank for tasks.
Closes #3581

(csv) added reflection phaseItem in csv

---

CHANGELOG.md
lerna.json
package.json
packages/client/Atmosphere.ts
packages/client/package.json
packages/cypress/package.json
packages/server/package.json
packages/server/socketHandlers/wssConnectionHandler.ts
packages/server/utils/sendToSentry.ts
yarn.lock

it's still not clear to me why clients are requesting websocket connections when they aren't authenticated.
this should help with that.

better logs for unauthed sockets

---

CHANGELOG.md
lerna.json
package.json
packages/client/Atmosphere.ts
packages/client/package.json
packages/cypress/package.json
packages/server/package.json
packages/server/socketHandlers/wssConnectionHandler.ts

Fix unauth

---

packages/server/dataloader/LoaderMakerPrimary.ts
packages/server/email/sendEmail.ts
packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts
packages/server/graphql/mutations/emailPasswordReset.ts
packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
packages/server/graphql/mutations/inviteToTeam.ts
packages/server/resendMeetingEmailDebugger.ts
packages/server/utils/createEmailVerification.ts

add tags to mailgun emails

---

packages/client/package.json
packages/cypress/package.json
packages/server/babelRegister.js
packages/server/dataloader/LoaderMakerPrimary.ts
packages/server/email/sendEmail.ts
packages/server/graphql/intranetSchema/mutations/sendUpcomingInvoiceEmails.ts
packages/server/graphql/mutations/emailPasswordReset.ts
packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts
packages/server/graphql/mutations/inviteToTeam.ts
packages/server/package.json
packages/server/resendMeetingEmailDebugger.ts
packages/server/utils/createEmailVerification.ts
yarn.lock

upgrades sucrase to handle the latest typescript features

bump sucrase

---

packages/client/Atmosphere.ts
packages/client/components/EmailInputField.tsx
packages/client/package.json
packages/server/dataloader/customLoaderMakers.ts
packages/server/graphql/mutations/emailPasswordReset.ts
packages/server/graphql/mutations/helpers/attemptLogin.ts
packages/server/graphql/mutations/helpers/notifySlack.ts
packages/server/graphql/mutations/signUpWithPassword.ts
packages/server/socketHandlers/wssConnectionHandler.ts
packages/server/utils/isEmailVerificationRequired.ts

emails should be case insensitive.
also attempts to fix the bad auth with websockets, but no way to test that
TEST

Fix capitalized emails

---

packages/client/components/ReflectionGroupVoting.tsx
packages/client/mutations/NavigateMeetingMutation.ts
packages/client/utils/autogroup/getTitleFromComputedGroup.ts
packages/server/graphql/mutations/navigateMeeting.ts
packages/server/graphql/mutations/upgradeToPro.ts
packages/server/graphql/mutations/voteForReflectionGroup.ts
packages/server/graphql/types/UpdateTaskPayload.ts

Fixes a handful of Sentry bugs

Sentry fixes 3

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/client/utils/SlackManager.ts
packages/cypress/package.json
packages/server/graphql/intranetSchema/intranetSchema.ts
packages/server/graphql/intranetSchema/queries/dailyPulse.ts
packages/server/graphql/intranetSchema/queries/helpers/authCountByDomain.ts
packages/server/package.json

This adds a dailyPulse internal graphql query

Slack stats

---

packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooter.tsx

fix #3587 partially. i couldn't reproduce the error, but now the task cards will show an error, if one arises

show error messages on tasks

---

packages/client/components/GroupingKanbanColumn.tsx
packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx
packages/client/components/ReflectionGroup/ReflectionGroup.tsx
packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx
packages/client/components/ReflectionGroupHeader.tsx
packages/client/components/RetroGroupPhase.tsx
packages/cypress/integration/demo_group.ts

Can do the following tests:
verifying that the robots group cards
creating a new group
adding a new reflection during grouping
editing a new reflection during grouping
deleting a reflection after it has been created
renaming a group
advancing to voting

created test suite for group phase

---

packages/client/components/RetroMeeting.tsx
packages/client/components/RetroSidebarDiscussSection.tsx
packages/client/hooks/useGotoStageId.ts
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
packages/client/modules/meeting/components/RejoinFacilitatorButton/RejoinFacilitatorButton.tsx

fix #3687 adding links to discussion from the summary
can't make everything clickable since it's email & anchor tags are inline
also cleans up the meeting more for post-meeting viewing

Summary links

---

packages/client/components/ReflectionGroupVoting.tsx
packages/client/components/RetroGroupPhase.tsx
packages/client/components/RetroMeeting.tsx
packages/client/components/RetroVotePhase.tsx
packages/cypress/integration/demo_group.ts
packages/cypress/integration/demo_vote.ts

Does the following tests: 
cards can be voted on (multiple times)
cards have a max voting limit
votes can be removed from cards
the vote counter becomes 0 when all votes are spent
can advance to discussion page

added test suite for voting phase

---

packages/client/components/RetroMeetingSidebar.tsx
packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/modules/demo/initDB.ts
packages/server/graphql/mutations/updateRetroMaxVotes.ts

this enables the new custom voting in the demo.
also fixes a few bugs, namely the one where discussion topics weren't specific to the stage in the demo (yikes!)

fix voting in demo

---

packages/server/graphql/intranetSchema/mutations/stripeUpdateInvoiceItem.ts

fixes #3734 
this matches enterprise invoice items with hooks.
if it doesn't match them, it's not the end of the world, but may be nice for analytics to see how teams grow/shrink.

attempt matching unprorated invoice items

---

packages/client/modules/email/components/SummaryEmail/newMeetingSummaryEmailCreator.tsx
packages/client/modules/email/components/emailVerificationEmailCreator.tsx
packages/client/modules/summary/components/MeetingSummaryEmailRootSSR.tsx
packages/client/mutations/EndNewMeetingMutation.ts
packages/server/graphql/mutations/helpers/notifySlack.ts
packages/server/graphql/mutations/inviteToTeam.ts
packages/server/utils/SAMLHandler.ts
packages/server/utils/makeAppLink.ts

this adds utm parameters where possible.
also prevents meeting redirects to summary for those not in the meeting

add utm params

---

CHANGELOG.md
lerna.json
package.json
packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/modules/demo/LocalAtmosphere.ts
packages/client/package.json
packages/cypress/package.json
packages/gql-executor/package.json
packages/server/package.json

If you refresh/reload the demo, you're in for a bad time. this fixes that by saving progress after bots do things, too.

HOTFIX Support demo restarts

---

packages/client/client.tsx
packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/polyfills.ts

This is just a little one to make development with firefox work again. No testing required.

Fix firefox dev [base: billing]

---

packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx

Users are able to see Emojis on CSV export with Unicode shown properly.
Closes #2947

Fix CSV unicode error

---

packages/server/socketHandlers/handleOpen.ts
packages/server/utils/getQueryToken.ts
packages/server/utils/getVerifiedAuthToken.ts
packages/server/utils/sendToSentry.ts

Until we can figure out how to keep clients from doing a lame duck replay attack, we might as well gather more info.

attached userId to expired ws req

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/gql-executor/package.json
packages/server/GoogleLanguageManager.ts
packages/server/package.json
yarn.lock

abort google call after 10 seconds

---

packages/server/graphql/mutations/addOrg.ts
packages/server/graphql/mutations/addTeam.ts
packages/server/graphql/mutations/endNewMeeting.ts
packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
packages/server/graphql/mutations/inviteToTeam.ts

add new segment events

---

packages/client/components/Action/Action.tsx
packages/client/components/AnalyticsPage.tsx
packages/client/hooks/useCacheEmail.tsx
packages/client/mutations/LoginWithGoogleMutation.ts
packages/client/mutations/LoginWithPasswordMutation.ts
packages/client/mutations/SignUpWithPasswordMutation.ts
packages/client/mutations/VerifyEmailMutation.ts
packages/client/types/constEnums.ts
packages/client/utils/handleSuccessfulLogin.ts
packages/server/socketHandlers/handleDisconnect.ts
packages/server/utils/PubSubPromise.ts
packages/server/utils/publishInternalGQL.ts

persist email for analytics

---

CHANGELOG.md
lerna.json
package.json
packages/client/components/BottomControlBarReady.tsx
packages/client/package.json
packages/cypress/package.json
packages/gql-executor/package.json
packages/server/package.json

This removes the confirmation flow from most things because it was firing waaay too much

No confirm

---

packages/server/graphql/intranetSchema/intranetSchema.ts
packages/server/graphql/intranetSchema/queries/company.ts
packages/server/graphql/intranetSchema/queries/users.ts
packages/server/graphql/mutations/endNewMeeting.ts
packages/server/segmentFns/SegmentFnHubspot.js
packages/server/segmentFns/SegmentFnHubspot.ts

support bulk update

---

packages/server/database/migrations/20200602211355-lowercase-emails.ts
packages/server/email/createEmailVerification.ts
packages/server/graphql/intranetSchema/mutations/loginSAML.ts
packages/server/graphql/mutations/loginWithGoogle.ts

this guarantees that every `email` property in the DB is lowercase

guarantee all email fields are lowercase in db

---

packages/server/utils/GraphQLRedisPubSub.ts

graphql pubsub unsub fix

---

.eslintignore
packages/server/graphql/intranetSchema/mutations/draftEnterpriseInvoice.ts
packages/server/graphql/types/Company.ts
packages/server/segmentFns/SegmentFnHubspot.js
packages/server/segmentFns/SegmentFnHubspot.ts
packages/server/segmentFns/hubSpotProperties.js
packages/server/segmentFns/hubSpotProperties.ts

Segmentfn fixups

---

packages/server/graphql/intranetSchema/mutations/draftEnterpriseInvoice.ts
packages/server/utils/StripeManager.ts

allow for custom plans in enterprise invoices

---

packages/client/components/DiscussionThread.tsx
packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/types/graphql.ts
packages/server/graphql/intranetSchema/queries/dailyPulse.ts

fixes the demo & also adds a fix to dailyPulse

fix demo add dailyPulse total

---

packages/client/components/DeleteAccount.tsx
packages/client/components/DeleteAccountModal.tsx
packages/client/modules/userDashboard/components/UserProfile.tsx
packages/client/mutations/DeleteUserMutation.ts
packages/client/types/graphql.ts
packages/server/database/types/User.ts
packages/server/graphql/mutations/deleteUser.ts
packages/server/graphql/types/User.ts

add delete account

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/cypress/package.json
packages/gql-executor/package.json
packages/server/graphql/mutations/emailPasswordReset.ts
packages/server/package.json

Email password reset

---

packages/server/graphql/types/User.ts

don't show overlimit copy if user is a member of any paid org

---

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts

added required properties to segment track call for GA destination

---

.circleci/config.yml

Dev server config

---

.circleci/config.yml

The only change now is that deploying to development triggers a build too.

migrate and postdeploy against ci env

---

README.md

Hi Parabol Team,
While attempting to build Parabol locally, this link would have saved me some time as I didn't have any prior knowledge of the Watchman project from Facebook. I thought adding it to the README might help others as well.
Thanks,
William

Added link to the watchman project in README

---

packages/client/hooks/useControlBarCovers.ts

Fix for control bar undefined bug

---

packages/server/graphql/rootSchema.ts
scripts/webpack/dev.servers.config.js

fix dev server hmr

---

packages/server/graphql/intranetSchema/queries/company.ts
packages/server/graphql/mutations/deleteUser.ts
packages/server/graphql/types/Company.ts
packages/server/segmentFns/SegmentFnHubspot.js
packages/server/segmentFns/SegmentFnHubspot.ts

fix #4086
can't promise it'll fix all of em, but it should fix most. no tests needed, segment will be testing for us.

fix hubspot segment bugs

---

packages/client/components/AddTeamMemberModal.tsx

Fix 4123 invite UI copy

---

packages/client/components/MyDashboardTasks.tsx
packages/client/components/MyDashboardTasksRoot.tsx
packages/client/modules/userDashboard/components/UserTasksHeader/UserTasksHeader.tsx

@tianrunhe here's the changes we did

address flicker

---

packages/server/utils/segmentIo.ts

Nick – I'd love to get this PR in the next release. Last release [we made a change](https://github.com/ParabolInc/parabol/pull/4117) to try and fix a data irregularity with Google Analytics. When we reviewed how this fix had been performing with the Segment Solutions Architect, he realized he gave us the wrong data shape to implement. This PR fixes this so we can try for reals.

Correct Segment GA schema; default to userId if null

---

packages/client/components/JiraScopingNoResults.tsx
packages/client/components/JiraScopingSearchInput.tsx
packages/client/components/JiraScopingSearchResultItem.tsx
packages/client/components/JiraScopingSearchResults.tsx
packages/client/components/JiraScopingSearchResultsRoot.tsx
packages/client/components/JiraScopingSelectAllIssues.tsx
packages/client/components/ScopePhaseAreaJiraScoping.tsx
packages/client/modules/meeting/components/MockScopingTask.tsx
packages/client/types/graphql.ts
packages/client/utils/AtlassianManager.ts
packages/server/graphql/mutations/addReflectTemplate.ts
packages/server/graphql/mutations/updateTemplateScope.ts
packages/server/graphql/queries/helpers/connectionFromTasks.ts
packages/server/graphql/queries/tasks.ts
packages/server/graphql/types/EstimateStageJira.ts
packages/server/graphql/types/JiraIssue.ts
packages/server/graphql/types/ReflectPhase.ts
packages/server/graphql/types/ReflectTemplate.ts
packages/server/graphql/types/Team.ts

Proxy jira through parabol

---

packages/server/graphql/mutations/addReflectTemplate.ts
packages/server/graphql/mutations/updateTemplateScope.ts
packages/server/graphql/types/ReflectPhase.ts
packages/server/graphql/types/ReflectTemplate.ts

fixes #4171 
@nickoferrall to take it home!

filter for isActive on reflect prompts

---

packages/server/email/components/SummaryEmail/MeetingSummaryEmail/QuickStats.tsx
packages/server/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
packages/server/graphql/types/RetrospectiveMeeting.ts

This PR attempts to solve the following issue: #4157 
Changed the sort by variable in RetroTopic and QuickStats from stageOrder to voteCount so that topics are sorted in ascending order.

Summary Topics

---

packages/server/database/migrations/20201008134420-addPlainTextContentToTask.ts

fix faulty migration `packages/server/database/migrations/20201008134420-addPlainTextContentToTask.ts`

await the batch update

---

packages/client/utils/parseEmailAddressList.ts

PR for issue #4281
See: [test data](https://www.notion.so/parabol/Bulk-Invite-by-Email-Test-Data-42e73f4daaaa4ff3bac50ef982f5936a) 🔒

Outlook email parser

---

packages/client/mutations/VoteForPokerStoryMutation.ts
packages/client/subscriptions/MeetingSubscription.ts
packages/client/types/graphql.ts
packages/client/utils/meetings/isPhaseComplete.js
packages/client/utils/meetings/isPhaseComplete.ts
packages/server/database/rMapIf.ts
packages/server/database/types/EstimateUserScore.ts
packages/server/database/updateStage.ts
packages/server/graphql/mutations/removePokerTemplateScaleValue.ts
packages/server/graphql/mutations/voteForPokerStory.ts
packages/server/graphql/rootMutation.ts
packages/server/graphql/types/EstimateUserScore.ts
packages/server/graphql/types/MeetingSubscriptionPayload.ts
packages/server/graphql/types/PokerMeeting.ts
packages/server/graphql/types/TemplateScale.ts
packages/server/graphql/types/TemplateScaleValue.ts
packages/server/graphql/types/VoteForPokerStoryPayload.ts

fixes #4263. all behind feature flag

add voteForPokerStory

---

packages/client/mutations/PokerAnnounceDeckHoverMutation.ts
packages/client/mutations/PokerResetDimensionMutation.ts
packages/client/mutations/PokerRevealVotesMutation.ts
packages/client/mutations/PokerSetFinalScoreMutation.ts
packages/client/subscriptions/MeetingSubscription.ts
packages/client/types/graphql.ts
packages/client/utils/AtlassianManager.ts
packages/server/database/types/EstimateStage.ts
packages/server/graphql/mutations/endSprintPoker.ts
packages/server/graphql/mutations/pokerAnnounceDeckHover.ts
packages/server/graphql/mutations/pokerResetDimension.ts
packages/server/graphql/mutations/pokerRevealVotes.ts
packages/server/graphql/mutations/pokerSetFinalScore.ts
packages/server/graphql/mutations/updatePokerScope.ts
packages/server/graphql/mutations/voteForPokerStory.ts
packages/server/graphql/resolvers/resolveStage.ts
packages/server/graphql/rootMutation.ts
packages/server/graphql/types/EstimateStage.ts
packages/server/graphql/types/MeetingSubscriptionPayload.ts
packages/server/graphql/types/PokerAnnounceDeckHoverPayload.ts
packages/server/graphql/types/PokerResetDimensionPayload.ts
packages/server/graphql/types/PokerRevealVotesPayload.ts
packages/server/graphql/types/PokerSetFinalScorePayload.ts
packages/server/graphql/types/Task.ts
packages/server/graphql/types/TaskEstimate.ts
packages/server/graphql/types/TemplateDimension.ts
packages/server/graphql/types/VoteForPokerStoryPayload.ts

fixes #4264 
fixes #4266 
fixes #4267
fixes #4268
this adds all the server/client mutations required for the estimate phase of the poker meeting.

Poker estimate mutations

---

packages/client/components/DeckActivityAvatars.tsx
packages/client/components/EstimatePhaseArea.tsx
packages/client/components/PeekingAvatar.tsx
packages/client/components/PokerCard.tsx
packages/client/components/PokerCardDeck.tsx
packages/client/components/PokerEstimatePhase.tsx
packages/client/mutations/PokerAnnounceDeckHoverMutation.ts
packages/client/subscriptions/MeetingSubscription.ts
packages/client/types/graphql.ts
packages/server/graphql/mutations/pokerAnnounceDeckHover.ts
packages/server/graphql/types/PokerAnnounceDeckHoverPayload.ts

When you hover a card in the deck, everyone else in the meeting is notified that you are thinking. this is shown by animating your avatar in from the right side. When you cast your vote, the avatar will animate to the votedUsers row. Otherwise, if you leave the deck without casting a vote, your avatar just hides on the right side.

Add Deck Activity Peekers

---

packages/server/database/migrations/20201116132414-modifyDefaultPokerTemplate.ts

Add migration for modified Poker Templates

---

packages/client/components/MeetingSelector.tsx
packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
packages/client/package.json
packages/server/package.json
yarn.lock

fixes #4348
also fixes an undocumented bug where setAppLocation would fire before a socket connection was established (or re-established).
also upgrades sanitize-svg, which should fix yarn install in some cases.

fix remove agenda item, setAppLocation

---

packages/client/utils/getSSODomainFromEmail.ts

this fixes SAML domain resolution for subdomains

fix saml domain getter

---

packages/client/components/JiraFieldMenu.tsx
packages/client/components/PokerEstimateHeaderCardJira.tsx
packages/client/mutations/UpdateJiraDimensionFieldMutation.ts
packages/client/types/constEnums.ts
packages/client/types/graphql.ts
packages/client/utils/AtlassianManager.ts
packages/client/utils/getJiraCloudIdAndKey.ts
packages/server/database/types/JiraDimensionField.ts
packages/server/graphql/mutations/pokerSetFinalScore.ts
packages/server/graphql/mutations/updateJiraDimensionField.ts
packages/server/graphql/mutations/updatePokerScope.ts
packages/server/graphql/types/EstimateStage.ts
packages/server/graphql/types/JiraDimensionField.ts
packages/server/utils/ensureJiraDimensionField.ts

Pre-validate jira field mappers

---

packages/client/components/ReflectionCard/ReactjiCount.tsx
packages/client/types/graphql.ts

This fixes the collapsed width in chromium browsers for reactjis

fix #4427 reactji spacing

---

packages/client/validation/makeUserServerSchema.js
packages/client/validation/templates.js
packages/server/graphql/mutations/helpers/updateOrgValidation.js

validate optional picture url when updating a user or org

---

scripts/webpack/assert.js
scripts/webpack/dev.clientdll.config.js
scripts/webpack/prod.client.config.js

graphiql is  borked & PRing that thing is a nightmare. this fixes it though.

fix-graphiql

---

packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx

Fix json2csv Parser import after upgrading

---

packages/client/components/RetroReflectPhase/PhaseItemColumn.tsx
packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
packages/client/components/Snackbar.tsx
packages/client/components/SwipeableDashSidebar.tsx
packages/client/hooks/useEditorState.ts
packages/client/hooks/useInterval.ts
packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
packages/client/types/graphql.ts
packages/client/utils/mergeServerContent.ts

this should solve the bug where the Task content gets updated multiple times within 20ms. it also removes useRefState from a bunch of places & replaces it with something that's a little easier to understand. it doesn't get rid of all the instances of it though, since it's still a valid pattern. just hard to wrap your head around.

more explicit handling of refs & state

---

packages/client/components/EstimateDimensionColumn.tsx
packages/client/components/JiraScopingSearchFilterMenu.tsx
packages/client/components/ScopePhaseArea.tsx
packages/client/hooks/useFilteredItems.ts
packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
packages/client/modules/meeting/components/TemplateScaleValueList.tsx
packages/client/package.json
packages/server/graphql/mutations/endSprintPoker.ts
packages/server/graphql/types/SuggestedIntegration.ts
scripts/dev.js
scripts/webpack/dev.client.config.js
yarn.lock

- Hide Team Revote on completed meeting
- add key to scale values
- fix migration in dev
- fix graphiql in dev
- fix #4512

Poker fixups

---

packages/client/hooks/useEditorState.ts

Fix task not updating bug

---

packages/client/utils/relay/clientTempId.ts

Fix client tempId

---

packages/client/components/ReflectionGroup/ReflectionGroupTitleEditor.tsx

Handle group title error message

---

packages/client/components/TopBarNotifications.tsx
packages/client/utils/relay/setActiveTemplate.ts

Fixes for issues #4618 and #4619 that were caught in Sentry.

Fix for undefined meetingSettings & notifications

---

packages/client/modules/outcomeCard/components/OutcomeCardAssignMenu/TaskFooterUserAssigneeMenu.tsx

Fix task footer menu fatal error

---

packages/server/graphql/mutations/endCheckIn.ts

PR to fix #4352 
`PromiseAll` guarantees the order on the client but not on the backend. It looks like the agenda items could occasionally be cloned and then cleared rather than cleared and then cloned.

Fix pinned items removed on meeting end

---

packages/client/components/TaskEditor/CommentEditor.tsx

Make hyperlinked comments editable

---

packages/client/components/NewMeeting.tsx

Adds Sprint Poker to the New Meeting options.

Release Sprint Poker

---

packages/server/graphql/mutations/endCheckIn.ts
packages/server/graphql/mutations/endRetrospective.ts
packages/server/graphql/mutations/endSprintPoker.ts
packages/server/graphql/mutations/helpers/endMeeting/sendNewMeetingSummary.ts

Fix the issue where only meeting member get summary email

---

packages/server/graphql/mutations/loginWithGoogle.ts

Generate a new id for user who has signed in with Google and deleted their account before

---

packages/client/components/Avatar/VideoAvatar.tsx
packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatarGroup.tsx

Meeting avatars are populated from MeetingMembers

---

packages/client/modules/demo/initDB.ts

Demo is crashing as `teamMember` is missing in `meetingMember`.

Hot fix meetingMember in demo

---

packages/server/postgres/getPgConfig.ts

set max pg connections to 40 (max allowable is 47)

---

packages/client/mutations/PokerRevealVotesMutation.ts

Fix an issue where app crashes on revealing votes if there are people who did not vote

---

packages/client/components/StageTimerModalTimeLimit.tsx
packages/client/hooks/useForm.tsx
packages/client/modules/newTeam/NewTeam.tsx
packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
packages/client/modules/newTeam/components/NewTeamForm/NewTeamFormOrgName.tsx
packages/client/modules/newTeam/components/NewTeamForm/NewTeamFormTeamName.tsx
packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationList.tsx
packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationRow.tsx
packages/client/mutations/AddOrgMutation.ts
packages/client/validation/teamNameValidation.ts
packages/client/validation/templates.js
packages/server/graphql/mutations/addOrg.ts
packages/server/graphql/mutations/addTeam.ts
packages/server/graphql/mutations/helpers/addOrgValidation.ts
packages/server/graphql/mutations/helpers/addTeamValidation.js
packages/server/graphql/mutations/helpers/addTeamValidation.ts

PR to fix issue #4028 
This PR also:
- Fixes a bug where the `AddOrgMutation` wasn't handling errors in the `onComplete` function
- Fixes several bugs where error objects were being used in the jsx instead of a string
- Refactored a few class components to functional components 
I'll leave the testing criteria out of this public PR description as it's a security issue.

Fix security issue #46

---

packages/client/utils/AtlassianManager.ts
packages/server/debugJira.ts
packages/server/tsconfig.json

chances are, we'll have a lot of bugs with the jira integration, so this is the file i used to debug the latest. we can use it in the future for more debugging

Debug jira

---

packages/client/components/PokerEstimateHeaderCardJira.tsx
packages/client/mutations/UpdatePokerScopeMutation.ts

fix #4782, we weren't requesting all the fields back on the mutation payload

fix #4782 missing story description

---

packages/server/graphql/mutations/loginWithGoogle.ts

always generate random id for google signup

---

packages/client/components/JiraFieldMenu.tsx
packages/client/components/JiraFieldMenuRoot.tsx
packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
packages/client/components/MeetingSubnavItem.tsx
packages/client/components/PokerEstimateHeaderCardJira.tsx
packages/client/components/PokerSidebarEstimateSection.tsx
packages/client/components/RetroSidebarDiscussSection.tsx
packages/client/hooks/useMakeStageSummaries.ts
packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx
packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
packages/client/mutations/UpdateJiraDimensionFieldMutation.ts
packages/client/shared/gqlIds/JiraServiceTaskId.ts
packages/client/utils/AtlassianManager.ts
packages/client/utils/getJiraCloudIdAndKey.ts
packages/server/graphql/mutations/pokerSetFinalScore.ts
packages/server/graphql/mutations/updatePokerScope.ts
packages/server/graphql/types/EstimateStage.ts
packages/server/graphql/types/PokerMeeting.ts

Folks want the jira issue key in the left nav. 
So, here it is:
@ackernaut to confirm if this looks good. maybe we don't put a strikethrough the subtitle?
TEST
fix #4671

add issueKey to left nav subtitle

---

packages/server/database/migrations/20180206135107-renameProjectToTask.js
packages/server/database/migrations/20210224121516-mergeDuplicateUsers.ts
packages/server/postgres/migrations/1614030642692_refs-for-meetings.ts
packages/server/postgres/migrations/1614361628531_github-auth.ts
scripts/dev.js

had some problems initializing the DBs from scratch, this fixes that.
Also this fixes the hanging migrations that @ackernaut found

end db connections

---

packages/client/components/PokerDiscussVoting.tsx

Sort revealed scores in Poker

---

packages/server/graphql/types/DragEstimatingTaskPayload.ts

I have to put on my magnifying glasses 🧐 for this one!

Fix a typo in DragEstimatingTaskSuccess

---

packages/client/types/graphql.ts
packages/server/graphql/types/JiraDimensionField.ts

Fix types for fieldName and dimensionName in JiraDimensionField

---

packages/server/database/migrations/20210330163028-addPriorityScale.ts

Add migration for priority scale

---

packages/client/mutations/PushInvitationMutation.ts

my bad for letting this one slip through.
FYI @nickoferrall can't use hooks outside of react components

fix push invitation

---

packages/server/createSSR.ts

Fix `content-type` typo

---

packages/client/components/NewGitHubIssueInput.tsx
packages/client/components/NewJiraIssueInput.tsx
packages/client/types/graphql.ts
packages/server/graphql/mutations/gitHubCreateIssue.ts

This PR:
- Validates the new GitHub or Jira issue 
- Increases the width of the new issue input
- Gives the user feedback if they enter an invalid new issue title
I thought I'd create a separate PR for this one to avoid scope creep in the Create GH Issue PR.

Validate new poker issues

---

packages/server/graphql/intranetSchema/mutations/enableSAMLForDomain.ts
packages/server/graphql/intranetSchema/mutations/loginSAML.ts

too lazy to cherry pick, will merge after i get in the other branch i'm working on

Saml no encode

---

packages/server/billing/debug.babel.js
packages/server/graphql/mutations/deleteUser.ts
packages/server/hubspot/backfillHubSpot.ts
packages/server/hubspot/debug.babel.js
packages/server/tsconfig.json
packages/server/utils/updateHubspot.ts

A few HubSpot update fixes + backfill script

---

.vscode/settings.json
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
packages/client/utils/makeAppURL.ts

Apparently i never merged this? :see_no_evil:

fix origin bug

---

packages/server/graphql/mutations/updateJiraDimensionField.ts

before, updating the jira dimension field was only updating the field name, not the field ID.
This was causing updating poker scores to go to the previous field (big BIG problem).
Onward to less buggy poker meetings!

fix changing jira fields

---

packages/client/components/AnalyticsPage.tsx
packages/client/components/ErrorBoundary.tsx
packages/client/types/constEnums.ts
packages/client/utils/handleSuccessfulLogin.ts

To remain within LogRocket's free tier, let's only record sessions where the user has encountered a fatal error

LogRocket free tier

---

packages/server/graphql/intranetSchema/mutations/backupOrganization.ts

backupOrganization wasn't working, so this should fix it.

fix bug backing up users

---

packages/server/graphql/intranetSchema/README.md
packages/server/graphql/intranetSchema/intranetSchema.ts
packages/server/graphql/intranetSchema/mutations/updateEmail.ts

Related issue: https://github.com/ParabolInc/parabol/issues/5005 
One note, `User` is also updated in PG, I'm not sure about `TeamMember` as I don't see what's the relation between `User` and `Team` in PG so I haven't done anything related to that.

Added update email mutation to intranet schema

---

packages/client/components/MockFieldList.tsx
packages/server/dataloader/customLoaderMakers.ts
packages/server/graphql/mutations/updateJiraDimensionField.ts

make the `selectedField` a little stricter

fix implicit any

---

nginx.conf.sigil
packages/client/Atmosphere.ts
packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx

Pw protect staging

---

packages/client/components/JiraScopingSearchHistoryMenu.tsx

Related issue: https://github.com/ParabolInc/parabol/issues/4962

Support removing Jira persisted queries

---

packages/server/database/migrations/202106024111905-sortJiraDimensionFields.ts
packages/server/graphql/mutations/updateJiraDimensionField.ts
packages/server/utils/ensureJiraDimensionField.ts

1. Sort `jiraDimensionFields` by JSON strings before updates to DB
2. Backfill scripts for RethinkDB

Sort jiraDimensionFields before updates & backfill script

---

packages/client/components/AnalyticsPage.tsx
packages/client/components/AndroidEditorFallback.tsx
packages/client/types/graphql.ts
packages/server/database/migrations/20210714160201-addIsWatched.ts
packages/server/database/types/User.ts
packages/server/graphql/intranetSchema/intranetSchema.ts
packages/server/graphql/intranetSchema/mutations/updateWatchlist.ts
packages/server/graphql/types/User.ts
packages/server/postgres/migrations/1626296172790_addIsWatched.ts
packages/server/postgres/queries/generated/getGitHubAuthByUserIdTeamIdQuery.ts
packages/server/postgres/queries/generated/getUsersByIdQuery.ts
packages/server/postgres/queries/generated/updateUserQuery.ts
packages/server/postgres/queries/src/updateUserQuery.sql

I've added a `isWatched` field to the User object and a private mutation that lets us toggle the boolean. With `isWatched`, we can create a watch list of the users where we want to record all of their sessions in LogRocket.

Implement LogRocket watchlist

---

packages/client/shared/gqlIds/GitHubIssueId.ts
packages/client/shared/gqlIds/GitHubRepoId.ts
packages/client/types/graphql.ts
packages/server/database/migrations/20210721151034-integration-hash.ts
packages/server/database/types/Task.ts
packages/server/database/types/TaskIntegration.ts
packages/server/database/types/TaskIntegrationJira.ts
packages/server/graphql/mutations/createGitHubTaskIntegration.ts
packages/server/graphql/mutations/createJiraTaskIntegration.ts
packages/server/graphql/mutations/createTask.ts
packages/server/graphql/mutations/helpers/createGitHubTask.ts
packages/server/graphql/mutations/helpers/createJiraTask.ts
packages/server/graphql/mutations/helpers/createTaskInService.ts
packages/server/graphql/types/CreateTaskInput.ts
packages/server/graphql/types/Task.ts

big refactor job.
now, if you want to create a task in parabol as well as in an integraiton, you can do that in a single call.
we'll use this when folks add integrated services in the poker scoping phase

createTask accepts optional integration

---

packages/client/components/AnalyticsPage.tsx

Resolves https://github.com/ParabolInc/parabol/issues/5102

fix nonexistent method

---

packages/client/components/TimelineEventCard.tsx

Add archive button to poker meeting timeline events

---

packages/server/utils/getReqAuth.ts

See in-code comments for deets

always check x-application-authorization first

---

packages/client/components/TaskFooterIntegrateMenuList.tsx

fix #5308 bad lowercase call

---

packages/server/graphql/intranetSchema/mutations/stripeSucceedPayment.ts

Fixes #5245
This fix ensures that upon a succeed payment:
*   Teams are unlocked
*   `subscriptionId` are updated for the org

Fix stripeSucceedPayment to unlock team and update subscriptionId

---

packages/client/components/PokerEstimateHeaderCard.tsx
packages/client/components/PokerEstimateHeaderCardGitHub.tsx
packages/client/mutations/UpdatePokerScopeMutation.ts
relay.config.js

add GitHub story card

---

packages/client/components/DashboardAvatars/DashboardAvatars.tsx
packages/client/components/InviteTeamMemberAvatar.tsx
packages/client/modules/teamDashboard/components/AgendaToggle/AgendaToggle.tsx
packages/client/modules/teamDashboard/components/TeamTasksHeader/TeamTasksHeader.tsx
yarn.lock

I think the best option for the header alignment is 28 over 16. Sorry for the back and forth. I also added a hover state for those icon controls.

Use 28 + 16 blocks for team header

---

packages/server/billing/helpers/generateInvoice.ts
packages/server/billing/stripeWebhookHandler.ts
packages/server/dataloader/RethinkDataLoader.ts
packages/server/graphql/resolvers.ts
packages/server/graphql/types/Company.ts
packages/server/graphql/types/NewMeeting.ts
packages/server/graphql/types/NewMeetingStage.ts
packages/server/graphql/types/Organization.ts
packages/server/graphql/types/RetrospectiveMeeting.ts
packages/server/graphql/types/TimelineEvent.ts
packages/server/graphql/types/User.ts
packages/server/tsconfig.json
packages/server/utils/authorization.ts

fixed ~200 noImplicitAny errors, mostly on graphql type files

---

packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx

Fixes #5415 
The successor of #5514.

Prevent remote reflection from loosing its position when opening spotlight

---

packages/client/package.json
yarn.lock

graphiql < 1.4.0 is vuln to a xss attack

bump graphiql

---

packages/client/components/GroupingKanban.tsx
packages/client/components/SpotlightGroups.tsx
packages/client/components/SpotlightModal.tsx
packages/client/components/SpotlightResultsRoot.tsx
packages/client/components/SpotlightSourceGroup.tsx
packages/client/hooks/useGroupMatrix.ts
packages/client/hooks/useQueryLoaderNow.tsx
packages/client/hooks/useResultsHeight.ts
packages/client/mutations/handlers/handleUpdateSpotlightResults.ts

Proposed changes to the search query following some merge conflict fun.

Spotlight search proposed changes

---

packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx

Fixes master errors - https://github.com/ParabolInc/parabol/runs/4188695281?check_suite_focus=true

Fix graphiql fetcher import

---

packages/client/components/GroupingKanbanColumn.tsx
packages/client/components/ReflectionGroup/ReflectionGroup.tsx
packages/client/components/RetroDiscussPhase.tsx
packages/client/components/SpotlightGroups.tsx
packages/client/components/SpotlightModal.tsx

Fix #5677
Hey @BartoszJarocki, could you review this PR, please?

Fix console errors when remotely ungrouping

---

.vscode/settings.json
packages/client/components/ScopePhaseAreaAddGitHub.tsx
packages/client/components/ScopePhaseAreaAddJira.tsx
packages/client/components/ScopePhaseAreaGitHub.tsx
packages/client/components/ScopePhaseAreaJira.tsx

hasAuth was defined differently in the parent & child components, which caused it to be false in the parent & true in the child, which meant oauth wouldn't open if there was a scope mismatch.
TEST

remove hasAuth from scopephaseareaadd

---

packages/client/hooks/useTooltip.ts
packages/client/modules/meeting/components/NewMeetingCheckInGreeting.tsx

Closes #4868
Language tooltip is updated with standard tooltip component. Please see Before and After screen recordings below. 
This change also eliminated long hover time (around 2.5s) mentioned in the issue. 
**BEFORE**
https://user-images.githubusercontent.com/37421564/142458132-7e8fe1bb-20a5-4ae1-bedc-a338a6050f6f.mov
**AFTER**
https://user-images.githubusercontent.com/37421564/142458230-7e6aab15-c00f-4f02-8bcd-aa3e2d6194e6.mov

Language tooltip is updated on New Meeting CheckIn Greeting

---

packages/server/dataloader/atlassianLoaders.ts

Returning refreshed token from fresh atlassian auth loader

---

packages/server/graphql/types/User.ts

Fix spotlight not loading similar reflections

---

packages/server/__tests__/addFeatureFlag.test.ts
packages/server/__tests__/updateWatchlist.test.ts
packages/server/graphql/intranetSchema/queries/dailyPulse.ts
packages/server/graphql/intranetSchema/queries/helpers/authCountByDomain.ts
packages/server/graphql/types/User.ts
packages/server/postgres/migrations/1638170546562_userDomainField.ts
packages/server/postgres/queries/generated/getUsersByDomainQuery.ts
packages/server/postgres/queries/generated/getUsersByEmailsQuery.ts
packages/server/postgres/queries/generated/getUsersByIdsQuery.ts
packages/server/postgres/queries/src/getUsersByDomainQuery.sql
packages/server/utils/getActiveDomainForOrgId.ts

Add calculated domain field to User

---

packages/server/graphql/resolvers.ts

Fixes #5762 
Context: https://parabol.slack.com/archives/C836NA350/p1639086456192000

This is proper this again in make resolve

---

packages/server/postgres/queries/getTeamsByIds.ts

Fix mapping to jira dimension field

---

packages/client/components/ReflectionCard/ReflectionCard.tsx

This PR removes the feature flag check so that all users can access the Spotlight feature

Release Spotlight

---

packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/modules/demo/LocalAtmosphere.ts
packages/client/modules/demo/initDB.ts

fetchQuery was undefined in LocalAtmosphere, so testing resulting in a runtime error. Would you mind adding this back in?

Agarg21 fix demo integration task

---

docker/dev.yml

sometimes it's nice to have redis commander 🤷

add redis-commander to dev docker-compose

---

packages/client/hooks/useMeetingMemberAvatars.ts
packages/client/modules/meeting/components/MeetingAvatarGroup/NewMeetingAvatarGroup.tsx
packages/client/types/graphql.ts
packages/server/__tests__/autopauseUsers.test.ts
packages/server/__tests__/loginWithPassword.test.ts
packages/server/database/types/User.ts
packages/server/dataloader/hydrateRedisDoc.ts
packages/server/graphql/intranetSchema/mutations/connectSocket.ts
packages/server/graphql/intranetSchema/mutations/loginSAML.ts
packages/server/graphql/types/User.ts
packages/server/postgres/migrations/1641581237527_addNonNullLastSeenAtConstraint.ts
packages/server/postgres/queries/generated/getGitHubAuthByUserIdTeamIdQuery.ts
packages/server/postgres/queries/generated/getUserIdsToPauseQuery.ts
packages/server/postgres/queries/generated/getUsersByDomainQuery.ts
packages/server/postgres/queries/generated/getUsersByEmailsQuery.ts
packages/server/postgres/queries/generated/getUsersByIdsQuery.ts
packages/server/postgres/queries/src/getUserIdsToPauseQuery.sql

Fixes #5360.
@Dschoordsch can you take a look? Thanks!

Make User.lastSeenAt non null

---

packages/server/graphql/mutations/helpers/isStartMeetingLocked.ts
packages/server/graphql/mutations/startCheckIn.ts
packages/server/graphql/mutations/startRetrospective.ts
packages/server/graphql/mutations/startSprintPoker.ts
packages/server/utils/authorization.ts

enforce server side lock

---

packages/client/components/EstimateDimensionColumn.tsx
packages/client/components/PokerActiveVoting.tsx
packages/client/components/PokerCardDeck.tsx
packages/client/mutations/SetPokerSpectateMutation.ts
packages/client/types/graphql.ts
packages/server/graphql/mutations/setPokerSpectate.ts
packages/server/graphql/mutations/voteForPokerStory.ts
packages/server/graphql/types/SetPokerSpectatePayload.ts

Fix isSpectating toggle & Reveal Votes count

---

packages/client/package.json
yarn.lock

removes ansi-html (high security risk)

SECURITY: bump react-refresh-webpack-plugin

---

packages/server/graphql/traceGraphQL.ts

no idea why typescript decided now was the right time to complain about this...

add undefined to wrappedQuery vars

---

.circleci/config.yml
.github/workflows/typecheck.yml
docker/Dockerfile.prod
package.json
yarn.lock

Critical and High security findings: cross-fetch: ^3.1.5, node-fetch: ^2.6.7, clean-css: ^5.2.2, node-forge: ^1.2.1, glob-parent: ^6.0.2, node-pre-gyp: ^0.17.0
Medium and Moderate security findings: cross-fetch: ansi-regex: ^5.0.1, json-schema: ^0.4.0, nanoid: ^3.1.31, @xmldom/xmldom: ^0.7.0"

6.44.0 ironbank fixes

---

scripts/webpack/dev.client.config.js
scripts/webpack/prod.client.config.js

Where env vars go isn't intuitive. But words work!

add comments on putting env vars in __ACTION__

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

It looks like the same ISSUE_TEMPLATE used to cover bugs and feature requests. This PR removes the bug language from the feature request (and vice versa).

chore: improve GH issue templates

---

packages/client/modules/meeting/components/PokerTemplateItem.tsx
packages/client/modules/meeting/components/ReflectTemplateItem.tsx
packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
packages/server/database/migrations/20220121600507-addMoreRetroTemplates.ts
packages/server/database/migrations/20220124600507-addMoreRetroTemplates.ts
yarn.lock

Fix #5890, fix #5891, fix #5892 
This PR adds new retro templates and prevents the template menu from scrolling up when you click on a menu item.

New retro templates

---

packages/client/Atmosphere.ts
packages/client/components/PrivateRoutes.tsx
packages/client/modules/admin/containers/Impersonate/ImpersonateContainer.tsx
packages/client/mutations/CreateImposterTokenMutation.ts
packages/client/types/AuthToken.ts
packages/client/types/graphql.ts
packages/server/database/types/AuthToken.ts
packages/server/graphql/mutations/createImposterToken.ts
packages/server/graphql/types/CreateImposterTokenPayload.ts
packages/server/socketHandlers/handleConnect.ts
packages/server/socketHandlers/handleDisconnect.ts

fix #4947
20% passion project, i've been wanting this for over a year now.
TEST
Loom here: https://www.loom.com/share/122527fe02174e63ad6f4c6e81657ff5

better impersonation

---

package.json
yarn.lock

Ironbank 6.25.0 security fixes

---

packages/server/postgres/migrations/1642094555266_addJiraServerIntegrationProvider.ts
packages/server/postgres/queries/generated/getBestTeamIntegrationAuthQuery.ts
packages/server/postgres/queries/generated/getGitHubAuthByUserIdTeamIdQuery.ts

@Dschoordsch couple DB down migration & generated file fixes for your PR

fix old migrations, pg:build

---

packages/server/graphql/CompiledQueryCache.ts
packages/server/graphql/executeGraphQL.ts

Fixes https://github.com/ParabolInc/action-devops/issues/80
Repro is found in issue above

fix gql executor with bad queries in dev

---

.circleci/config.yml
packages/server/__tests__/jiraServerIntegration.test.ts
packages/server/email/getMailManager.ts
packages/server/package.json
pm2.dev.config.js
yarn.lock

This PR automatically runs the server `jest` tests as part of the CI run. See inline comments for details.

Add GraphQL server tests to circle ci

---

packages/client/components/SearchMenuItem.tsx
packages/server/package.json
yarn.lock

bump nest-graphql-endpoint

---

packages/server/dataloader/atlassianLoaders.ts
packages/server/graphql/queries/helpers/fetchAllRepoIntegrations.ts

This happened when jira integration is not added an TaskFooterMenu is
opened.

Fix TypeError: jiraProjects is not iterable

---

packages/client/components/MeetingTopBar.tsx
packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
packages/client/components/TeamPromptMeeting.tsx

Fixes https://github.com/ParabolInc/parabol/issues/6196
Create the stub for the top bar, and wrap the existing meeting space placeholder

feat(standups): Top Bar Component Stub

---

packages/client/components/MeetingSelector.tsx
packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
packages/client/components/TeamPromptMeeting.tsx

fixes https://github.com/ParabolInc/parabol/issues/6198
https://www.loom.com/share/f497ec22108442fb87d7c8d6e5dd67b0
Needs rebase once https://github.com/ParabolInc/parabol/pull/6318 is merged

feat(standups): Show meeting title

---

packages/server/graphql/types/MeetingMember.ts

This is causing issues around meeting viewer checkin on the team prompt meeting

fix(standups): Include TeamPromptMeetingMember on MeetingMember type

---

CONTRIBUTING.md
README.md

This PR introduce a new section on CONTRIBUTING describing the step by step guide how to make changes (including code review flow described by @nickoferrall in Slack).

docs: Update CONTRIBUTING

---

docs/manualTestingGuide.md

Updated version of the manual testing guide. Moved some sections around and cleaned up some of the punctuation and wording.

chore:  Create manualTestingGuide.md

---

packages/server/graphql/nestedSchema/nestGitLabEndpoint.ts

Fix https://github.com/ParabolInc/parabol/issues/6478

fix: remove octokit from nestGitLabEndpoint

---

packages/client/mutations/ResetRetroMeetingToGroupStageMutation.ts

fix: Reset retro meeting to group stage response handling

---

packages/client/mutations/AddAgendaItemMutation.ts

Fixes how mutation response handling by adding types and fixing possible TypeError (similar to #5383).

fix: add agenda item response handling

---

packages/client/hooks/useQueryLoaderNow.tsx
packages/client/modules/email/components/MeetingSummaryEmailRootSSR.tsx

fix(email-summary): revert MeetingSummaryEmailRootSSR to use query renderer

---

packages/client/hooks/useQueryLoaderNow.tsx
packages/client/modules/email/components/MeetingSummaryEmailRootSSR.tsx

fix: email summaries - production

---

packages/client/components/TeamPromptMeeting.tsx

feat(standups): Place viewer's card at the start of the list

---

packages/client/.eslintignore
packages/client/components/AddToGitLabMenuItem.tsx
packages/client/components/RetroGroupPhase.tsx
packages/client/components/ScopePhaseArea.tsx
packages/client/components/TaskFooterIntegrateMenu.tsx
packages/client/components/TaskFooterIntegrateMenuSignup.tsx
packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
packages/client/modules/teamDashboard/components/ProviderRow/GitLabProviderRow.tsx
packages/client/mutations/AddFeatureFlagMutation.ts
packages/client/subscriptions/NotificationSubscription.ts
packages/client/tsconfig.eslint.json
packages/server/graphql/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/6552
- Open up an incognito window
- Create a new user
- Create a Sprint Poker meeting
- See that you can integrate with GitLab from within the meeting & everything works as expected such as pushing estimates to the issue
- In `/tasks`, see that you can push a task to a GitLab project
This PR should only be merged to master once https://github.com/ParabolInc/parabol/issues/6511 and https://github.com/ParabolInc/parabol/issues/6540 have been closed.

chore: remove GitLab feature flag

---

packages/client/components/ScopePhaseArea.tsx
packages/client/components/TaskFooterIntegrateMenu.tsx
packages/client/components/TaskFooterIntegrateMenuSignup.tsx
packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
packages/server/graphql/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Lorena is off sick tomorrow so we're going to postpone launching GitLab until next week.

chore: readd gitlab feature flag

---

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md

This PR introduces a PR template. The main reason for listing technically the obvious things is forming the habit of actually sharing the proper information with the hope it'll speed up the review process. 
let's discuss!

chore: added PR template

---

packages/server/graphql/types/JiraIssue.ts

Fixes #6236
How to test:
- add jira integration
- push task to jira

fix(jira): Fix server error when pushing task to jira

---

packages/server/graphql/mutations/addAtlassianAuth.ts
packages/server/graphql/mutations/addGitHubAuth.ts
packages/server/graphql/mutations/addSlackAuth.ts
packages/server/graphql/mutations/addTeamMemberIntegrationAuth.ts
packages/server/graphql/mutations/createTask.ts
packages/server/graphql/mutations/createTaskIntegration.ts
packages/server/graphql/mutations/removeAtlassianAuth.ts
packages/server/graphql/mutations/removeGitHubAuth.ts
packages/server/graphql/mutations/removeSlackAuth.ts
packages/server/graphql/mutations/removeTeamMemberIntegrationAuth.ts
packages/server/utils/analytics/analytics.ts

Fixes #5341  
Changes:
1. Added missing "Integration Added" events for GitLab, MS Teams, Jira Server, etc
2. Added new "Integration Removed" events
3. Consolidate "Published Task to XXX" events into "Task Published" event with `service` property
4. Migrated "Task Created" events
**Remember to copy [Segment keys](https://github.com/ParabolInc/action-devops/blob/master/environments/development#L63-L64) to your `.env` first**
1. Go to team integration page `http://localhost:3000/team/[teamId]/settings/integrations`
2. Add or remove an integration
3. Go to [Segment development](https://app.segment.com/parabol-jordan/sources/actiondevelopment/debugger) and search for "Integration", verify the event is present and the `service` property is expected
1. Go to team page with Jira/GitHub/GitLab …

feat(metrics): migrate and consolidate integration related metrics

---

packages/client/components/ScopePhaseArea.tsx
packages/client/components/TaskFooterIntegrateMenu.tsx
packages/client/components/TaskFooterIntegrateMenuSignup.tsx
packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
packages/server/graphql/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/6552
We can only merge this PR once https://github.com/ParabolInc/parabol/pull/6594 has been merged and once the Growth team have let us know that they're ready for launch.

chore: remove gitlab flag

---

packages/server/graphql/public/types/Organization.ts

I did a bad merge from master & somehow the typechecker didn't flag this 🤯 .
Gonna look into why now...

fix bad merge on Organization.ts

---

packages/client/components/TeamPrompt/TeamPromptGridDimensions.ts
packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
packages/client/components/TeamPromptMeeting.tsx

Partially Fixes `Standups: Improve mobile experience #6601`
https://user-images.githubusercontent.com/1017620/172626445-1b06248d-7960-429d-808e-64bf31f9d508.mp4

feat(standups): Standups responses grid UI improvements

---

packages/server/graphql/mutations/addMissingJiraField.ts

Fixes #6675
Previous PR: #6676
* Looks like Jira API does not allow fetching more than 100 items, set `batchSize` to 100
* Changed `evaluateProbability` function to make it more precise, otherwise it sometimes picks screens that belong to different projects
* Fixed hardcoded value

fix(jira): Fix add missing jira field new algorithm

---

packages/server/database/migrations/20220614155505-addTeamCharterTemplate.ts

Fix https://github.com/ParabolInc/parabol/issues/6340

feat: add team charter template

---

packages/server/billing/helpers/terminateSubscription.ts
packages/server/database/migrations/20220329101759-dropTeams.ts
packages/server/database/rethinkDriver.ts
packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
packages/server/graphql/mutations/helpers/removeTeamMember.ts
packages/server/graphql/mutations/helpers/resolveDowngradeToPersonal.ts
packages/server/graphql/mutations/helpers/upgradeToPro.ts
packages/server/graphql/mutations/moveTeamToOrg.ts
packages/server/graphql/mutations/startCheckIn.ts
packages/server/graphql/mutations/startRetrospective.ts
packages/server/graphql/mutations/startSprintPoker.ts
packages/server/graphql/mutations/updateJiraDimensionField.ts
packages/server/graphql/mutations/updateTeamName.ts
packages/server/graphql/private/mutations/backupOrganization.ts
packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
packages/server/graphql/private/mutations/lockTeams.ts
packages/server/graphql/private/mutations/stripeSucceedPayment.ts
packages/server/postgres/getPg.ts
packages/server/postgres/migrations/1614030642692_refs-for-meetings.ts
packages/server/postgres/migrations/1625576993064_sortJiraDimensionFields.ts
packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts
packages/server/postgres/migrations/postDeploy/1615148741896_backfillTeamTable.ts
packages/server/postgres/migrations/postDeploy/1623747531144_backfillMissingTeams.ts
packages/server/postgres/utils/checkEqBase.ts
packages/server/postgres/utils/dropUndefined.ts
packages/server/safeMutations/safeArchiveTeam.ts
packages/server/utils/ensureJiraDimensionField.ts

Hello
Bellow you can find changes relate to #4631
I know that it was not marked as "help wanted" but it was so low-hanging fruit that I couldn't resist ;)

refactor: Stop writes to RethinkDB Team table

---

packages/client/components/MeetingControlBar.tsx

Close #6843
- Start a new Poker meeting
- Verify the timer in different Phases

feat(Poker): Add a timer to Sprint Poker

---

packages/client/components/NewIntegrationRecordButton.tsx
packages/client/components/ScopePhaseArea.tsx
packages/client/components/ScopePhaseAreaAddAzureDevOps.tsx
packages/client/modules/teamDashboard/components/ProviderRow/AzureDevOpsProviderRow.tsx
packages/server/graphql/types/AzureDevOpsIntegration.ts
packages/server/utils/AzureDevOpsServerManager.ts
scripts/toolboxSrc/primeIntegrations.ts

Fixes #6789 
Add global IntegrationProvider for Azure DevOps
https://www.loom.com/share/db1cf1cef2d94ea09c8a9aaf9ce11e1a
* update your `.env` with the secrets from [this pr](https://github.com/ParabolInc/action-devops/pull/96)
* run `yarn postdeploy`
* add `azureDevOps` feature flag for your user

feat(Azure DevOps): Add global provider

---

packages/client/Atmosphere.ts

Fix https://github.com/ParabolInc/parabol/issues/6429

fix: impersonate user bug

---

packages/client/utils/makeAppURL.ts
packages/server/graphql/mutations/helpers/addSeedTasks.ts

Fixes/Partially Fixes #5943
- go to the integration setting page
- verify the URL with UTM query parameters

fix: add query parameter to identify the page source

---

packages/client/components/ReflectionCard/ReflectionCard.tsx

fix: Text in reflection cards is not selectable during vote period

---

packages/client/components/ForgotPasswordPage.tsx
packages/server/graphql/mutations/emailPasswordReset.ts

fixes #6712
users who reset their password often can now keep resetting it often
- trigger a password reset 3 times in 1 day. then come back 24+ hours later & trigger another one. it works

fix(resetPassword): Reset request count daily

---

packages/server/database/migrations/20220815156512-addScrumValuesTemplate.ts
packages/server/graphql/types/AzureDevOpsWorkItem.ts

Fix https://github.com/ParabolInc/parabol/issues/7045
Adds the scrum template to retros:

feat: add scrum template

---

codegen.json
packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
packages/client/mutations/StopRecurrenceMutation.ts
packages/client/subscriptions/TeamSubscription.ts
packages/server/database/migrations/20220819072356-addMeetingSeriesIdIndex.ts
packages/server/database/rethinkDriver.ts
packages/server/database/types/Meeting.ts
packages/server/database/types/MeetingTeamPrompt.ts
packages/server/graphql/public/mutations/stopRecurrence.ts
packages/server/graphql/public/typeDefs/startRecurrence.graphql
packages/server/graphql/public/typeDefs/stopRecurrence.graphql
packages/server/graphql/public/types/StopRecurrenceSuccess.ts
packages/server/postgres/queries/src/updateMeetingSeriesByIdQuery.sql
packages/server/postgres/queries/updateMeetingSeries.ts

Fixes #6918 
- Set up recurrence using menu in the top right corner
- Stop the recurrence using menu in the top right corner
- Check rethinkdb if given meeting have `scheduledEndTime` set to null
- Check postgres if related meeting series have `cancelledAt` set to a proper date

feat(standups): Recurrence - `stopRecurrence` mutation

---

packages/client/components/NewMeetingCarousel.tsx

Fixes https://github.com/ParabolInc/parabol/issues/7040
Alternative approach to #7061 (Comment: https://github.com/ParabolInc/parabol/pull/7061#issuecomment-1218340602)
https://user-images.githubusercontent.com/466991/185211426-d1cee100-495d-4323-b664-651a98861494.mov
https://user-images.githubusercontent.com/466991/185211430-f3eaac29-740a-445b-9b11-e211ac91873b.mov

fix: center new meeting dialog slides on mobile

---

.github/workflows/labeler.yml

Compared our config with [this person](https://github.com/CodelyTV/pr-size-labeler/issues/40#issuecomment-1142130933) and removed two lines. It then just magically works!

fix(DX): Fix the PR labeler

---

CHANGELOG.md
lerna.json
package.json
packages/gql-executor/package.json
packages/server/package.json
packages/server/utils/stripe/StripeManager.ts

The parameter `prorate` is gone and instead `prorate_behavior` is not
being set.
**I did not test!**

fix: Update stripe.subscription.create prorate parameter

---

packages/client/components/Facilitator.tsx
packages/client/components/NewMeetingSidebar.tsx

fix: Facilitator's name is tiny and hard to read

---

packages/client/components/Dashboard/DashSidebar.tsx

Fixes/Partially Fixes #7152
https://user-images.githubusercontent.com/106697681/188719224-8b2ed11a-85f5-4f1b-a722-a85ba9df9bed.mp4

fix: New Add Meeting button is pushing the Add Team button out of reach

---

packages/client/components/ErrorBoundary.tsx

We lost some ? in #7067, found them.
Fixes #7197, #7199

fix: Fix cannot read email of undefined in ErrorBoundary

---

scripts/create-jira-keys.sh

Add a script to simplify generating the necessary private/public keys for a Jira Server integration. Based on https://developer.atlassian.com/server/jira/platform/oauth/#step-1--configure-jira
How to add these to Jira Server: https://www.loom.com/share/74eb6bbab9094424a33faa6785c147fc
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Add jira server key generation script

---

.husky/pre-commit
packages/client/components/LogoBlock/LogoBlock.tsx
packages/client/components/TeamPrompt/TeamPromptTopBar.tsx

Fixes #7100
**Before:**
**After:**

style: replace back arrow with logo

---

.github/workflows/stats.yml

We upped the required node version, adapt the review stats script as well.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Use correct node version for review stats

---

packages/server/utils/analytics/analytics.ts

See https://github.com/ParabolInc/parabol/pull/7190#discussion_r989552229

fix: unsubscribe analytics bug

---

packages/server/graphql/mutations/helpers/removeFromOrg.ts

Fix https://github.com/ParabolInc/parabol/issues/6144
https://www.loom.com/share/81c633b5d1304c6fb8e8a76ee07c916a

fix: assign new billing leader after deleting billing leader

---

packages/client/components/DiscussionThreadInput.tsx
packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx
packages/client/components/EditorLinkChanger/EditorLinkChangerModal.tsx
packages/client/utils/draftjs/completeEntity.tsx

fix: Hyperlink removes whitespace

---

packages/client/components/EditorLinkChanger/EditorLinkChangerDraftjs.tsx

Pre-commit checks are not run for external contributors automatically.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Fix missing types

---

packages/server/database/migrations/20221025161717-addIsFreeMeetingTemplate.ts
packages/server/database/migrations/20221025161717-addIsPremiumMeetingTemplate.ts
packages/server/database/types/MeetingTemplate.ts
packages/server/graphql/types/MeetingTemplate.ts
packages/server/utils/analytics/helpers.ts

Fix https://github.com/ParabolInc/parabol/issues/7334

feat: add isFree to meeting template

---

packages/server/utils/updateHubspot.ts

Properties of company objects in HubSpot are now backed & updated by Data Sanctum. We can now turn off the updates from app side to:
1. Save some HubSpot API costs
2. Reduce DB query counts & increase performance
3. Avoid duplicate & potential conflicting updates:

feat(metrics): disable Company properties update to HubSpot

---

packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/7390

feat: add template limit feature flag

---

packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

feat(teams-limit): add teams limit feature flag

---

packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts

Fix https://github.com/ParabolInc/parabol/issues/7455
Demo: https://www.loom.com/share/9cf26db3744140bf907aa4c4222c443e

feat: update selected template for free teams

---

packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/7473

feat: add ai summary feature flag

---

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/makePokerStats.ts
packages/server/graphql/mutations/endSprintPoker.ts

fix: number of stories in summary stats is one less than actual stories

---

packages/server/database/migrations/20221201121536-addHeardSeenRespectedTemplate.ts

Fix https://github.com/ParabolInc/parabol/issues/7220

feat: add heard seen respected template

---

packages/client/components/TeamPrompt/Recurrence/HumanReadableRecurrenceRule.tsx
packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
packages/client/package.json
yarn.lock

feat(recurrence): added human readable recurring meeting indicator

---

.vscode/launch.json
packages/server/graphql/public/rootSchema.ts

Add some comments to the `rootSchema` to not get lost next time.
https://www.loom.com/share/387739634cde4f709882e6b36d11526f
Build passes and app starts

chore: Add comments to rootSchema

---

packages/server/graphql/types/NewMeeting.ts
packages/server/graphql/types/helpers/isMeetingLocked.ts

Cherry-pick of #7581 
Cherry picking to production to not delay the rollout until January.

fix: new meetings were locked with the history limit

---

packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

This PR makes simple recurrence available to all users
No demo

feat: removed recurrence feature flag

---

packages/client/components/Dashboard/DashSidebar.tsx
packages/client/components/Dashboard/LeftDashNavItem.tsx
packages/client/components/Dashboard/MobileDashSidebar.tsx
packages/client/components/MyDashboardTimeline.tsx

chore: change "Timeline" to "History"

---

packages/server/billing/stripeWebhookHandler.ts
packages/server/graphql/private/mutations/stripeInvoicePaid.ts
packages/server/graphql/private/typeDefs/stripeInvoicePaid.graphql

Fixes #7688
https://www.loom.com/share/19e10f8669154551b6f68e3716c6c303
Reproduce steps taken in the demo. Probably not necessary, it's a simple fix!

fix: use stripe invoice.paid event instead of invoice.payment_succeeded

---

packages/server/graphql/public/typeDefs/addFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/7528

chore(checkout-flow): add checkout feature flag

---

package.json
packages/client/package.json
packages/server/package.json
yarn.lock

chore(deps): bump webpack, undici

---

packages/client/components/TeamPrompt/TeamPromptOptions.tsx
packages/client/utils/react/mergeRefs.ts

feat(standups): added options menu tooltip

---

packages/server/dataloader/NullableDataLoader.ts
packages/server/dataloader/RootDataLoader.ts
packages/server/dataloader/UpdatableCacheDataLoader.ts
packages/server/dataloader/__tests__/nullableDataLoader.test.ts
packages/server/dataloader/foreignKeyLoaderMaker.ts
packages/server/dataloader/rethinkForeignKeyLoader.ts
packages/server/dataloader/rethinkPrimaryKeyLoader.ts
packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts

Fixes  #7687
How to test:
- Run a meeting with AI summary, see that all works (see `generateWholeMeetingSummary`)
- Run `yarn test nullableDataLoader`

chore(dx): add updateCache function to dataLoader

---

packages/client/components/EditingStatus/EditingStatusText.tsx

fix: 'Updated time/Created time' is not instantaneous on task cards

---

packages/client/components/AnalyticsPage.tsx
packages/client/utils/getContentGroup.ts

Fixes https://github.com/ParabolInc/parabol-data-sanctum/issues/544
Install [this Chrome extension](https://chrome.google.com/webstore/detail/gtmga-debugger/ilnpmccnfdjdjjikgkefkcegefikecdc?hl=en&utm_source=gtm-ga) to make testing easier
- Start the local server
- Open up Chrome developer tools and click the "Analytics Debugger", then "Start debugging"
- Go to any page in the app
- Expand the item in Analytics Debugger and click the "GA4" tab, there should be:
1. An page_view event
2. Expand the EVENT PARAMETERS, you should see an associated value with `content_group`

chore(metrics): Add content_group in GA4 page_view event

---

packages/client/utils/AtlassianManager.ts

chore: add temporary story points update result logging

---

packages/server/socketHelpers/sendEncodedMessage.ts

fix: handle SSE and socket done checks

---

packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
packages/client/modules/userDashboard/components/OrgBilling/BillingLeaders.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
packages/client/types/constEnums.ts

Fix https://github.com/ParabolInc/parabol/issues/7531

feat(checkout-flow): implement billing leader UI

---

packages/client/components/BillingLeaderActionMenu.tsx
packages/client/components/DashNavList/DashNavList.tsx
packages/client/components/InvitationLinkDialog.tsx
packages/client/components/MeetingsDash.tsx
packages/client/components/ReflectionGroup/DraggableReflectionCard.tsx
packages/client/components/ReflectionGroupVoting.tsx
packages/client/components/StandardHub/StandardHub.tsx
packages/client/components/TaskColumns/TaskColumns.tsx
packages/client/components/TaskIntegrationLink.tsx
packages/client/components/TeamInvitationDialog.tsx
packages/client/components/TimelineEvent.tsx
packages/client/components/TimelineSuggestedAction.tsx
packages/client/components/TopBarAvatar.tsx
packages/client/components/TopBarSearch.tsx
packages/client/components/UserDashTeamMemberMenu.tsx
packages/client/components/UserDashTeamMenu.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailTaskCard.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TaskSummarySection.tsx
packages/client/modules/invoice/components/InvoiceLineItem/InvoiceLineItemDetails.tsx
packages/client/modules/meeting/components/EditableTemplateScaleName.tsx
packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
packages/client/modules/teamDashboard/components/AgendaList/AgendaList.tsx
packages/client/modules/teamDashboard/components/AgendaListAndInput/AgendaListAndInput.tsx
packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx
packages/client/modules/teamDashboard/components/TaskColumn/TaskColumn.tsx
packages/client/modules/teamDashboard/components/TaskColumn/TaskColumnAddTask.tsx
packages/client/modules/teamDashboard/components/Team/Team.tsx
packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
packages/client/modules/userDashboard/components/Organization/OrganizationPage.tsx
scripts/codeshift/convertToUseFragment.ts

refs https://github.com/ParabolInc/parabol/issues/6283
Converted using the process described in https://www.notion.so/parabol/How-to-Migrate-createFragmentContainer-useFragment-with-codeshift-d534e7d0b8674089a2075f2835544558 🔒

chore(relay): createFragmentContainer -> useFragment 6/N 

---

.circleci/config.yml

Removes any reference from the CircleCI pipelien to the development environment
Master and other branches (non staging and production) continue working as they should.

chore(pipeline): Remove any reference to dev environment in the CircleCI pipeline

---

package.json
scripts/webpack/prod.servers.config.js
yarn.lock

Removes dependency on a globally available VIPS
- `yarn build --no-deps`
- `rm -rf node_modules`
- `node dist/gqlExecutor & node dist/web`
- in the app, change your profile picture to something fun (it has to be fun 👀 )

chore: add libvips to dist

---

packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
packages/server/graphql/public/typeDefs/Organization.graphql
packages/server/graphql/public/types/OrganizationFeatureFlags.ts

fixes #7789
**how to test**
http://localhost:3000/admin/graphql
```
mutation {
addFeatureFlagToOrg(orgIds: ["PUT ORG ID HERE"], flag: promptToJoinOrg) {
... on AddFeatureFlagToOrgSuccess {
updatedOrganizations {
featureFlags {
promptToJoinOrg
}
}
}
}
}
```

chore(prompt-to-join-org): add promptToJoin feature flag

---

packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx

Fixes #7996 Removes Public/Private dropdown in GraphiQL
https://www.loom.com/share/713bf59ae8dc4fa6b4345baca26904bc

feat: remove private schema dropdown in graphiql

---

CHANGELOG.md
lerna.json
package.json
packages/gql-executor/package.json
packages/server/graphql/rootTypes.ts
packages/server/package.json

fixes missing notification type

hotfix: notification meeting stage time limit end

---

CHANGELOG.md
lerna.json
package.json
packages/client/components/AddTeamMemberModal.tsx
packages/client/package.json
packages/gql-executor/package.json
packages/server/graphql/mutations/inviteToTeam.ts
packages/server/package.json

fix: prevent spam invites

---

packages/client/components/ActivityLibrary/CreateActivityCard.tsx
tailwind.config.js

Fixes an issue where tailwind classes didn't work properly in overriding external library styles. 
No demo

chore: improve tailwind classes specificity

---

packages/client/components/ActivityLibrary/CreateActivityCard.tsx
tailwind.config.js

Reverts #8064 due to broken modals.

chore: remove tailwind selector strategy

---

packages/client/components/ActivityLibrary/ActivityDetails.tsx
packages/client/components/ActivityLibrary/TeamPickerModal.tsx
packages/client/mutations/AddReflectTemplateMutation.ts
packages/client/mutations/handlers/handleAddReflectTemplate.ts
packages/server/graphql/mutations/addReflectTemplate.ts

Fixes https://github.com/ParabolInc/parabol/issues/8024
~Needs rebase once https://github.com/ParabolInc/parabol/pull/8027 lands~
Enable cloning templates from the Activity Library Details view.
**Note to maintainer reviewer:** This slightly relaxes the backend permissions for cloning. Previously, a user could only clone a template if a) it's team-scoped and they're on that team, or b) it's org-scoped and the cloning team is in the org, or c) it's public. This PR changes (b) to only require that the user is in the org. This means templates could be cloned across orgs. Alternatively, we could revert the backend permission changes, and only support cloning within an org.
https://www.loom.com/share/ce0ef593692c42258a3dd2da1152c445

feat(rid): Clone template

---

pm2.dev.config.js

Successor to #8103
Call kysely codegen whenever dev starts

chore: generate kysely schema in dev

---

packages/server/postgres/pg.d.ts

Storing generated files in VC can be troublesome 😆

chore: remove test columns from pg.d

---

packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
packages/server/graphql/public/typeDefs/Organization.graphql
packages/server/graphql/public/types/OrganizationFeatureFlags.ts

Fix https://github.com/ParabolInc/parabol/issues/8122

feat(suggest-groups): Add suggestGroups org feature flag

---

packages/client/components/ActivityLibrary/ActivityLibrary.tsx
packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx

Fixes https://github.com/ParabolInc/parabol/issues/7972
Needs rebase once https://github.com/ParabolInc/parabol/pull/8131 lands
Create new poker template from the create activity view.
https://www.loom.com/share/b5aeefd2a6b14f5e84e801169a88e59a

feat(rid): Create new poker template

---

.circleci/config.yml
package.json
packages/server/postgres/pg.d.ts

Fail CI if source files were modified during the build.
Avoid situations like #8147
Don't add this test step to linting, as devs might want to lint with changes present.
Check previous build results where I intentionally added changes and current build where these are absent.

chore: Verify all checked in generated files are clean

---

packages/client/components/ThreadedCommentHeader.tsx
packages/server/graphql/mutations/deleteComment.ts
packages/server/graphql/mutations/updateCommentContent.ts
packages/server/utils/isDiscussionFromMeeting.ts

Fix https://github.com/ParabolInc/parabol/issues/8096

feat: can edit & delete AI comment

---

.github/workflows/labeler.yml
yarn.lock

I broke the yarn.lock on master.
This should fix it & remove those security flags.

fix: regenerate yarn.lock

---

packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
packages/server/graphql/mutations/setOrgUserRole.ts
packages/server/utils/analytics/analytics.ts
yarn.lock

Fix https://github.com/ParabolInc/parabol/issues/7813
See that we're tracking the following event in Segment:

chore: add checkout flow tracking

---

packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts

Fixes https://github.com/ParabolInc/parabol/issues/7876

feat: Don't show discussion mention toast if already on stage

---

packages/client/components/Dashboard/DashSidebar.tsx
packages/client/components/Dashboard/LeftDashNavItem.tsx
packages/client/components/Dashboard/MobileDashSidebar.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgDetails.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
packages/client/utils/constants.ts

Fix: https://github.com/ParabolInc/parabol/issues/8250

feat(checkout-flow): add org details 

---

packages/server/utils/stripe/StripeManager.ts

Updates the default pricing plan for enterprise upgrades

fix: update the default enterprise plan ID

---

packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
packages/client/mutations/CreateSetupIntentMutation.ts
packages/server/graphql/public/mutations/createSetupIntent.ts
packages/server/graphql/public/typeDefs/createSetupIntent.graphql
packages/server/graphql/public/types/CreateSetupIntentSuccess.ts

Fix https://github.com/ParabolInc/parabol/issues/8316 & fix https://github.com/ParabolInc/parabol/issues/7914
Loom demo: https://www.loom.com/share/120bf2df861d4cf78eef86a015bfbe93

feat(checkout-flow): credit card UI

---

package.json

This PR changes our `yarn clean` script to use `git clean -fdx` under the hood. it makes it more future proof, as it'll remove all the stuff that's generated or ignored by `.gitignore`. long story short, it restores the repo to the fresh clone state, except for keeping the `.env` file.

chore: improve yarn clean script

---

scripts/toolboxSrc/pushToCDN.ts

Updates pushToCDN to use new API call

chore: fix filestore API call

---

CHANGELOG.md
lerna.json
package.json
packages/client/package.json
packages/gql-executor/package.json
packages/integration-tests/package.json
packages/server/package.json
pm2.config.js

bumping to 24GB so i can heapdump without crashing the server.

chore: mem restart limit

---

packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx

feat: text align center for icebreakers

---

packages/client/components/ReviewRequestToJoinOrgModal.tsx

Added missing scroll-y to add teammate dialog
- Trigger prompt to join org,
- Have enough teams/orgs for the scroll to appear

fix(prompt-to-join): add scroll-y to add teammate dialog

---

codegen.json
packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
packages/client/components/ActivityLibrary/ActivityLibrary.tsx
packages/server/database/types/MeetingTemplate.ts
packages/server/dataloader/customLoaderMakers.ts
packages/server/graphql/public/rootSchema.ts
packages/server/graphql/public/typeDefs/MeetingTemplate.graphql
packages/server/graphql/public/typeDefs/User.graphql
packages/server/graphql/public/types/FixedActivity.ts
packages/server/graphql/public/types/MeetingTemplate.ts
packages/server/graphql/public/types/PokerTemplate.ts
packages/server/graphql/public/types/ReflectTemplate.ts
packages/server/graphql/public/types/User.ts
packages/server/postgres/migrations/1685721573097_addPrePostMortemTemplates.ts
packages/server/postgres/migrations/1685721574097_fixed-activities.ts
scripts/webpack/dev.servers.config.js
scripts/webpack/prod.servers.config.js

- Adds FixedActivity in GQL
- Improves sort order of activities

feat: FixedActivity in GQL (Part 4 of 4)

---

packages/server/postgres/README.md

Docs update for clearing PG connections

chore: add sql to kill all pg connections

---

package.json
scripts/toolboxSrc/assignSURole.ts
scripts/webpack/toolbox.config.js
yarn.lock

Add a script to assign the su role to a list of emails.
```
[man@moon parabol]$ node scripts/toolbox/assignSURole.js --removeAll
Removed all []
[man@moon parabol]$ node scripts/toolbox/assignSURole.js --add georg@parabol.co
Added [ { email: 'georg@parabol.co' } ]
[man@moon parabol]$ node scripts/toolbox/assignSURole.js --add georg@parabol.co georg+test1@parabol.co
Added [ { email: 'georg+test1@parabol.co' }, { email: 'georg@parabol.co' } ]
[man@moon parabol]$ node scripts/toolbox/assignSURole.js --removeAll
Removed all [ { email: 'georg+test1@parabol.co' }, { email: 'georg@parabol.co' } ]
[man@moon parabol]$ node scripts/toolbox/assignSURole.js --add georg@parabol.co georg+test1@parabol.co --removeAll
Removed all []
Added [ { email: 'georg+test1@parabol.co' }, { email: 'georg@parabol.co' …
```

chore: Add assignSURole script

---

CHANGELOG.md
lerna.json
packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
packages/client/package.json
packages/gql-executor/package.json
packages/server/package.json

Fixes showing upgrade prompt for activities like standups and checkins
No demo

fix: do not show upgrade prompt for standups and checkins

---

packages/client/utils/AtlassianManager.ts

Reverts ParabolInc/parabol#7897
Removing logs as the issue [seems to be fixed (slack)](https://parabol.slack.com/archives/C4JAUUZ9P/p1687282262013709) 
Fixes #7896

chore: revert add temporary story points update result logging

---

packages/server/graphql/public/mutations/helpers/getIsUserIdApprovedByOrg.ts

fix: improve error message when a user cannot join an org

---

README.md
packages/client/README.md

This PR introduces client `README.md` that includes a Tailwind CSS migration guideline
No demo
No testing scenarios

chore: added Tailwind CSS migration readme

---

packages/client/modules/admin/containers/Graphql/GraphqlContainer.tsx
packages/client/package.json
yarn.lock

Upgrades graphiql. Special request from the sales team.
Notable features:
https://www.loom.com/share/3e05604e486d4ebd8892c44266c6f063

fix: upgrade graphiql

---

packages/server/postgres/migrations/1689031398651_del-team-meetingTemplate.ts

Housekeeping for RethinkDB: removing unused tables

chore: drop unused RethinkDB tables

---

packages/client/components/BottomControlBarTips.tsx
packages/client/components/MeetingHelp/TeamHealthHelpMenu.tsx

Fixes #8453
https://www.loom.com/share/a74a06664a9c4b23a5d4853129f01bdc?sid=aa448ccb-6ef3-4cfd-8348-a2753285bfb3
- to speed up testing different combinations, return a static array [here](https://github.com/ParabolInc/parabol/blob/7add26b505a6e27ccbca67a18e69d9dca6b40255/packages/server/graphql/public/types/TeamHealthStage.ts#L38)

feat: Add Team Health tips

---

packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
packages/client/mutations/AddTeamMutation.ts

Fix https://github.com/ParabolInc/parabol/issues/8511

fix: can create team within existing org

---

packages/client/mutations/EndRetrospectiveMutation.ts

Fix https://github.com/ParabolInc/parabol/issues/8547
I'm requesting to merge this into Staging as I've started the ship, and it would be great to start testing it with users quickly.

chore: update summary url with Suggest Groups

---

packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Fix https://github.com/ParabolInc/parabol/issues/8527
Adds a user feature flag for the gcal integration

feat: add gcal integration user flag

---

packages/server/dataloader/customLoaderMakers.ts
packages/server/graphql/public/types/ReflectTemplate.ts

See https://parabol.slack.com/archives/C836NA350/p1690212940822539
The logic implemented for certain subcategories in https://github.com/ParabolInc/parabol/pull/8413 is pretty slow (especially in production), so refactor the logic a bit to speed it up.
Specifically, instead of fetching a bunch of meetings (which can take on the order of seconds), do a map-reduce to find the last usage time for each `[teamId, templateId]` tuple (which takes on the order of 10s of milliseconds).

fix(al): Speedup subcategory resolver

---

packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
packages/client/utils/constants.ts

Fix https://github.com/ParabolInc/parabol/issues/8572

Update enterprise advantages

---

CHANGELOG.md
lerna.json
package.json
packages/chronos/package.json
packages/gql-executor/package.json
packages/server/graphql/public/types/ReflectTemplate.ts
packages/server/package.json

hotfix for [https://app.datadoghq.com/apm/error-tracking/issue/4ded4ffc-2fcc-11ee-96c5-da7ad09000[…]oduction&from_ts=1690742178742&to_ts=1690828526854&live=true](https://app.datadoghq.com/apm/error-tracking/issue/4ded4ffc-2fcc-11ee-96c5-da7ad0900002?query=env%3Aproduction&from_ts=1690742178742&to_ts=1690828526854&live=true)

fix: activity library reduce

---

.env.example
packages/client/components/MassInvitationTokenLink.tsx
packages/client/types/modules.d.ts
packages/client/utils/getMassInvitationUrl.ts
packages/server/types/modules.d.ts

Make INVITATION_SHORTLINK optional and document it.

chore: Document INVITATION_SHORTLINK environment and make optional

---

packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
packages/client/components/TeamPrompt/TeamPromptWorkDrawerRoot.tsx

Fixes https://github.com/ParabolInc/parabol/issues/8691
Needs rebase once https://github.com/ParabolInc/parabol/pull/8690 lands - only commits from 2f68d7f48d59c13cb8f6dc6d2e93399c50c7e310 onward need review in this PR.
https://www.loom.com/share/c6fa5fd7a6ce4a92b87d2933c10744d3?sid=2f9ad449-227d-4e5a-85b9-b8380b67b86f

feat(standups): "Add task" button in Parabol task drawer

---

codegen.json
packages/server/graphql/public/types/TeamPromptQuestion.ts

patch: team prompt q

---

scripts/webpack/prod.servers.config.js

Fixes an issue for pubsec where the error gets truncated because the callstack is too long.
CI dockerize should work!

chore: no minify server

---

packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
packages/server/__tests__/inviteToTeam.test.ts

Fix https://github.com/ParabolInc/parabol/issues/8773
Demo: https://www.loom.com/share/6cbec0355c054008bf4ef9170cd64565?sid=70440557-d590-4921-a07f-5787dd875fd7

feat: scroll to card section

---

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheetCTA.tsx

Fix https://github.com/ParabolInc/parabol/issues/8777

feat: download summary as pdf

---

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
packages/server/utils/analytics/analytics.ts

Fix https://github.com/ParabolInc/parabol/issues/8853

chore: track download to pdf

---

packages/server/graphql/getDataLoader.ts

Avoid repeating the same mistake again, see #8839

chore: Add warning to getDataLoader

---

packages/client/components/Dashboard/DashSidebar.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/MeetingSummaryEmail.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheetCTA.tsx
packages/client/modules/summary/components/NewMeetingSummary.tsx
packages/client/modules/summary/components/NewMeetingSummaryRoot.tsx

Fix https://github.com/ParabolInc/parabol/issues/8749
Demo: https://www.loom.com/share/cc327831b7614612b08c50acc2059cf7

feat: show sidebar by meeting summary

---

pm2.config.js

Adds one more web server in production (already applied to Staging).

chore(dokku): add one more web server

---

packages/client/components/promptResponse/PromptResponseEditor.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummary.tsx
packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx

Fixes #8784 #8664 
In addition to fixing the links wrap, this PR also fixes styles (for example list item paddings etc).

fix: loom links wrap, changed layout to single column

---

CHANGELOG.md
lerna.json
package.json
packages/chronos/package.json
packages/client/package.json
packages/gql-executor/package.json
packages/server/graphql/public/mutations/loginWithGoogle.ts
packages/server/graphql/queries/SAMLIdP.ts
packages/server/graphql/queries/verifiedInvitation.ts
packages/server/package.json
packages/server/utils/getSAMLURLFromEmail.ts

Undocumented bug where logging in with SAML does not retrieve the SAML record from PG.
Merging to staging because I'm about to release to prod right now

fix: read SAML from PG

---

packages/client/components/DiscussionThreadListEmptyState.tsx

fix #8922
How to test:
- See that in check-in, retro and other meeting types the panel works as expected
- See that zoom functionality still works as expected

fix: fix check-in discussion panel layout

---

packages/server/graphql/private/mutations/loginSAML.ts

Some errors are expected and can be traced from the error message. If there are unexpected errors, i.e. without a custom error message, we should log these to Sentry to simplify debugging.

chore: Log unexpected SAML errors to sentry

---

packages/server/utils/RecallAIServerManager.ts

The transcription bot is working locally but not in prod. This PR logs the error to Sentry to help with debugging.

chore: log recall error

---

packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationPanel.tsx
packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResultsRoot.tsx
packages/client/components/TeamPrompt/WorkDrawer/JiraObjectCard.tsx
packages/client/utils/AtlassianManager.ts
packages/server/graphql/public/typeDefs/JiraIssue.graphql
packages/server/graphql/public/types/JiraIssue.ts

Fixes https://github.com/ParabolInc/parabol/issues/8900
Implement the Jira integration for Your Work.
Note that this does _not_ include pagination - the panel will load up to 20 issues, but not more. Pagination will be implemented in a separate follow-up PR, as the behavior + API of the Jira `issues` GQL resolver needs to be modified to correctly support pagination in this panel, which could cause regressions in Sprint Poker.
https://www.loom.com/share/7c49530e24794d6fa16232bd97cfa2a3?sid=faeaf396-5f36-4934-8baf-8f51d8069581

feat(your-work): Jira Integration

---

packages/client/serviceWorker/sw.ts

Fixes #8868 
We don't know whether an opaque response was a success, so if we're serving the response from cache indefinetely, we might serve broken versions till the next update. To avoid this, only serve opaque responses if the network request threw an exception. Right now, dynamic images are not cached by the service worker this way, but the browser should do caching, too. Right now it's not possible to request these with CORS.
https://www.loom.com/share/f31954e624e341e99b79e36f8aa6d489?sid=af998b75-4646-411e-abb1-fb00665ab217
- run ` yarn build && yarn predeploy && yarn start`
- everything still works

fix: Do not serve cached opaque responses if possible

---

packages/server/postgres/migrations/1697477646986_swot-typo.ts

typo fix. just doing it here so it goes out to the PPMIs. already fixed in cloud

fix: SWOT typo

---

packages/server/listenHandler.ts

Re-add server health checker since we determined it is not the root cause of the downtime.

fix: server health checker

---

packages/client/Atmosphere.ts
packages/server/listenHandler.ts
release-please-config.json

merge release to master

---

packages/client/hooks/useServiceWorkerUpdater.ts

We're not using the production branch anymore

fix: Link to correct CHANGELOG

---

.env.example
packages/server/database/types/Organization.ts
packages/server/database/types/User.ts
packages/server/graphql/mutations/helpers/createNewOrg.ts
packages/server/graphql/public/mutations/loginWithGoogle.ts
packages/server/utils/createNewLocalUser.ts
packages/server/utils/defaultTier.ts
scripts/toolboxSrc/setIsEnterprise.ts

See #9049
Fix for PPMIs who pay for enterprise so if they stray from their single org they still get enterprise features
hangelog

feat: enterprise-patch

---

release-please-config.json

fixes the PR title so release-please triggers a release

fix: PR title

---

packages/server/postgres/migrations/1698831891828_moreFreeRetroTemplates.ts

Fixes #8974
Make a bunch of templates free.

feat: More templates are free now

---

packages/server/dataloader/__tests__/getVerifiedOrgIds.test.ts
packages/server/dataloader/__tests__/isOrgVerified.test.ts
packages/server/dataloader/customLoaderMakers.ts

chore: Add getVerifiedOrgIds tests

---

.github/workflows/ironbank.yml

chore: ironbank github action, update permissions, add proper cp path

chore: ironbank github action, update permissions, add proper cp path

---

.github/workflows/build.yml

github-action bot doesn't trigger the build workflow 😠

fix: maybe a pull_request can be bot triggered

---

.github/workflows/build.yml
.github/workflows/release-please.yml

uses a PAT so the release-please bot can trigger another workflow

fix: use PAT for release-please

---

.github/workflows/build.yml
.github/workflows/release-please.yml

fix: remove predeploy step in CI

---

.github/workflows/build.yml
.github/workflows/test.yml

- 8 cores is definitely faster than 2 or 4!
- this cancels running jobs when a newer job gets started
- reduces curl retry interval to 2 seconds (saves ~8 seconds that way)
- groups env vars together

chore: cancel previous in-progress workflows

---

.github/workflows/release.yml

release should work based on the head branch name, not the base branch name, as previously defined

fix: target PR head instead of base

---

.github/reviewers.yml
.github/workflows/release.yml

removes the reviewer action when release-please opens a PR

fix: ignore reviewer on release

---

.github/workflows/release.yml

fix: release, remove glob

---

.github/workflows/release.yml

fix: add version back in

---

.github/workflows/release.yml

Prevent gcloud from asking "Are you sure"?

fix: add quiet flag to gcloud

---

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts

Fix https://github.com/ParabolInc/parabol/issues/9188

fix: can auto join with saml login

---

docker/parabol-ubi/docker-build/dockerfiles/parabol.dockerfile
docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile

fix: release please build add systemtap

fix: release please build add systemtap

---

.github/workflows/release-to-staging.yml
.vscode/settings.json

Debugging the release-to-staging script...
also vscode keeps updating the settings.json, so allowing that here.

fix: release-to-staging debug

---

.github/workflows/release-to-staging.yml

fix: release-to-staging debugging 2

---

packages/server/__tests__/autoJoin.test.ts

The test fails randomly, supposedly because the underlying issue is not completely fixed yet. This should be fixed in #9302, until then let's unblock CI.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: disable autoJoin test

---

packages/client/components/EmailNotifications.tsx

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Change email summary setting copy to be clearer

---

.env.example

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: document SOCKET_PORT environment

---

.github/workflows/release-to-staging.yml

fix: add pr write permission to CI

---

.github/workflows/release-to-staging.yml

perhaps jobs are unplayable for more than a minute? debugging...

fix: longer timeout for unplayable job

---

packages/server/graphql/mutations/endRetrospective.ts
packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
packages/server/graphql/public/mutations/startRetrospective.ts
packages/server/graphql/public/typeDefs/_legacy.graphql
packages/server/graphql/public/typeDefs/startRetrospective.graphql

Only refactored part of the functionality into different functions to call them later in `processRecurrence`
- smoke test starting and ending a retro

chore: prepare start and endRetrospective for recurrence

---

packages/client/modules/demo/initDB.ts

how to test:
- run demo till the end
- see summary appears without error

fix: fix broken demo summary

---

.github/workflows/debug.yml

fix: create release branch as head 2

---

.github/workflows/release-to-staging.yml

contents: write is required for pushing a branch to origin

fix: contents: write for gh actions

---

.vscode/extensions.json

updates suggested vscode extensions

fix: add suggested vscode extensions

---

.github/workflows/ironbank.yml

Updates deprecated GH action dependencies for the Ironbank workflow
N/A

chore: update Ironbank GH action dependencies

---

docker/Dockerfile.prod
docker/parabol-ubi/docker-build/README.md
package.json

chore: bump node to v20.11.0

---

.github/workflows/release-to-staging.yml

currently pushes to prod have to be force pushed, but i want to use the UI to push to prod.
this should solve for that, i hope?

chore: no force-push to prod

---

.github/workflows/release-to-staging.yml

fix: merge production to avoid force push

---

.github/workflows/release-to-staging.yml

fix: checkout prod before merging it

---

.github/workflows/release-to-staging.yml

fix: mrege origin/production strategy

---

.github/workflows/release-to-staging.yml

fix: force push 5

---

.github/workflows/ironbank.yml

Adds stage to Ironbank action to upload assets to GCS
N/A
If action is successful, configuration is validated

chore: add upload to GCS step in ironbank

---

docker/parabol-ubi/docker-build/dockerfiles/basic.dockerfile

Fixes the home folder of the docker image

fix(docker-build): home folder is /home/node now

---

packages/server/graphql/private/mutations/loginSAML.ts
packages/server/utils/getSAMLURLFromEmail.ts

fixes saml logins from any domain in a single tenant instance that only supports saml

fix: support single-tenant saml record

---

.github/reviewers.yml

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Update reviewers

---

packages/server/package.json
yarn.lock

snyk did me dirty. can't upgrade to v0.33 yet until we handle prebuilt binaries

fix: revert sharp

---

packages/client/components/ActivityLibrary/ActivityLibrary.tsx
packages/client/components/ActivityLibrary/Categories.ts
packages/client/components/ActivityLibrary/CreateActivityCard.tsx

Sort 
https://www.loom.com/share/e0930f718a774cceac08b98f2ccba26a?sid=f71a363f-5da1-4cc4-93ea-3ca97ea2c7ad
- check all categories, especially "Quick Start" and "Retrospective"
- "Custom" with no custom templates
- custom templates on different teams
- search
- AI search

feat: Add team sections to the Custom category in activity library

---

packages/client/modules/demo/DemoUser.ts
packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/types/UserFlagEnum.ts

Partially Fixes #9408 
Remove the feature flag and make it available for everyone.

feat: Release MS Teams integration

---

.github/workflows/migration-order.yml

We're not always targeting master.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: use base ref for migrition order check

---

packages/server/graphql/queries/team.ts

Fixes #9559 
- [Promote yourself to ORG_ADMIN](https://www.notion.so/parabol/How-to-Set-or-Remove-Org-Admin-Role-5eadb324114e40a88ae02ea7989448b7?pvs=4#906adc73b55c4747b853237a97dcf7cd)
- **Remove your super user role from your local PG**
- Go to an org teams page
- Click into a team you are _not_ in
- You can see the team members and perform operations

fix(admin): fix an issue where ORG_ADMIN cannot see members from team they are not in

---

.github/reviewers.yml

DevOps review when there are changes on:
- `docker` folder.
- `release-please-config.json`.

chore(github): DevOps review if docker folder is modified or release-please-config is changed

---

packages/server/email/teamInviteEmailCreator.tsx

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: type error in invite email

---

packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
packages/server/graphql/public/typeDefs/Organization.graphql
packages/server/graphql/public/types/OrganizationFeatureFlags.ts

Remove the feature flag and make it available to everyone.
- Step 1
- Step 2...
- Step 1
- Step 2....

feat: release recurring retros

---

packages/client/modules/userDashboard/components/OrgBilling/OrgDetails.tsx

quick style fix found after the avatar refactor

fix: margin spacing on hover

---

.github/workflows/ironbank.yml

Fixes the failing ironbank GH action
N/A
N/A
- [X ] I checked the [code review guidelines](../docs/codeReview.md)
- [ X] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [X ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [X ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [X ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [ X] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does not contain any architectural changes or does not introduce any new …

chore: fix ironbank action file copy

---

scripts/webpack/dev.client.config.js

https://github.com/webpack/webpack-dev-server/blob/master/migration-v5.md
Without this, the dev server would not start up.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Migrate webpack dev server settings to v5

---

.github/workflows/ironbank.yml

Updates Ironbank GH action, adds ip-to-server script to zip file
N/A
If GH action completes successfully, it's working.
- [X ] I checked the [code review guidelines](../docs/codeReview.md)
- [X ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [ X] I have performed a self-review of my code, the same way I'd do it for any other team member
- [ X] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [ X] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [X ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20Review if the PR introduces only minor changes, does …

chore: add ip-to-server script dir to zip file

---

packages/server/postgres/migrations/1712075131388_retroReflectionGroups2.ts

Supports junky rethinkdb data 🙃 
we can fix up the schema after we're completely off of rethinkdb.

fix: change retro group schema to allow for rethinkdb table migration

---

packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
packages/client/utils/useTemplateDescription.ts
packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
packages/server/graphql/mutations/selectTemplate.ts
packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
packages/server/graphql/public/types/UserFeatureFlags.ts
packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
packages/server/graphql/types/UserFlagEnum.ts

Fixes #9523 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: remove noTemplateLimit flag

---

docker/images/parabol-ubi/dockerfiles/basic.dockerfile
packages/server/graphql/private/mutations/helpers/generateIdenticon.ts

to paint an svg to canvas we need a font on the server, so this should install plex.

fix: install plex on system

---

packages/server/graphql/private/mutations/processRecurrence.ts

Relates to #9722 
The mutation is slow and we don't know where it spends its time.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Add some processRecurrence tracing

---

.gitignore
docker/images/parabol-ubi/README.md
docker/stacks/single-tenant-host/README.md
docker/stacks/single-tenant-host/docker-compose.yml

Adds the Embedder and the Text Embeddings Inference to the Docker Compose stack. Each one with its own profile (embedder and text-embeddings).

feat(single-tenant-host): Embedder and Text Embeddings Inference added to the stack

---

packages/server/graphql/private/mutations/processRecurrence.ts

There is a 5s gap in the [traces ](https://app.datadoghq.com/apm/trace/811555692883192912?colorBy=service&env=production&graphType=flamegraph&shouldShowLegend=true&sort=time&spanID=811555692883192912&spanViewType=metrics&timeHint=1715789100103.002&view=spans) 🔒 from fetching all the meeting series' last meetings and starting the new ones. In this time we only do some RRule parsing and calculations. Let's trace these.
[If possible, please include a screenshot or gif/video, it'll make it easier for reviewers to understand the scope of the changes and how the change is supposed to work. If you're introducing something new or changing the existing patterns, please share a Loom and explain …

chore: Trace RRule

---

packages/server/package.json
yarn.lock

This reverts commit 5cbca8dfc11e27f5550a3a23bccd590ce5481bd4.
The updated version does not work in our predeploy.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Revert @aws-sdk/client-s3 upgrade

---

packages/client/components/DashNavList/DashNavList.tsx
packages/client/components/DashNavList/DashNavListTeams.tsx
packages/client/components/Dashboard/DashSidebar.tsx
packages/client/components/Dashboard/MobileDashSidebar.tsx
packages/client/components/SideBarStartMeetingButton.tsx
packages/client/modules/userDashboard/components/GcalModal/VideoConferencing.tsx
packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx

- Refines alignment of nav items
- Refines border, text styles etc.
- Removes ‘Organizations’ nav item from mobile
- Updates the icon for Sign Out on mobile

feat: new nav styles refinement

---

packages/server/postgres/migrations/1718014858965_updateEmbeddingOnMeetingTemplateUpdate.ts

The trigger was only installed on update, but needs to run on insert as well. Because we did not have a release yet, I decided to simplify the change by modifying the last migration.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Update MeetingTemplate embeddings on insert

---

packages/embedder/indexing/meetingTemplate.ts

The description is often undefined.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Avoid undefined in embeddings for Poker scales

---

packages/embedder/indexing/createEmbeddingTextFrom.ts
packages/embedder/workflows/embedMetadata.ts

Previously we would only update the full text if it was empty, now we're doing it if the reference object is newer than the metadata
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Update fullText when embedding is older than reference

---

packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx

Loom demo: https://www.loom.com/share/80483015ef354adbad79cbc467d9a39d

fix: update promote team member copy

---

packages/server/graphql/mutations/helpers/updateReflectionLocation/updateSmartGroupTitle.ts

Fixes #9833
In SQL null !== null. i knew this, yet i still messed up... 😞

fix: handle sql null equalities

---

packages/server/graphql/types/User.ts

Found a bug in staging where the timeline goes the wrong way

fix: timeline ordering

---

packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
packages/client/modules/userDashboard/components/OrgBilling/PaymentDetails.tsx
packages/client/mutations/AddOrgMutation.ts
packages/client/mutations/DowngradeToStarterMutation.ts
packages/client/mutations/fragments/CompleteOrganizationFrag.ts
packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
packages/client/package.json
yarn.lock

Fixes 4 bugs:
- When upgrading, clicking "Select" Team now focuses on the card number field
- the card number field no longer has the "autofill with Link" ad
- upgrading shows the invoices/credit card info without having to refresh
- downgrading no longer requires a refresh to get the right view
https://www.loom.com/share/f1ef71b40df142c4a04d23575112618f?sid=7667d5a9-c1bd-4b7f-838e-c7eaeabc9365## Testing scenarios

fix: bugs during upgrade/downgrade

---

packages/server/fileStorage/S3FileStoreManager.ts

Fixes #9911 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Fix debug output when retrying after Cloudflare error

---

packages/server/dataloader/customLoaderMakers.ts

fix SAML records return from dataloader

fix: SAML return values from dataloader

---

packages/server/postgres/migrations/1721348544381_QueryMapOneShot.ts

forgot to check for an empty DB

chore: fix broken build mig file

---

packages/server/graphql/mutations/helpers/bootstrapNewUser.ts

Fixes #10085 
For non-organic autojoin users we would add the suggested actions once per team.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Do not add suggested actions multiple times for autojoin

---

packages/server/graphql/executeGraphQL.ts
packages/server/graphql/handleGraphQLTrebuchetRequest.ts
packages/server/graphql/public/mutations/startCheckIn.ts
packages/server/utils/sendToSentry.ts

handle empty array for Agenda Item

fix: handle empty array to PG. fixup error handling

---

packages/server/graphql/mutations/addAgendaItem.ts

fix: add missing ID

---

packages/server/utils/OpenAIServerManager.ts

Upgrade the open ai models for suggest groups

feat: upgrade suggest groups openai models

---

packages/server/graphql/public/mutations/addComment.ts

Fixes #10205 
The value of isAnonymous was not written to the DB anymore after #10166 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Anonymous comments

---

packages/server/__tests__/processRecurrence.test.ts

Run all tests with the same user. This saves several roundtrips and significantly speeds up this test.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Speed up processRecurrence test

---

packages/server/postgres/migrations/1726174443131_dropThreadParentId.ts

fix: add quotes to constraint

---

packages/client/modules/teamDashboard/components/TeamDashInsightsTab/TeamInsights.tsx

Minor styling changes for Team Insight sheet container

feat: team insights skeleton, minor style nits

---

packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
packages/server/graphql/public/types/MeetingSeries.ts

Found 2 bugs in the logs, this fixes them.

fix: endTeamPrompt bugs

---

.github/workflows/synk-yarn-lock-commit.yml

Updates deprecated actions used within workflow to v4 - node20
N/A
Action runs without deprecation warnings

chore: update snyk workflow to use node20

---

packages/embedder/package.json
packages/gql-executor/package.json
packages/server/package.json
yarn.lock

Fixes https://security.snyk.io/vuln/SNYK-JS-JSONPATHPLUS-7945884

fix(dd-trace): upgrade to v5.0.0

---

.github/workflows/release-to-staging.yml

PRs that deploy to production will have now as title `chore(release): Test and deploy to Production vA.B.C` instead of `chore(release): Test vA.B.C`

chore(deployment): PR title for the PR that deploys to production states its purpose

---

packages/server/graphql/mutations/helpers/importTasksForPoker.ts

fixes empty array problem in PG

fix: shortcircuit looking up tasks my integrationHash

---

packages/server/graphql/mutations/helpers/publishChangeNotifications.ts

this bug came in on sentry. duplicate pkey.  i can't make sense of what it's doing here, but the logic is from 6 years ago. I think it's back when a notification had the task on it instead of a taskId.

fix: no duplicate notification inserts

---

packages/server/graphql/public/mutations/generateInsight.ts

Super users should be able to generate insights for any team

chore: super user can generate insight

---

.config/kysely.config.ts
.config/kyselyMigrations.ts
scripts/toolboxSrc/standaloneMigrations.ts

this only affects the prod bundle, which isn't caught by standard CI tests 😢

chore: remove kysely-ctl from prod bundle

---

scripts/webpack/utils/transformRules.js

fix: apply imports transform

---

packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx

Fix https://github.com/ParabolInc/parabol/issues/10244

feat: show insights by default

---

packages/server/integrations/mattermost/mattermostWebhookHandler.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Cleanup Mattermost API

---

packages/server/package.json
yarn.lock

The updated version does not work with --no-deps
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Fix GraphQL-JIT version

---

.github/workflows/docker-external.yml

Adds logic to provide Docker images to self-hosted paying clients

chore: add a workflow to push to a docker repository to share with external clients

---

packages/server/graphql/public/mutations/generateInsight.ts
packages/server/graphql/public/permissions.ts
packages/server/graphql/public/rules/isViewerTeamLead.ts

This PR enables team leads to use the generate insight mutation

fix: update generate insight permissions

---

packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
packages/client/modules/userDashboard/components/OrgBilling/OrgFeatures.tsx

Tests are failing because React is being imported and not used

fix: remove react imports

---

packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx

This PR releases the share summary feature to all users

chore: release shareSummary

---

.github/workflows/migration-order.yml

chore: migrations renamed or deleted fail on migration-order GH action

---

packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx

Sometimes discussionThreads are of type Task, i forgot that 🙈 .

fix: parse draft discussions for csv

---

packages/client/components/DiscussionThreadInput.tsx
packages/client/components/ThreadedCommentBase.tsx

fix: add useEventCallback on keyboard shortcuts

---

packages/client/components/DiscussionThreadInput.tsx
packages/client/hooks/useTipTapCommentEditor.ts
packages/client/mutations/UpdateTaskMutation.ts
packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts

Bugs fixed:
- input stays focused when switching between discussions
- padding on add a task footer
- bullet points fixed for related discussions
- flickering task cards when task gets updated

fix: Discussion bugs

---

packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
packages/mattermost-plugin/components/CreateTaskModal/index.tsx
packages/mattermost-plugin/components/ModalRoot.tsx
packages/mattermost-plugin/components/Select.tsx
packages/mattermost-plugin/components/SimpleSelect.tsx
packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
packages/mattermost-plugin/index.tsx
packages/mattermost-plugin/public/mattermost-plugin-commands.json
packages/mattermost-plugin/reducers.ts
packages/mattermost-plugin/selectors.ts

Fixes #10573 
For now only plaintext is generated
- Step 1
- Step 2...
- Step 1
- Step 2....

feat: Create task from Mattermost plugin

---

packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
packages/mattermost-plugin/components/InviteToTeamModal/index.tsx
packages/mattermost-plugin/components/InviteToTeamModal/useMassInvitationToken.tsx
packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
packages/mattermost-plugin/components/Modal.tsx
packages/mattermost-plugin/components/ModalRoot.tsx
packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
packages/mattermost-plugin/index.tsx
packages/mattermost-plugin/public/mattermost-plugin-commands.json
packages/mattermost-plugin/reducers.ts
packages/mattermost-plugin/selectors.ts
packages/mattermost-plugin/utils/mutationResult.ts

Fixes #10570 
- Step 1
- Step 2...
- Step 1
- Step 2....

feat(Mattermost): Add invite team slash command

---

packages/server/dataloader/integrationAuthLoaders.ts

This check was accidentally removed in #10426
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Check if integration was removed

---

packages/mattermost-plugin/package.json
release-please-config.json

Fixes #10656 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Update mattermost-plugin version on release

---

devTemplate.html
packages/client/components/AuthenticationPage.tsx
packages/client/components/GenericAuthentication.tsx
packages/client/components/InvitationLinkDialog.tsx
packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
scripts/webpack/prod.client.config.js
template.html

Closes #9407
- Note and proofread new meta
- Note and proofread new meta
- Note and proofread new meta
- Note and proofread new meta

feat: modified/added meta tags with new content

---

.vscode/settings.json
packages/client/components/DashNavList/DashNavList.tsx
packages/server/graphql/public/types/User.ts

fix: consolidate organizations sorting logic

---

packages/client/utils/makeCheckinGreeting.ts

Adds two new languages for the greetings and a new icebreaker

feat(greetings): add Finnish and Basque greetings and a new icebreaker

---

packages/client/components/StageTimerModalEndTimeSlackToggle.tsx

Fixes #10719 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Check events is not null in stage timer modal

---

packages/server/graphql/private/mutations/changeEmailDomain.ts

fixes the edge case where a user created a new account with their new domain & we try to change the domain of the email of their old user account.
it doesn't merge accounts, it just alerts that there were no changes made instead of returning a cryptic error from PG

fix: support edge case changeEmailDomain no users to update

---

packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx

Adds the invoices panel for Enterprise users

fix: show invoices for enterprise customers

---

packages/client/mutations/UpdatePokerScopeMutation.ts

fixes #10518
speeds up updatePokerScope by A TON if they have a jira integration

fix: speed up updatePokerScope

---

packages/client/components/DiscussionThreadInput.tsx
packages/client/components/promptResponse/TipTapEditor.tsx
packages/client/hooks/useTipTapTypingStatus.ts
packages/client/mutations/EditCommentingMutation.ts

fix: tiptap bugs

---

packages/server/graphql/public/fields/invoices.ts

fixes #10764 hides voided invoices in the app.

fix: hide deleted and voided invoices

---

packages/client/components/SendCommentButton.tsx
packages/client/components/promptResponse/TipTapEditor.tsx

reverts changes made to fix #10732.
also fixes width of submit button shrinking on large text.

fix: line breaks in reflections

---

packages/client/components/DiscussionThreadInput.tsx

max-h was unconstrained so it got hard to submit very long comments, so fixed that too

fix: overflow-auto for comment input add max-h

---

packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
packages/client/components/EmojiDropdown.tsx
packages/client/components/MentionDropdown.tsx
packages/client/components/TaskTagDropdown.tsx
packages/client/styles/theme/global.css

Fixes menu animations and font loading for tailwinds v4

fix: tailwind v4 fonts and animations

---

packages/client/components/ReflectionGroup/RemoteReflection.tsx

Fixes #10804 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Hook error during grouping reflections

---

packages/client/components/ThreadedCommentFooter.tsx

Fixes #10803
This can be very distracting when trying to read comments in an active discussion.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Don't scroll discussions on new reactjis

---

scripts/webpack/dev.servers.config.js

fix: app version on dev server

---

packages/server/createSSR.ts
packages/server/graphql/public/mutations/helpers/getTopics.ts
packages/server/utils/OpenAIServerManager.ts

Removes action.parabol.co references in the application code

fix: remove hardcoded action.parabol.co from the application code

---

packages/client/mutations/AutogroupMutation.ts
packages/client/mutations/EndDraggingReflectionMutation.ts
packages/server/graphql/ResponseStream.ts
packages/server/graphql/handleGraphQLTrebuchetRequest.ts
packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts
packages/server/utils/publishInternalGQL.ts

fixes a couple bugs found in the dd logs. still unable to pinpoint why we're seeing timeouts during deploys.

fix: no smart title, log socket server id

---

package.json
packages/client/Atmosphere.ts
packages/server/fileStorage/FileStoreManager.ts
packages/server/fileStorage/GCSManager.ts
packages/server/graphql/private/mutations/helpers/generateIdenticon.ts
packages/server/pipeStreamOverResponse.ts
yarn.lock

bumps to the latest version of typescript

chore: bump typescript

---

packages/server/graphql/private/mutations/disconnectSocket.ts

this bug keeps popping up on staging & I'm not sure why. Here's the first step to debug

fix: log userId on missing user disconnect

---

packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
packages/mattermost-plugin/hooks/useInviteToMeeting.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

fix(Mattermost Plugin): Update Parabol URLs

---

.github/workflows/ironbank.yml

Changes the Iron Bank target GCS bucket to the new one in tooling
N/A
If the job succeeds it works

chore: update target GCS bucket for IB action

---

packages/client/components/promptResponse/StandardBubbleMenu.tsx

Fixes #8471 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Failed to execute `removeChild`

---

packages/client/hooks/useTipTapPageEditor.ts

fix: in prod connect ws to /hocuspocus to get forwarded

---

packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
packages/server/graphql/mutations/helpers/updateReflectionLocation/removeReflectionFromGroup.ts

Fix https://github.com/ParabolInc/parabol/issues/10922
Demo: https://www.loom.com/share/872b25487ab74321bc4ed75bbfc54284

fix: no ai title for custom groups

---

packages/mattermost-plugin/Atmosphere.ts
packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx

Fixes #10915
Subscriptions need a bit more work, till it's ready just poll.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore(Mattermost Plugin): Poll active meetings

---

packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore(Mattermost Plugin): Update notify API

---

packages/client/components/Tabs/Tabs.tsx
packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
packages/mattermost-plugin/components/Sidepanel/index.tsx

- Step 1
- Step 2...
- Step 1
- Step 2....

chore(Mattermost Plugin): Sidepanel styling

---

packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
packages/mattermost-plugin/components/LinkTeamModal/LinkTeamModal.tsx
packages/mattermost-plugin/components/LoadingSpinner.tsx
packages/mattermost-plugin/components/Modal.tsx
packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
packages/mattermost-plugin/hooks/useLinkTeam.ts
packages/mattermost-plugin/hooks/useStartMeeting.ts
packages/mattermost-plugin/hooks/useUnlinkTeam.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore(Mattermost Plugin): Error and loading states

---

packages/server/graphql/public/mutations/helpers/__tests__/getIsEmailApprovedByOrg.test.ts
packages/server/graphql/public/mutations/helpers/getIsEmailApprovedByOrg.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: getIsEmailApprovedByOrg was overly permissive

---

.github/workflows/build.yml
.github/workflows/test.yml
docker/stacks/development/docker-compose.yml
docker/stacks/single-tenant-host/docker-compose.yml

Upgrades pgvector to the version used in production

chore(postgresql): upgrade pgvector to 0.8.0

---

packages/server/graphql/private/mutations/loginSAML.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Add logging for SAML login errors

---

packages/server/graphql/private/mutations/loginSAML.ts

The body gets truncated
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Log attributes if the emails don't match

---

packages/client/modules/pages/Page.tsx
packages/client/styles/theme/global.css
packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx

global css files are hard. how did we do it for so long??!

fix: placeholder regression in tiptap

---

packages/client/styles/theme/global.css

fix: link css

---

packages/server/postgres/migrations/2025-03-12T18:37:30.953Z_remove-entities.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Syntax error in down migration

---

packages/server/graphql/public/types/Organization.ts

Fix https://github.com/ParabolInc/parabol/issues/10995

feat: sort public teams dialog

---

packages/gql-executor/RedisStream.ts

a failover happens when redis replicas are scaled down to 0 and then scaled back up. This is different than just killing a redis container & then restarting it.
We know each service reconnects to redis successfully because the redis errors in the consoles go away. We also know messages are getting adding to the gqlStream from the socketServer. However, the gqlExecutor is not consuming the messages added to the stream. This leads me to believe that the stream consumption is breaking and not restarting.

fix: GQL retries consuming the stream on failover

---

packages/client/modules/demo/ClientGraphQLServer.ts
packages/client/modules/demo/initDB.ts

Fix: https://github.com/ParabolInc/parabol/issues/11003

feat: add gitlab to demo

---

.github/workflows/test.yml
.husky/post-checkout

Fixing issues discovered while living with it.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Fixes for down migration checks

---

packages/server/graphql/public/types/Company.ts

Fixes company query so super user can view all companies

chore: company query allows super user to query all companies

---

packages/client/components/NewMeetingCheckIn.tsx

This just restores the previous behaviour.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Undefined TeamMember in NewMeetingCheckIn

---

packages/client/utils/constants.ts

Fix https://github.com/ParabolInc/parabol/issues/11036

chore: add private teams to team benefits

---

packages/server/graphql/private/mutations/loginSAML.ts

Fixes #9375
https://www.loom.com/share/95846615cf38426c827fc866953317aa?sid=044f6395-8759-4746-ad48-624e033c2fbe
- setup SAML
- sign in with new User
- be on the org

feat: Join your organization when signing up with SAML

---

packages/client/components/AddTeamDialog.tsx
packages/client/components/AddTeamDialogRoot.tsx
packages/client/components/DashNavList/DashNavList.tsx
packages/client/components/DashNavList/DashNavListTeams.tsx
packages/client/components/DashNavList/EmptyTeams.tsx
packages/client/components/DashNavList/PublicTeamsModal.tsx
packages/client/components/EmailPasswordAuthForm.tsx
packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
packages/client/mutations/LoginWithGoogleMutation.ts
packages/client/mutations/LoginWithMicrosoftMutation.ts
packages/client/mutations/LoginWithPasswordMutation.ts
packages/client/mutations/SignUpWithPasswordMutation.ts
packages/client/mutations/VerifyEmailMutation.ts
packages/client/schemaExtensions/clientSchema.graphql
packages/client/utils/handleSuccessfulLogin.ts

Fixes #11068 
- Step 1
- Step 2...
- Step 1
- Step 2....

feat: Add actions to the empty team experience

---

packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx

feat(orgAdmin): org admin can invite people right in the org team view

---

packages/client/utils/tiptapMentionConfig.ts

fix #11052
there was a regression in #11026 
https://github.com/ParabolInc/parabol/pull/11026/files#diff-25a757884e60d1a79bb75fe8063bd54f83836ef5b7de81872cfa4a649b5f29f0

fix: tiptap mentions

---

packages/server/graphql/public/mutations/createPage.ts
packages/server/graphql/public/mutations/generateInsight.ts
packages/server/graphql/public/mutations/toggleTeamPrivacy.ts
packages/server/utils/analytics/analytics.ts

Add metrics for some of the newly created mutations

chore: add metrics for page creation, insight generation, and team privacy changes

---

packages/server/graphql/getDataLoader.ts
packages/server/utils/publish.ts

found just a little memory leak on staging, this should fix it

fix: dataloaders in redis bugfix

---

packages/client/Atmosphere.ts
packages/client/mutations/SetAppLocationMutation.ts

couple bugs found in prod logs

fix: set app location on ws conn

---

.github/workflows/build.yml
scripts/webpack/prod.servers.config.js

pushes webserver sourcemaps to datadog
we could probably get away with just pushing the web sourcemaps...

fix: #11107 push server sourcemaps to dd

---

.github/workflows/build.yml

fix: use abs path

---

packages/server/server.ts

now that we can count the number of connected clients we can disconnect x clients per second deterministically, which means we can close faster if we say close at least 5 per second.

fix: sigterm faster

---

packages/server/graphql/mutations/helpers/publishChangeNotifications.ts
packages/server/graphql/public/mutations/acceptTeamInvitation.ts

fix #11166 
fix #11167
found these bugs in the datadog logs, so this makes #11166 fail gracefully and #11167 had 2 possible culprits, so I addressed both without knowing which one caused it since it's likely race condition related

fix: bugs from datadog logs updateTask, acceptTeamInvitation

---

docs/serviceDiagram.md

Fixes #11164 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Update service diagram

---

packages/server/chronos.ts

chronos election needs its own namespace

fix: chronos primary lock

---

packages/client/utils/createWSClient.ts

when we switched to graphql-yoga, we used native ping/pong handling, which is great for keeping a socket alive, but we can't do anything with it.
this adds app-level keep alive. now if the server dies, the client will try to reconnect & get a new server.

fix: terminate client WS if server does not respond

---

package.json
packages/server/package.json
yarn.lock

fix: bump node version

---

packages/client/utils/constants.ts

Fixes #10445 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Add Self Managed GitLab to the Enterprise benefits list

---

packages/server/disconnectAllSockets.ts
packages/server/getIsBusy.ts
packages/server/graphql/private/mutations/dumpHeap.ts
packages/server/graphql/private/typeDefs/Mutation.graphql
packages/server/server.ts
packages/server/wsHandler.ts
packages/server/yoga.ts

dumpHeap keep failing, even though we dump when memory is at 50%.
I suspect this has something to do with users still connecting

fix: dump sockets before dumping heap

---

packages/server/graphql/public/typeDefs/UpdateRecurrenceSettingsSuccess.graphql
packages/server/graphql/public/types/UpdateRecurrenceSettingsSuccess.ts
packages/server/utils/AzureDevOpsServerManager.ts

fixes 2 errors found in datadog logs

fix: udpaterecurrencesetting return type

---

packages/embedder/package.json
packages/server/package.json
packages/server/pipeStreamOverResponse.ts
yarn.lock

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Node 22 type fixes

---

packages/server/wsHandler.ts

only call `message` when the socket is still open fixes #11274
in place of #11279

fix: only call wsHandler message if socket is open

---

packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts

Fixes #11058
I had replaced all `//` with `/` which makes the URL invalid if it includes a protocol.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix(Mattermost): fix notifications

---

pm2.dev.config.js
scripts/webpack/dev.client.config.js

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: Mattermost relay compiler in dev

---

packages/server/utils/useDatadogTracing.ts

turn on resolver tracing

---

package.json
packages/server/postgres/pgtypedConfig.js
packages/server/postgres/queries/src/backupUserQuery.sql

We had syntax errors in .sql files which only produced warnings. Fixed it and changed to error.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: fail on pgtyped errors

---

.env.example
packages/server/chronos.ts

Fixes #11333 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: make chronos debug output optional

---

packages/client/components/ScopePhaseArea.tsx

Fixes #11347 
Trivial change. Fixing review.

fix: ScopePhaseArea styling

---

packages/server/graphql/types/Team.ts

Relates to #11024
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: return missing Organization.isPaid field

---

scripts/webpack/dev.client.config.js
scripts/webpack/toolbox.config.js

Pulled from #11214
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: disable unsafe webpack cache

---

packages/server/graphql/private/mutations/lockOrganizations.ts

Relates to #11024 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: set message in lockOrganizations

---

packages/client/components/MeetingCard.tsx
packages/client/components/TeamPrompt/TeamPromptEndedBadge.tsx
packages/client/styles/theme/global.css

- The global colors were missing some definition
- Aligns the activity ended badge
- Makes the recurring tag a little more visible, easier to read

chore: improve recurring badge readability

---

packages/client/hooks/useMeetingMusicSync.ts
packages/server/graphql/public/mutations/setMeetingMusic.ts
packages/server/utils/analytics/analytics.ts

Add tracking for background music activities so that we can learn how users use it

chore: track background music activity

---

.github/workflows/labeler.yml

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: fix PR size labeler

---

packages/client/hooks/useMeetingMusicSync.ts

Fix https://github.com/ParabolInc/parabol/issues/11493
See Slack thread here: https://parabol.slack.com/archives/C836NA350/p1751296202604209?thread_ts=1751280936.952899&cid=C836NA350

fix: use imported quietLofi file

---

packages/server/billing/helpers/adjustUserCount.ts
packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
packages/server/billing/helpers/updateSubscriptionQuantity.ts
packages/server/dataloader/__tests__/activeOrganizationUsersCustomLoader.test.ts
packages/server/dataloader/__tests__/isOrgVerified.test.ts
packages/server/dataloader/customLoaderMakers.ts
packages/server/graphql/private/queries/suOrgCount.ts
packages/server/graphql/private/queries/suProOrgInfo.ts
packages/server/graphql/private/queries/suUserCount.ts
packages/server/graphql/public/mutations/createStripeSubscription.ts
packages/server/graphql/public/types/Company.ts
packages/server/graphql/public/types/Organization.ts
packages/server/graphql/queries/helpers/countTiersForUserId.ts
packages/server/postgres/migrations/2025-07-02T12:57:36.236Z_removeOrgUserInactive.ts
packages/server/postgres/queries/insertStripeQuantityMismatchLogging.ts
packages/server/postgres/queries/src/insertStripeQuantityMismatchLoggingQuery.sql
packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
packages/server/utils/isRequestToJoinDomainAllowed.ts

Fixes #9932
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Remove OrganizationUser.inactive

---

packages/client/components/ParabolScopingSearchFilterMenu.tsx
packages/client/types/clientSchema.d.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: fix client schema types

---

.github/dependabot.yml

Simplifies it and uses directories to allow * patterns

fix(dependabot): fix configuration file

---

packages/client/components/promptResponse/TipTapLinkMenu.tsx

fix: can click link when changing pages

---

package.json
packages/client/validation/Legitity.ts
packages/client/validation/__tests__/Legitity.test.ts
packages/server/graphql/mutations/helpers/validateScaleValue.ts
packages/server/package.json
pnpm-lock.yaml

Fixes #11488 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: remove direct lodash dependencies

---

packages/server/package.json
pnpm-lock.yaml

Fixes #11489 
It was unused and pulled in lodash.setwith which has a vulnerability.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: remove api package dependency

---

packages/embedder/package.json
pnpm-lock.yaml

Fixes #11487 
This gets rid of the trim package dependency.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: update franc-min to 6.2.0

---

packages/server/utils/useDatadogTracing.ts

For debugging
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: Add userId to Datadog traces

---

.editorconfig
biome.jsonc

Biome was configured to obey .editorconfig. Let's add one as it adds convenience for editing at times.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: add more ignore files to biome and add .editorconfig

---

.github/workflows/build.yml

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: fix server source maps path for Datadog

---

.github/workflows/build.yml

This partially reverts commit 75c805a0610077844c6d03fbbb71e3fda8c62b72.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: fix source map path back

---

packages/client/components/DiscussionThreadInput.tsx
packages/client/components/ErrorComponent/ErrorComponent.tsx
packages/client/components/PokerSidebarEstimateSection.tsx
packages/client/mutations/UpdateTaskMutation.ts
packages/client/utils/createWSClient.ts
packages/server/utils/uwsGetIP.ts
packages/server/wsHandler.ts

fix #11654 fix #11648 fix #11690 fix #11689 fix #11678 fix #11664
does not reset hasConnected so fewer console errors.
also fixes up some smaller issues

fix: remove reconnecting toast

---

packages/client/hooks/useGotoStageId.ts
packages/server/email/renderSSRElement.tsx
packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
packages/server/graphql/mutations/helpers/addSeedTasks.ts
packages/server/graphql/mutations/helpers/dumpTranscriptToPage.ts
packages/server/graphql/mutations/helpers/summaryPage/publishSummaryPage.ts
packages/server/graphql/mutations/helpers/summaryPage/streamSummaryBlocksToPage.ts
packages/server/package.json
packages/server/utils/tiptap/generateJSON.ts
pnpm-lock.yaml

Testing locally, I saw happy-dom doesn't release memory even after there are no references to the instance. this is pretty bizarre, but i couldn't reproduce when I cleaned it up, so this should fix our mem leak problem.

fix: tiptap memory leak

---

packages/server/graphql/mutations/helpers/summaryPage/getInsightsBlocks.ts

handles teamPrompt meeting insights

fix: dynamic meeting type for insights block

---

.github/workflows/docker-external.yml
.github/workflows/ironbank.yml
.github/workflows/release-please.yml

Reports to Slack if docker-external, ironbank or release-please  GH Actions fail

chore(gh-actions): report to Slack GH Actions docker-external, ironbank and release-please if they fail.

---

packages/client/mutations/JoinTeamMutation.ts

fix: fetch active meetings when joining public team

---

.github/workflows/new-datadog-issue.yml

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: decode HTML entities for issue titles

---

packages/client/components/DashNavList/LeftNavHeader.tsx
packages/client/components/DashNavList/LeftNavItem.tsx
packages/client/components/DashNavList/LeftNavItemButtons.tsx
packages/client/components/DashNavList/LeftNavPageLink.tsx
packages/client/components/DashNavList/LeftNavTeamLink.tsx
packages/client/tiptap/extensions/slashCommand/slashCommands.ts

fixes the length of left nav items and when you hit /page it creates it where you want it

fix: left nav max length overflow

---

packages/server/utils/tiptap/hocusPocusRedis.ts

Relates to #11685 
We run into locking issues, which may be related to timeouts. Do some measurements to check.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: measure hocusPocus store document

---

packages/server/utils/tiptap/hocusPocusRedis.ts

Fixes #11685 
- open a page, copy the page id from the URL (last part)
- write to the lock key in redis `SET 'hocuspocus:page:2968014025:lock' GEORG EX 30 NX` (this will lock page 2968014025 for 30s)
- edit the page to trigger a store event
- see no crash

fix: do not crash when failing to acquire page store lock

---

packages/server/hocusPocus.ts

We have `onStoreDocument` traces up to 422ms in the last few hours. Let's find out where we spend our time.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: add more hocus pocus tracing

---

packages/client/styles/theme/global.css

fix #11499
todo lists now look better

fix: todo list styles in pages

---

packages/server/graphql/public/types/User.ts

fixes a regression in the shared pages query

fix: shared pages include pages where teamId is null

---

packages/server/hocusPocus.ts
packages/server/utils/tiptap/hocusPocusRedis.ts

Makes it easier to associated spans which are not properly nested in Datadog.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: add tags to dd-traces for hocusPocus

---

packages/server/postgres/migrations/2025-09-02T12:57:32.479Z_updatePagesFeatureFlag.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

fix: distinct orgs for pages feature flag migration

---

packages/server/utils/serverHealthChecker.ts

- Step 1
- Step 2...
- Step 1
- Step 2....

chore: reduce logs from server health checker

---

packages/server/utils/tiptap/hocusPocusRedisPublisher.ts

Fixes #11979 
Previously we would add a handler for each document. In addition to creating too many listeners we also did not filter the messages correctly per channel as all handlers would receive the same message.

fix: handle publish to public pages correctly

---

packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationSSOFrame.tsx

too many domains don't look good

fix: CSS wrap domains in SAML

---

packages/server/__tests__/pageAccess.test.ts

Fixes #12005 
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: add tests for public/restricted pages

---

packages/server/email/makeSummaryEmailV2.tsx
packages/server/utils/tiptap/generateHTML.ts

in staging ending a standup meeting resulted in a closed socket. not sure why it went fatal...

fix: support server usage

---

packages/server/utils/Logger.ts

Add tags separately to log message.
I want to be able to filter logs by user id.
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: improve log format for Datadog ingestion

---

packages/server/graphql/private/mutations/dumpHeap.ts
packages/server/wsHandler.ts

Fixes #11684 
see https://github.com/ParabolInc/parabol/pull/12023#discussion_r2343944652
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: dispose dataloaders on socket disconnect

---

packages/server/fileStorage/GCSManager.ts
packages/server/server.ts

Fixes: #11493
- Step 1
- Step 2...
- Step 1
- Step 2....

chore: disable static file handle if not needed

---

packages/server/chronos.ts

Fixes #12108 
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: name chronos jobs

---

packages/server/graphql/public/rules/hasOrgRole.ts
packages/server/graphql/public/rules/isAuthenticated.ts
packages/server/graphql/public/rules/isOrgTier.ts
packages/server/graphql/public/rules/isSuperUser.ts
packages/server/graphql/public/rules/isUserViewer.ts
packages/server/graphql/public/rules/isViewerBillingLeader.ts
packages/server/graphql/public/rules/isViewerOnOrg.ts

Fixes #11946 #11868
These are not errors and don't need to be logged. Except rateLimit errors as these should not happen in normal operation and either indicate a pen-test or bug in the app.
- Step 1
- Step 2...
- Step 1
- Step 2....

fix: do not log failed permission checks

---

packages/client/components/MeetingSelector.tsx
packages/client/utils/createWSClient.ts

attempt to solve #12039. It probably won't, but it is an attempt.

fix: only call on meetingId change setAppLocation

---

packages/server/utils/useAuditLogs.ts

support admin graphiql queries

fix: handle no variableVariables coming from graphiql admin queries
