ParabolInc/parabol

- CHANGELOG.md
- lerna.json
- package.json
- packages/gql-executor/package.json
- packages/server/__tests__/processRecurrence.test.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
- packages/server/graphql/public/types/RRule.ts
- packages/server/graphql/public/types/__tests__/RRule.test.ts
- packages/server/package.json
> fix: hanging recurrence

- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Fix https://github.com/ParabolInc/parabol/issues/7976
> fix: org members panel UI

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/PrivateRoutes.tsx
- packages/client/hooks/useSearchFilter.ts
- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/public/types/PokerTemplate.ts
- packages/server/graphql/public/types/ReflectTemplate.ts
Fixes https://github.com/ParabolInc/parabol/issues/7835
Add category filtering to the activity library. Categories are hard-coded for now.
https://www.loom.com/share/a06853e17e244a43ad4731ab15eb578f
> feat(rid): Activity categories

- packages/server/package.json
- packages/server/utils/OpenAIServerManager.ts
- yarn.lock
ChatGPT or GPT-3.5 performs at a similar capacity to GPT-3 but at only 10% of the price. This PR upgrades our OpenAI models to GPT-3.5. See the [official documentation](https://platform.openai.com/docs/guides/chat/chat-vs-completions) from OpenAI on this.
I would also like to make our prompts better, using all I've learnt from ["prompt engineering" course](https://learnprompting.org/docs/intro) but let's keep this one small and simple for now.
This is from production:
This is from my local test, using same set of reflection text:
- Start a retro meeting and advance to discussion phase with more than 1 reflection for the topic
- Observe the topic summary
- End a retro meeting
- Observer the meeting …
> feat(ai-summary): replace GPT-3 with ChatGPT

- packages/server/GoogleLanguageManager.ts
- packages/server/graphql/mutations/helpers/manageGoogleNLPErrorResponse.ts
Fixes #7987 
Tested Russian & Arabic and verified the reflections can be added:
Try a few language options from the supported & unsupported [list](https://cloud.google.com/natural-language/docs/languages#entity_analysis) and make sure reflections can be properly added
> fix(sentiment-analysis): Fix error payload from Google Language API

- .github/reviewers.yml
Fix typo and move devops out of developers to not assign them automatically to reviews.
> chore: fix reviewers

- packages/server/graphql/mutations/archiveTeam.ts
Allow super users to archive teams to process support requests.
Run the mutation
```graphql
mutation DeleteTeam {
archiveTeam(teamId: "kLdw73VT4A") {
error {
message
}
team {
id
}
}
}
```
with a team id where you're not team lead on **master** and see the error message
```json
{
"data": {
"archiveTeam": {
"error": {
"message": "Not team lead"
},
"team": null
}
}
}
```
with the **PR** rerun it
```json
{
"data": {
"archiveTeam": {
"error": null,
"team": {
"id": "kLdw73VT4A"
}
}
}
}
```
> chore: Allow super users to archive teams

- packages/server/utils/OpenAIServerManager.ts
I found a couple of small issues with the AI Summary following the change to ChatGPT in https://github.com/ParabolInc/parabol/pull/7958
I think we should use ChatGPT instead of the davinci model, but we should fix the following issues first.
I'd like to revert the ChatGPT change for now as the roll-out will happen today/tomorrow.  CC @tianrunhe 
Loom demo: https://www.loom.com/share/d0685ece343241578391432c42e192f7
Issues:
> chore(ai-summary): revert chatgpt change

- packages/server/graphql/mutations/helpers/generateWholeMeetingSentimentScore.ts
Fixing a bug where if there are no reflections with `sentimentScore` (e.g., because the team is not on a paid tier so we save ourselves from calculating the scores), we write 0 as the `sentimentScore` for the meeting. We should write `undefined` instead, as 0 can mean neutral sentiment.
- Run a retro meeting from a free tier team, write a few meaningful reflections
- Verify **no** reflections have the field `sentimentScore` in Rethink
- Verify the meeting does **not** have the field `sentimentScore` in Rethink
- Run a retro meeting facilitated by someone having the `aiSummary` feature flag, from a paid tier team
- Write a few meaningful reflections
- Verify the reflections have the field `sentimentScore` in Rethink
- Verify the meeting has the field `sentimentScore` in Rethink
- Run a …
> fix(sentiment-analysis): write undefined as sentimentScore for meetings without reflections with scores

- packages/client/utils/makeDefaultTeamName.ts
- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
- packages/server/graphql/mutations/updateTeamName.ts
- packages/server/utils/analytics/analytics.ts
Coming from #terrrible-ideas [here](https://parabol.slack.com/archives/C03NGEJUKCN/p1679935808804259). The idea is we have a list of funny names, when user signs up, we pick one randomly and make that the name for the default team. Also add a new metric to track when user changes team name.
Metrics: 
- Create a new account
- See a default team is created, with a fun name chosen randomly from the list
- Create a new account
- See a default team is created, with a fun name chosen randomly from the list
- Change the default team name to something else
- Go to [Segment Debugger](https://app.segment.com/parabol-jordan/sources/action_local/debugger) and verify a metric called `Team Name Changed` is populated and the `isOldNameDefault` property is `true`
> feat: pick a fun name for the default team when user signs up

- packages/client/components/MeetingCard.tsx
- packages/client/components/MeetingCardOptionsMenu.tsx
- packages/client/components/MeetingCardOptionsMenuRoot.tsx
- packages/client/components/TeamPrompt/Recurrence/EndRecurringMeetingModal.tsx
- packages/client/components/TeamPrompt/TeamPromptOptions.tsx
- packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
- packages/client/hooks/usePortal.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7973
In meeting:
https://www.loom.com/share/fa634c3aa1574a69814549037d8ecb0b
Dashboard:
https://www.loom.com/share/4ce79e6c309e4d128d1f40e6647c2ccb
On both dashboard and in meeting:
> feat(recurrence): End Recurring Meeting Confirmation Modal

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsRoute.tsx
- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
- packages/client/components/AzureDevOpsSVG.tsx
- packages/client/components/PrivateRoutes.tsx
- packages/client/modules/meeting/components/EditableTemplateName.tsx
- packages/client/modules/meeting/components/PokerTemplateDetails.tsx
- packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
- packages/client/modules/meeting/components/TemplateSharing.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7960
Implements the details view for retros primarily by reusing existing components, mutations, and GQL models.
I'm explicitly leaving mobile views out of scope for now.
Note that this doesn't match designs precisely, as some feature details are still somewhat ambiguous (e.g. cloning - to which team?) and/or requires disproportionate effort (e.g. distinct edit mode, modifying categories, etc.). We should punt on those features until the next iteration.
https://www.loom.com/share/147d92e0c39b4d4f9c16ace0904d1823
> feat(rid): Activity Details (no sidebar)

- packages/server/postgres/queries/updateUserTiers.ts
- packages/server/utils/setUserTierForUserIds.ts
Fixes #7934
SQL query expecting a list was called with an empty list which caused a syntax error
- Sign up with a new user and delete the user again from the profile
- Sign up with a user joining a starter and team org
- leave the team org
> fix: fix syntax error when adjusting the user tier with empty list

- packages/client/styles/theme/global.css
Fixes missing global styles after migration to TailwindCSS causing inputs and text areas to have weird styles in some places. Commit that removed & replaced old global styles is [here](https://github.com/ParabolInc/parabol/pull/7597/files#diff-a9f489e548dfdf934bd307787386171bfd078dc3ccff91cb959969d46e594d33L103-L113).
> fix: missing font styles on inputs, textareas etc

- packages/client/mutations/CreateTaskMutation.ts
Workaround for #7943 
There is a bug with Relay: adding an optimistic result to an array will cause it to be undefined once the real result arrives. This workaround just skips the optimistic update adding to unblock users until there is a better fix.
> fix: Workaround for adding Parabol tasks in Sprint Poker

- packages/client/components/Dashboard.tsx
- packages/client/components/MyDashboardTimeline.tsx
Previously it was only visible on the timeline, so it had limited reach. Moving it to the main dashboard shouldn't distract from meetings either while reaching a broader audience.
https://www.loom.com/share/60ab5f31a27649d3b436d48218f0e2e3
Add a new feature announcement by running
```graphql
mutation AnnounceNewFeature {
addNewFeature(
actionButtonCopy: "Why 🔍", 
snackbarMessage: "New: Find and group similar reflections more quickly and easily", 
url: "https://www.example.com") {
__typename
newFeature {
id
}
}
}
```
> chore: Move new feature announcement to main Dashboard

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/LeftDashNavItem.tsx
- packages/client/components/Dashboard/MobileDashSidebar.tsx
> feat(retros-in-disguise): added activity library to sidebar 

- packages/client/components/ActivityLibrary/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeeting.tsx
- packages/client/components/NewMeetingActionsCurrentMeetings.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
- packages/client/modules/meeting/components/EditableTemplateName.tsx
- packages/client/modules/meeting/components/SelectTemplate.tsx
- packages/client/mutations/SelectTemplateMutation.ts
Fixes https://github.com/ParabolInc/parabol/issues/7962
Implement retro details sidebar + improve responsiveness for smaller desktop screens.
The team selection dropdown case when the template is limited to team (vs org) is out of scope for this PR and will be implemented later - team selection here is reasonable for now.
Parts of the diff would benefit from `?w=1`
Needs rebase once https://github.com/ParabolInc/parabol/pull/7990 lands
https://www.loom.com/share/f9f857bf626d42acbd560c89e8dc0511
> feat(rid): Retro Details Sidebar

- packages/client/mutations/DeleteTaskMutation.ts
fixes #7944 ensures the task exists before trying to delete it
user a deletes a task. user b is on a screen that does not see that task. no error on user b
> fix: ensure task exists

- packages/client/mutations/RemoveOrgUserMutation.ts
fixes #7717 makes sure teamMember array exists in payload.
the root cause is actually in the type def file, but that'll take a lot longer to fix & get merged.
> fix: ensure teamMembers exist in payload

- packages/server/utils/isCompanyDomain.ts
@icloud.com is a personal email address. Apple Employee who works in iCloud department is not using this TLD in their work email. This makes us mistakenly thought we had an [Apple deal].(https://app.hubspot.com/contacts/3888472/company/1111839656)
> chore(metrics): Add icloud.com as another generic domain

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
- packages/client/components/ActivityLibrary/CreateActivityCard.tsx
- packages/client/components/ActivityLibrary/TeamPickerModal.tsx
- packages/client/components/NewMeeting.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
- packages/client/hooks/usePortal.tsx
- packages/client/mutations/UpdateReflectTemplateScopeMutation.ts
- packages/client/mutations/handlers/handleAddReflectTemplate.ts
- packages/client/mutations/handlers/handleRemoveReflectTemplate.ts
Fixes https://github.com/ParabolInc/parabol/issues/8025
~Needs rebase once https://github.com/ParabolInc/parabol/pull/8008 lands~
Create a new retro template from the "Create New {category} Activity" button under retro categories in the activity lib.
Note that templates don't keep the category they're created from - this will be added when we move categories to the DB and allow them to be changed.
https://www.loom.com/share/10160e33bb334a2ab55f8ae0d3687267
> feat(rid): Create retro template from retro categories view

- packages/server/graphql/mutations/helpers/attemptLogin.ts
Fixes #8037 
Previously failed login attempts for an email/ip combination did not expire which lead to a situation where a customer could not sign up anymore because they exceeded the threshold 6 month ago.
https://www.loom.com/share/3aa6c7aed7ab41f483edfd110876e627
```JavaScript
r.db('actionDevelopment').table('FailedAuthRequest').insert([{
email: 'failing@example.com',
id: 'abcdefghij-1',
ip: "0000:0000:0000:0000:0000:0000:0000:0001",
time: new Date('2022-01-01') 
},{
email: 'failing@example.com',
id: 'abcdefghij-2',
ip: "0000:0000:0000:0000:0000:0000:0000:0001",
time: new Date('2022-01-01') 
},{
email: 'failing@example.com',
id: 'abcdefghij-3',
ip: "0000:0000:0000:0000:0000:0000:0000:0001",
time: new Date('2022-01-01') 
},{
email: 'failing@example.com',
id: 'abcdefghij-4',
ip: …
```
> fix: expire failed login attempts

- packages/client/components/ActivityLibrary/ActivityDetails.tsx
- packages/client/components/TimelineEventTeamPromptComplete.tsx
- packages/client/modules/meeting/components/PokerTemplateDetails.tsx
- packages/client/modules/meeting/components/PokerTemplateItem.tsx
- packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
- packages/client/modules/meeting/components/ReflectTemplateItem.tsx
- packages/client/mutations/toasts/promptToJoinOrgSuccessToast.ts
- packages/client/utils/useTemplateDescription.ts
FIxes errors in https://github.com/ParabolInc/parabol/actions/runs/4726296812/jobs/8385744221?pr=8036
`makeTemplateDescription` (not a hook) calls `useFragment` (a hook), which breaks React hook rules, since hooks can only be called from function components and other hooks.
Rename `makeTemplateDescription` to `useTemplateDescription` to make it a hook + rearrange code that calls it conditionally.
Also includes a minor fix where `useAtmosphere` was called conditionally.
Also fixes prettier in a file (what's actually breaking code style on master)
N/A
Smoke test places where template descriptions are used.
> fix: Rename makeTemplateDescription -> useTemplateDescription to satisfy hooks rules

- packages/server/database/types/MeetingTeamPrompt.ts
- packages/server/graphql/mutations/helpers/safeCreateTeamPrompt.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
- packages/server/graphql/public/mutations/startTeamPrompt.ts
Fixes an issue where the standup title would be like `Friday Ship - April 17 - April 17`. The issue was caused by the implementation detail, where `MeetingTeamPrompt` constructor would always append a date to a title, no matter if it was already there or not. I moved creating title outside of the constructor for all cases as eventually we'll use a different timezone when creating a single instance meeting vs meeting series.
No demo
> fix(recurrence): prevent repeating date in standups name

- .github/workflows/notify_bug_assign.yml
Github Action to send an automated message to a new Slack channel, informing us that a bug got assigned to a squad.
New file to create a Github Action which gets triggered when a issue labeled "bug" also gets assigned a "Squad: 1" or "Squad: 2" label.
Can't test without the file being live.
> Create new Github Action - Notify on bug assignment

- packages/server/billing/helpers/terminateSubscription.ts
- packages/server/graphql/private/mutations/stripeFailPayment.ts
Fixes #8061. To reproduce the bug, on `master` branch:
1. [Install Stripe CLI](https://stripe.com/docs/stripe-cli) if you haven't
2. Setup Stripe webhook to forward to your local server: `stripe listen --forward-to localhost:3000/stripe`, and copy the webhook singing secret to replace the one in [your .env](https://github.com/ParabolInc/action-devops/blob/master/environments/local#L73)
3. Create a new team/org and go to the org billing page
4. Upgrade with this Stripe payment failure test card: `4000 0000 0000 3063`, expiration date any month in the future, CVC can be anything
5. Observe the org is upgraded
6. Wait a moment and then refresh the page, you should see that one invoice is in the state of PENDING (because the payment wasn't successful) but another invoice for next month with …
> fix(stripe): Fix the bug when there's failed payment we charge customer extra amount

- app.json
- packages/client/utils/constants.ts
- packages/server/fileStorage/FileStoreManager.ts
- packages/server/fileStorage/LocalFileSystemManager.ts
- packages/server/fileStorage/S3Manager.ts
- packages/server/package.json
- scripts/toolboxSrc/migrateImages.ts
- scripts/toolboxSrc/pushToCDN.ts
- scripts/webpack/dev.client.config.js
- scripts/webpack/prod.servers.config.js
- yarn.lock
Fixes #8070
- Template illustrations get bundled with the server assets
- a script gets called predeploy which looks for those assets & pushes them to a CDN if they don't exist
- it works for both S3 and local image hosting
- i had to bump the aws-sdk. It was reeeeeeeally old & calling `headObject` was sometimes failing
- After this is done we can start adding these URLs to rows in the DB
Nothing to see :-(
- run `yarn build` and look at /dist/templates
- run `node dist/migrateImages` and see the files have been pushed to S3 (e.g. https://action-files.parabol.co/development/store/Organization/aGhostOrg/template/gladSadMadTemplate.png)
- change your .env `FILE_STORE_PROVIDER='local'` and re-run the above 2 commands. see the files live in /self-hosted
- change your user avatar, just to make …
> feat: push meeting templates to CDN

- packages/client/components/ActivityLibrary/ActivityLibraryRoute.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryRoutes.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivityRoute.tsx
- packages/client/components/PrivateRoutes.tsx
Improves routing per https://github.com/ParabolInc/parabol/pull/8069#discussion_r1178351313
> chore(retros-in-disguise): improve activity library routing 

- packages/client/components/ActivityLibrary/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/modules/meeting/components/TemplateSharing.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8099
Needs rebase once https://github.com/ParabolInc/parabol/pull/8111 lands.
Edit mode for RiD Details View. Clicking the pencil icon on owned templates makes all fields editable.
Note that all edits persist immediately (rather than after exiting edit mode). We may want to change this behavior in a future iteration.
https://www.loom.com/share/257162a6f3eb4287a40ad80645d631a0
> feat(rid): Edit Mode

- packages/server/database/types/MeetingTemplate.ts
Fixes https://github.com/ParabolInc/parabol/issues/8119
By default, share templates to org
https://www.loom.com/share/922238657ba1460ea730674634d84356
> feat(templates): Share to org by default

- package.json
- packages/gql-executor/package.json
- packages/server/package.json
- yarn.lock
Fixes the 5 dependabot security findings (hopefully!)
If things still build it's probably OK! none of the vulns were in runtime deps
- See if it builds
> chore(security): bump vulnerable packages

- scripts/webpack/prod.servers.config.js
Removes a leading slash.
POSIX states that extra slashes get condensed to 1. Not sure why it's not working here...
Teaming this PR with Aaron directly on staging so no testing necessary
> fix: remove leading slash on dist nested dirs

- packages/client/subscriptions/NotificationSubscription.ts
- packages/client/subscriptions/subscriptionOnNext.ts
- packages/client/subscriptions/subscriptionUpdater.ts
- packages/server/graphql/subscribeGraphQL.ts
fixes #8090 
builds on top of #8118 & the great repro that @jmtaber129 found
I also added in a fix to remove null values from the payload. I must've had a bad merge conflict because that used to be there 😅 Makes this stuff easier to debug & generally keeps payload size to 1 MTU, so mobile clients should be happy.
Worth noting that there could be other similar bugs like this out there!
https://www.loom.com/share/733bcaafd1aa4f9a972cda8f62de4c48
> fix: subscribe to acceptInvite paylods in subscription

- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
- packages/client/modules/meeting/components/TemplateSharing.tsx
- packages/server/graphql/mutations/updateTemplateScope.ts
Fixes https://github.com/ParabolInc/parabol/issues/8026
When a template is team-scoped, the activity can only be started on the owning team, so the team dropdown in the details view would only show the owning team.
Instead, show a popover that prompts the user to change the scope to "org".
This loosens the template scope update mutation such that any team member can update the scope (not just team leads)
https://www.loom.com/share/0f4486618b4344a2a5924b281befb361
> feat(rid): Prompt user to change template scope to org

- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/public/types/TeamPromptMeeting.ts
Fixes https://github.com/ParabolInc/parabol/issues/8152
Adds prev+next buttons to recurring meetings to link to the previous or next meeting in the series, if applicable.
https://www.loom.com/share/450680aacaaf44bca9b1a2d211e6cb29
> feat(recurrence): Prev/next meeting navigation

- scripts/toolboxSrc/standaloneMigrations.ts
Working towards a future where migrations can be run without any dependencies.
Just because we migrate DBs doesn't mean we should flush redis.
This is fine in development, but not wonderful for production.
`yarn prod && node dist/migrate` will not flush redis
> fix: remove flushall redis on migrate

- .github/workflows/labeler.yml
My PRs aren't that big, honest! They just trigger generated file changes.
This ignores generated files that are checked into version control.
> chore: ignore generated files in PR size

- packages/server/graphql/mutations/helpers/canAccessAISummary.ts
- packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
- packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
- packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
- packages/server/graphql/private/typeDefs/addFeatureFlagToOrg.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Fix https://github.com/ParabolInc/parabol/issues/8023
I'd like to:
- Add this org level feature flag
- Once it's in prod, get all of the org ids of the users that have opted out so far
- Add this feature flag to all of those orgs
- Remove the user feature flag
If you're happy with this approach, I'll create an issue to remove the `noAISummary` feature flag.
> chore: AI opt out at org level

- packages/client/components/ActivityLibrary/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
- packages/client/components/ActivityLibrary/TeamPickerModal.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8151
Automatically enter edit mode from template cloning+creation via `edit` nav state.
https://www.loom.com/share/4ebf1bb32d554e8c9ba27d480801ca17
> feat(rid): Enter edit mode automatically for new templates

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
Currently, the search empty state in the activity library grid view shows the "Create activity" card for whichever category is selected.
Because search is category-agnostic, this "create activity" card should actually be the generic card shown in the quick start view.
Before:
After:
> fix(rid): Ignore category in search empty state

- packages/client/components/PokerActiveVoting.tsx
- packages/client/mutations/PokerRevealVotesMutation.ts
- packages/server/graphql/mutations/pokerRevealVotes.ts
fix #8158
- removes optimistic updater so error shows up
- disables reveal button when it's already in flight so you can't click twice
- removes check for estimate phase having ended. Not sure, but if i had to bet, I'd say this is the server error they were hitting
- can't reproduce the error that the user saw, so no great testing here 😕
> fix: more logs for voting error

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/LeftDashNavItem.tsx
- packages/client/components/SideBarStartMeetingButton.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8203
For RiD feature-flagged users (currently just internal users), navigate to the activity library by default, with a link to the "legacy" flow further down the nav bar. This is intended to promote the activity library from "here's something you can try out" to "here's something you should be using to start your meetings whenever possible" for internal Parabol users.
This should promote increased internal usage, allowing us to get more user feedback and identify more bugs.
Before:
After:
> feat(rid): Navigate to activity lib by default from CTA

- packages/server/graphql/mutations/endRetrospective.ts
- packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
- packages/server/graphql/types/NewMeeting.ts
Fix https://github.com/ParabolInc/parabol/issues/7674
Occasionally, the Slack stats are all 0. This could be because:
- The `generateWholeMeetingSummary` is updating the meeting object at the same time the Slack stats are being inserted into the meeting object.
- The meeting object cache is stale when the `SlackNotifier` requests it
> fix: slack notification race condition

- scripts/create-jira-keys.sh
If not supplied explicitly, these values will be taken from the local config file. These values might not be appropriate or totally absent causing the script to fail.
Explicitly supply an empty configuration and run the script. It would fail on master but succeed with this PR
```sh
cd parabol
mkdir foo && cd foo
OPENSSL_CONF='' ../scripts/create-jira-keys.sh
```
> fix: Add subject explicitly to create Jira key script

- packages/client/utils/handleSuccessfulLogin.ts
Patient 0 tracking in GA4 is still weird... This is yet another try.
I'd like to create a custom event `p0_sign_up`:
To do that, I need an **event level parameter** `is_patient_0` hence this small PR
> chore(metrics): Add event parameter is_patient_0 to GA4 sign up events

- codegen.json
- packages/server/graphql/private/mutations/updateOrgFeatureFlag.ts
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/private/types/UpdateOrgFeatureFlagSuccess.ts
Fix https://github.com/ParabolInc/parabol/issues/8243
I don't see any documentation in Notion about an org feature flag, so I created my own: https://www.notion.so/parabol/How-to-enable-or-remove-an-org-feature-flag-4b4be190ed674bf8903340d6b5fa50e4
> chore: refactor addFeatureFlagToOrg to updateOrgFeatureFlag

- packages/client/components/Dashboard.tsx
- packages/client/components/PrivateRoutes.tsx
The backgroundLocation approach does not work properly when nesting, so move the NewMeeting dialog a level up as well.
This caused the background dashboard to be rendered twice
https://www.loom.com/share/c18f23bd2c4444bda7dda015b4096b0b
Easiest way for me to visually reproduce:
* on meeting dashboard press new meeting button
* go to sprint poker
* press on the template
Also check that the dashboard is not added twice to the DOM when the new meeting dialog is shown.
> fix: NewMeeting dialog rendered the dashboard twice

- packages/client/components/PrivateRoutes.tsx
prev pr: #8246
Additional fix: when changing a team in a new meeting window, background shows 404 error:
- Open new meeting window, switch teams in team selector
- Play with windows and routes, see everything works as expected
> fix: Fix team change in new meeting window

- packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/getSummaryText.ts
- packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
Fixes https://github.com/ParabolInc/parabol/issues/7885
Implements `getSummaryText` and integration-specific buttons for standups, and adds `IntegrationNotifier.endMeeting` call to `safeEndTeamPrompt` (same place where we send meeting summaries)
> feat(standups): Meeting ended integration notification

- packages/client/components/TaskFooterIntegrateMenu.tsx
- packages/client/components/TaskFooterIntegrateMenuList.tsx
- packages/client/components/TaskIntegrationMenuItem.tsx
- packages/client/hooks/useIsIntegrated.ts
- packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasks.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasksMenu.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasksMenuRoot.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
- packages/client/mutations/AddAtlassianAuthMutation.ts
- packages/client/mutations/AddGitHubAuthMutation.ts
- packages/server/__tests__/processRecurrence.test.ts
- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/public/types/TeamPromptMeeting.ts
Add a bulk task export button to meeting summaries where tasks may have been created. This would:
* Enhance integration discoverability
* Reduce friction for moving meeting action items into a backlog (e.g. GitHub, Jira, etc.)
For simplicity, I'm calling the existing `createTaskIntegration` mutation multiple times in parallel instead of creating a new mutation or modifying the existing mutation to handle multiple tasks. We could refactor this approach into one of those two options, but it's best to use this simpler approach for now and pay down that tech debt sometime in the future.
https://www.loom.com/share/349595bcea0646f19b5202bb4a6e5a1e
> feat(summaries): Bulk task export button

- packages/client/components/MeetingCardOptionsMenu.tsx
- packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
Fixes https://github.com/ParabolInc/parabol/issues/7890
We currently refer to ending an "activity" in one place and ending a "meeting" in another. Though "activity" may be the terminology we'll want to present long term, most of the app currently uses the term "meeting", so using that term here will make things more consistent.
N/A
> fix(copy): Make copy for ending meeting consistent

- packages/server/utils/OpenAIServerManager.ts
Related to (and may fix) https://github.com/ParabolInc/parabol/issues/8200
`max_tokens` refers to the max number of tokens OpenAI should allocate to the completion, i.e. the text it generates. We want it to create a 1-2 sentence summary, which should cost ~30 tokens (see [here](https://help.openai.com/en/articles/4936856-what-are-tokens-and-how-to-count-them)). 
We shouldn't need the 256 tokens we're currently allocating to the completion. However, the summary could be incomplete if we set a token limit that's too low. While we probably only need ~30 tokens, to be on the safe side, I've set a new limit of 80, which should help us stay within OpenAI's rate limits while ensuring the summaries are still complete.
> chore: update max token limit

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8184
Based on https://github.com/ParabolInc/parabol/pull/7933 since that PR changes some stuff around `ExportToCSV` rendering, and that PR should land soon. Will need rebase after that PR lands.
Recommend reviewers to review with whitespace ignored.
No tasks, no CSV:
No tasks, CSV:
Tasks, no CSV:
Tasks and CSV:
> fix(standups): Remove CSV download button in standups

- packages/client/components/Checkbox.tsx
- packages/client/components/EmailNotifications.tsx
- packages/client/components/NewMeetingSettingsToggleAnonymity.tsx
- packages/client/components/NewMeetingSettingsToggleCheckIn.tsx
After rewriting `Checkbox` to tailwind, we can't simply override color with style component.
This happens because tailwind defines clasees like `body .text-slate-600` which is more specific than classname added by styled components.
By using `&&` it is possible to make styled components class more specific, it will look like `.css-ry6kcf.css-ry6kcf`
- see that checkbox shows the correct color
**Alternative possible approach:** refactor `Checkbox` and introduce `size` prop and `color` prop
Because of order of classes in tailwind stylesheet, one class would always be preferable:
**Another approach:**
Remove default color at all
> fix: checkbox color overriden by styled components

- packages/client/modules/meeting/components/EditableTemplatePromptColor.tsx
- packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
- packages/client/modules/meeting/components/TemplatePromptItem.tsx
- packages/client/modules/meeting/components/TemplatePromptList.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8272
The prompt color picker assumed that it's in the old template picker modal, so it threw an error when it couldn't find the template picker modal in the activity library.
Refactor a bit to pass the parent modal ID down from the parent.
https://www.loom.com/share/6c69352d8fda44bfbde26f39dbe28346
> fix(rid): Fix changing prompt colors in activity library

- packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
- packages/client/shared/rruleUtil.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
- packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
Fixes https://github.com/ParabolInc/parabol/issues/7953
The `rrule` library we're using handles times + time zones in a way that's very... strange. Basically, `rrule` assumes the UTC equivalent of all dates it sees are actually just in the system's time zone. So a time of `12:00:00Z` for a system in PST is actually interpreted by `rrule` as 12 PST, or `21:00:00Z` true UTC.
The immediate fix is simple but tedious - convert these "UTC" local time zone times returned by `rrule` to the true JS `Date`, and convert JS `Date`s to the weird "local as UTC" time before passing them to any `rrule` methods.
The long-term fix is probably to rip out the `rrule` lib and roll our own (or fork the lib and make changes for improved time zone support), but that's probably not worth it for now. …
> fix(recurrence): Incorrect start times due to timezone weirdness

- packages/client/mutations/EndRetrospectiveMutation.ts
Fixes https://github.com/ParabolInc/parabol/issues/8284
For retros, we update `taskCount` in a method called without `await`, so the `taskCount` may be updated _after_ the `endRetrospective` mutation returns. As a result, we'll sometimes not show the bulk task export button even though there are tasks from the meeting.
This unawaited method publishes its updates asynchronously to the meeting subscription, so we just need to add `taskCount` to the fragment for that subscription.
> fix(summaries): Race condition around bulk task exports

- codegen.json
- packages/client/components/RetroGroupPhase.tsx
- packages/client/components/RetroReflectPhase/RetroReflectPhase.tsx
- packages/client/modules/demo/initDB.ts
- packages/client/mutations/AutogroupMutation.ts
- packages/client/utils/constants.ts
- packages/server/database/types/MeetingRetrospective.ts
- packages/server/graphql/mutations/helpers/generateGroups.ts
- packages/server/graphql/mutations/helpers/handleCompletedStage.ts
- packages/server/graphql/mutations/helpers/updateReflectionLocation/addReflectionToGroup.ts
- packages/server/graphql/public/mutations/autogroup.ts
- packages/server/graphql/public/typeDefs/autogroup.graphql
- packages/server/graphql/public/types/AutogroupSuccess.ts
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
- packages/server/graphql/types/AutogroupReflectionGroup.ts
- packages/server/graphql/types/RetrospectiveMeeting.ts
- packages/server/utils/OpenAIServerManager.ts
- packages/server/utils/estimateTokens.ts
- packages/server/utils/isValidJSON.ts
Fix https://github.com/ParabolInc/parabol/issues/8123
Demo: https://www.loom.com/share/c453d1b30fca44c7b74066b64fe81343
Note:
- If you quickly click the "Suggest Groups" button after proceeding to the Group phase, it won't work as ChatGPT won't have responded. In a later PR, I'll add some error/loading feedback text. See: https://github.com/ParabolInc/parabol/issues/8133
- Non-viewers will need to refresh the page to see the change. See https://github.com/ParabolInc/parabol/issues/8126
> feat(suggest-groups): click button to group reflections

- packages/client/components/PrivateRoutes.tsx
When copy pasting add teammate modal url in a new tab, it shows 404 on the background. 
Works on just page refresh, that is why I didn't notice it.
How to test:
- trigger prompt to join org
- open add teammate dialog
- copy the URL
- paste in a new tab
- see everything is fine
> fix(prompt-to-join): fix add teammate routing when opened on a new tab

- packages/client/modules/meeting/components/PokerTemplateScalePicker.tsx
see [slack](https://parabol.slack.com/archives/C02438U0VJ4/p1685491486297169) 🔒 
Currently, readonly mode differs for poker scales between owned + non-owned templates.
This PR fixes those styles.
Non-owned:
Owned:
Owned + edit-mode:
Existing owned:
Existing non-owned
> fix(rid): Correct styles for non-owner readonly scales

- packages/client/components/ReviewRequestToJoinOrgModal.tsx
- packages/client/mutations/AcceptRequestToJoinDomainMutation.ts
- packages/client/mutations/useAcceptRequestToJoinDomainMutation.ts
- Trigger prompt to join org
- See that add teammate dialog buttons become disabled when mutation is running
> chore(prompt-to-join): disable buttons when running accept request mutation

- README.md
We no longer have slack community so the link in our readme was broken. 
No demo
No testing scenarios
> chore: remove slackin broken link from readme

- packages/server/graphql/public/mutations/acceptTeamInvitation.ts
Probably a solution for #7771 
(At least some of errors)
- Invite a user using email
- Click accept invitation, see it works
- Click accept invitation again, see no error in logs
> fix: fix loader.load with undefined in accept team invitation

- scripts/toolboxSrc/standaloneMigrations.ts
Fixes #8314
Drain RethinkDB pool as it blocks the process from exiting otherwise.
-
* run `yarn build --no-deps`
* clear local db `yarn db:stop && docker volume rm docker_postgres-data docker_rethink-data && yarn db:start`
* run `./dist/migrate.js`
> fix: Drain rethinkdb pool after running all migrations

- packages/client/components/DropdownToggleInner.tsx
- packages/client/components/NewMeeting.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8296
These dropdowns shouldn't wrap, so remove that style. Also needed to increase the new meeting modal width by a few pixels to get around removing `maxWidth` while still fitting the public template "Always Be Learning Retrospective 🌱" without wrapping.
> fix(rid): Long team names truncate instead of wrapping

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
We [decided](https://parabol.slack.com/archives/C836NA350/p1685572418054199) to allow unverified emails to access the "prompt to join org functionality
- Make sure no verification enabled for the domain you use 
- Do not use login with google
- Trigger prompt to join org flow using non-verified emails, see everything works as expected
> chore(prompt-to-join): allow non-verified emails

- packages/client/components/TeamHealth.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamHealthSummary.tsx
- packages/client/styles/theme/global.css
- packages/client/utils/blendColors.ts
- packages/client/utils/getTeamHealthVoteColor.ts
- packages/server/email/MailManagerDebug.ts
Fixes #7941
Also blend colors based on the votes percentage.
Run retros with `teamHealth` org flag and team health phase
> feat(Team Health): Add summary

- packages/server/graphql/private/mutations/dumpHeap.ts
The node process drops all user rights and thus needs to write to a directory writable by all.
run `mutation Dump { dumpHeap(isDangerous: true) }` locally and check the file exists
> fix: dumpHeap to /tmp directory

- packages/server/utils/analytics/helpers.ts
See [slack](https://parabol.slack.com/archives/C03C3J42WDU/p1686069496724449)
> feat(analytics): Track meeting category on meeting start

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
See [spec](https://www.notion.so/parabol/miniRFC-Adding-new-users-to-RiD-feature-flag-f1d3fa0524664c47aa9cfe12f5426b6a?pvs=4#a7f9fc955dad4c8c8dac816e055e54d7) 🔒 
For new P0 users (users for which no existing users share the domain), add 5% of them to the RiD feature flag.
> feat(rid): Add new users to feature flag

- packages/client/utils/SlackManager.ts
Fix https://github.com/ParabolInc/parabol/issues/8328
Slack has a default limit of 100 channels on the `conversations.list` API. By setting the limit to 1000, we can see all the channels.
> fix: show all slack channels in dropdown

- packages/client/components/ErrorComponent/ErrorComponent.tsx
Fixes #4482 . Details in the issue itself.
- build production version of an app by running `yarn build`
- run it via `yarn start`
- open retro meeting, go to discuss phase
- right click anywhere, translate the page to a different language than English
- write a comment, add a task and shortly after you'll see our error boundary catching this error
- check the message
> fix: better description for failed to execute removeChild on Node error

- .github/ISSUE_TEMPLATE/design_issue.md
Adds a new template to be used for design issues. [See this Slack convo for more context](https://parabol.slack.com/archives/C02438U0VJ4/p1681931376785769).
> docs: Adds new template for design issues

- CHANGELOG.md
- packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
See [slack](https://parabol.slack.com/archives/C836NA350/p1686249487077819?thread_ts=1686161803.697149&cid=C836NA350) 🔒
> fix(templates): Many public templates not displayed

- docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
Adds the `self-hosted` folder into the HOME directory of our Docker images.
Verify that the folder is there on the newly created images.
> chore(docker-image): self-hosted folder added in HOME directory

- packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
- Create a starter org
- You can manually lock the org with the limits
```
r.db('actionDevelopment')
.table("Organization")       
.get('nWsBsQtzm8')
.update({
scheduledLockAt: new Date(),
lockedAt: new Date(),
tierLimitExceededAt: new Date()
})
```
- Upgrade to enterprise, see limits were removed
```
mutation {
draftEnterpriseInvoice(
orgId: "nWsBsQtzm8", 
quantity: 10,
email: "test@example.com"
apEmail: "test@example.com"
) {
organization {
tier
}
error {
message
}
}
}
```
> fix(teams-limit): remove teams limit when upgrading to enterprise

- packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
- packages/client/components/NewMeetingSettingsToggleTeamHealth.tsx
- packages/client/components/TeamHealth.tsx
- packages/client/mutations/EndRetrospectiveMutation.ts
- packages/client/utils/features/isTeamHealthAvailable.ts
- packages/client/utils/meetings/lookups.ts
- packages/server/database/types/MeetingSettingsRetrospective.ts
- packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
- packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/mutations/setMeetingSettings.ts
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
- packages/server/graphql/types/TeamMeetingSettings.ts
- packages/server/postgres/migrations/1686226640890_addTeamHealthToAllMeetingSettingsRetrospective.ts
- packages/server/utils/analytics/analytics.ts
- packages/server/utils/isPhaseAvailable.ts
Fixes #8288 #8324
It's much less error prone to add the new phase to all retrospective
settings by default and filtering the paid phases from the settings.
The alternative of adding it only to paid teams is more tricky as it
would need to be added in all upgrade paths and we'd need to keep track
if it was disabled.
https://www.loom.com/share/2468e37aeae24cc4bb7345f7a9a7aa53
* start on **master**
* create 2 orgs, 1 starter, 1 team
* checkout **PR**
* both teams should now have `TEAM_HEALTH` meeting phase in their `MeetingSettingsRetrospective` in R
* only the team org has the team health setting
* the starter org will not have the team health phase when starting a retro meeting
* create a new org, check it has `TEAM_HEALTH` meeting phase in their settings
> feat(Team Health): enable team health by default for paid tiers

- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
Add team health settings to new activity library.
* enable 'retrosInDisguise' feature flag
* start a retro
* see the team health setting
> feat(Team Health): Add setting to new activity library

- packages/client/modules/meeting/components/ReflectTemplateListPublic.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8372
Don't use data to determine whether to include the new pre-/post-mortem templates in the old new meeting view. Instead, use category.
> fix(templates): Public templates missing in new environments

- packages/server/postgres/getPgp.ts
- packages/server/postgres/migrations/1625576993065_addAtlassianAuthTable.ts
- packages/server/postgres/migrations/1631553388387_add-template-teams-users.ts
- packages/server/postgres/migrations/1640229261909_mattermostToIntegrationsTables.ts
- packages/server/postgres/migrations/1654861495450_migrateSecureDomain.ts
- packages/server/postgres/migrations/1674074684762_deleteEmptyGroups.ts
- packages/server/postgres/migrations/1676299334703_addSeasonalTemplates.ts
- packages/server/postgres/migrations/1677272969994_meetingTemplatesMove.ts
- packages/server/postgres/migrations/1682541572157_deleteUserRethink.ts
- packages/server/postgres/migrations/1684250022646_teamHealthPhase.ts
- packages/server/postgres/migrations/1685721573097_addPrePostMortemTemplates.ts
- packages/server/postgres/migrations/1686226640890_addTeamHealthToAllMeetingSettingsRetrospective.ts
Some migrations cleanup. We should not use application logic in migrations, however initializing the database is an exception to that, because if we change our infrastructure, connecting to the db needs to change everywhere.
* clean your db and run migrations
> chore: cleanup connect rethink db in migrations

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/hooks/useSearchFilter.ts
Fixes https://github.com/ParabolInc/parabol/issues/8323
Enhance search functionality in the activity library by expanding what the search query matches against. In this PR, the search query will match:
* Team name
* Meeting type
* Category
* Category-related keywords
* Dimension names + descriptions + scale names for poker templates
* Prompt questions + descriptions for retro templates
https://www.loom.com/share/0fa984491b7d457398536585630b1cbc
> feat(rid): Enhance search

- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
- packages/client/components/ActivityLibrary/TeamPickerModal.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
- packages/client/modules/teamDashboard/components/TeamDashMainRoot.tsx
- packages/client/schemaExtensions/clientSchema.graphql
- packages/client/utils/relay/setDefaultTeamId.ts
- packages/client/utils/relay/setPreferredTeamId.ts
Fixes https://github.com/ParabolInc/parabol/issues/8312
In the activity library, we default to the first alphabetically-ordered team, with preference to premium teams. This is different from the existing flow, in which if a user navigates to a team dashboard, that team is the default.
Add a new global client-side relay field called `defaultTeamId` that gets updated any time the user navigates to a team dashboard or selects a team from a dropdown. This team ID is then the default for other team dropdowns.
https://www.loom.com/share/c795617873d9437ca1e374dce17fdfee
> feat(rid): After navigating to or selecting a team, use that team by default

- packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
Fixes #8390
* start retro with team health
* advance to voting
* go back to grouping and press "Edit Groups"
> fix: reset retro groups with team health

- packages/server/utils/analytics/helpers.ts
- Start/Join/Complete a meeting with/without team health phase
- See in [Segment Debugger](https://app.segment.com/parabol-jordan/sources/action_local/debugger) to verify the `hasTeamHealth` property is added to the events
> chore(metrics): Add hasTeamHealth to meeting properties for meeting related events

- packages/server/utils/atlassian/jiraImages.ts
fixes #8400
HDEL is for deleting a specific key in a hash. DEL is for deleting the entire hash.
> fix: del instead of hdel

- CHANGELOG.md
- scripts/cleanup-changelog.sh
Add a script to cleanup the changelog, i.e. remove all `chore: `
prefixes etc.
- checkout uncleaned changelog and run the script
```
git checkout HEAD~ CHANGELOG.md
./scripts/cleanup-changelog
```
> chore: cleanup changelog

- packages/client/hooks/useGotoStageId.ts
Fixes https://github.com/ParabolInc/parabol/issues/7265
Our meeting flow allows users to skip between phases, as long as they navigated to the previous phase before. For example, a user could navigate group -> vote -> group -> discuss. However, our current navigation logic only executes "completion" side effects for stages/phases we just navigated from. In the above example, we wouldn't execute side effects for completing the "vote" phase because we navigated from group to discuss.
To fix this, check if we're skipping phases when navigating to a new stage, and execute side effects for any skipped stages.
https://www.loom.com/share/a467a9b8add045d28c1417e05c6e0070
> fix(retros): When skipping phases, mark interim stages as complete

- .github/workflows/build.yml
Using this in favor of #8229 to avoid the merge conflict.
Adds comments on how to build for ARM64
> chore: add comments for supporting multi-platform builds

- apollo.config.js
Now as we use [Official Relay GraphQL exetension](https://marketplace.visualstudio.com/items?itemName=meta.relay), we don't need this old apollo extension config hanging around
No demo
No testing scenarios
> chore: removed old apollo gql extension config

- packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
- packages/server/utils/stripe/StripeManager.ts
To handle 3D Secure cards, we're setting the payment behaviour to `default_incomplete` so that it's authorised on the client. While this works for the new payment flow, for the old flow, it results in subscriptions being incomplete. 
Merging this PR right away as it's using the old code, and I want to get this in before the ship.
> Remove default_incomplete payment behaviour for old subscription flow

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryCard.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryCardDescription.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Fixes #8385 
One thing worth noting - cards now have fixed aspect ratio so we're actually able to scroll the content. Also, I made all the spacing and sizing in various hover elements (for different categories) the same, it looked really odd with different icon sizes and spacing between icons and sizes. 
Depends on #8388 
https://github.com/ParabolInc/parabol/assets/1017620/d15b85e3-0ff1-4585-9c9a-fdc388633f09
> feat(activity-library): Show activity description when hovering over activity card

- packages/client/components/PrivateRoutes.tsx
- packages/client/components/ShareTopicModal.tsx
- packages/client/components/ShareTopicRoot.tsx
- packages/client/hooks/useModal.ts
- packages/client/hooks/useModalPortal.tsx
- packages/client/hooks/usePortal.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
Partially solves: #8232 #8234
**Demo**
https://www.loom.com/share/1302d78b31494ff8a02a20d6f8790a4d
**In this PR**
- Added `share topic` to the email summary (works both in the email and the website)
- Button opens a modal (Added routing and modal placeholder)
**Not included**
- Modal UI
- I have some scroll issue when modal is opened, going to look into it in next PR (Please let me know if you know what is going on)
**How to test**
- Add `shareSummary` org-level feature flag
- Run a retro and have some topics
- Click on `Share topic` button, see modal is opened and routing works fine
- Click on `Share topic` button from email, see modal is opened and routing works fine
> feat(share-summary): Add share topic button to meeting summary

- packages/client/components/BottomControlBarTips.tsx
> fix: types in meeting tips; prevent rendering undefined

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/server/graphql/public/typeDefs/MeetingTemplate.graphql
- packages/server/graphql/public/types/ReflectTemplate.ts
Fixes https://github.com/ParabolInc/parabol/issues/8365
Splits the "Retrospective" category into sub-categories:
* Popular templates
* You used these recently
* Others in your organization are using
* Try these activities
Since this is still pretty experimental, I didn't invest much time into making this code especially robust - if/when we decide to follow this sub-section pattern long-term, we'll want to clean this up a bit (e.g. make the subsections an enum instead of just a string, clean up DB calls, etc.)
https://www.loom.com/share/68dbae64ebfb4a88bd2381c23ce6b9dc
> feat(AL): Activity subsections for retros

- packages/client/mutations/CreateTaskMutation.ts
Fixes #8094 
Optimistic update was disabled because it threw an error. This happened because one of the fields was undefined while it should have been null.
https://www.loom.com/share/8500771c4b3048eaa45724ae553e4350?sid=599ca38f-fc7b-4b06-a775-60bd05e12935
- start a Sprint Poker meeting
- in scoping create a Parabol task
> fix: Fix optimistic update for create task in Sprint Poker

- packages/client/components/NewAzureIssueInput.tsx
- packages/client/components/NewGitHubIssueInput.tsx
- packages/client/components/NewGitLabIssueInput.tsx
- packages/client/components/NewJiraIssueInput.tsx
- packages/client/hooks/useTimedState.ts
- packages/server/graphql/public/types/CreateTaskPayload.ts
Fixes #6320 
When creating a Jira task in Sprint Poker failed, the error message wasn't send properly to the client. It also wouldn't be shown to the client.
If task creation failed, show the error message now for 5s.
This does not fix the underlying issue, but presents it to the user, so they hopefully can react accordingly or report more detailed errors.
https://www.loom.com/share/d798bb9765394f2a9097a51a1fea41e4?sid=6da48e5b-40ec-4599-88cc-36f3b51e4b8e
Run `node scripts/toolbox/postDeploy.js` if you're missing some of the integrations.
You can test error scenarios by adding a something like
```ts
return {error: new Error('Georg was here')}
```
in https://github.com/ParabolInc/parabol/blob/063a526dbcfd6340f4daa645c5875c679745519b/packages/server/graphql/mutations/helpers/createTaskInServ …
> fix: Show error message when creating Jira task fails

- .github/ISSUE_TEMPLATE/release_test.md
On master, I noticed that we can't create tasks: https://github.com/ParabolInc/parabol/pull/8472
We should add this to the release tests to catch this in the future (see [Slack thread](https://parabol.slack.com/archives/C836NA350/p1688407245901649?thread_ts=1687971553.304529&cid=C836NA350)).
> chore: add task and comment to release checks

- packages/client/modules/userDashboard/components/OrgBilling/OrgBilling.tsx
- packages/client/modules/userDashboard/components/OrgBilling/OrgPlansAndBilling.tsx
Fix https://github.com/ParabolInc/parabol/issues/8268
> chore: hide invoices for enterprise users

- packages/server/graphql/mutations/moveTeamToOrg.ts
Fixes https://github.com/ParabolInc/parabol/issues/8216
Set a hard limit on the `moveTeamToOrg` mutation to short-circuit to an error when the mutation is likely to time out.
This doesn't solve the underlying issue, but since this is an internal-only mutation, these guardrails should be sufficient. Once this lands, we could optionally convert the GH issue from a "bug" to "enhancement" (or create a new issue), with the AC being to solve the underlying issue and remove this guardrail, but such a task would probably be so low priority it'd likely be marked as "Closed - won't do" pretty quickly.
> fix: Limit number of teams that can be moved in one moveTeamToOrg call

- packages/client/mutations/CreateTaskMutation.ts
#8472 only reverted part of the fix for #8451 which reintroduced
#7943. Reverting fully until there is a fix for #8094.
- create a Parabol task in Sprint Poker scope phase
> fix: Fix create Parabol task in Sprint Poker

- packages/server/graphql/private/mutations/loginSAML.ts
- packages/server/package.json
- packages/server/utils/samlXMLValidator.ts
- yarn.lock
fix #8498
https://www.loom.com/share/8bb1ace6d4da4c3091daee1ef33046f8
testing performed in demo, probably not necessary to test it yourself, but if you'd like to...
To test that the memory leak is gone:
> chore: replace xml-lint due to mem leak

- packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
- packages/client/modules/userDashboard/components/OrgBilling/OrgPlanDrawer.tsx
- packages/client/mutations/handlers/upgradeToTeamTierSuccessUpdater.ts
- packages/client/schemaExtensions/clientSchema.graphql
- packages/client/subscriptions/OrganizationSubscription.ts
Fix https://github.com/ParabolInc/parabol/issues/8484
Loom demo: https://www.loom.com/share/c6099d36128a4cd593cd1a49126612b7
The problem in master:
- To handle 3D Secure cards, we have to separate the Stripe subscription logic from the upgrade logic. This is because the client need to authenticate the 3D Secure payment after the subscription has been created.
- After the subscription has been created, Stripe webhooks triggers `upgradeToTeamTier` which upgrades the org 
- After `createStripeSubscription` has complete, we show the right draw and confetti before `upgradeToTeamTier` has finished to give the user faster feedback (it's already pretty slow)
- When the right drawer initially shows, it shows the Starter tier info, not the Team tier info
Solution:
- Add a …
> fix: show correct drawer info after upgrade

- .circleci/config.yml
- .github/workflows/build.yml
- docker-compose.yml
- docker/parabol-ubi/docker-host-st/docker-compose.yaml
- packages/server/postgres/Dockerfile
pg v12 has some vulns when version is < 12.15.
this bumps pg to 12.15 for all deploys.
@adaniels-parabol can you confirm if 12.15 works for gov clients?
> chore: bump pg to v12.15

- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/8491
I used a newline delimiter as @jordanh suggested [here](https://parabol.slack.com/archives/C042HTVBH8D/p1688755623776749). 
I didn't include the text `If you can't provide a summary, simply write the word "No".` which is mentioned in the issue because I got the following response when summarising reflections which mentioned a bunch of random artists (something it can usually do without problems):
> fix: avoid pronoun assumptions in ai summary

- packages/server/graphql/private/mutations/upgradeToTeamTier.ts
- packages/server/graphql/public/mutations/updateCreditCard.ts
Fix https://github.com/ParabolInc/parabol/issues/8452
Demo: https://www.loom.com/share/8095302e24ec45ddb4c6df42009eab00
We need to get a failed invoice and then run `updateCreditCard` to charge the failed invoice. This is a hacky way of testing this; I'm open to any better ways.
> feat: retry invoice after failed payment

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopics.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ShareTopic.tsx
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
added utm params and reflectionGroupId to the segment event
- Add shareSummary org-level feature flag
- Run a retro and have some topics
- Click on Share topic button
- Share some topic
- Check that segment event is sent correctly
- Check that shared slack message has UTM params in its links
> chore(share-summary): add utm params and reflectionGroupId param

- packages/client/components/AddTeamMemberModal.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8519
When `inviteToTeam` returns an error, we weren't correctly catching and surfacing that error on the front-end.
Update types + check for errors better.
Perform repro steps in original issue.
> fix: Correctly show error when email invite fails

- packages/server/utils/stripe/StripeManager.ts
Fix: https://github.com/ParabolInc/parabol/issues/8544
Credit to @mattkrick for helping me with this during office hours. 
Sorry, this includes the updated changelog from the Ship. It'll end up in master shortly, so I think it's OK leaving it here.
This PR will increase the time it takes to upgrade as there could be a few retries. I've created a GitHub issue here to sped things up: https://github.com/ParabolInc/parabol/issues/8546
- Run `stripe listen --forward-to localhost:3000/stripe` in your terminal
- Upgrade to Team tier a few times using the new checkout flow
- You don't see the console error message mentioned in the linked issue
> fix: stripe console err

- packages/client/components/DashNavList/DashNavList.tsx
- packages/client/components/TimelineEventTeamCreated.tsx
- packages/client/modules/summary/components/NewMeetingSummary.tsx
- packages/client/modules/teamDashboard/components/TeamArchiveHeader/TeamArchiveHeader.tsx
- packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
- packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
- packages/client/modules/teamDashboard/components/TeamDashMain/TeamDashMain.tsx
- packages/client/modules/teamDashboard/components/TeamDashTasksTab/TeamDashTasksTab.tsx
- packages/client/modules/teamDashboard/containers/Team/TeamContainer.tsx
- packages/client/modules/teamDashboard/containers/TeamTasksHeader/TeamTasksHeaderContainer.tsx
Fixes #8502 
Add a tab for meetings to the team dashboard. The default view is still "Tasks" to not interrupt users habits too much.
https://www.loom.com/share/d3a5e74fd16842d387c59648f3539a48?sid=92906de6-0297-4f1e-b09d-bb9c62e9fe48
> feat: Add meetings to the team dashboard

- pm2.dev.config.js
`yarn pg:build -w` would keep the node process running after pm2 was killed. Switched to use the watch mode from pm2 instead so we don't run out of PG connections while developing.
- run `yarn dev` a couple of times and kill it again by ^C
- check `ps aux | grep pgtyped` and see no running process
> chore: fix open pgtyped connections after running `yarn dev`

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
L&E Squad has decided to roll out the Activity Library to all new P0 users. Instead of adding only 5% of new P0s to the flag, add all new P0s to the flag.
For non-P0 signups (i.e. another user already exists with the same company domain), we'll continue using domain affinity (user will be added to the flag iff another user in the domain has the flag).
> feat(al): Roll out Activity Library to all new users

- packages/client/components/Tooltip.tsx
- packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
- packages/server/database/types/Meeting.ts
- packages/server/graphql/mutations/endCheckIn.ts
- packages/server/graphql/mutations/endRetrospective.ts
- packages/server/graphql/mutations/endSprintPoker.ts
- packages/server/graphql/mutations/helpers/collectReactjis.ts
- packages/server/graphql/mutations/helpers/collectTeamInsights.ts
- packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
- packages/server/graphql/mutations/helpers/updateTeamInsights.ts
- packages/server/graphql/public/typeDefs/TeamInsights.graphql
- packages/server/graphql/public/types/Team.ts
- packages/server/postgres/migrations/1689949187848_addTeamInsights.ts
Fixes #8465
At the end of a meeting, count the used emojis and add them to the
insights.
https://www.loom.com/share/f040d0e3cb274754bcfb9f2fd0fa9878?sid=ef83dfb1-7105-40d3-a8dc-01ff88d8c31f
> feat: add emoji insights

- packages/server/__tests__/inviteToTeam.test.ts
- packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
Looking at [Amplitude](https://app.amplitude.com/analytics/parabol/chart/xv8lafw7/edit/v85plt3b), spammers have been sending almost all of the invites to @qq.com. This PR modifies the trust score logic to also look at domains from the invitees.
> fix: do not trust invites sent to emails from the untrusted domains

- packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
Fixes #8582
Highlight the correct tab
- Go from the meeting dash to the team dashboard
- See the activity tab being selected and shown
> fix: change default tab to activities in team dash

- packages/client/utils/features/isTeamHealthAvailable.ts
Fixes #8589 
Ignore the wtf moment at the end, this will be fixed in #8588 separately.
https://www.loom.com/share/aaaf0d924e7642a0a16cf48922fa7575?sid=dc6c7995-c7d8-4cda-9e0d-73e53d5e019d
- on **master** create a retro with team health with a starter team
- checkout **PR**
- check that existing meeting still works
- see Team Health option is not present anymore in meeting settings
- new retro does not have Team Health phase
- check that Team Health can still be …
> chore: Restrict Team Health phase for starter tier

- scripts/toolboxSrc/preDeploy.ts
- scripts/toolboxSrc/primeIntegrations.ts
- scripts/toolboxSrc/standaloneMigrations.ts
fix #8523
See https://github.com/ParabolInc/parabol/issues/8523#issuecomment-1638641082 for logs & how to reproduce in test
> fix: exit code 1 on preDeploy failure

- packages/client/modules/demo/initDB.ts
- packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
- packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Previously `AIGeneratedDiscussionPrompt` is a user-level feature flag. This PR makes it also an org-level feature flag so we can roll out to non-Parabol orgs/users.
> fix: make AIGeneratedDiscussionPrompt org level feature flag

- .github/workflows/build.yml
Build Github Action was broken due to a exit code 137 in the command `yarn build --no-deps` which means JVM Heap memory limit for the max_old_space_size. Setting max_old_space_size to 8192 only changed the exit code to 134 which means not enough memory.
After some testing, it was required to increase the RAM available on the system, and not only the Heap parameters. A new Github Large Runner was created with 8 cores and 32 GB RAM. Even with that, the max_old_space_size must be set to 8192 to make it build correctly.
Since [this commit](https://github.com/ParabolInc/parabol/actions/runs/5727737418) the build process takes longer and requires more memory. Before it took about 3m40s and now, even in a more powerful machine, it takes about 4m10s. Also, before it worked in 16 GB RAM machines …
> fix(pipeline): increase size of the runner used for the build action

- packages/server/postgres/migrations/1691421540088_updateRetroReflectionGroupSortOrderType.ts
Fix https://github.com/ParabolInc/parabol/issues/8598
We moved the `RetroReflectionGroup` table to pg in https://github.com/ParabolInc/parabol/pull/8504 and defined `sortOrder` as an `INT`, but it can be a float.
An alternate approach would be to ensure that `sortOrder` is always an integer. Perhaps @mattkrick knows whether the `sortOrder` is accidentally or deliberately a float?
Demo: https://www.loom.com/share/435ac05016ee4fb489b525f2caee2c02
> fix: unable to ungroup some reflection groups

- packages/server/database/migrations/20230801200811-fixOrganizationTier.ts
- packages/server/postgres/migrations/1691422128820_fixOrganizationTier.ts
Fixes #8507 
When we changed the names of our plan tiers in #7505, there were two organizations created while the migration `20221220161224-updateTier.ts` was running that are left with the old `personal` tier name.  This migration cleans up those tier values, and migrates them to the new `starter` tier name.
> chore: Cleanup old starter tier organizations

- packages/server/graphql/mutations/selectTemplate.ts
Fixes https://github.com/ParabolInc/parabol/issues/8570
On master, repro the issue:
On this branch:
> fix: Remove check for whether template was updated

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
- packages/client/mutations/EndTeamPromptMutation.ts
- packages/client/subscriptions/MeetingSubscription.ts
- packages/server/graphql/mutations/helpers/canAccessAISummary.ts
- packages/server/graphql/mutations/helpers/generateDiscussionSummary.ts
- packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
- packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
- packages/server/graphql/mutations/helpers/generateWholeMeetingSummary.ts
- packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
- packages/server/graphql/mutations/helpers/updateQualAIMeetingsCount.ts
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/typeDefs/Subscriptions.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
- packages/server/utils/OpenAIServerManager.ts
Fixes https://github.com/ParabolInc/parabol/issues/8568
Implement AI Summaries for standups. Instead of prompting the model for an _overall_ summary, prompt the model to identify up to 5 themes found in responses, and provide brief summaries for those.
Reuse UI components for simplicity.
This is the summary from several responses in our own July 17th Friday ship (copy-pasted to a local standup meeting).
A different summary in slack:
> feat(standups): Standup AI Summaries

- packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationList.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/SlackNotificationRow.tsx
- packages/server/database/types/SlackNotification.ts
- packages/server/graphql/mutations/addSlackAuth.ts
- packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
- packages/server/graphql/mutations/helpers/notifications/Notifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
- packages/server/graphql/types/SlackNotificationEventEnum.ts
Fixes https://github.com/ParabolInc/parabol/issues/8606
When a user submits their standup response, send a message to slack with a direct link to their response.
To minimize scope, only supports slack for now.
> feat(standups): Notify slack when user submits standup response

- .github/workflows/build.yml
force CI=true for CI. Allows us to get rid of the env var kept in GH.
> chore: CI=true in tests

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
- packages/server/graphql/public/types/User.ts
- packages/server/utils/sendToSentry.ts
see [slack](https://parabol.slack.com/archives/C042HTVBH8D/p1691596459048329) 🔒 
If a user has access to more than 200 activities, we won't return all of their activities to the client. Sometimes, this means that even basic activities like check-ins won't be shown on the client.
Bump up the max number of activities we return to 2000, and send an error to sentry if we ever see more than 1000 activities.
Also add an `extras` field to our sentry util for capturing additional non-tag context (in this case, number of activities seen).
Smoke test AL.
> fix(al): Number of activities exceeds number requested

- packages/client/utils/SlackManager.ts
- packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Fixes https://github.com/ParabolInc/parabol/issues/8608
When a standup meeting ends, post the submitted responses in a thread on the "meeting ended" slack message.
Only do this in slack for now to minimize scope.
Needs rebase once https://github.com/ParabolInc/parabol/pull/8607 lands.
With responses:
Without responses:
> feat(standups): Post standup responses in 'meeting ended' message thread

- packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
- packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
Fix https://github.com/ParabolInc/parabol/issues/8628
Loom demo: https://www.loom.com/share/bbfd53b43b59418eb152321be0023a14
> chore: active plan visual cue

- packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
- packages/client/components/TeamPrompt/TeamPromptResponseEmojis.tsx
Fixes #7458 
It was simply caused by rerendering whole response card component instead of just emoji part, when emoji is added/removed.
No demo
a. Join as user A, add response
b. Join as user B from different window, add response
c. In the user's A window scroll so the response current window user isn't visible
d. In the user's B window add reaction to the user's A response
e. User's A window isn't scrolled
> fix: prevent scroll jump when emoji is added 

- packages/client/components/ShareTopicRoot.tsx
- packages/client/components/ShareTopicRouterRoot.tsx
Looks like for some users share topic modal can't see the slack integration added
This should probably fix it
> fix: fix share topic modal can't see slack integration

- packages/client/mutations/UpsertTeamPromptResponseMutation.ts
Fixes an issue with undefined emoji list when adding initial standup response
No demo
> fix: optimistic updater in UpsertTeamPromptResponseMutation 

- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/8621
Here's a long-winded demo where I look through the reflection groups from the recent Growth Retro: https://www.loom.com/share/41e45efd828d49378db820582d6b4423
> chore(suggest-groups): increase number of suggested groups

- scripts/toolboxSrc/modules.d.ts
- scripts/toolboxSrc/preDeploy.ts
- scripts/webpack/prod.servers.config.js
Fix #7557
I use the `sha:` prefix in the logs because that's how you search by hash in github so it makes for easy copypasta.
```
🚀 Predeploy Started v6.115.0 sha:568070ed9f899b93cef4abd2640b6a0021eca27c
```
TEST
> chore: add version and sha to predeploy logs

- packages/server/createSSR.ts
- scripts/codegenGraphQL.js
After a fresh clone of the repo I noticed that the app wasn't building in dev mode. All our CI tests only run in prod mode, so they didn't catch this.
No demo, the app just starts
> fix: build in dev mode from clean clone

- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
There are two different sets of emojis in use in the app: emoji-mart for reactions and a custom list used for emojis in tasks and responses. Team Insights shows only reactions, but used the other list to convert the text to an emoji.
- with feature flag enabled, react with :thinking_face: more than 4 times and end the meeting to make it show up in insights
- make sure another emoji has been used 5 or more times as well so the card shows up in insights
- check it's shown correctly in team insights
- alternatively with the feature flag set, just manually set the "Team.mostUsedEmojis" column to
```
[
{
"id": "heavy_plus_sign",
"count": 13
},
{
"id": "thinking_face",
"count": 5
}
]
```
> fix: Show Team Insights emojis correctly

- .github/workflows/build.yml
- package.json
- scripts/webpack/dev.client.config.js
- scripts/webpack/prod.client.config.js
- scripts/webpack/prod.servers.config.js
- yarn.lock
`yarn build --no-deps` is currently broken. 
The reason why is because `process.env.DEBUG` is set to false & we have a package which mutates it. So, that means `process.env.DEBUG = false` gets compiled to `"false" = false`. I assume this worked in the past because that bit of code probably got tree-shaken, but now some upgraded nested dependency is using it.
After I fixed that, I noticed I couldn't build with `--no-deps` locally because I kept running out of memory, so i bumped up the memory in node when building in prod.
> fix: terser in prod build

- packages/server/graphql/mutations/segmentEventTrack.ts
- packages/server/utils/segmentIo.ts
fixes #8674
We had a PPMI who does not use segment get segment-related errors in their server logs. This should fix that.
> fix: exit early if no segment write key

- packages/client/components/PokerEstimateHeaderCardContent.tsx
- packages/client/components/promptResponse/PromptResponseEditor.tsx
Linked text can be in Standup response cards, thread comments, task cards, and in Poker item descriptions. We wanted to normalize the minimal styles, links use:
- Body color (Slate 700)
- Text decoration underline
- Have an outline on tab (this is the browser default)
This PR adds the text decoration to the Poker item description and updates the color of links in Standup response cards
> style: Normalize link styles

- packages/client/components/ReflectionCard/ReactjiCount.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
- packages/client/utils/getReactji.ts
TeamDashInsights and ReactjiCount both uncompressed the emojies provided by emoji-mart. This caused occasional exceptions. Moving this to a helper instead used by both.
no demo
- have a team which shows emoji insights
- start a meeting and add some reactions
- see no exception
> fix: Uncompressing emojies twice causes a failure

- packages/client/components/promptResponse/PromptResponseEditor.tsx
Support `HorizontalRule` (`<hr/>`) nodes in tiptap.
See https://parabol.slack.com/archives/C03LL1JRFH8/p1692299915145879
Normal:
Selected:
Type `---` on a new line in a standup and confirm you see a horizontal rule.
Confirm styles when selected.
> fix(tiptap): Show <hr/> nodes

- packages/client/components/RetroMeetingSidebar.tsx
- packages/server/database/types/ReflectPhase.ts
- packages/server/database/types/TeamHealthStage.ts
Fixes #8077
Open the reflect phase even if the facilitator is still on icebreaker or team health.
https://www.loom.com/share/a076b547d34c42999662a6e32ef75bce?sid=d5abac53-7773-4b43-a329-ff8ac6d95d3e
- start a retrospective with icebreaker or team health phase as facilitator Frank
- join with a non-facilitator user Nordberg
- Nordberg can advance to team health and reflect phase while Frank is still on icebreaker
> chore: Allow non-facilitator to advance to reflect phase

- packages/server/utils/OpenAIServerManager.ts
At first I tried a step approach and that worked pretty well. I then asked ChatGPT to improve my prompt:
I then borrowed the last bit of the improved prompt.
I'm taking this discussion thread from production as a test case:
Using the prompt in Playground, together with the parameters we set, I can get shorter summary consistently:
In the app:
> fix(ai-summary): update the prompt to emphasize brevity

- packages/client/components/promptResponse/PromptResponseEditor.tsx
- packages/client/components/promptResponse/loomExtension.ts
- packages/client/components/promptResponse/tiptapConfig.ts
Fixes https://github.com/ParabolInc/parabol/issues/8659
Implement a read-only Loom extension - when loom links are present in a standup response, add a Loom TipTap node immediately after the paragraph containing the link.
Because this is read-only, other users will always see the expanded Loom embeds, while the author will only see them in closed meetings and the discussion drawer.
Do nothing for summaries, though we could leverage Loom gif thumbnails if we wanted to.
What the author sees:
What the reader sees:
Discussion drawer (both author and readers see this):
> feat(tiptap): Loom embed extension

- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
- packages/server/graphql/public/typeDefs/Team.graphql
- packages/server/graphql/public/types/Team.ts
Fix https://github.com/ParabolInc/parabol/issues/8636
Demo: https://www.loom.com/share/30ebfc16554e41b2bdcbece0d9eba1a8
> feat(gcal): unauthed schedule button ux

- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeetingSettingsRetrospective.tsx
- packages/client/components/NewMeetingSettingsRetrospectiveSettings.tsx
- packages/client/components/NewMeetingSettingsToggleTeamHealth.tsx
- packages/client/components/NewMeetingSettingsUpgradeForTeamHealth.tsx
- packages/client/components/Tooltip.tsx
- packages/server/graphql/types/UpgradeCTALocationEnum.ts
> chore: Show disabled Team Health option to Starter tier

- packages/client/components/IconLabel.tsx
- packages/client/components/TeamPrompt/TeamPromptDiscussionDrawer.tsx
- packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
- packages/client/components/TeamPrompt/TeamPromptOptions.tsx
- packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/components/TeamPrompt/TeamPromptWorkDrawerRoot.tsx
- packages/client/components/TeamPromptMeeting.tsx
- packages/client/schemaExtensions/clientSchema.graphql
- packages/client/styles/helpers/cardRootStyles.ts
Fixes https://github.com/ParabolInc/parabol/issues/8679
Implement the "Your tasks" drawer to show a user's Parabol tasks within a standup meeting, and update the topbar with the new "your tasks" button.
This PR does a few things to implement this:
1. Refactor the existing `TeamPromptDiscussionDrawer` into a `TeamPromptDrawer` and a `TeamPromptDiscussionDrawer`. The `TeamPromptDrawer` acts as the container for any components that exist in the drawer, handling things like overlay vs static sidebar, sliding in/out, etc.
1. This is a sizeable chunk of the overall diff.
3. Adding a new `TeamPromptWorkDrawer` to hold all "your work" components, starting with Parabol tasks.
4. Refactors + updates components in the `TeamPromptTopBar` to match updated designs.
**I recommend reviewers review with …
> feat(standups): "Your tasks" drawer with Parabol tasks

- packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
- packages/server/graphql/types/SegmentEventTrackOptions.ts
Fixes #8466
Add a team insights card with buttons for "Is this helpful?". Clicks are tracked via `sendSegmentEvent`.
Because this alone would not give any feedback to the user, I thought about how we could preserve the fact that they've voted already. The best solution would be to store the information in the `TeamMember`, but that would require the additional field, it would need to get queried and we'd need to have a custom mutation just for the button highlight.
I've chosen a simpler approach to just store it in local state of the component, so the user sees that something had happened, but next time they're free to vote again.
https://www.loom.com/share/0530da3c9dd047be81c871a1866f15c2?sid=9ade9d27-45af-4b70-a9ab-5dbb0320b4d3
```
[
{
"id": "heavy_plus_sign",
"count": 13
},
{
"id": …
```
> feat: Add "Is this helpful?" for insights

- .circleci/config.yml
Changes the DNS domain for Staging components from action-staging.parabol.co to action-staging.parabol.fun.
> chore(ci): CircleCI using the new staging domain action-staging.parabol.fun

- packages/client/utils/getAnonymousId.ts
Fixes #8725 
The ad blocker (like uBlock origin) are blocking a call to `gtag` which never resolves and thus leaves the app hanging with the popup window blank. Added a timeout for the call.
https://www.loom.com/share/3f301ab7d4f34525af3201161184e393?sid=ca8e275e-2177-4c5c-a882-2f7f98135784
> fix: Allow login with google with ad blocker enabled

- packages/client/modules/outcomeCard/components/TaskFooterTeamAssigneeMenuRoot.tsx
An incorrectly rendered Suspense fallback causes us to throw an error in the "Your Work" drawer when a user attempts to select a different team in a parabol task card.
It seems like this only manifested now because other parts of the app using this component already have this data loaded, and therefore never suspends.
Interestingly, TS doesn't catch this - not sure why not.
> fix(standups): Selecting team in Parabol card throws error

- packages/client/mutations/StartRetrospectiveMutation.ts
- packages/server/dataloader/customLoaderMakers.ts
- packages/server/graphql/mutations/startRetrospective.ts
- packages/server/graphql/mutations/startSprintPoker.ts
- packages/server/graphql/public/types/ReflectTemplate.ts
- packages/server/postgres/migrations/1692650094687_TeamMeetingTemplate.ts
- packages/server/postgres/queries/updateMeetingTemplateLastUsedAt.ts
fix #8581 speeds up queries for recently used activities
Before merging I think we should add in a little extra logic so templates can't appear in both popular and recently used, but I wanna leave out changes until we like the refactor.
No visual difference 😕 
https://www.loom.com/share/e64150215e9d4067bd6c8232f48d4b8c?sid=1b6e632a-b893-48d2-97b1-1cecd0442ac1
> chore: first pass at lastUsedAt caching

- packages/client/mutations/AcceptTeamInvitationMutation.ts
- packages/client/types/constEnums.ts
- packages/server/graphql/public/mutations/acceptTeamInvitation.ts
- packages/server/graphql/public/permissions.ts
Fixes #8669 
Before this fix the wrong error would be shown when a user followed an invitation link but then failed to sign in. Now we're not throwing a permission exception anymore in `acceptTeamInvitation` if the caller is not signed in, but instead return an error result. This way we can handle it on the client side and the return of the login mutation is not lost.
https://www.loom.com/share/98da2c53aae444e88cb7243cff504427?sid=08dd92d4-c5d3-421c-ba40-3cfe156d264d
> fix: Show correct error message on login failure with invitation

- packages/server/billing/helpers/adjustUserCount.ts
- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
- packages/server/graphql/private/mutations/connectSocket.ts
- packages/server/graphql/public/mutations/updateUserProfile.ts
- packages/server/utils/analytics/amplitude/AmplitudeAnalytics.ts
- packages/server/utils/analytics/analytics.ts
- packages/server/utils/analytics/segment/SegmentAnalytics.ts
- packages/server/utils/setUserTierForUserIds.ts
Fixes #8680.  As part of our migration to Amplitude for analytics, this PR centralizes all `identify()` calls in analytics.ts instead of calling `segmentIo` directly, and makes `identify()` calls to Segment and Amplitude in parallel.  Segment writes will later be removed when we address #8677.
- Get the development environment Amplitude write key from [here](https://app.amplitude.com/data/parabol/Parabol%20Production/sources/development) and save as the env var `AMPLITUDE_WRITE_KEY`
- Open any page and verify that the `Connect Websocket` event fires in both:
- Check that the `identify()` calls work properly by:
> chore(analytics): Route analytics identify calls through analytics.ts

- scripts/cleanup-changelog.sh
cleanup-changelog.sh fails on mac os with an error:
```
sed: 2: "
s/^- ([A-Z]\w*): /-  ...": \1 not defined in the RE
```
> chore: fix cleanup-changelog.sh on mac os

- docker/Dockerfile.prod
- docker/parabol-ubi/docker-build/dockerfiles/pipeline.dockerfile
queryMap is now imported through the native JS `import` syntax so we don't have to issue a filesystem read. That means we no longer need queryMap.json in the docker image.
Check out CI, if it passes, it should work!
> chore: docker rm queryMap

- packages/server/types/modules.d.ts
- packages/server/utils/updateGQLSchema.ts
- scripts/toolboxSrc/modules.d.ts
- scripts/webpack/dev.servers.config.js
- scripts/webpack/prod.servers.config.js
- scripts/webpack/toolbox.config.js
Fixes #8202
`__PROJECT_ROOT__` is no longer possible since we are doing so much work in predeploy vs build
If it builds in CI, it works!
> chore: remove __PROJECT_ROOT__

- packages/server/graphql/public/mutations/acceptTeamInvitation.ts
- packages/server/safeMutations/acceptTeamInvitation.ts
Fixes #8668
When an invite was accepted a second time, we did try to return the team and meeting information regardless of whether or not the user was still on the team. This was checked further down in the GraphQL tree, but can result in misleading errors in Sentry. Checking for this particular case now to see if it still shows up for users down the road which might cause to a real bug somewhere.
https://www.loom.com/share/2e945766e47548e7ab586b28a8c78eee?sid=28d68b0e-191d-4ee7-8099-3c9635ab6552
> fix: Check if team member status on accepting an invite twice

- packages/client/utils/SlackManager.ts
- packages/server/database/types/Meeting.ts
- packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
- packages/server/graphql/mutations/helpers/notifications/Notifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/mutations/renameMeeting.ts
- packages/server/utils/sendToSentry.ts
We send the Slack message on meeting creation and only afterwards allow to rename it. Store the `ts` of the meeting started notification and update the message if a meeting is renamed.
https://www.loom.com/share/97aac89a69444585bb7355a60d9e300b?sid=0261ca0c-a3d5-4248-83a8-3e32aa10a0da
This only works on new meetings
- integrate with Slack
- create a meeting
- see the Slack message
- rename the meeting
- see the Slack message being updated with the new name
> feat: Update Slack message on meeting rename

- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/makeSlackBlocks.ts
- packages/server/package.json
- packages/server/utils/tiptap/convertToMarkdown.tsx
- yarn.lock
Fixes #8651
Testing scenarios assume Slack is already integrated
> feat(standups): rich text in slack notifications

- packages/client/modules/userDashboard/components/GcalModal/DateTimePickers.tsx
- packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
- packages/server/graphql/mutations/helpers/createGcalEvent.ts
- packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
- packages/server/graphql/public/types/CreateGcalEventInput.ts
Fix https://github.com/ParabolInc/parabol/issues/8714
Demo: https://www.loom.com/share/9923a47d690d4e26ad5369faaa6fc94c
> fix(gcal): handle Zoom add-on conflict

- packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
Fixes #8704 
https://www.loom.com/share/4a8ddfe7851e4bff978bfef2421e99a5?sid=3dca0e4f-7ebb-452d-ae14-0b4bdd044168
> fix(checkin): prevent newly added agenda item to be accessible when `agendaitems` phase has not been started yet

- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Fixes `Your tasks` btn bg on standups meetings
before
after
nothing to test
> fix: removed default button background from your tasks button

- nginx.conf.sigil
Right now, https://action.parabol.co/robots.txt has `Allow: create-account` instead of `Allow: /create-account`, which is blocking the create account page from being indexed by Google (and other search engines).  Fixing this should help drive more organic search signups.
N/A, I believe we only run NGINX on dokku, not when developing locally.
> chore: Allow google to index /create-account

- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/components/ThreadedTaskBase.tsx
- packages/client/containers/TaskCard/DraggableTask.tsx
- packages/client/modules/teamDashboard/components/TeamArchive/TeamArchive.tsx
- packages/client/styles/helpers/cardRootStyles.ts
> fix: allow to set task max-width

- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
> fix: filter tasks that are being created by different users in your work drawer

- packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
…enda items phase has not been started yet (#8799)"
This reverts commit 4ce50eeacf257b7de65d07bdaba0f34967227c09.
With #8799 adding agenda items from first call if there are none already makes the meeting non-navigatable.
> fix: make new agenda items accessible from first call phase

- packages/server/utils/analytics/analytics.ts
- packages/server/utils/segmentIo.ts
Fixes a memory leak.
Note, this should not be a long term fix! This is just to keep our app from crashing.
Long term fix is here: https://github.com/ParabolInc/parabol/issues/8840
https://www.loom.com/share/7491a7ea6d0247649d700c555ab0c959
> fix: remove memory leak from analytics

- packages/server/graphql/mutations/helpers/addAgendaItemToActiveActionMeeting.ts
Fixes: #8799 
Fix navigating to a newly created agenda item in "first call".
https://www.loom.com/share/108626a1e1b8401dab8e9e7ac9a646e8?sid=6432f262-21b8-46bb-946f-0176701d2573
- start a checkin with no agenda items
- move to first call
- add an agenda item
- see you can navigate there
> fix(check-in): fix navigating from first call to a new agenda item

- packages/server/graphql/public/types/User.ts
Fixes https://github.com/ParabolInc/parabol/issues/8848
Move the "standup" meeting type to the top of the quick start view in the activity library.
> feat(al): Show standup meeting type first in all views

- packages/server/billing/helpers/updateSubscriptionQuantity.ts
- packages/server/graphql/private/mutations/stripeCreateInvoice.ts
Fixes #8104.
The fix introduced by #8105 didn't catch all cases, and we've continued to see some enterprise subscriptions updated with AU counts over the last few months.  This change moves the check to the `updateSubscriptionQuantity` function itself, and early exits if the tier of the org we are asking to update is an enterprise org.  It also removes the now unnecessary check introduced in #8105 in `stripeCreateInvoice.ts`.
Repeat testing steps from #8105.
> fix(billing): Stop updating Enterprise Stripe subscription quantities to AU count

- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8869
> fix(standups): 'Your tasks' -> 'Your work'

- packages/client/components/TeamPrompt/TeamPromptOptionsMenu.tsx
See [slack discussion](https://parabol.slack.com/archives/C042HTVBH8D/p1695159030945889) 🔒 
Add a standup meeting option menu item for "slack configuration" that links to the team's integrations page.
Also add metrics for when this option is clicked (note: this won't fire if the user specifically opens the link in a new tab instead of clicking)
> feat(standups): Add slack configuration link to standup options

- packages/server/package.json
- packages/server/utils/OpenAIServerManager.ts
- yarn.lock
Fix https://github.com/ParabolInc/parabol/issues/8737
https://github.com/ParabolInc/parabol/issues/8737 mentions that during a meeting, some of the AI features were showing up and some weren't. I agree with @tianrunhe that there may have been a timeout issue. There are plenty of threads (like [this one](https://community.openai.com/t/resolved-is-gpt3-5-api-timing-out-a-known-issue/106094)) where people report performance issues.
Looking at the [usage data](https://platform.openai.com/account/usage), I don't see us hitting any rate limits. I also don't see any recent 429 errors in Sentry. 
I don't see why any potential timeouts would be connected to the meeting crashing, though, as we're handling errors safely. 
Upgrading to the latest version of `openai` may help with the AI performance …
> chore: upgrade openai

- packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
- packages/client/components/TeamPromptMeeting.tsx
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Fixes https://github.com/ParabolInc/parabol/issues/8865
Standup responses are pretty narrow for our own internal Friday Ship updates, leading to updates that can take up the entire height of the screen (or more), which can be annoying.
Add a feature flag for showing these responses in a single column. We'll use this internally, and roll out to everyone if we decide that's what we want to do. Alternatively, we could potentially add a "grid vs. list" option for each user, persisted on the client-side.
> feat(standups): Display responses in single column (feature flagged)

- packages/client/modules/demo/initDB.ts
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
- packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
- packages/server/utils/isRequestToJoinDomainAllowed.ts
Fixes #8274 
Reverse the feature flag and include checking the feature flag when finding eligible orgs.
The check was accidentally removed previously in #8798 
no demo
- check with eligible org without feature flag
- see prompt to join org request
- add feature flag
- recheck
> feat(Prompt to join org): reverse feature flag

- packages/client/modules/teamDashboard/components/TeamDashInsights/MeetingEngagementCard.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamDashInsights.tsx
- packages/server/database/types/Comment.ts
- packages/server/database/types/Meeting.ts
- packages/server/database/types/Reflection.ts
- packages/server/database/types/ReflectionGroup.ts
- packages/server/graphql/mutations/endCheckIn.ts
- packages/server/graphql/mutations/endRetrospective.ts
- packages/server/graphql/mutations/endSprintPoker.ts
- packages/server/graphql/mutations/helpers/calculateEngagement.ts
- packages/server/graphql/mutations/helpers/gatherInsights.ts
- packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
- packages/server/graphql/mutations/helpers/updateTeamInsights.ts
- packages/server/graphql/public/typeDefs/TeamInsights.graphql
- packages/server/graphql/public/types/Team.ts
Fixes #8468
Calculate the engagement at the end of each retro, standup and poker meeting. Show the insights for all meetings combined over the last 30 days.
The meeting engagement is stored on each meeting individually allowing us to tweak the thresholds of what can be considered low or high engagement.
I considered >80% as high engagement, <= 60% as low by imagining a 5 person team. If 2 people do not participate that's low, if 1 does not participate it's average, if all participate it's high.
https://www.loom.com/share/35fbd6e60c594a82b79c2521bdd5223d?sid=a52120e6-d74e-4644-8bd1-cf5687ab3eb1
* add `teamInsights` org flag
* run a **retro**, **standup** and **poker** with only the facilitator, see no engagement is shown
* run **retro** with 1 additional participant who does nothing, see …
> feat(Team Insights): add meeting engagement insights

- packages/server/graphql/mutations/helpers/createGcalEvent.ts
- scripts/toolboxSrc/primeIntegrations.ts
Use the Google oauth credentials instead of gcal. 
While building the Gcal integration, I initially created a new Gcal Project and used those credentials. Now we're using the existing Parabol project, so we can use those credentials instead.
The ship is happening shortly, and as this PR is very small and low risk, I'll merge it right away and tag @mattkrick so that you've seen it.
> chore: use google creds instead of gcal

- .github/workflows/build.yml
Adds the branch `release` to the build pipeline so it will build the Docker image for that branch as well.
Later, once in the new environment, branches production and staging should be removed from the build action and from the repository.
> chore(ci): adding release branch to the build action

- packages/server/graphql/mutations/helpers/createGcalEvent.ts
- scripts/toolboxSrc/primeIntegrations.ts
Use the Google oauth credentials instead of gcal.
While building the Gcal integration, I initially created a new Gcal Project and used those credentials. Now we're using the existing Parabol project, so we can use those credentials instead.
> chore: change gcal creds to google creds

- packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
- packages/server/graphql/mutations/helpers/createGcalEvent.ts
- scripts/toolboxSrc/primeIntegrations.ts
This PR updates the Google calendar modal description to make it clearer that we'll create a Google Calendar event.
> chore: update gcal modal description

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryHeader.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Implements @avivapinchas's [idea 🔒](https://parabol.slack.com/archives/C03NGEJUKCN/p1695749810137199)
> feat: added meeting link to a meeting summary

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/TeamPromptResponseSummaryCard.tsx
Fixes an issue with standup summary formatting caused by #8884
The issue was caused by playing with various properties in order to improve the email layout see the wrong margin on the right here
it was present before the the changes and I'll address it later. 
No demo
> fix: standup meeting summary layout

- .github/workflows/build.yml
- scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
- scripts/webpack/prod.servers.config.js
fix #8834
since index.html doesn't exist in the docker image, we need to generate it wherever `node dist/web.js` is called.
N/A
> feat: add support for multi-replica deploys

- packages/server/PROD.ts
- packages/server/graphql/CompiledQueryCache.ts
- packages/server/graphql/DocumentCache.ts
- packages/server/graphql/executeGraphQL.ts
- packages/server/graphql/handleGraphQLTrebuchetRequest.ts
- packages/server/graphql/private/mutations/disconnectSocket.ts
- packages/server/listenHandler.ts
- packages/server/postgres/getPgConfig.ts
- packages/server/postgres/migrations/1692638249976_isOneOnOneTeam.ts
- packages/server/server.ts
- packages/server/utils/analytics/amplitude/AmplitudeAnalytics.ts
- packages/server/utils/segmentIo.ts
- scripts/migrate.js
fix #8627
`__PRODUCTION__` is a webpack variable that is calculated at build time. 
Since this var is a constant at runtime, webpack can tree shake conditional branches & remove bits of unreachable code, e.g. `if (!__PRODUCTION__) doThing()` gets removed entirely & `doThing()` may also get removed if it is not used elsewhere.
If CI passes it works!
> fix: move PRODUCTION bool to build time

- .github/workflows/build.yml
draftEnterpriseInvoice will fail the build action if `process.env.CI !== 'true'`. this occurs whenever an outsider triggers the build because today we have `CI=true`in our repo env vars.
TEST
> fix: CI=true for build action

- .github/workflows/build.yml
- packages/client/components/Action/Action.tsx
fixes #8925
Demo was performed stubbing in `v6.1220.0-exotic` for version & removing the `if:` clause in the yml
> chore: test sentry and dd uploads

- packages/server/graphql/private/mutations/loginSAML.ts
Support Microsoft Entra ID (formaly Azure Active Directory) out of the box. They're sending `emailaddress` and `name` prefixed with the http://schemas.xmlsoap.org/ws/2005/05/identity/claims/ namespace. Map those to values we expect.
Instead of stripping all URI prefixes, I decided to just map these explicitly to avoid cases where there could be duplicate values in different namespaces (although extremely unlikely)
https://www.loom.com/share/6d23e89c31d84ef0b2784e2139d781fb?sid=d850e510-ba6c-47be-b85f-ca665a5edad9
- set up Microsoft Entra ID and test...
- https://www.loom.com/share/37ef6f0bccc742358987df3ce0c00a96?sid=d77edb31-6d35-4d4a-a6e7-a32f0012699b
> feat(SAML): Support attributes with namespace

- packages/client/utils/makeAppURL.ts
- packages/server/email/createEmailVerification.ts
- packages/server/email/emailVerificationEmailCreator.tsx
- packages/server/graphql/public/mutations/signUpWithPassword.ts
Fixes #8801 
https://www.loom.com/share/405857cf937b458f91e3ddab2882ec0d?sid=792a735c-8f86-4044-9917-4ca65fa7aa04
> feat: handle redirect in email verification

- packages/server/postgres/migrations/1696443115482_addCustomerFeedbackTemplate.ts
This migrations adds a new retro template ‘Customer feedback analysis’ in support of a market entry point experiment.
- Open the Activity Library, go to Feedback, and try starting the new activity
> feat: migration adds customer feedback RID template

- packages/server/postgres/migrations/1696616922662_addPeerReviewTemplates.ts
Adds three ‘360 Review’ templates in support of testing the market entry point around performance and reviews
- Go to the Activity Library -> Feedback category
- Try running one of the three ‘360 Review’ templates
> feat: migration adds 360 review RID templates

- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
- packages/client/components/TeamPromptMeeting.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8940
Open the your work drawer by default to attempt to increase feature adoption.
N/A - see tests
> feat(your-work): Open your work drawer by default

- packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
- packages/client/utils/AtlassianManager.ts
- packages/server/graphql/private/typeDefs/_legacy.graphql
- packages/server/graphql/public/typeDefs/AtlassianIntegration.graphql
- packages/server/graphql/public/typeDefs/JiraIssue.graphql
- packages/server/graphql/public/types/AtlassianIntegration.ts
Fixes https://github.com/ParabolInc/parabol/issues/8917
Pagination for Your Work - Jira.
Note that because this modifies the Jira GQL API (both pagination args and behavior) there is a risk of regression in the Jira integration for Sprint Poker, so that should be smoke tested more rigorously than usual.
Needs rebase once https://github.com/ParabolInc/parabol/pull/8907 lands
Multiple pages (2 per page):
https://www.loom.com/share/83e737abb0bc4c30a1b61f9d20bd29f3?sid=469f4e61-0ecb-44a4-9c40-f7e1dc92cdc2
Paginate on scroll to bottom (7 per page):
https://www.loom.com/share/7dcf95f1fe6249faad5d9fac9f6609ec?sid=112a19e7-eecd-4a06-96a5-1468a95fd8a2
> feat(your-work): Jira Integration pagination

- .circleci/config.yml
- .github/workflows/build.yml
- certs/README.md
- docker-compose.yml
- docker/dev.yml
- docker/parabol-ubi/docker-build/README.md
We are already using Redis 7 in both Digital Ocean and GCP. This PR upgrades all Redis references to 7.0.
- It uses 7.0, without a patch version, because it is what's configured in GCP. We cannot control the patch upgrades. By definition, these images aren't inmutable, but the risk is very low and we need to test things ahead of GCP automated upgrades.
- The image  [Docker official 7.0-alpine](https://hub.docker.com/_/redis/tags?page=1&name=7.0-alpine) is used everywhere.
- Redis TLS documentation has been modified in order to ease the use of that functionality in development if required.
> feat(redis): upgrade to use Redis 7

- packages/server/graphql/private/queries/dailyPulse.ts
- packages/server/graphql/private/queries/helpers/authCountByDomain.ts
Fixes our internal daily pulse.
On Sept 25 we started using a new dataloader to determine if something is a company domain.
Dataloaders can't handle `null`. https://github.com/ParabolInc/parabol/blob/0508fad31335d0cedb324237fcb6342a83c56793/packages/server/dataloader/customLoaderMakers.ts#L709
We could make the dataloader handle nulls, or we could ensure that only non-nulls make it to the dataloader.
Since none of the other dataloders handle `null`, I figured the latter was the better option.
This relies on prod data to verify the fix.
In admin/graphql run this
```gql
query DailyPulse($after: DateTime!, $email: String!, $channelId: ID!) {
dailyPulse(after: $after, email: $email, channelId: $channelId)
}
```
with these vars (replace X with what you see in the dokku prod env)
```json
{ …
```
> fix: dailyPulse handle nulls

- packages/client/components/ScopingSearchInput.tsx
- packages/client/components/TeamPrompt/TeamPromptDrawer.tsx
- packages/client/components/TeamPrompt/TeamPromptTopBar.tsx
- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GCalEventCard.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationPanel.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationPanel.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GitHubObjectCard.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationPanel.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraObjectCard.tsx
- packages/client/components/TeamPrompt/WorkDrawer/ParabolTasksPanel.tsx
- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/types/SegmentEventTrackOptions.ts
- packages/server/graphql/types/ServiceEnum.ts
Fixes https://github.com/ParabolInc/parabol/issues/8924
Add analytics for Your Work drawer.
Needs rebase once [gCal PR](https://github.com/ParabolInc/parabol/pull/8939) lands.
N/A
> feat(your-work): Product analytics

- packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
- packages/client/utils/makeAppURL.ts
Fixes https://github.com/ParabolInc/parabol/issues/8955
Support copying permalinks of standup responses.
https://www.loom.com/share/407d84a2400c4bc1b371b7cbc6db28b8?sid=20ed10d4-0c08-4646-b3a7-77645604eef0
> feat(standups): Response permalink sharing

- packages/client/Atmosphere.ts
- packages/server/listenHandler.ts
> fix: server health check comment out

- packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationResults.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GCalIntegrationResultsRoot.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResults.tsx
- packages/client/components/TeamPrompt/WorkDrawer/GitHubIntegrationResultsRoot.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResults.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraIntegrationResultsRoot.tsx
Fixes https://github.com/ParabolInc/parabol/issues/8881
On error or no data, show the user a link to integration settings.
For each of GitHub, Jira, and gCal:
> feat(your-work): Provide link to integration settings on error + no data

- .github/workflows/build.yml
- .github/workflows/release-please.yml
- packages/client/Atmosphere.ts
- packages/server/listenHandler.ts
- release-please-config.json
we've been building 3 docker images when we should only be building 1.
- one for branch production
- one for branch release
- one for the tag e.g. v6.124.0
to do away with this, we'll only build when the release-please PR gets merged.
if you absolutely have to, you can make a commit start with "dockerize" to trigger this manually, but that's not recommended. that build will supercede the previous, taking its version tag.
> fix: dockerize ignores git tags

- release-please-config.json
release-please wasn't set to bump dependencies. now it is! (if the syntax is correct...)
> fix: bump versions for dependencies

- packages/server/postgres/migrations/1697477646986_swot-typo.ts
adds `await` to the last migration so it completes before the connection is terminated after migrations complete.
> fix: await last migration

- .github/workflows/build.yml
- package.json
- yarn.lock
Installing datadog-ci before using it to push source maps incurs a cost of over 2 minutes. https://github.com/ParabolInc/parabol/actions/runs/6629528330/job/18009009859
if we install datadog-ci into our package like we do everything else we can avoid calling `yarn install` by just loading the CI cache.
This should bring our release time to about 8 minutes.
> chore: add dd-ci to package.json to reduce release time

- packages/server/database/rethinkDriver.ts
- packages/server/database/types/Notification.ts
- packages/server/database/types/NotificationDiscussionMentioned.ts
- packages/server/database/types/NotificationKickedOut.ts
- packages/server/database/types/NotificationMeetingStageTimeLimitEnd.ts
- packages/server/database/types/NotificationPaymentRejected.ts
- packages/server/database/types/NotificationPromoteToBillingLeader.ts
- packages/server/database/types/NotificationPromptToJoinOrg.ts
- packages/server/database/types/NotificationRequestToJoinOrg.ts
- packages/server/database/types/NotificationResponseMentioned.ts
- packages/server/database/types/NotificationResponseReplied.ts
- packages/server/database/types/NotificationTaskInvolves.ts
- packages/server/database/types/NotificationTeamArchived.ts
- packages/server/database/types/NotificationTeamInvitation.ts
- packages/server/database/types/NotificationTeamsLimitExceeded.ts
- packages/server/database/types/NotificationTeamsLimitReminder.ts
- packages/server/graphql/mutations/addComment.ts
- packages/server/graphql/mutations/helpers/notifications/IntegrationNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/Notifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
For standup mentions + replies, send the user a slack DM if they have slack integrated on some team.
When finding a slack integration for the user, we'll prioritize integration on the team > team within the org > any team for that user.
In the future, we may support mapping parabol users to slack users, such that users don't need to integrate slack on a team in order to receive these DM notifications. This may simply be a user-level slack integration that's not connected to any particular team.
Based on the [POC PR](https://github.com/ParabolInc/parabol/pull/8653), and re-inspired by Gareth's [terrible idea](https://parabol.slack.com/archives/C03NGEJUKCN/p1697195167936709).
> feat(slack): Send certain notifications via slack DM

- .github/workflows/build.yml
When a release-please PR is merged to `release`, the build.yml will push a docker image to our registry.
Now, it will also add a commit message to gitlab that increments the version, which kicks off the pipeline diff.
This removes 1 more step from the release process. Now all that remains is a dev going to the pipeline & clicking Play.
Tested without the IS_RELEASE conditional here: https://github.com/ParabolInc/parabol/actions/runs/6644516359/job/18053839586
You can see that it worked on the staging repo here: https://gitlab.com/parabol1/saas/staging/parabol/-/blob/main/version.yaml?ref_type=heads
> chore: build bumps version in gitlab

- packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
- packages/server/graphql/mutations/helpers/updateTeamInsights.ts
Fixes #8887 
https://www.loom.com/share/516fc5120015449e81c5a38076c5880b?sid=77d5cf4f-68af-4048-8072-7b54fc13aadb
- with the feature flag enabled and insights shown, use 4 different retro templates and see only 3 show up
> chore(Team Insights): Limit most used retro templates

- .github/workflows/build.yml
- .github/workflows/release-please.yml
- packages/client/hooks/useServiceWorkerUpdater.ts
Removes the `release` branch.
If you're doing a standard release, merge to `master`.
If you're doing a hotfix, just make sure the branch name starts with `hotfix` e.g. `hotfix/4022/fix-user-details`
release-please will open a PR for you. merge it & it will push a new docker image to the registry.
> chore: remove release branch

- scripts/webpack/prod.client.config.js
Fixes #8948 
Prefix static file URLs with `__PUBLIC_PATH__` so they're loaded from CDN.
https://www.loom.com/share/0a6cbcbe2161499bb2d8f2a9053bf733?sid=06fcf923-afb8-487b-ab90-f5e9cf35412f
- run a production build `yarn build && yarn predeploy && yarn start`
- inspect the static cache with dev tools and see files are valid
> fix: Fix service worker static cache base url

- packages/server/utils/StaticServer.ts
- packages/server/utils/serveStatic.ts
StaticServer caches all files. The array with explicitly cached files is therefore meaningless and was never read.
> chore: remove unused filesToCache logic

- packages/client/serviceWorker/sw.ts
If we fail to fetch a file for the static cache, we previously failed to install the new service worker. Now we're just catching this error. If the file is missing from the static cache, it will be fetched from the dynamic one later.
- run production `yarn build && yarn predeploy && yarn start`
- add a failing file, like 'https://parabol.fun/invalid' to the cache and see installation not failing
> fix: do not fail installing service worker on fetch fail

- LICENSE
- packages/client/package.json
- packages/integration-tests/package.json
- packages/server/package.json
The e-mail love@parabol.com was found multiple times on the code base. It is replaced now with the actual e-mail love@parabol.co
> fix: e-mail love@parabol.com replaced by love@parabol.co

- packages/server/postgres/migrations/1698263155574_addPrioritizationTemplates.ts
Adds MoSCoW and RICE prioritization templates using the poker meeting and scales
- Run a test meeting using each new template (under the strategy category)
- Add Parabol tasks to estimate. Estimate the items. Add a final score per dimension
- End the meeting. See that the CSV has the items with their estimates for each dimension of the template
> feat: adds MoSCoW and RICE prioritization templates

- pm2.config.js
Github build action was broken since yesterday after merging the PR to remove old Dokku artifacts due to missing pm2.config.js. This PR restores the pm2.config.js and gets the tests working again.
- [Action failing on the PR before merging](https://github.com/ParabolInc/parabol/actions/runs/6724538961)
- [Master action failing after merging the PR](https://github.com/ParabolInc/parabol/actions/runs/6724558476)
> fix: restore missing pm2.config.js

- packages/server/activeClients.ts
- packages/server/graphql/httpGraphQLHandler.ts
- packages/server/server.ts
- packages/server/socketHandlers/handleDisconnect.ts
- packages/server/socketHandlers/handleOpen.ts
- packages/server/sse/SSEConnectionHandler.ts
- packages/server/sse/SSEPingHandler.ts
fixes #8903 
https://www.loom.com/share/c891b7ca7e7346ba9f6dfbfa8c138157?sid=445095fa-b1a4-4890-b091-3aa1ae7211fa
> fix: gracefully handle reconnects when servers upgrade

- packages/server/billing/helpers/terminateSubscription.ts
- packages/server/graphql/private/mutations/stripeFailPayment.ts
fixes #8341
- Run: `stripe listen --forward-to localhost:3000/stripe` (Do `stripe login` if you see an error)
- Upgrade starter org to team plan using "Decline after attaching" test card number: 4000000000000341
- Wait few seconds, refresh page. See that org is not locked
- See that it i upgraded to team tier
- See that card rejected notification is added in the notification center
> chore: don't lock org in case of failed payment

- packages/client/components/RequestToJoin.tsx
fixes borked master
From slack rant:
> master is broken right now! It looks like our GitHub strategy is to blame:
The error is Can't resolve '../mutations/SendClientSideEvent'
This is because https://github.com/ParabolInc/parabol/pull/9067 changed the location of that file
And https://github.com/ParabolInc/parabol/pull/9057 referenced the old location
The root cause is that we don’t require PRs be brought up to date before we allow them to be merged. For example, I open a PR, the checks pass, someone else’s PR gets merged which would cause my PR to break, but since my checks already passed, I can merge & break master
> fix: reference to SendClientSideEvent

- .github/workflows/ironbank.yml
Adds a manual workflow that can be triggered to pull a prebuilt parabol image, copy build, dist, and static assets. Then zip the assets, and upload them to S3 for use in Ironbank.
> feat: create ironbank s3 artifacts manual GH

- packages/client/mutations/fragments/PublicTeamsFrag.ts
`viewerTeams` are undefined after creating a new org on master. The app crashes and the user needs to refresh the page to see their org.
> fix: unable to create org

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Demo: https://www.loom.com/share/e0b1d96c4c5f4a10975fe02399845b90
This fixes a bug where you need to refresh the page to see the auto joined teams.
> fix: autoJoin needs refresh

- docs/deployment.md
release.yml is not running, I assume because the release-please bot opened the PR so it can't trigger a GH workflow.
Testing it again with GH App credentials
> chore: update deployment docs

- .github/workflows/release.yml
release step failing because the sha was invalid, it was grabbing the sha from master instead of the PR head.
> fix: fix sha from base to head

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
Fixes #8971 
Apply the setting based on domain similar to `retrosInDisguise`. This way no additional database query is necessary.
no demo
> chore: Apply no template limit feature flag to some new users

- packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/modules/meeting/components/ReflectTemplateDetails.tsx
- packages/client/modules/meeting/components/SelectTemplate.tsx
- packages/client/utils/useTemplateDescription.ts
- packages/server/graphql/mutations/selectTemplate.ts
- packages/server/graphql/queries/helpers/resolveSelectedTemplate.ts
Fixes #8972 
https://www.loom.com/share/b9d8fd64a68b4babbcbf13f703052c7c?sid=67d8350a-8811-42b0-af95-e82c34f264e9
- with the `noTemplateLimit` flag applied to your user and a `starter` org
- start a premium retro meeting from the activity library
- repeat with the legacy dialog
- mark a poker template non-free in the database
- start a meeting with a premium poker template from the activity library
- repeat with the legacy dialog
> chore: Users with noTemplateLimit flag can use paid templates

- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
I noticed there are two borders when you select a custom template, so I removed the outer one. See Loom demo: https://www.loom.com/share/a2246d909cc04b7b8c3e5177d85ad059
(I should have committed fix instead of feat).
> feat: fix custom template border

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/LeftDashNavItem.tsx
- packages/client/components/Dashboard/MobileDashSidebar.tsx
- packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthentication.tsx
- packages/client/modules/userDashboard/components/OrgBilling/OrgPage.tsx
> chore: Add SAML setup to new checkout flow

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/LogoFooter.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Partially Fixes #8549
when possible, we don't want to use `action.parabol.co` in the codebase because PPMIs shouldn't go there, they should go to their own instance.
There are 2 exceptions:
- for PPMIs tell robots to `noindex` so they don't show up in search engines
- for PPMIs, point to action.parabol.co as canonical so we don't hurt our SEO
> fix: replace saas url with calculated value for PPMIs

- packages/client/modules/summary/components/NewMeetingSummary.tsx
Fixes https://parabol.slack.com/archives/C836NA350/p1698080641122759
When we moved meeting summaries to be inside the dashboard sidebar+topbar, demo summaries were included as well. This means users on the demo summary could do things like click the "Add Meeting" button that's supposed to only be accessible for logged-in users.
I tried to restrict the sidebar+topbar to only logged-in users, but because the `DemoSummary` uses the stubbed local demo atmosphere, we can't easily render these components, even for logged-in users.
Instead, simply don't render the sidebar+topbar for demo summaries.
N/A
> fix(demo): Don't show top bar or sidebar on demo summary

- packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
- packages/server/database/types/OrganizationUser.ts
- packages/server/graphql/types/OrgUserRole.ts
Fixes https://github.com/ParabolInc/parabol/issues/9181
Add the base `ORG_ADMIN` org role, and who which user(s) are an admin in the members list.
Doesn't do anything around permissions (see https://github.com/ParabolInc/parabol/issues/9183)
Give an `OrganizationUser` the `ORG_ADMIN` role via rethink query:
```
r.db('actionDevelopment').table('OrganizationUser')
.get('<org user id>')
.update({role: 'ORG_ADMIN'})
```
Confirm the user is shown as an Org Admin in the UI.
> feat(admin): Base Org Admin role

- packages/server/graphql/types/Organization.ts
Fix https://github.com/ParabolInc/parabol/issues/9136
> fix: sort team names alphabetically

- packages/client/components/DiscussionMentioned.tsx
- packages/client/components/ResponseReplied.tsx
- packages/client/modules/email/components/EmailNotifications/EmailDiscussionMentioned.tsx
- packages/client/modules/email/components/EmailNotifications/EmailResponseReplied.tsx
- packages/client/mutations/toasts/mapDiscussionMentionedToToast.ts
- packages/client/mutations/toasts/mapResponseRepliedToToast.ts
- packages/server/graphql/public/typeDefs/NotifyDiscussionMentioned.graphql
- packages/server/graphql/public/typeDefs/NotifyResponseReplied.graphql
- packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
- packages/server/graphql/public/types/NotifyResponseReplied.ts
Fixes #9197 
Main issue was that we didn't check if comment was anonymous in related gql resolvers. keep in mind svg avatars in emails won't work, they _should_ work on prod, see [thread 🔒 ](https://parabol.slack.com/archives/C608QL4RH/p1701167748897159).
> fix: author should be nullable when comment was anonymous

- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
- packages/server/graphql/mutations/helpers/createGcalEvent.ts
- packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
- packages/server/graphql/public/types/UserFeatureFlags.ts
- packages/server/graphql/types/UserFlagEnum.ts
Fix https://github.com/ParabolInc/parabol/issues/9246
> feat: remove gcal flag

- packages/client/components/IconLabel.tsx
- packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
- packages/client/modules/outcomeCard/components/OutcomeCardFooter/TaskFooterIntegrateToggle.tsx
This is intended as a small UX improvement to increase visibility of the integration button on task cards.
> fix: increases integration icon visibility

- packages/server/graphql/mutations/helpers/notifications/MSTeamsNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/NotificationIntegrationHelper.ts
- packages/server/graphql/mutations/helpers/notifications/Notifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
These will need some refactoring for #8840 and this will hopefully simplify this.
> chore: Cleanup Slack/Mattermost/MSTeams notifiers

- .github/workflows/release-please.yml
- .github/workflows/release.yml
I named my hotfix branch `hotfix/` instead of `hotfix-` and thought the whole release process was broken because the build didn't happen.
As long as the branch starts with `hotfix`, it should create a release, no matter the delimiter.
> chore(dx): allow any branch with hotfix prefix to build

- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeetingActionsCurrentMeetings.tsx
- packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
Fix https://github.com/ParabolInc/parabol/issues/9061
I noticed that the active meeting menu position is off in prod. I'd prefer to tackle that in a separate PR rather than delay & bloat this one: https://github.com/ParabolInc/parabol/issues/9272
The NewMeetingTeamPicker menu position can also behave strangely. I have an issue for this too: https://github.com/ParabolInc/parabol/issues/9274
Loom demo: https://www.loom.com/share/26a4e81d4d2041ca8d4eaff014dd8e0d
> fix: activity library settings mobile

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
Fix https://github.com/ParabolInc/parabol/issues/9276
Perhaps there was a merge conflict that went wrong as the text colours and the background colours weren't imported correctly from `CATEGORY_THEMES`.
On master, the meeting type tabs don't have the correct background colours. This is now fixed and looks like this:
> fix: activity library colour imports

- scripts/prod.js
- scripts/webpack/prod.client.config.js
- scripts/webpack/prod.servers.config.js
I've been doing a lot of testing of the production build & I hate waiting around for 1 minute to watch it build.
By building client & server at the same time, in separate threads, it cuts that time in half 🎉 .
I used `child_process` instead of `worker_threads` because the API is a little cleaner (no need for an extra file). Plus it looks like it's more performant, too, which is a NodeJS problem: https://github.com/orgs/nodejs/discussions/44264
The webpack files hardly changed, i just wrapped the return value in `{}` & normalized the input params. The git diff makes it look much worse!
Before
```
🙏🙏🙏      Building Production Server      🙏🙏🙏
✔ Parse Configuration
✔ Generate outputs
✨  Done in 58.23s.
```
After
```
🙏🙏🙏      Building Production Server      🙏🙏🙏
✔ Parse Configuration
✔ Generate …
```
> chore: webpack client and server in parallel

- packages/server/utils/__tests__/isRequestToJoinDomainAllowed.test.ts
- packages/server/utils/isRequestToJoinDomainAllowed.ts
Prefer higher tiers and bigger over smaller orgs.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Restrict prompt to join org to a smaller set of orgs

- packages/server/graphql/uWSAsyncHandler.ts
fixes #9289
`req` may only be accessed before the first `await` call, it gets GC'd on next tick, which is one of the sneaky ways uWS keeps memory consumption so low.
This was introduced about 2 months ago, i just didn't catch it: https://github.com/ParabolInc/parabol/pull/9023/files
> fix: grab auth token before await

- packages/client/components/DiscussionThreadInput.tsx
Because "add an activity" button redirects on activity library, I will use `retrosInDisguise` flag for now for displaying this button.
After merge it will instantly be available for users with this flag
Previous PR: #8750
- Add `retrosInDisguise` flag and see add an activity button in the discussion panel
- Remove `retrosInDisguise` flag and see no button
> chore(meeting-inception): use retrosInDisguise flag for displaying add an activity button

- .github/workflows/release-to-staging.yml
more CI debugging:
- gitlab creates pipelines before the jobs inside the pipelines, so we have to wait for the job, not just the pipeline
- gh cli doesn't interpret \n, so we handle that
- checking the status of deployment requires an auth_token
> fix: release to staging debug #4

- .github/workflows/release-to-staging.yml
jq returns `null` as a string & not actually a null value. this confused me.
> fix: default to empty instead of null

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/Categories.ts
- packages/client/components/ActivityLibrary/CreateActivityCard.tsx
The custom category lists all team and organization custom templates.
https://www.loom.com/share/f64c0a02e77c4d5286458baf037f647f?sid=dcf371db-d1ed-406e-9fc9-fd60be5d161e
- create custom templates
- edit custom templates
- start a meeting
> feat: Add custom category to activity library

- docker/parabol-ubi/docker-build/README.md
Updates the Docker build readme to use the correct PostgreSQL version when building manually (from 12.10 to 15.4)
> fix: Docker build readme updated with the correct PostgreSQL version

- .github/pull_request_template.md
- .github/reviewers.yml
- docs/codeReview.md
Updated the code review policy to only require 1 review in total.
> chore: Update code review guidelines

- packages/client/types/constEnums.ts
No issue, just a simple change to remove unnecessary github oauth2 scopes. The further improvement would be to do https://github.com/ParabolInc/parabol/issues/6208
instead of
> feat: remove unnecessary github oauth scopes

- packages/server/graphql/public/types/MeetingTemplate.ts
Without this fix the edit controls were shown but did not work.
https://www.loom.com/share/f9b2a3765b7945b092414fd0791b58dc?sid=43577910-cf01-447e-8285-731d76ee0817
- have a team A with user Hannibal
- create a template in team A which is shared with the org automatically
- remove Hannibal from team A
- check that Hannibal can still see the template, but the edit controls are hidden
> fix: Show correct template owner for ex-team members

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/LeftDashNavItem.tsx
- packages/client/components/Dashboard/MobileDashSidebar.tsx
Highlight in the sidebar vanished when navigating from the main team dash to a subtab, like tasks or activity.
https://www.loom.com/share/5b29e927ef3247f194b5b88757f02293?sid=badb2cf4-f713-4473-9a1c-254a8045f820
- navigate through the pages and check the highlight in the sidebar
- repeat with mobile sidebar
> fix: highlight team dash in sidebar regardless of tab

- packages/client/components/ActivityLibrary/CreateNewActivity/CreateNewActivity.tsx
- packages/client/modules/meeting/components/AddNewPokerTemplate.tsx
- packages/client/modules/meeting/components/AddNewReflectTemplate.tsx
- packages/client/modules/meeting/components/EditableTemplateName.tsx
- packages/client/mutations/AddPokerTemplateMutation.ts
- packages/client/mutations/AddReflectTemplateMutation.ts
- packages/server/graphql/mutations/addPokerTemplate.ts
- packages/server/graphql/mutations/addReflectTemplate.ts
- packages/server/graphql/public/types/ReflectTemplate.ts
Let's just allow duplicate names until the UX enforces proper naming of new templates
https://www.loom.com/share/4499f45d4a134977954db3cb5326cae9?sid=e8d5b5f3-1902-4b62-8172-3133662e7884
- create a new retro template without renaming it
- repeat
> fix: Allow multiple "*New Template"

- .github/workflows/release-to-staging.yml
when GH opens a PR to `production` the head should not be master because another dev could have pushed something new to master. Instead, we are pushing a specific version, so we should use that version as the tag.
> fix: gh action release switch head to version tag

- packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
- packages/client/mutations/CreateReflectionMutation.ts
- packages/server/graphql/mutations/createReflection.ts
- packages/server/graphql/public/typeDefs/_legacy.graphql
- Start a retro and add a reflection with kudos
- See snackbar appearing:
> feat(kudos): show snackbar when reflection with kudos created

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/server/graphql/public/types/FixedActivity.ts
- packages/server/graphql/public/types/MeetingTemplate.ts
- packages/server/graphql/public/types/User.ts
Fix https://github.com/ParabolInc/parabol/issues/9113
In this PR, I've added "Activities to get you started" title, the four templates from the linked issue, and updated the order to show the Retro template first.
I haven't included the "Our most popular" section as it seems repetitive. There's just one Standup and 1-1 template and two Sprint Poker templates. As we're showing a Standup and 1-1 template in the Quick Start section, we shouldn't show the same templates in the "Our most popular" section, too. 
That means the "Our most popular" section would largely just show popular retro templates, which we already do when they click on the "Retrospective" tab.
I think there's also an advantage to showing a minimal amount of info so users don't feel overwhelmed. Curious to get @acressall's …
> feat: update activity library quick start

- .github/workflows/debug.yml
testing how a github workflow can create a new branch
> fix: create release branch as head

- .github/workflows/release-to-prod.yml
- .github/workflows/release-to-staging.yml
- .github/workflows/test.yml
- removes extra logs
- fixes release-to-production
- doesn't run test on prod PR
> fix: support edge cases in release to prod

- .github/workflows/release-to-prod.yml
backticks that live in GH variables break bash, so we instead save it to a file & pipe it to perl for regex.
> fix: handle breaking syntax in pr body

- packages/client/Atmosphere.ts
- packages/client/package.json
- yarn.lock
support server secret rotations without our app trying to DOS us.
before the client would see it failed to connect & keep retrying forever because it had succeeded in the past.
now it realized that just because it succeeded in the past, it may not succeed now.
https://www.loom.com/share/891a552c4f3c4e3d99d5f71d9dcdcdcb?sid=00bfa14e-60e7-406f-8ebf-68c42ebb3723
> feat: support SERVER_SECRET rotations gracefully

- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
Format the "Time's up" message similar to the rest of the messages. MSTeams seems to have a nicely formatted message already.
Before:
Now:
For ease of testing I replaced
https://github.com/ParabolInc/parabol/blob/35121827ea3eb8a34f839367fa8480c7727d1241/packages/server/graphql/public/mutations/startCheckIn.ts#L113
with
```
IntegrationNotifier.endTimeLimit(dataLoader, meetingId, teamId)
```
and just started a check-in
- check Slack
- check Mattermost
> chore: Prettify "Time's up" Slack message

- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
- packages/server/graphql/public/mutations/addReactjiToReactable.ts
- packages/server/graphql/public/mutations/upsertTeamPromptResponse.ts
- packages/server/utils/analytics/analytics.ts
- Add some kudos see `kudosSent` event tracked correctly
> chore(kudos): track kudos type and meeting type in kudosSent event

- packages/client/components/ActivityLibrary/ActivityGrid.tsx
In production, the tooltip with the prompt details isn't showing up when you hover over the activity library card.
> fix: render activity library tooltip

- packages/client/components/ActivityLibrary/ActivityDetailsRecurrenceSettings.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeeting.tsx
- packages/client/components/NewMeetingRecurrenceSettings.tsx
- packages/client/components/TeamPrompt/Recurrence/RecurrenceSettings.tsx
- packages/client/components/TeamPrompt/Recurrence/UpdateRecurrenceSettingsModal.tsx
- packages/server/__tests__/startRetrospective.test.ts
- packages/server/database/types/MeetingRetrospective.ts
- packages/server/database/types/MeetingTeamPrompt.ts
- packages/server/graphql/mutations/helpers/createMeetingSeriesTitle.ts
- packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
- packages/server/graphql/public/mutations/startRetrospective.ts
- packages/server/graphql/public/mutations/startTeamPrompt.ts
Fixes #9343
Chose the correct placeholder for the series name based on meeting type and use the same naming scheme for retro instances that we also use for standups.
https://www.loom.com/share/1e282a34a11f425ca7eb1cb722065820?sid=76d56a91-998a-4018-a7e9-02d0a02bc71c
- PR includes some basic test
- Set a meeting series name "MeetingSeries" when creating a series
- See the individual meeting will be named "Meeting Series Jan 23"
> feat: Allow retro meeting series naming

- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- Add slack integration
- Run standup meeting
- Post standup response
- From another user comment on the response as Anonymous
- See that slack notification comes with Anonymous name in it
- Comment as non-anonymous, see it also works
> fix: fix slack response replied anonymous notification

- packages/server/utils/sendToSentry.ts
fix #9386 by stringifying the error in any way possible
> fix: handle all types of errors in sendToSentry

- docker/dd-conf.d/gqlExecutor.yml
- docker/dd-conf.d/web.yml
- docker/dev.yml
- packages/client/utils/AtlassianManager.ts
- packages/server/dataloader/atlassianLoaders.ts
- packages/server/graphql/types/JiraRemoteProject.ts
- packages/server/utils/AtlassianServerManager.ts
- packages/server/utils/atlassian/jiraImages.ts
- packages/server/utils/atlassian/jiraIssues.ts
- pm2.dev.config.js
Mainly associate the logs with the traces so it's possible to check which GraphQL request caused a certain debug output.
I needed to shuffle some stuff from `AtlassianManager` to `AtlassianServerManager` because `AtlassianManager` lives in `parabol-client` and we don't have the tracing stuff there. That's a cleaner solution anyways because we cannot call the API from the client because we wouldn't expose the secrets there.
https://www.loom.com/share/0625c83f3d1845159d89db0253ba7da1?sid=fbbbd4ed-3719-470c-8fd5-f60ad2aeb9c9 🔒 
- see demo
- check you have the correct datadog variables set (there is a [PR](https://github.com/ParabolInc/action-devops/pull/186/files#diff-8a86bc8dcf3eb7b34043c2b8509fec32fff3680a9c9067de3135e48216d974fe) 🔒) for these
- additionally add
```
DD_LOGS_ENABLED='true' …
```
> chore: Add more Atlassian logging

- packages/server/graphql/public/mutations/helpers/__tests__/getKudosUserIdsFromJson.test.ts
- packages/server/graphql/public/mutations/helpers/getKudosUserIdsFromJson.ts
We didn't handle kudos in nested structures. Made function recursive
How to test:
- Write some standup response with kudos in nested lists, example:
- See kudos sent correctly
> fix: fix kudos in standups in nested lists

- .github/ISSUE_TEMPLATE/release_test.md
Previous 3d secure card number does not work anymore and I don't see it in the stripe docs https://stripe.com/docs/testing?testing-method=card-numbers#regulatory-cards
How to test:
- See that new card number triggers 3d secure window auth on staging
> chore: update 3d secure card number in release_test.md

- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/9340
GPT-3.5 turbo now has a large enough context window that it can accept the list of available templates.
I get similar results to GPT-4, and the response time is dramatically faster, so I think we should go with 3.5-turbo.
> feat: speed up ai search

- packages/client/components/TaskFooterIntegrateMenuList.tsx
Problem:
- Some users have a lot of jira projects, more than 1000 it looks like
- They start searching their project and can't find it because we maximum fetch 100 on frontend
Quick solution:
- increase number of projects we fetch on frontend. It is only fetched when project is not found. We fetch all projects on backend anyway ATM
Hot to test:
- Play with jira projects dropdown, try to search various projects, see everything working
- Add few different integrations like github etc, see nothing is broken
- Ideally: use jira account with 100+ projects, search project at the end of the list, see it works.
> fix: not all jira projects are displayed in the list if there are a lot of them

- packages/server/utils/AtlassianServerManager.ts
We ran into timeouts in `getAllProjects`, presumably because we're doing too many roundtrips. As a quick fix, increse the number of projects fetched per request from 50 to 500.
> fix: Increase the number of projects fetched per request from Atlassian

- .env.example
- packages/server/graphql/public/mutations/helpers/SAMLHelpers/getURLWithSAMLRequestParam.ts
- packages/server/utils/getSAMLURLFromEmail.ts
fix #9454
Supports single tenant SAML:
- admins can set `env.SAML_ISSUER` & override what parabol calls itself to the IdP
- admins can use a single SAML record for the entire instance if SSO is the only way to log in to the app & a SAML record already exists. To set up SAML, they can temporarily enable email/password auth & then after it's set up successfully they can disable that.
> feat: support env-defined saml issuer for PPMIs

- packages/server/graphql/mutations/helpers/inviteToTeamHelper.ts
Fix https://github.com/ParabolInc/parabol/issues/9374
If the user has sent 100 or more invites and none have been accepted, prevent them from sending more invites. 
We could be stricter and set a lower limit or prevent them from sending invites even if they have more than one accepted invite if there are many unaccepted invites, but I'm more concerned about preventing real users from sending invites.
> fix: limit invites from spammers

- packages/server/utils/AtlassianServerManager.ts
Previously we tried to fetch more projects per page, but Jira only ever returns 50 max. Instead once we know how many projects there are after fetching the first page, we fetch all remaining pages in parallel.
I observed we are fetching the projects multiple times, also when we do seemingly unrelated things like selecting all issues or checking/unchecking "use JQL". This is not addressed here.
https://www.loom.com/share/16d9346aa4f4428198b539f46786a209?sid=be0817a7-4799-4846-895c-c89425daaf58
- integrate with a Jira account with lots of projects (I can invite you)
- try sprint poker
> fix: Fetch Jira projects in parallel

- packages/server/package.json
- packages/server/postgres/migrations/1693991480688_truncateReflectPromptIds.ts
- packages/server/postgres/migrations/1694191002164_migrateSAML.ts
- packages/server/postgres/migrations/1698265572466_renameEmailVerificationSegmentIdToPseudoId.ts
- yarn.lock
Dumps ts-node to facilitate a more useful REPL.
Loom: https://www.loom.com/share/0d3311fe7a5640c5a0e9d81781c7f6b9?sid=895f8705-f17d-4928-9f37-31ccd717e3a9
Run as:
```bash
DOTENV_CONFIG_PATH=<absolute path to your .env> npx -w parabol-server ts-node -r dotenv/config -O '{"noUnusedLocals":false, "strict":false, "noImplicitAny":false, "module":"NodeNext","target":"ESNext"}'
```
At the REPL prompt, try:
```
> import getKysely from './postgres/getKysely'
undefined
> const pg = getKysely()
undefined
> await pg.selectFrom('Team').select(['name','orgId']).where('id','=','6VSEcEuGdy').limit(1).execute()
[ { name: 'Company', orgId: 'Skc7syWwNox' } ]
```
Neat!
- Add to your VSCode `task.json` (⌘ + shift + p) -> …
> chore: bump ts node

- packages/server/postgres/migrations/1709551949071_makeAllTemplatesFree.ts
Fix https://github.com/ParabolInc/parabol/issues/9472
I suggest that we don't remove all of the template limit logic as it's possible that we will want to implement template limits again in the near future. 
So, we should just set `isFree` to true for all meeting templates.
When I run `yarn pg:migrate up` I get the following error locally:
<details>
> - 1709551949071_makeAllTemplatesFree
> Rolling back attempted migration ...
RethinkDBError [ReqlOpFailedError]: Table `actionDevelopment.MeetingTemplate` does not exist in:
r.db("actionDevelopment").table("TemplateDimension").getAll(r.args(["estimatedEffortTemplate", "p5L84RD2og", "nLmvkxa43S", "wsjfTemplate"]), {
index: "templateId"
}).merge((var_1) => {
scale: r.db("actionDevelopment").table("TemplateScale").get(var_1("scaleId")) …
> feat: make all templates free

- .github/workflows/build.yml
- .github/workflows/test.yml
Notifies the team, on the Slack channel engineering, if build or test GH Action fails to avoid unexpected problems during releases.
Using [this available and super simple action](https://github.com/marketplace/actions/notify-slack-action) with the default and simplest step in the workflow.
> chore(gh-actions): reporting status to Slack if test or build GH Actions fail

- .github/workflows/validate_pr_title.yml
- yarn.lock
fixes broken master
root cause was using snyk to bump the package without also bumping the yarn lockfile.
in this case, it was graphql-jit
> fix: recreate lockfile

- .github/workflows/build.yml
Adds workflow_dispatch to allow building docker images manually on-demand. It simply requires to go to the Github Action - Build, click on  `Run workflow` and select the branch or tag. The build action will start on that branch/tag and produce and image, pushing it to the development repository. The tag of that Docker image is the sha of the last commit on the branch or tag.
This only works once merged to master.
> chore(ci): add capability to manually generate Docker Images

- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/public/typeDefs/startCheckIn.graphql
- packages/server/graphql/public/typeDefs/startRetrospective.graphql
- packages/server/graphql/public/typeDefs/startTeamPrompt.graphql
- packages/server/graphql/public/types/StartRetrospectiveSuccess.ts
Fixes: #8976
During testing I ran into "Cannot return null for non-nullable field hasGCalError" issues. This is not necessary because it's not a criitical field. Avoid these kind of mistakes by just making it optional.
- restart a team prompt via processRecurrence
> fix: Make hasGCalError optional

- packages/client/utils/makeCheckinGreeting.ts
feat: added additional greetings
feat: added additinal check-in questions
> fix: Korean greeting corrected

- scripts/webpack/prod.servers.config.js
- scripts/webpack/utils/node-loader-private/cjs.js
- scripts/webpack/utils/node-loader-private/index.js
- scripts/webpack/utils/node-loader-private/options.json
#9278 broke master because the webpack public path is being used for loading node binaries.
this ignores the public path when loading custom binaries.
> fix: node-loader that ignores public path

- .github/workflows/snyk-yarn-lock-commit.yml
Had a couple of minutes for a little palette cleanser. Decided to create this action.
If the PR title include [snyk] (case-insensitive), check out the PR branch, run yarn install, and then commit the resulting lock file and push the branch.
> chore: add GH Action, on Snyk PRs commit yarn.lock

- packages/server/utils/uwsGetIP.ts
Server does not accept requests if there are more ips listed.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Only read the first ip of the x-forwarded-for header

- packages/client/components/ActivityLibrary/ActivityCard.tsx
Add the background image as an img tag. This way it's used to auto size.
> fix: Activity library illustrations in Firefox

- .env.example
- packages/server/utils/uwsGetIP.ts
Our proxy will add the client ip to the x-forwarded-for header correctly and also itself as it does NAT. Configure the number of trusted proxies to read the correct entry from the header to avoid manipulation by clients.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Configure trusted proxies

- packages/client/modules/demo/initDB.ts
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
- packages/server/graphql/mutations/helpers/generateGroupSummaries.ts
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Fixes #8730 
- Select a paid team
- Run a retro meeting
- See the AI generated discussion prompt in the discussion phase
- In the meeting summary page, see discussion question for each topics instead of topic summary
- Create a new org/team
- Run a retro meeting
- See the AI generated discussion prompt in the discussion phase, with the free trial message
- In the meeting summary page, see discussion question for each topics instead of topic summary
> chore: Roll out AIGeneratedDiscussion to all users

- packages/server/postgres/migrations/1709933510512_addFreeCustomTemplatesRemaining.ts
See Slack thread where the release initially failed: https://parabol.slack.com/archives/C836NA350/p1711538854886859
There was an error: `Error: Cannot use a pool after calling end on the pool`. 
`await pg.destroy()` closes all db connections: https://kysely.dev/docs/getting-started
It looks like we should remove this line to keep the connection open.
> fix: ensure pool is callable after custom template migration

- packages/client/serviceWorker/sw.ts
If we fetch our own assets we want a CORS response to properly cache it in the service worker. If the response is served from the browser cache however, then there is a high chance that the required response headers are missing and the browser responds with a CORS error instead of refetching the resource. This happens because the Vary header does not include headers not present in the original request. To avoid this error, always fetch from the network for requests we intend to cache in the SW.
https://www.loom.com/share/280ee174d1484814a06e4d2a1c9c2674?sid=374d929f-89ef-4ae5-ad9b-b108e5391737
- setup ngrok to get a public URL with https (`ngrok http 3000`) and configure it in `.env` afterwards
- locally run in production mode (`yarn predeploy && yarn start`)
- open the site from the …
> fix: Fetch CORS resources from network

- docker/stacks/single-tenant-host/README.md
Fixes the readme of the single-tenant instances
> fix(single-tenant): application upgrades do not need --profile databases

- package.json
`DomainJoinRequestId` has a dependency to graphql-relay :-/
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Add graphql-relay to predeploy

- packages/client/modules/userDashboard/components/OrgBilling/OrgPlans.tsx
- packages/client/utils/constants.ts
Fix https://github.com/ParabolInc/parabol/issues/9589
> feat: update pricing page with template changes

- packages/server/utils/uwsGetIP.ts
Saw this issue when checking logs.
> fix: trim inet address

- packages/client/utils/AtlassianManager.ts
- packages/client/utils/JiraServerClientManager.ts
- packages/server/graphql/mutations/helpers/importTasksForPoker.ts
If we reuse another team members integrated task, then we can end up in a situation where they're not on the team anymore and mess up the integration access.
- create a team with 2 users: Stan and Lili
- Lili starts Poker, adds Task ABC-1 from Jira and finishes the meeting
- Stan removes Lili from the team
- Stan starts a Poker meeting and also adds ABC-1
- check DB that the new task for ABC-1 has the userId of Stan
- something along the lines of these queries
```
r.db('actionDevelopment').table('NewMeeting').get('vQvshNiFz2')
r.db('actionDevelopment').table('Task').getAll('vQvsROWc6I', 'vQsYJeTEVa')
```
> fix: Don't reuse another team members integrated task

- packages/client/components/MeetingControlBar.tsx
- packages/client/components/TeamHealth.tsx
Fixes #9540 
- Start a retro meeting with team health option selected
- Go to the team health phase
- Start a timer
- See the timer & count down properly shown up
> fix: fix the issue where timer doesn't work in TEAM_HEALTH phase

- .github/workflows/ironbank.yml
The ironbank GH action does not copy the tools script to use the pod IP for server ID in the application image. This adds that script to the artifacts used for that process
- [x ] I checked the [code review guidelines](../docs/codeReview.md)
- [x ] I have added [Metrics Representative](../docs/codeReview.md#metrics-representative) as reviewer(s) if my PR invovles metrics/data/analytics related changes
- [x ] I have performed a self-review of my code, the same way I'd do it for any other team member
- [x ] I have tested all cases I listed in the testing scenarios and I haven't found any issues or regressions
- [x ] Whenever I took a non-obvious choice I added a comment explaining why I did it this way
- [x ] I added the label https://github.com/ParabolInc/parabol/labels/Skip%20Maintainer%20 …
> chore: update ironbank GH action to copy ip-to-server-id script

- packages/client/components/Avatar/Avatar.tsx
touches on #9555, but doesn't fix it properly.
this adds a fallback image in case their profile pic fails to load, but it only does this on the Avatar component (think user dash).  there may be other places that their avatar fails to load!
not eager to dump 1300 images into our github repo, but not sure what the better alternative is...
> fix: fallback for missing avatar images

- .github/workflows/release-to-staging.yml
release-staging was not found in the JOBS response. Culprit was a pagination of 20 results. Set to 100 to make sure the staging-release job is found.
> fix: return 100 gitlab pipeline jobs

- package.json
- packages/client/shared/gqlIds/DomainJoinRequestId.ts
This messed up the require order in the --no-deps build. I had previously added it because the DomainJoinRequestId depended on 2 functions from it while living in the client package. Instead I copied these very small helpers.
```
yarn && yarn pg:build && yarn build --no-deps && yarn predeploy && yarn start
```
> fix: remove top level graphql-relay dependency

- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/rootTypes.ts
The GraphQL type was not correctly added. This lead to server errors when opening "My Settings".
- log in with Microsoft
- open "My settings" from the top right menu
- see no server errors
> fix: Add AuthIdentityMicrosoft

- packages/client/components/MeetingOptions.tsx
- packages/client/components/RetroDrawer.tsx
Fix: https://github.com/ParabolInc/parabol/issues/9577
> chore: disable change template ui if phase complete

- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetailsCategoryBadge.tsx
Don't list custom and quick start as categories as these cannot be assigned.
> fix: Only list available categories in edit template

- packages/client/components/SimpleTooltip.tsx
- packages/client/components/TimelineEventDate.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/MostUsedEmojisCard.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TeamInsightsCard.tsx
- packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
Relative times are nice to read, but sometimes it's nice to see which date 22 days ago actually was.
> chore: Add absolute date tooltip in history

- packages/client/modules/teamDashboard/components/TeamDashInsights/TopRetroTemplatesCard.tsx
Redirect directly to the activity libraray.
https://github.com/ParabolInc/parabol/assets/7331043/88edc8e3-1417-426a-8b5c-6d61780964dc
- in top templates click on one
> feat: Make top team templates clickable

- packages/client/components/ThreadedReplyButton.tsx
Fixes #9650 
When replying a local update is commited to the store. This happened in the mouse event handler and is propagated to other components before the event handling of the click finished. This caused the `useClickAway` handler to fire for the same click event and revert the store update immediately. There are two ways to fix this, stop propagating the event or do 
https://github.com/ParabolInc/parabol/assets/7331043/87aa505e-7b1e-4ee9-85de-60de27c657d6
- start a discussion thread and play around with the reply button
> fix: Threaded reply input does not immediately close

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
Fix https://github.com/ParabolInc/parabol/issues/9646
> chore: update activity library custom tab empty state

- packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
- packages/server/graphql/private/typeDefs/updateOrgFeatureFlag.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/types/OrganizationFeatureFlags.ts
Fix https://github.com/ParabolInc/parabol/issues/9541
I find the AI suggestions OK, but I'd probably prefer a feature where the AI creates a brand-new icebreaker question based on a prompt. It _could_ suggest something that's not safe for work, but the facilitator would still need to approve it, so I think that's a tolerable risk. Just an idea for a future enhancement, anyway.
> feat: roll out ai icebreakers

- packages/server/graphql/public/mutations/setOrgUserRole.ts
Fixes #9642 
- As a super user, run the GraphQL mutation ` setOrgUserRole(orgId: "xxx", userId: "yyy", role: ORG_ADMIN)` to promote user A to org admin
- Login as user A
- Verify user A can then promote user B to org admin through the UI
- Verify user A can demote user B from org admin role through the UI
> feat(orgAdmin): org admin can promote others to org admin

- packages/embedder/EmbeddingsJobQueueStream.ts
- packages/server/postgres/getKysely.ts
- packages/server/postgres/getPg.ts
fixes #9643 
When the DB disconnects, it's nice to reconnect it.
This is a ridiculously hard problem as it turns out:
https://github.com/brianc/node-postgres/issues/1324
https://github.com/brianc/node-postgres/issues/2112
Depending on when & how the disconnect happens, the client may not be aware of it. 
For example:
- If PG sends `terminating connection due to administrator command` then the PG client reports the error `Connection terminated unexpectedly` and the app gets killed. I think it gets killed because it's a `ProcessInterrupts` routine coming from `postgres.c` and the severity is `FATAL`. 
- If PG sends `the database system is shutting down` then it reconnects just as expected. This is what we've seen coming from Google CloudSQL.
-  The driver also does not throw an error if a …
> fix: support PG reconnects

- packages/client/components/ActivityLibrary/ActivityGrid.tsx
- packages/client/components/ActivityLibrary/CreateActivityCard.tsx
- packages/client/components/RetroDrawerTemplateCard.tsx
Long time no see! This PR removes `Premium` badges from Activity Library as they're misleading
No demo
> fix: remove premium badges from activity library cards

- packages/client/modules/userDashboard/components/GcalModal/DateTimePickers.tsx
- packages/client/modules/userDashboard/components/GcalModal/GcalModal.tsx
- packages/client/modules/userDashboard/components/GcalModal/GcalSettings.tsx
Fix https://github.com/ParabolInc/parabol/issues/9667
> fix: can update gcal start datetime

- packages/chronos/chronos.ts
- packages/server/utils/PubSubPromise.ts
- packages/server/utils/publishWebhookGQL.ts
Fixes #9664
We know this might be long running, so adding a separate long running timeout. We're not reusing the adhoc timeout as this is excessive and might obfuscate issues in the query.
- add debug output to https://github.com/ParabolInc/parabol/blob/4f49f950325e1092ac138b5d8cf401781a6dbda0/packages/server/utils/PubSubPromise.ts#L57
- add `CHRONOS_PROCESS_RECURRENCE='* * * * *'` to your `.env`
- run `yarn build && yarn start`
- check the output
> fix: Increase process recurrence timeout

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/TemplateDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/components/IntegrationsTip.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
Fixes #9440 
Make the activity detail view more reactive.
https://www.loom.com/share/f35fd5fc6a2e44fe8d5450e71d68df76?sid=c6c831d6-2dcc-4524-bb6b-4b4116cb7db5
- open a custom activity
- play around with the editing mode and resolutions
> fix: Sidebar in start custom activity

- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityDetailsSidebar.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
- packages/client/components/SelectTeamDropdown.tsx
- packages/server/graphql/public/typeDefs/updateFeatureFlag.graphql
- packages/server/graphql/public/types/UserFeatureFlags.ts
- packages/server/graphql/types/UserFlagEnum.ts
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Remove adhoc teams

- docker/images/parabol-ubi/dockerfiles/basic.dockerfile
- scripts/webpack/prod.servers.config.js
> fix: copy fonts from static

- packages/server/dataloader/customLoaderMakers.ts
- packages/server/dataloader/normalizeArrayResults.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
Fixes #9664 
MeetingSeries related dataloaders were loading data one by one instead of batching resulting in more roundtrips.
- create many meeting series for example by running
```
for i in {1..100}; do yarn workspace parabol-server test process; done
```
(Note that these fail in signup for lack of randomness in faker after many iterations.)
- Run `processRecurrence` and don't see any errors
> fix: Optimize processRecurrence

- docker/images/parabol-ubi/dockerfiles/basic.dockerfile
Moves the folder creation and copy of fonts where the rest of the application related stuff are. That improves the docker pull commands when fonts change, as things that are above it are very unlikely to change.
> chore(docker): fonts are managed with the rest of app related stuff

- packages/server/postgres/migrations/1714579256634_removeOneOnOneTeam.ts
`Team.isOneOnOne` is not used anywhere, so let's remove it from the schema
> fix: remove oneOnOne column in Team table

- packages/client/components/ActivityLibrary/ActivityGrid.tsx
- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/RetroDrawerTemplateCard.tsx
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Add custom label to templates

- packages/server/graphql/public/types/MeetingTemplate.ts
forgot about illustrationUrls! they need to be presigned, too, since they are UGC kept in the /store.
> fix: presign MeetingTemplate.illustrationUrl

- packages/embedder/EmbeddingsJobQueueStream.ts
- packages/embedder/embedder.ts
- packages/embedder/lint-staged.config.js
- packages/embedder/logMemoryUse.ts
- packages/embedder/logPerformance.ts
- packages/embedder/mergeAsyncIterators.ts
- packages/embedder/package.json
- packages/embedder/resetStalledJobs.ts
- packages/gql-executor/gqlExecutor.ts
- packages/server/server.ts
Fixes #9693
End all streams on receiving a kill signal to properly shutdown the embedder. Ending just the merged stream does not work in the current situation as it will wait indefinitely if all the workers are idle.
Nothing to see here.
- run the embedder outside of pm2
```
sh -c 'export SERVER_ID=7 && exec node dev/embedder.js'
```
- send `SIGINT` via Ctrl+C
- see the process ending gracefully
> chore: Gracefully shutdown the embedder

- packages/embedder/EmbeddingsJobQueueStream.ts
- packages/embedder/JobQueueError.ts
- packages/embedder/WorkflowOrchestrator.ts
- packages/embedder/ai_models/TextEmbeddingsInference.ts
- packages/embedder/embedder.ts
- packages/embedder/indexing/retrospectiveDiscussionTopic.ts
- packages/embedder/logPerformance.ts
- packages/embedder/workflows/embedMetadata.ts
- packages/embedder/workflows/rerankRetroTopics.ts
fix #9716 
fix #9673
cleans up embedder logs & a few errors that we encountered
> fix: remove logs from embedder

- packages/server/graphql/private/mutations/processRecurrence.ts
Relates to #9722 
We know the slowness stems from starting new meetings, let's see if it's all of them or just some outliers.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: add more granular process recurrence tracing

- packages/client/components/MeetingOptions.tsx
- packages/client/components/MeetingTopBar.tsx
- packages/client/components/RetroDrawer.tsx
- packages/client/components/RetroDrawerRoot.tsx
- packages/client/ui/Menu/Menu.tsx
Fix https://github.com/ParabolInc/parabol/issues/9620
> fix: only query templates when a user clicks the options menu

- packages/server/dataloader/customLoaderMakers.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
Relates to #9722
We know the slowness stems from starting new meetings, add more tracing in the hopes to find out from where.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: More processRecurrence tracing

- packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
- packages/server/graphql/mutations/helpers/handleCompletedStage.ts
Fix https://github.com/ParabolInc/parabol/issues/8858
This PR doesn't remove the discussion summary from the meeting summary. This will be handled in a separate issue: https://github.com/ParabolInc/parabol/issues/9710
> chore: remove ai summary from discussion thread

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
- packages/client/mutations/EndRetrospectiveMutation.ts
- packages/server/graphql/mutations/helpers/addAIGeneratedContentToThreads.ts
- packages/server/graphql/mutations/helpers/generateDiscussionPrompt.ts
- packages/server/graphql/mutations/helpers/handleCompletedStage.ts
- packages/server/graphql/types/Discussion.ts
- packages/server/graphql/types/RetroReflectionGroup.ts
Fix https://github.com/ParabolInc/parabol/issues/9710
Demo: https://www.loom.com/share/728f893c2e054fbbad82f849e89ffeaa
The AI Summary for the reflection group is no longer being used but I don't want to remove it now as it looks like we're migrating that table from RethinkDB to PG. I've created an issue: https://github.com/ParabolInc/parabol/issues/9712
> chore: remove discussion prompt from summary

- packages/client/modules/userDashboard/components/OrgBilling/OrgPlan.tsx
- packages/client/utils/constants.ts
- packages/server/graphql/queries/helpers/makeUpcomingInvoice.ts
- packages/server/utils/stripe/StripeManager.ts
Fixes #9707 
- Here's the new price in [Stripe test](https://dashboard.stripe.com/test/prices/parabol-pro-800)
- Here's the new price in [Stripe prod](https://dashboard.stripe.com/prices/parabol-pro-800)
- Create a new org & a new team
- Try to upgrade the org to `team` tier, observe the text is correctly updated from $6 to $8
- Upgrade and make sure it works
- Go to [Stripe](https://dashboard.stripe.com/test/) and verify the customer is correctly setup with the new $8 subscription (price app id: `parabol-pro-800`)
> feat: increase team subscription to $8

- packages/client/mutations/AcceptTeamInvitationMutation.ts
When following an invitation link with an old auth token, we would just show an ugly error message and don't give the user an action to do. Sign them out if we get the 'notSignedIn' error.
https://www.loom.com/share/76bd4fce2f7140fc929d82798d6310f6?sid=3b4d8953-ec62-4dd1-a0a1-639e4be6f945
> fix: Handle invitation links with invalid auth token

- packages/server/graphql/mutations/archiveTeam.ts
- packages/server/graphql/mutations/promoteToTeamLead.ts
- packages/server/graphql/mutations/removeTeamMember.ts
Fix https://github.com/ParabolInc/parabol/issues/9733
Currently throws an [error](https://parabol.sentry.io/issues/4780883754/?query=not+team+lead&referrer=issue-stream&statsPeriod=14d&stream_index=0) if the viewer isn't the team lead. This PR enables both team leads and org admins to change team lead, remove team members, and archive teams.
> fix: org admin can change team lead

- packages/client/package.json
- packages/server/socketHandlers/handleOpen.ts
- packages/server/socketHandlers/handleUpgrade.ts
- yarn.lock
fix #8370 
The server wasn't closing websockets with a `reason` when the session was invalidated.
This is important because if a `reason` is included, the client nukes the authToken.
Either I missed an API change in uws.js, or it hasn't been working for awhile.
This also rolls back to trebuchet-client 3.0.1 because once `canConnect` is true, it should not turn to false when it encounters an error. It should just try again.
The downside to this pattern is that the server has to upgrade the HTTP1.1 request to a websocket before it can close the websocket. This means the server tells the client that the websocket is open (fires `WebSocket.onopen`), the client sends pending messages (e.g. subscription requests) and then the server immediately closes it. It's extra work on the client & server, …
> fix: close websocket with reason on invalid token

- packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
- packages/client/mutations/handlers/upgradeToTeamTierSuccessUpdater.ts
Fixes #9737 
Stripe webhooks are slow locally. Please be patient while viewing this GIF😂:
- Upgrade an org to `team` tier
- ~Brew a cup of coffee and wait~
- Observe the billing page refreshes itself and the confetti shows up eventually
> fix: fix the issue where a successful upgrade won't refresh the billing page

- packages/client/modules/userDashboard/components/OrgAuthentication/OrgAuthenticationMetadata.tsx
- packages/client/mutations/useUploadIdPMetadataMutation.ts
- packages/client/ui/Button/Button.tsx
- packages/server/fileStorage/FileStoreManager.ts
- packages/server/graphql/public/mutations/uploadIdPMetadata.ts
- packages/server/graphql/public/permissions.ts
- packages/server/graphql/public/rules/getResolverDotPath.ts
- packages/server/graphql/public/rules/isOrgTier.ts
- packages/server/graphql/public/rules/isViewerOnOrg.ts
- packages/server/graphql/public/typeDefs/uploadIdPMetadata.graphql
fix #9254
Supports uploading an XML file, which can then be used for the metadata URL
https://www.loom.com/share/23e34f4943ca4650803c9faad05bc488?sid=9d52a92c-093b-4b88-8bc3-8f37c31db1ca
> feat: saml upload

- packages/client/package.json
- packages/server/socketHandlers/handleOpen.ts
- yarn.lock
Fixes #8370 
Safari will ignore the reason if the code is not in the valid range.
```
12:31:32 1|Socket Server    | Trace: SEND TO SENTRY invalid signature {"jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJsb2NhbHx3TklJVEZySW1BIiwidG1zIjpbIndOSUlVNHFwT2giXSwiaWF0IjoxNzE1MzI3Mjg1LCJhdWQiOiJhY3Rpb24iLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0OjMwMDAvIiwiZXhwIjoxNzE3OTE5Mjg1LCJyb2wiOm51bGx9.ORiRoaQSXBl3C9jgAZ8NatS9YLaai2NLbu2YiDIOdCc"} undefined
12:31:32 1|Socket Server    |     at sendToSentry (/Volumes/User/parabol/dev/web.js:85538:11)
12:31:32 1|Socket Server    |     at getVerifiedAuthToken (/Volumes/User/parabol/dev/web.js:84436:28)
12:31:32 1|Socket Server    |     at getQueryToken (/Volumes/User/parabol/dev/web.js:84081:41)
12:31:32 1|Socket Server    |     at handleUpgrade …
```
> fix: Send correct websocket status code

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/MobileDashSidebar.tsx
- packages/client/modules/userDashboard/components/OrgBilling/Organization.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
- packages/server/graphql/types/Organization.ts
Fix: https://github.com/ParabolInc/parabol/issues/9738
> fix: team lead can view teams in org settings

- packages/server/__tests__/processRecurrence.test.ts
Running the tests locally crashes the server, because the retro constructed for testing was not fully fleshed out. Also updated the RRules used to have the frequency weekly, which is the only setting the app allows.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Update processRecurrence tests

- packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
I was running through the app on an un-upgraded team and noticed the CTA to upgrade under TeamSettings was "Upgrade Team to Team" which read a bit oddly to me. It wasn't clear that "Team" was a plan you could buy. Without reading the description text near the CTA, I would have thought, "wait, isn't my team already a team?"
This trivial change changes the CTA to read "Upgrade to Team Plan"
Adding @nickoferrall to the PR review just in case there was some intention behind this CTA I missed
> feat: update plan upgrade CTA label

- packages/client/modules/teamDashboard/components/PromoteTeamMemberModal/PromoteTeamMemberModal.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
- packages/server/graphql/public/typeDefs/Team.graphql
- packages/server/graphql/public/typeDefs/_legacy.graphql
- packages/server/graphql/public/types/Team.ts
Fix https://github.com/ParabolInc/parabol/issues/9732
> feat: update promote team copy

- packages/server/billing/stripeWebhookHandler.ts
- packages/server/graphql/private/mutations/stripeDeleteSubscription.ts
- packages/server/graphql/private/mutations/stripeUpdateSubscription.ts
- packages/server/graphql/private/mutations/upgradeToTeamTier.ts
- packages/server/graphql/private/typeDefs/_legacy.graphql
When we increase the team subscription price from $6 to $8, it would be a new pricing ([parabol-pro-800](https://dashboard.stripe.com/prices/parabol-pro-800) vs. [parabol-pro-600](https://dashboard.stripe.com/prices/parabol-pro-600)) and that means we need to migrate all customers from the old subscriptions to new ones. I plan to do the migration with a separate script that interacts with Stripe directly. The change we need from Parabol app side is to listen for the subscription changes and then update the `stripeSubscriptionId` field for the org accordingly.
1. Start a local listener `stripe listen --forward-to localhost:3000/stripe`
2. Upgrade an org to `team` tier and verify the `stripeId` and `stripeSubscriptionId` in `Organization` table match with the `customerId` and …
> feat(stripe): handle Stripe subscription events

- packages/server/fileStorage/FileStoreManager.ts
- packages/server/graphql/private/mutations/checkRethinkPgEquality.ts
Writes errors to S3 instead of to the local filesystem.
Now we don't have to go on a scavenger hunt across our pods trying to find the file 🎉 
e.g. https://action-files.parabol.co/local-development/store/__debug__/rethinkdbEquality_RetroReflectionGroup_2024-05-28T21:50:43.936Z.json
> feat: write equality checker to file store

- packages/client/package.json
- yarn.lock
v3.0.3 has the same logic as v3.0.1, I just don't want to risk having someone upgrade to the broken v3.0.2
I also updated some packages in trebuchet client so there's more code reuse.
> fix: bump trebuchet-client to latest version

- packages/client/components/Dashboard/DashSidebar.tsx
- packages/client/components/Dashboard/LeftDashNavItem.tsx
- packages/client/components/SideBarStartMeetingButton.tsx
- packages/client/types/constEnums.ts
Easier than noting small paddings and margins, colors, etc. (which I would think is annoying), I made a few refinements to get closer to the Figma. If you like them feel free to merge them!
[See the Loom](https://www.loom.com/share/b2bec95ef2af4407ae037f00f9033c62)
> feat: nav style refinements

- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationPanel.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResults.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResultsRoot.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerObjectCard.tsx
- packages/server/graphql/private/typeDefs/_legacy.graphql
- packages/server/graphql/types/JiraServerIntegration.ts
- packages/server/graphql/types/JiraServerIssue.ts
- packages/server/integrations/jiraServer/JiraServerRestManager.ts
Fixes #9788 
https://www.loom.com/share/0c3e669749d14780896e4185a8e74727?sid=96871a93-2b12-4b78-aa88-5ffcc24f987e
> feat: Add Jira Server to Your Work

- packages/server/graphql/public/permissions.ts
- packages/server/graphql/public/rules/getResolverDotPath.ts
- packages/server/graphql/public/rules/isOrgTier.ts
- packages/server/graphql/public/rules/isViewerBillingLeader.ts
- packages/server/graphql/public/rules/isViewerOnOrg.ts
Adds type safety to the GQL permission rules.
Addresses comment here: https://github.com/ParabolInc/parabol/pull/9750#discussion_r1607070301
I'm not sure I love this solution. It fixes the problem, but it's a little verbose. Looking for thoughts!
https://www.loom.com/share/6e708950dd4344e5beb7c6e6366cdd80?sid=36830171-f926-4c86-96b4-e70cce2f1c76
> feat: type safety for gql perms

- packages/server/postgres/migrations/1717083323369_removeKudosNotifications.ts
Fix issue on staging where kudos notifications can't be resolved: https://app.datadoghq.com/logs?query=service%3Aparabol%20env%3Astaging&agg_m=count&agg_m_source=base&agg_t=count&cols=host%2Cservice&event=AgAAAY_KGuJT0GOswAAAAAAAAAAYAAAAAEFZX0tHdWxDQUFCQ2xQY1BFQzd3dlFBQgAAACQAAAAAMDE4ZmNhMWItMjJmNy00ZWUyLWI1ZTItZThmMjBmNjhlMTkx&fromUser=true&index=%2A&messageDisplay=inline&refresh_mode=sliding&storage=hot&stream_sort=desc&viz=stream&from_ts=1717079344464&to_ts=1717082944464&live=true
> fix: clear kudos received notifications

- packages/client/components/ActivityLibrary/ActivityCard.tsx
- packages/client/components/ActivityLibrary/ActivityDetails/ActivityDetails.tsx
- packages/client/components/ActivityLibrary/ActivityGrid.tsx
- packages/client/components/RetroDrawerTemplateCard.tsx
Fixes #9809 
It conflicts with the favourite indicator.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: remove custom activity badge

- packages/server/database/rethinkDriver.ts
- packages/server/postgres/migrations/1717685812675_addSuggestedActionTeamIdIndex.ts
- packages/server/safeMutations/safeArchiveTeam.ts
Removing a team would filter through all SuggestedActions which results in read spikes and is very slow.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Add teamId index to SuggestedAction

- packages/server/fileStorage/S3FileStoreManager.ts
Fixes #9757
Cloudflare 520 does not give us enough information to know what went wrong on AWS side, so let's just treat it as transient and retry.
```
yarn build
for X in {1..10}; do echo $X; yarn predeploy; done
```
> fix: Retry S3 upload after cloudflare error

- packages/client/components/DashNavList/DashNavList.tsx
- packages/client/components/DashNavList/DashNavMenu.tsx
- packages/client/components/MeetingOptions.tsx
- packages/client/components/NewMeetingActionsCurrentMeetings.tsx
- packages/client/ui/Menu/Menu.tsx
- packages/client/ui/Menu/MenuContent.tsx
Fix https://github.com/ParabolInc/parabol/issues/9830
Loom demo: https://www.loom.com/share/ba5521f4b6464fd8bb5f6331ec5eab2e
> feat: add menu to dashboard nav

- packages/client/components/Dashboard/DashSidebar.tsx
With the new nav styles, the add meeting primary button block is a little shorter, so update the nav layout
> fix: add meeting block is now 70px

- .github/workflows/release-to-prod.yml
- .github/workflows/release-to-staging.yml
Adds notifications for Slack whenever release-to-[staging|production] workflow fail.
> chore(ci): release-to jobs for both staging and production will notify Slack whenever they fail

- packages/client/components/ScopingSearchResultItem.tsx
Fix https://github.com/ParabolInc/parabol/issues/9858
Loom demo: https://www.loom.com/share/d47bb7b4bdce4ad49cc43cbbd7e38714
> fix: clicking scope link does not affect checkbox

- packages/server/database/types/ReflectionGroup.ts
- packages/server/graphql/mutations/helpers/notifications/SlackNotifier.ts
- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
- packages/server/graphql/mutations/resetRetroMeetingToGroupStage.ts
- packages/server/postgres/migrations/1718641323037_removeSummaryFromRetroGroup.ts
Fix https://github.com/ParabolInc/parabol/issues/9712
> chore: remove summary from retro reflection group

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
Fix https://github.com/ParabolInc/parabol/issues/9822
Demo: https://www.loom.com/share/9cc4e5ff56134197ae0e7295359c9dbf
> fix: remove AI UI if user doesn't have access to AI

- packages/client/components/DashNavList/DashNavList.tsx
- packages/client/components/DashNavList/DashNavListTeams.tsx
- packages/client/components/SideBarStartMeetingButton.tsx
- packages/client/ui/Menu/MenuContent.tsx
Fix issues @mattkrick shared [here](https://github.com/ParabolInc/parabol/pull/9863#issuecomment-2187305336)
Loom demo: https://www.loom.com/share/7ec1e767949b4c7fbee1fff3afe2ed09
This PR ensures that:
- Opening and closing the sidebar animates smoothly
- If an org has no teams, there's no divider
- The settings menu doesn't conflict with the text on the task cards
Things to note:
- I reduced the width of the Add Meeting button slightly. It's still wider than prod, but narrower than it was. 
- The three-line long team name is an edge case. A team name with the max characters allowed is usually 2 lines, but if the characters are particularly wide, e.g. `3` instead of `i`, it can take up three lines. I'm hesitant about changing the padding without a review from @ackernaut, so I'd prefer to …
> fix: ensure dashboard sidebar animates smoothly

- packages/embedder/resetStalledJobs.ts
Fixes #9842 
When resetting stalled jobs we did not check whether it was still running or it had failed. This would reset the jobs to queued so the embedder would retry failed job indefinetely.
> fix: Don't reset failed embedding jobs

- packages/client/components/DashNavList/PublicTeamsModal.tsx
In production, if there are a bunch of public teams, you can't scroll down to see all of them. 
This PR lets users scroll down to see all of their teams.
> fix: can scroll public teams modal

- packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailReflectionCard.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/RetroTopic.tsx
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummarySheet.tsx
Fix https://github.com/ParabolInc/parabol/issues/9862
In production, download to pdf just downloads the first page, rather than all pages. This is because `window.print()` just shows the visible part of the web page in a SPA.
In this PR, I'm opening a new window and rending the HTML as a static snapshot so that all of the content is visible. 
The pdf shows "about:blank" at the bottom left of the page. I don't think this can be removed as the browser checks the URL. And there's some box shadow at the end of the summary in the PDF, but I think that's fine.
> fix: download pdf shows multiple pages

- packages/client/components/NewMeetingActionsCurrentMeetings.tsx
- packages/client/components/NewMeetingTeamPicker.tsx
Fixes #9892 
Menu items were not properly nested because I did not retest #9679 with latest master before merging.
> fix: User can change team in Activity Library

- packages/client/modules/userDashboard/components/OrgBilling/OrgBillingDangerZone.tsx
For Team tier users in Organization Settings, in production, we ask them to contact us if they want to downgrade. This PR links them to the billing page where they can downgrade instead. 
In prod:
In this PR for enterprise users (less space before "Contact us"):
> chore: remove contact us message for team users that want to downgrade

- packages/embedder/insertDiscussionsIntoMetadataAndQueue.ts
- packages/embedder/insertMeetingTemplatesIntoMetadataAndQueue.ts
When no new metadata was inserted, the resulting empty array would be fully outer joined with the models, resulting in [undefined, 'ember_1'] pairs.
> fix: Avoid adding embedding jobs without metadata id

- packages/client/components/ActivityLibrary/ActivityLibrary.tsx
- packages/client/components/ActivityLibrary/ActivityLibraryEmptyState.tsx
- packages/client/hooks/useDebouncedSearch.ts
- packages/client/package.json
- packages/embedder/ai_models/TextEmbeddingsInference.ts
- packages/embedder/importHistoricalRetrospectiveDiscussionTopic.ts
- packages/server/__tests__/user.test.ts
- packages/server/graphql/public/typeDefs/User.graphql
- packages/server/graphql/public/types/User.ts
- packages/server/package.json
- yarn.lock
Fixes #9774, #9775
Add a template search query to the User object.
https://www.loom.com/share/114efbf0a1864ba09816c0bf87a28620?sid=86867080-17c0-405a-bf6a-828a591bdfad
> feat: Add search template mutation

- packages/client/mutations/EndRetrospectiveMutation.ts
Discovered by @Dschoordsch [here](https://parabol.slack.com/archives/C608QL4RH/p1719502480380049)
> fix: remove ai from summary url if no ai env var

- packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
- packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
- packages/client/subscriptions/TeamSubscription.ts
- packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
- packages/server/graphql/private/mutations/stripeDeleteSubscription.ts
- packages/server/graphql/private/mutations/upgradeToTeamTier.ts
- packages/server/graphql/public/mutations/createStripeSubscription.ts
- packages/server/utils/defaultTier.ts
- packages/server/utils/stripe/StripeManager.ts
Upgrading via stripe takes too long!
It's still too long, but this shaves off about 2 seconds (in the video it was 6!) & now you don't need to listen to webhooks to test locally.
https://www.loom.com/share/a2482e91d4b940e19dd31f66fb7fa119?sid=67a06848-bc0e-490d-85ac-3d230073d975
> fix: speed up team upgrade

- packages/client/mutations/fragments/UpgradeToTeamTierFrag.ts
- packages/server/graphql/public/typeDefs/Organization.graphql
we had an old field in the GQL schema that had no resolver. this fixes it
> fix: remove Organization.teams field from gql

- packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
Fixes #9901
I had messed this up in #9370
https://github.com/ParabolInc/parabol/assets/7331043/d8cabb2d-0b22-448f-9755-1d9012e8be32
> fix: Allow to start recurrence for existing Standups

- packages/client/components/ActivityLibrary/ScheduleMeetingButton.tsx
- packages/client/components/ScheduleDialog.tsx
We were hiding the schedule button when no GCal integration was available on the instance. This is wrong in some cases when the dialog still allows to set up recurrence.
This PR also addresses a small title mismatch discovered by @garethaledavies which claimed recurring meetings when the option was not available.
Fixes #9913 #9777 
https://www.loom.com/share/fda8dcea642949f698d37962fab216b6?sid=a2acbf99-6e62-4a0d-becb-f63a9da21b96
> fix: Allow starting recurring meetings without GCal

- packages/server/socketHandlers/handleOpen.ts
Developing locally, sometimes when the server would restart i'd get a `cannot read isReady of undefined` error.
I think that's because connectionContext wasn't created synchronously, so this fixes that.
In my testing, it fixes the problem, but there may be a 2nd culprit somewhere.
> fix: connectionContext always available

- packages/client/modules/userDashboard/components/OrgBilling/BillingForm.tsx
- packages/server/billing/stripeWebhookHandler.ts
- packages/server/graphql/mutations/helpers/oldUpgradeToTeamTier.ts
- packages/server/graphql/private/mutations/draftEnterpriseInvoice.ts
- packages/server/graphql/private/mutations/stripeCreateSubscription.ts
- packages/server/graphql/private/mutations/stripeUpdateSubscription.ts
- packages/server/graphql/private/typeDefs/_legacy.graphql
- packages/server/graphql/public/mutations/createStripeSubscription.ts
- packages/server/utils/stripe/StripeManager.ts
When a 3DS payment fails, that causes the subscription to go from incomplete to incomplete_expired.
We had a webhook handler that would set the `stripeSubscriptionId` to whatever was coming in from stripe, even if the incoming subscription was expired!
That chain of logic would attach an expired `stripeSubscriptionId` onto an organization, and when they tried to upgrade again, it would fail because they already had a subscription 🤮 
this checks to make sure the subscription is valid before updating the `Organization.stripeSubcriptionId`.
Additionally, i noticed that after an upgrade failed, if you click the upgrade button again, it doesn't do anything except remove the error message. That felt bad, so I fixed that logic.
> fix: handle failed 3DS payments

- packages/server/graphql/public/types/User.ts
I had hardcoded it before 🤦
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Read embedder URL from env

- packages/client/hooks/useServiceWorkerUpdater.ts
Fixes #9930 
Tested using an on-demand-env. I started it on 7.37.8, upgraded to 7.38.0 without this change, so the link was to [releases](https://github.com/ParabolInc/parabol/releases/), then upgraded to a Docker generated on this branch and the link was pointing to [v7.38.1](https://github.com/ParabolInc/parabol/releases/tag/v7.38.1)
> chore(client): when a release happens, links to the specific tag version

- packages/server/graphql/public/typeDefs/NotifyDiscussionMentioned.graphql
- packages/server/graphql/public/types/NotifyDiscussionMentioned.ts
Notify discussion mentioned can get triggered by any meeting!
This is likely caused by the 2nd source of truth we had until now.
> fix: discussion mentioned can be triggered by all meetings

- packages/server/postgres/migrations/1722632147643_IntegrationProvider-null-not-distinct.ts
no dupe global providers here!
> fix: null not distinct

- packages/server/graphql/mutations/helpers/bootstrapNewUser.ts
- packages/server/safeMutations/acceptTeamInvitation.ts
Fixes #10085 
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Don't fail acceptTeamInvitation for duplicate suggested actions

- packages/server/dataloader/azureDevOpsLoaders.ts
- packages/server/utils/AzureDevOpsServerManager.ts
We used to fetch this per issue although we only need it per project. Moved it to a dataloader to simplify this.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Avoid refetching project template for ADO

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummaryResult.tsx
- packages/client/package.json
- packages/server/package.json
- yarn.lock
Meeting summary emails aren't sending because `dompurify` doesn't work on the server. This PR uses `sanitize-html` instead, which now works.
> fix: email-meeting-summaries

- packages/server/postgres/migrations/1723492538114_MeetingSettings-phase2redo.ts
Some action meetings had selectedTemplateIds. i'm not sure how this happened, but it did. 
the old migration didn't migrate over action meetings with bogus selectedTemplateIds. yay relational integrity ftw!
> fix: action meetings that had templates. wtf

- packages/client/hooks/useMeetingMemberAvatars.ts
- packages/server/graphql/mutations/helpers/removeTeamMember.ts
- packages/server/graphql/mutations/promoteToTeamLead.ts
- packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
- packages/server/postgres/migrations/1724174924811_oneTeamLead.ts
- packages/server/safeMutations/acceptTeamInvitation.ts
we have a staggering number of teams without leads.
I'm not sure how we got here, but this includes a migration to fix the existing teams & changes the business logic to make sure it doesn't happen again.
> fix: no team leads

- packages/client/modules/userDashboard/components/InvoiceRow/InvoiceRow.tsx
- packages/server/graphql/public/fields/invoices.ts
- packages/server/graphql/public/typeDefs/Invoice.graphql
I mistakenly used due_at, which can be null if the payment type is automatic.
switched to period_end.
> fix: use period end instead of due at

- packages/client/mutations/ArchiveTeamMutation.ts
Fixes #10076 
- Go to `http://localhost:3000/me/organizations/xxx/teams` as a team/billing lead or org admin
- Click into a. team
- Click to top-right drop down menu and select "Delete Team"
- In the opened-up modal, type the team name and click the red button
- Observe the page falls back to `http://localhost:3000/me/organizations/xxx/teams` and the archived team has been removed from the list
> fix(orgAdmins): archived teams should be removed from the OrgTeams view

- packages/client/modules/userDashboard/components/OrgTeamMembers/OrgTeamMembers.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
- packages/server/graphql/public/types/Organization.ts
Fixes #10080 
- Go to `http://localhost:3000/me/organizations/xxxx/teams`
- Can only see the teams the billing lead is in
- Click into a team, can delete the team
- Go to `http://localhost:3000/me/organizations/xxxx/teams`
- Can see all teams within the org
- Click into any teams, can delete them
> fix(orgAdmins): Billing leaders should not see all teams in the org

- packages/client/modules/demo/initDB.ts
- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/9861
> feat: add ai summary to demo

- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Fixes #10185 
- Go to org members page: `http://localhost:3000/me/organizations/xxxx/members`
- Type something in the search bar
- Observed name matched members present
> feat(orgAdmin): search in org members page

- packages/server/dataloader/integrationAuthLoaders.ts
forgot to filter out duplicate channelIds on the SlackNotification dataloader when refactoring to PG.
> fix: multiple slack notifications

- packages/client/components/OrgAdminActionMenu.tsx
Fixes [🔒the issue](https://parabol.slack.com/archives/C4JAUUZ9P/p1725887797276709) where user cannot remove themselves from the org
- Logged in as a normal user without billing leader or org admin role
- Go to `http://localhost:3000/me/organizations/xxxx/members`
- Observe the 3-dot menu icon at the user row
- Click it and see you can remove yourself
> fix(orgAdmin): user should be able to remove themselves from the org

- package.json
- packages/client/hooks/useSortNewReflectionGroup.ts
- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
- packages/client/utils/handleSuccessfulLogin.ts
- packages/embedder/ai_models/ModelManager.ts
- packages/embedder/package.json
- packages/gql-executor/package.json
- packages/integration-tests/package.json
- packages/server/fileStorage/LocalFileStoreManager.ts
- packages/server/package.json
- packages/server/parseBody.ts
- packages/server/parseFormBody.ts
- packages/server/postgres/migrations/1726174443131_dropThreadParentId.ts
- yarn.lock
threadParentId exists on Task, too, so we can't use it as a foreign key just on Comment.
Also bumped the version of typescript since we were a few behind & i started getting errors when using the vscode version vs. our workspace version.
> fix: threadParent can exist outside comment table

- packages/server/__tests__/autoJoin.test.ts
- packages/server/billing/helpers/adjustUserCount.ts
- packages/server/postgres/migrations/1725438336254_addOrganizationUserUniqueConstraint.ts
Fixes #9302
Add a constraint that forbids duplicate organization users. There is no need to have multiple entries as the join/leave events are already captured in OrganizationUserAudit.
> fix: Remove duplicate org users

- packages/client/components/MeetingSubnavItem.tsx
- packages/client/modules/teamDashboard/components/AgendaItem/AgendaItem.tsx
- Hover an agenda item at team dash page
- See full length of the text in the tooltip
- Delete/Pin/Unpin still works
- Hover an agenda item in a check-in meeting
- See full length of the text in the tooltip
- Delete/Pin/Unpin still works
> fix(misc): show full length of agenda item text when hovering

- packages/server/graphql/mutations/moveTeamToOrg.ts
handles orgs without an unarchived team
> fix: isPaid flag when moving teams to 0-team org

- packages/server/graphql/private/mutations/processRecurrence.ts
- packages/server/graphql/public/mutations/updateRecurrenceSettings.ts
In production we have a case where teams that are empty are still creating series, but the new meetings have no stages since there are no team members.
We have a 2nd case where archived teams could still have active meeting series. Once a team is archived, their series should be cancelled.
> fix: stop series when team is no more

- packages/server/graphql/mutations/endCheckIn.ts
Postgres does not like inserts with empty lists.
End a checkin without any pinned agenda items.
> fix: Fix crash in end checkin without pinned agenda items

- packages/client/components/ActionMeetingAgendaItems.tsx
- packages/client/components/ActionMeetingUpdates.tsx
- packages/client/components/MeetingControlBar.tsx
- packages/client/components/PokerEstimatePhase.tsx
- packages/client/utils/showTimerInPhase.ts
Originated from [this Slack message](https://parabol.slack.com/archives/C03LL1JRFH8/p1727731167093669)
- Start a poker meeting
- Add some item to estimate
- Advance to the estimate phase
- See you can start a timer
- Start an action meeting
- Add some agenda items
- Advance to the agenda item phase
- See you can start a timer
> feat(misc): add timer control to more meeting phases

- packages/server/postgres/migrations/1727885996466_migrateFeatureFlags.ts
Fix https://github.com/ParabolInc/parabol/issues/10248
I think noAISummary should just exist on the org and not the org and user. That's a simpler approach. 
This PR migrates the noAISummary flag to the new featureFlag table and creates an org scoped flag. 
This is the only flag that I think we need to migrate.
> chore: migrate noaisummary flag

- packages/server/server.ts
- packages/server/socketHandlers/handleDisconnect.ts
Makes sure the Web Server ends with code 0 if SIGTERM is handled.
> fix(webserver): exits with code 0 when SIGTERM is handled

- packages/server/graphql/public/types/NewMeetingStage.ts
this bug popped up with the NewMeeting migration. we don't log variables, so I couldn't get a good trace on it
> fix: timeRemaining

- packages/client/hooks/useAutoCheckIn.ts
- packages/server/graphql/mutations/joinMeeting.ts
Sentry started reporting a new error: `duplicate key value violates unique constraint "MeetingMember_pkey"`.
This is called because `joinMeeting` must be getting called by the same user multiple times.
To prevent this, I stopped the client from issuing multiple calls & stopped the server in case the meeting member was already created.
> fix: catch error if user tries to join meeting twice

- codegen.json
- packages/server/graphql/private/mutations/removeFeatureFlagOwner.ts
- packages/server/graphql/private/typeDefs/Mutation.graphql
- packages/server/graphql/private/typeDefs/RemoveFeatureFlagOwnerSuccess.graphql
- packages/server/graphql/private/typeDefs/RemoveFeatureFlagPayload.graphql
- packages/server/graphql/private/types/RemoveFeatureFlagOwnerSuccess.ts
With this PR, we can remove feature flag owners. I prefer creating a new mutation rather than updating `applyFeatureFlag` because I think it's better to have distinct names to make it clearer for the sales team. 
Add a feature flag, apply a feature flag to a subject, e.g. an orgId, and the remove it like so:
```
mutation { 
removeFeatureFlagOwner(flagName: "hasSingleColumnStandupsFlag", subjects: {
orgIds: ["AQQ5zJw652"]
}
) {
__typename
... on RemoveFeatureFlagOwnerSuccess {
organizations {
name
featureFlag(featureName: "hasSingleColumnStandupsFlag")
}
}
... on ErrorPayload {
error {
message
}
}  
}
}
```
> chore: remove feature flag owner

- packages/server/postgres/migrations/1728596434080_Task-phase2fixup.ts
The phase 2 migration serialized the `content` column 1 too many times.
This corrects that problem
> fix: correct serialization of Task.content

- packages/client/hooks/useManualClientSideTrack.ts
- packages/client/modules/teamDashboard/components/TeamDashInsightsTab/FeedbackModal.tsx
- packages/server/utils/analytics/analytics.ts
Fix https://github.com/ParabolInc/parabol/issues/10243
> feat: insights feedback functionality

- packages/server/graphql/public/types/UpdateTaskPayload.ts
uses the full payload from the DB instead of a partial (saw this bug come through in sentry)
> fix: complete partial value for updateTaskPayload

- packages/server/postgres/migrations/1729269619262_addSharedSecretIntegrationProvider.ts
Preparations for #10360
For mattermost notifications we need to store a shared key and the server url in the integration provider. To make it explicit I added a new field for the key. The serverBaseURL field is already very fitting, so reusing that one.
Unlike the previous webhook integration, the provider will be used on org or global scope and does not have the channel information. This needs to go into the integration auth.
[Please list all the testing scenarios …
> chore: Add migration for shared secret integration provider

- packages/server/graphql/mutations/helpers/createNewMeetingPhases.ts
- packages/server/graphql/mutations/helpers/safeCreateRetrospective.ts
- packages/server/graphql/mutations/startSprintPoker.ts
- packages/server/graphql/public/mutations/startCheckIn.ts
Resolves #10384 
Discussion items were created and inserted before the meeting, which resulted in foreign key errors.
- Create and run through meetings of the following types **with** and **without** agenda items on the team:
- checkin
- retrospective
- poker
> fix: Crash when starting a checkin with agenda items

- packages/server/postgres/migrations/1729696433080_addMeetingsCountToInsight.ts
`1728596433080_addMeetingsCountToInsight` was already pushed to prod, but now the migration exists with a new name.
this fixes that
> fix: if not exists on meetingsCount

- packages/server/dataloader/customLoaderMakers.ts
- packages/server/postgres/select.ts
- packages/server/postgres/types/index.d.ts
this is the hottest query we have right now & it runs every 5 mins, so i made it a little more efficient.
> fix: latestMeeting query

- packages/server/graphql/public/mutations/createStripeSubscription.ts
- packages/server/utils/analytics/analytics.ts
We have a long-term bug where we lost track of the user who has performed self-serve upgrade (we just record `love@parabol.co` did that). This has caused issue like [this one](https://parabol.slack.com/archives/C03C3J42WDU/p1730223946941409).
This small PR is a walk around fix: we emit a new metric when a user attempted to upgrade. This way later in the data sanctum we can then join this new metric with the old `Organization Upgraded` metric to find the match.
> chore(metrics): add metrics to identify who attempte to upgrade organization

- scripts/toolboxSrc/preDeploy.ts
- scripts/toolboxSrc/standaloneMigrations.ts
Predeploy now throws if a migration fails
> fix: throw on migration error

- packages/server/graphql/public/mutations/generateInsight.ts
Team member can be null in `generateInsight` when a Parabol super user executes the mutation for a team they are not a member of
> fix:  teamMember is nullable in generate insight

- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
The field is visible in the member list, so it should be in the CSV export as well.
- Export the member list to CSV and see the last seen at field in the export
> feat: Add lastSeenAt to organization members CSV export

- scripts/webpack/dev.servers.config.js
- scripts/webpack/prod.servers.config.js
no-deps requires the jsx-runtime, so we add that to the server bundler as well
> fix: supprt jsx runtime in SSR

- .github/ISSUE_TEMPLATE/release_test.md
Fixes a broken link in the Github release test pr template
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: github pr template release test now with the correct Mattermost link

- .github/workflows/docker-external.yml
Fixes name of the workflow to share Docker images externally
> fix(docker-external): workflow name fixed

- packages/client/mutations/LoginWithGoogleMutation.ts
- packages/client/mutations/SignUpWithPasswordMutation.ts
- packages/client/mutations/VerifyEmailMutation.ts
We were testing whether redirecting new users to the team page would increase sign-ups. This isn't being tested now, so let's remove the code.
We agreed to remove this feature flag and the code here: https://parabol.slack.com/archives/C836NA350/p1727801752709289
> chore: remove signUpDestinationTeam

- packages/client/components/ReflectionCard/AddReactjiButton.tsx
Fixes #10512 
The popover would close before the emoji was selected. Switching its mode to modal fixes this issue.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Adding reactions in standup via mouse works more than once

- packages/client/components/JiraScopingSearchFilterMenu.tsx
- packages/client/components/JiraServerConfigMenu.tsx
- packages/client/components/JiraServerScopingSearchBar.tsx
- packages/client/components/JiraServerScopingSearchResults.tsx
- packages/client/components/PokerDimensionFinalScorePicker.tsx
- packages/client/components/PokerEstimateHeaderCard.tsx
- packages/client/components/ScopePhaseArea.tsx
- packages/client/components/ScopePhaseAreaAddJiraServer.tsx
- packages/client/components/TaskIntegrationLink.tsx
- packages/client/components/TeamPrompt/TeamPromptWorkDrawer.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationPanel.tsx
- packages/client/components/TeamPrompt/WorkDrawer/JiraServerIntegrationResults.tsx
- packages/client/modules/teamDashboard/components/ProviderList/ProviderList.tsx
- packages/client/types/constEnums.ts
- packages/client/utils/constants.ts
- packages/server/graphql/mutations/setTaskEstimate.ts
- packages/server/graphql/public/typeDefs/JiraServerIntegration.graphql
- packages/server/graphql/public/typeDefs/JiraServerIssue.graphql
- packages/server/graphql/public/typeDefs/Mutation.graphql
- packages/server/graphql/public/typeDefs/TeamMemberIntegrations.graphql
- packages/server/integrations/jiraServer/JiraServerRestManager.ts
- scripts/create-jira-keys.sh
Fixes #10051 
Only UI text was updated.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Rename Jira Server to Jira Data Center

- packages/server/graphql/public/types/Organization.ts
Public teams were showing up for super users, e.g. Parabol's org, but not for other orgs that have the flag turned on. This fixes that.
See slack thread: https://parabol.slack.com/archives/C4JAUUZ9P/p1732789118369329
> fix: show public teams

- .env.example
Clarifies when GOOGLE_CLOUD vars must be set:
- To use the GCP Natural Language API. The error message is more detailed.
- To use Google Cloud Storage as file store provider.
> chore: clarify when Google Cloud credentials are required

- packages/server/graphql/public/types/Task.ts
- packages/server/postgres/migrations/2024-11-27T00:50:24.390Z_taskContentToTipTap.ts
Migrates legacy draft-js formatted tasks to TipTap.
NOTE: these migrations are using 3rd party packages, e.g. draft-js. Once we're done with draft-js, we'll have to rebase our migrations to get rid of draft-js.
> chore: convert legacy tasks to TipTap

- package.json
- packages/chronos/package.json
- packages/embedder/package.json
- packages/gql-executor/package.json
- packages/server/package.json
- yarn.lock
Upgrades node to [latest stable in v20](https://nodejs.org/en/about/previous-releases) to get the [updated Docker images](https://hub.docker.com/_/node/tags?name=20.).
> feat(node): upgrade to 20.18.1, latest stable in v20

- packages/client/components/ParabolScopingSearchResultItem.tsx
- packages/client/components/ParabolScopingSearchResults.tsx
- packages/client/components/promptResponse/TipTapEditor.tsx
- packages/client/components/promptResponse/TipTapLinkMenu.tsx
- packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
- packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
- packages/client/mutations/handlers/handleUpsertTasks.ts
Fixes a few bugs that a user found in poker scoping.
Namely:
- tasks stick around, even after archived
- old tasks are not readonly
- the link editor updates new poker scoping tasks, making it an old task, which is then readonly (this UX is still not great)
- the edit link on the link preview menu didn't work
> fix: tasks in poker scoping

- packages/server/listenHandler.ts
- packages/server/utils/serverHealthChecker.ts
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Catch server health checker errors

- packages/client/Atmosphere.ts
- packages/client/components/ActionMeetingSidebar.tsx
- packages/client/components/ActionSidebarAgendaItemsSection.tsx
- packages/client/components/AnalyticsPage.tsx
- packages/client/components/AtmosphereProvider/AtmosphereProvider.tsx
- packages/client/components/AuthProvider.tsx
- packages/client/components/MassInvitationTokenLink.tsx
- packages/client/components/MeetingSidebarTeamMemberStageItems.tsx
- packages/client/components/PokerMeetingSidebar.tsx
- packages/client/components/PokerSidebarEstimateSection.tsx
- packages/client/components/RetroMeetingSidebar.tsx
- packages/client/components/RetroSidebarDiscussSection.tsx
- packages/client/components/TeamInvitationSSO.tsx
- packages/client/hooks/useAutoCheckIn.ts
- packages/client/hooks/useGotoNext.ts
- packages/client/hooks/useGotoPrev.ts
- packages/client/hooks/useSVG.ts
- packages/client/hooks/useServiceWorkerUpdater.ts
- packages/client/hooks/useSlackChannels.ts
- packages/client/hooks/useSubscription.ts
- packages/client/hooks/useTrebuchetEvents.ts
- packages/client/modules/email/components/SummaryEmail/ExportToCSV.tsx
- packages/server/billing/helpers/adjustUserCount.ts
- packages/server/billing/helpers/handleEnterpriseOrgQuantityChanges.ts
- packages/server/graphql/mutations/createTask.ts
- packages/server/graphql/subscribeGraphQL.ts
Fixes #10567 
`new Promise().catch()` is implicitly passing `undefined` to the rejection handler and thus the error is not caught, but bubbles up.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Properly ignore supposedly ignored errors

- packages/client/Atmosphere.ts
- packages/client/components/EmailPasswordAuthForm.tsx
- packages/client/utils/getSAMLIdP.ts
- packages/server/graphql/mutations/helpers/resolveDowngradeToStarter.ts
- packages/server/graphql/private/mutations/loginSAML.ts
- packages/server/postgres/migrations/2024-12-12T08:40:19.695Z_removeURLFromSAML.ts
- packages/server/utils/getSAMLURLFromEmail.ts
The request contains the issue instant date, which needs to be fresh for CloudFlare Access.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Refresh the SAML request URL for each login attempt

- packages/client/components/ParabolScopingSearchResultItem.tsx
- packages/client/components/PokerEstimateHeaderCardParabol.tsx
- packages/client/components/TeamPrompt/TeamPromptResponseCard.tsx
- packages/client/components/ThreadedCommentBase.tsx
- packages/client/components/promptResponse/PromptResponseEditor.tsx
- packages/client/hooks/useTipTapEditorContent.ts
- packages/client/hooks/useTipTapTaskEditor.ts
- packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
- packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
- packages/client/shared/isEqualWhenSerialized.ts
Fixes #10606
There were 2 bugs triggering this:
1. When testing if TipTap JSON content had changed, the answer was always true because our equality check looked at prototypes, and tiptap uses a null prototype e.g. Object.create(null), whereas JSON.parse uses an Object prototypes `{}`. I wrote a custom equality checker & fixed the issue in all tiptap instances
2. the onBlur handler was firing after navigation. This even happened if we delayed navigation until after the blur event via `setImmediate`. I moved the `onBlur` from the component to the TipTap instance and now onBlur does not fire. This means if the user makes changes and then navigates away from that page without first blurring the content, the content will not get updated. I think this is the desired effect, as it's the same …
> fix: Parabol poker task overwrites, ignore prototypes for equality check on tiptap

- packages/client/modules/demo/commentLookup.ts
- packages/client/modules/demo/initDB.ts
Fixes comments in the demo meeting
> fix: Comments in demo meeting

- packages/client/components/GroupingKanban.tsx
- packages/client/components/GroupingKanbanColumn.tsx
- packages/client/components/ReflectionCard/ReflectionCard.tsx
- packages/client/components/ReflectionCard/ReflectionCardAuthor.tsx
- packages/client/components/RetroGroupPhase.tsx
- packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
- packages/client/components/promptResponse/TipTapEditor.tsx
- packages/client/components/promptResponse/TipTapLinkMenu.tsx
- packages/client/hooks/useResizeObserver.ts
- packages/client/hooks/useTipTapReflectionEditor.ts
- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/EmailReflectionCard.tsx
- packages/client/mutations/NavigateMeetingMutation.ts
- packages/client/styles/theme/global.css
- packages/client/utils/smartGroup/getTitleFromComputedGroup.ts
- packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
- packages/server/graphql/mutations/helpers/updateGroupTitle.ts
This fixes the following bugs discovered during the retro we had on staging before Christmas:
- Scroll container on unanonymous reflections does not include name
- Hitting # does not suggest Task Tags
- Headings on Reflections have proper line-height
- Link Modal pops up on top of Reflection
- Block quotes have style
- An error pops up when the reflection JSON length exceeds 2000 chars
- On safari, draggin a reflection doesn't trigger highlighting around the whole phase
- If user 1 has spotlight open & the facilitator navigates back a phase, user 1 doesn't automatically follow the facilitator
- When making a heading, list, codeblock or block quote, hitting enter does not submit. You must hit Enter 1 time to get out out of the mark, then again to submit
- Group titles remove linebreaks
- …
> fix: bugs in TipTap Reflection editor

- packages/server/__tests__/processRecurrence.test.ts
The tests are flaky. The effects of one test sometimes carry over to the next and cause the whole suite to fail. Or they simply timeout.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Disable processRecurrence tests

- packages/server/postgres/migrations/2025-01-07T19:41:35.458Z_reflectionsToTipTap.ts
This is about a 2 hour migration to translate legacy reflections to tip tap.
In the future, we should store reflections as JSON instead of a string, but we can do that later.
> chore: migrate old reflections to tiptap

- packages/server/graphql/public/mutations/generateRetroSummaries.ts
@gcrickman reported an issue generate retro summaries [here](https://parabol.slack.com/archives/C4JAUUZ9P/p1736453418125189?thread_ts=1736441058.342209&cid=C4JAUUZ9P).
GenerateRetroSummaries mutation needed to be moved to the public folder so that the mutation works. This was previously working, so maybe I resolved a merge conflict incorrectly and moved it back to the wrong folder. 
I'll merge this right away as it's a low risk change.
> fix: move generate retro summaries mutation to public folder

- .config/kyselyMigrations.ts
- packages/server/postgres/README.md
- packages/server/postgres/migrations/2025-01-08T00:27:52.203Z_init.ts
Our new migrator is _really_ strict & won't run any migrations if it detects that previous migration files do not exist.
So, for rebasing I came up with the strategy of changing the name of the table. That way the migrator assumes no migrations have run yet & won't throw any errors. Then, inside the migration we delete the old _migration table.
> fix: rebasing migrations

- packages/client/components/MyDashboardTimeline.tsx
- packages/client/components/TimelineRightDrawer.tsx
This PR fixes the issue where scrolling the Timeline Feed on the /me route would cause the "Active Tasks" column, to scroll as well. The Timeline Feed column now scrolls independently, ensuring the "Active Tasks" column remains static.
Fixes #10648
I had to remove the `overflow: 'auto'` from the FeedAndDrawer and add it to just the `TimelineFeed`
https://github.com/user-attachments/assets/db9086f0-15bc-4009-a00c-ae07d8cfc681
- Step 1: Navigate to the /me route.
- Step 2: Populate the Timeline Feed with enough content to cause vertical overflow.
- Step 3: Scroll within the Timeline Feed column and verify only that column is affected.
> fix: Restrict Timeline Feed scrolling to its column on /me route

- packages/mattermost-plugin/scripts/hmrServer.js
- pm2.dev.config.js
Fixes #10645 
Start the hot module reload (hmr) dev server for the mattermost plugin manually so that pm2 properly cleans it up.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: kill mattermost plugin dev server on pm2 kill

- packages/mattermost-plugin/prod.webpack.config.js
- packages/mattermost-plugin/webpack.config.js
Fixes #10657
Some systems have a very limited NAME_MAX for filenames (143), so let's strip some not so useful parts of the chunk names.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Shorten chunk names for Mattermost plugin

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/WholeMeetingSummary.tsx
- packages/server/graphql/mutations/helpers/generateRetroSummary.ts
- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
- packages/server/graphql/public/typeDefs/RetrospectiveMeeting.graphql
- packages/server/graphql/public/types/RetrospectiveMeeting.ts
Demo: https://www.loom.com/share/974d623e1e5f4864bc0fbd4947cac20b
Fix https://github.com/ParabolInc/parabol/issues/10499
In prod, if the AI summary fails to generate because of a problem with ChatGPT or because the retro doesn't have any votes so `generateRetroSummary` doesn't have any valid reflection groups, the AI meeting summary will load indefinitely.
In this PR, if we fail to generate the AI summary, we won't show the loading UI indefinitely.
> fix: summary does not load indefinitely if there are no votes

- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/10673
> feat: update insight prompt

- packages/client/types/constEnums.ts
- packages/server/graphql/mutations/helpers/generateStandupMeetingSummary.ts
- packages/server/utils/OpenAIServerManager.ts
Fix https://github.com/ParabolInc/parabol/issues/10676
This PR:
- Makes the standup AI summary more concise, reducing themes from 5 to 3, and making each paragraph shorter
- Updates the AI Explainer text so that it's not Retro specific
- Adds context of who said what in the Standup
- Upgrades the standup open ai model to gpt-4o from 4o-mini. It's still very fast, but better quality.
Note: when ending a standup locally, I run into this bug: https://github.com/ParabolInc/parabol/issues/8471
> chore: make ai standups more concise and add context

- packages/client/components/TimelineFeedList.tsx
- packages/client/utils/date/relativeDate.ts
- packages/client/utils/date/timelineGroups.ts
Fixes [this bet](https://www.notion.so/parabol/2025-T1-Shape-Up-Cycle-6-1613b8ee3774808883e1dd03932724a5?pvs=4#1613b8ee37748144b055d7d63a21e8cd):
> The “Scrum Knights” found our Timeline view to be cluttered. Let’s improve its organization by adding headers that group activities by time. Ideally we can determine an appropriate header frequency when presenting the meeting history (days, weeks, or months) dynamically.
- Go to http://localhost:3000/me
- See timeline events grouped by relative date headers
- Go to http://localhost:3000/me with a `starter` team & locked histories
- Scroll down and still see the locked history card
> feat: group timeline events by relative dates

- packages/client/components/StageTimerModalEndTimeSlackToggle.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsPanel.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MattermostPanel.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/NotificationSettings.tsx
- packages/client/mutations/SetNotificationSettingMutation.ts
- packages/client/subscriptions/TeamSubscription.ts
- packages/server/graphql/public/typeDefs/SetNotificationSettingSuccess.graphql
Partially Fixes #10647
Add UI to modify the notification settings for MS Teams and Mattermost
- Step 1
- Step 2...
- Step 1
- Step 2....
> feat: notification settings UI

- packages/client/components/Tab/Tab.tsx
- packages/client/tailwindTheme.ts
Fixes #10714 
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Tab button style

- .env.example
- packages/server/graphql/mutations/helpers/notifications/MattermostNotifier.ts
- packages/server/graphql/mutations/helpers/notifications/Notifier.ts
Catch if a notification service throws and continue with the rest. Also fail on startup if the global Mattermost integration is wrongly configured.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore(Mattermost): Catch notification errors

- packages/mattermost-plugin/Atmosphere.ts
- packages/mattermost-plugin/AtmosphereProvider.tsx
- packages/mattermost-plugin/components/AutoLogin.tsx
- packages/mattermost-plugin/components/ModalRoot.tsx
- packages/mattermost-plugin/components/Sidepanel/index.tsx
- packages/mattermost-plugin/index.tsx
- packages/mattermost-plugin/reducers.ts
- packages/mattermost-plugin/selectors.ts
There was a race condition with the login method. If the user was already logged in when the modals were rendered, it worked. Otherwise it would not rerender correctly. Moving the authToken into the redux store fixes the rerender issue.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix(Mattermost Plugin): Load modals correctly

- packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
- packages/client/hooks/useBlockResizer.tsx
- packages/client/hooks/useTipTapReflectionEditor.ts
- packages/client/tiptap/extensions/imageBlock/ImageBlock.ts
- packages/client/tiptap/extensions/imageBlock/ImageBlockView.tsx
Surprisingly, writing directly to the HTMLAttributes is fast enough so we don't need to maintain a local state while allowing per-pixel resizing.
this also sets the img.width and img.height properties so before the image loads, it takes up space
> fix: images keep size before loading

- .env.example
- packages/server/server.ts
Allows setting a custom reconnect window for the web server, so it can gracefully stop in environments where 60s grace period isn't allowed.
> chore(web-server): reconnect window can be manually set but keeps a 60s default value

- packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
fixes a bug where if the gif menu is opened on the very far right of the screen the popover doesn't scooch over
> fix: gif menu goes off screen

- packages/server/postgres/migrations/2025-01-28T18:45:26.843Z_update-public-teams-expiry-date.ts
The public teams feature flag expires at the end of Jan. We should update the expiry date for self hosted customers.
> chore: update public teams feature flag expiry date

- packages/server/utils/atlassian/jiraIssues.ts
`jira:*` keys in redis are taking up 1.6GB. let's reduce the TTL to 1 day so we don't have to grow our redis instance.
> fix: reduce jira issue TTL from 2 days to 1 day

- .env.example
- packages/server/graphql/private/mutations/updateEmail.ts
- packages/server/utils/AtlassianServerManager.ts
- packages/server/utils/SlackServerManager.ts
- packages/server/utils/makeOAuth2Redirect.ts
- scripts/toolboxSrc/applyEnvVarsToClientAssets.ts
- scripts/webpack/dev.client.config.js
fix #10438 fix #10452 fix #10409
Makes oauth2_redirect env var optional for PPMIs.
When they create an integration, instruct them to use `https://<HOST>/auth/service` as a redirect_url
> chore: set oauth2redirect defaults, document env vars

- packages/client/utils/getSidebarItemStage.ts
Fixes #10783
While we should avoid setting an invalid facilitator stage in the first place, this fix allows navigation in already broken meetings.
See also #7675
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Allow navigation in meetings with invalid facilitator stage

- packages/client/components/DiscussionThreadInput.tsx
- packages/client/components/NullableTask/NullableTask.tsx
- packages/client/components/ParabolScopingSearchResultItem.tsx
- packages/client/components/PokerEstimateHeaderCardParabol.tsx
- packages/client/components/ReflectionCard/ReflectionCard.tsx
- packages/client/components/ReflectionGroup/RemoteReflection.tsx
- packages/client/components/ResponseReplied.tsx
- packages/client/components/RetroReflectPhase/HTMLReflection.tsx
- packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
- packages/client/components/ThreadedCommentBase.tsx
- packages/client/components/promptResponse/BubbleMenuButton.tsx
- packages/client/components/promptResponse/PromptResponseEditor.tsx
- packages/client/components/promptResponse/StandardBubbleMenu.tsx
- packages/client/components/promptResponse/TipTapEditor.tsx
- packages/client/components/promptResponse/TipTapLinkMenu.tsx
- packages/client/components/promptResponse/TiptapLinkExtension.ts
- packages/client/hooks/useTipTapCommentEditor.ts
- packages/client/hooks/useTipTapIcebreakerEditor.ts
- packages/client/hooks/useTipTapReflectionEditor.ts
- packages/client/hooks/useTipTapTaskEditor.ts
- packages/client/modules/outcomeCard/components/OutcomeCard/OutcomeCard.tsx
- packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
- packages/client/package.json
- packages/client/shared/tiptap/serverTipTapExtensions.ts
- packages/client/tiptap/extensions/imageUpload/ImageUpload.ts
- packages/client/tiptap/extensions/imageUpload/ImageUploadView.tsx
- yarn.lock
I really didn't like the leaky abstraction I originally built where linkState was created by the parent Component & passed to useEditor and then TipTapEditor. 
This fixes it by using the event emitter built into the editor. Keeps everything modular and cleeeean.
Also adds underlines to the bubble menu
> chore: Refactor tiptap events 

- packages/server/graphql/ResponseStream.ts
- packages/server/graphql/handleGraphQLTrebuchetRequest.ts
this adds extra logging to triage the TIMEOUT error.
Since none of the datadog logs had tags, I'm assuming all those TIMEOUTs came from subscriptions, which means the UX wasn't impacted since the client will refresh those when it connects to a new webserver. These new logs should support that assumption.
> chore: add extra logging to gql executor timeouts

- packages/client/styles/theme/global.css
This PR updated global styles to fix the icebreaker styles but that has caused a bug where the reflection editor has too much padding. 
This PR reverts that change: https://github.com/ParabolInc/parabol/pull/10723/files
An alternative to updating global styles could be: `className='text-2xl [&_.ProseMirror_p]:leading-normal'` but I'll save that for a separate PR.
> fix: revert global styles change

- packages/gql-executor/gqlExecutor.ts
- packages/server/utils/Logger.ts
- packages/server/utils/publishInternalGQL.ts
- packages/server/utils/sendToSentry.ts
When GQL executor receives a SIGTERM, it has 40 seconds to finish up the jobs it's doing and then shuts down (or earlier, when possible).
Also sends tags we were sending to datadog, too.
> chore: flush pending GQL executor jobs before graceful shutdown

- packages/server/postgres/migrations/2025-01-08T15:10:42.442Z_addRetroTemplateLikeWishWonder.ts
> fix: use canonical image storage path helper func

- packages/client/modules/meeting/components/MeetingCheckInPrompt/NewCheckInQuestion.tsx
Fix https://github.com/ParabolInc/parabol/issues/10683
Ideally, we'd update global styles, but in a previous PR, this caused issues elsewhere. For now, I'd like to make this quick change as the Icebreaker looks bad and everyone sees it as soon as they start a meeting.
> fix: update icebreaker styles

- packages/mattermost-plugin/index.tsx
- packages/mattermost-plugin/reducers.ts
This way the client does not need to expose additional files and if the client is refreshed, it can push the updated command help list.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore(Mattermost Plugin): Push command list from the client

- packages/client/package.json
When the server disconnects (e.g. during a new version release) the client would reconnect to the new server. Then, SOMETIMES it would disconnect and reconnect to a new server again. I believe this was initiated client-side due to a keepAlive that was not cancelled when the first connection was closed. Should be fixed now.
> fix: bump trebuchet-client

- packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
- packages/server/graphql/public/typeDefs/Team.graphql
- packages/server/graphql/public/types/Team.ts
Closes #10845 
- Go to `http://localhost:3000/me/organizations/E3wNXGxEZy/teams`
- See teams are sorted by `Last Met At` date by default, descending
- Go to `http://localhost:3000/me/organizations/E3wNXGxEZy/teams`
- Click `Member Count` or `Last Met At` to sort the teams by the column
> feat(orgAdmin): add sortable `memberCount` and `lastMetAt` columns in OrgTeams view

- packages/client/package.json
- packages/server/graphql/subscribeGraphQL.ts
- packages/server/socketHandlers/handleClose.ts
- yarn.lock
This fixes 2 issues:
- when the server redeploys or crashes, or the client disconnects, the server no longer sends a "complete" message for each subscription. That way the client holds onto the subscription operation so when it reconnects it resubscribes
- bumps trebuchet-client to kill the keepAlive inside the CloseEvent so it doesn't fire after a new connection has already been established.
> fix: client resub on server redeploy

- packages/gql-executor/RedisStream.ts
- packages/gql-executor/gqlExecutor.ts
- packages/server/graphql/private/mutations/disconnectSocket.ts
- packages/server/package.json
- packages/server/socketHandlers/handleDisconnect.ts
- packages/server/utils/serverHealthChecker.ts
- yarn.lock
Still trying to hunt down all the logs when we deploy...
Current working theory is that when we SIGTERM the executor that we shut down the consumer, but we still left xreadgroup open. Per redis docs:
> Note, however, that any pending messages that the consumer had will become unclaimable after it was deleted. It is strongly recommended, therefore, that any pending messages are claimed or acknowledged prior to deleting the consumer from the group.
To test, I'm now killing the xreadgroup connection & logging any pending messages-- there should be 0!
Next theory is that the GQL Executors are not available when they say they are, so I increased shutdown length to a minimum of 10 seconds so new ones have to wait 8 more seconds.
FInally, the seemingly separate issue of disconnectSocket getting …
> fix: end xreadgroup gracefully on shutdown

- packages/server/listenHandler.ts
- packages/server/server.ts
- packages/server/utils/serverHealthChecker.ts
After combing the logs, it's clear to see the serverHealthChecker was calling disconnect on users who were not disconnected, and then when they DID disconnect, we saw the errors in the logs. This should fix that (although it may take 2 deploys since some of those connections are already unjustly disconnected when this goes live)
> fix: joinPool early and wait for old servers to shut down

- packages/server/socketHandlers/handleDisconnect.ts
- packages/server/utils/serverHealthChecker.ts
Looks like we fixed it. I still saw 2 instances where the server health checker removed invalid sockets. Leaving logs in there in case that happens again.
> fix: remove handleDisconnect logs

- packages/client/components/RetroGroupPhase.tsx
- packages/server/graphql/mutations/helpers/addDiscussionTopics.ts
- packages/server/graphql/mutations/helpers/removeEmptyReflections.ts
- packages/server/graphql/public/mutations/autogroup.ts
Fix https://github.com/ParabolInc/parabol/issues/10799
Demo: https://www.loom.com/share/ed780b147c314f5ea88bcf632441ed7c
> fix: empty discussion stages

- packages/client/components/promptResponse/StandardBubbleMenu.tsx
- packages/client/components/promptResponse/TipTapLinkMenu.tsx
- packages/client/components/promptResponse/TiptapLinkExtension.ts
- packages/mattermost-plugin/components/PushReflection/PushReflectionModal.tsx
- packages/mattermost-plugin/components/TipTap/Editor.tsx
- packages/mattermost-plugin/components/TipTap/LinkEditor.tsx
- packages/mattermost-plugin/components/TipTap/LinkMenu.tsx
- packages/mattermost-plugin/components/TipTap/LinkPreview.tsx
- packages/mattermost-plugin/hooks/useTipTapTaskEditor.tsx
- packages/mattermost-plugin/index.css
Fixes #10797 
Mattermost uses react-bootstrap for modals. To play nicely with their components, that's what we're using as well in the plugin. The bubble menu used for formatting works nicely once the z-index is set accordingly.
The radix-ui/react-popover used by the link menu does not work because we portal it to the document.body. The modal does not detect that the popover is a child and thus steal its focus. Not portaling it would solve it (after fixing the offset) but using a portal might be necessary in the app at some point, so this might be broken by unrelated code changes.
I would have liked to use a mechanism similar to the BubbleMenu. This would work in theory, but BubbleMenu does not follow the React update cycle. It only re-evaluates `shouldShow` on document changes. This …
> feat(Mattermost Plugin): TipTap link menu

- packages/client/modules/teamDashboard/components/ProviderRow/AzureDevOpsProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/GcalProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/GitHubProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/GitLabProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MSTeamsProviderRow.tsx
- packages/client/modules/teamDashboard/components/ProviderRow/MattermostProviderRow.tsx
Handling for showing the error message was missing.
Add an early return to https://github.com/ParabolInc/parabol/blob/e1d0c7248bce22e39800c91af9e1eab061155ff5/packages/server/graphql/public/mutations/addTeamMemberIntegrationAuth.ts#L39
```ts
return standardError(new Error('GEORG was here'), {userId: viewerId})
```
and try integrating.
> fix: Show error message when failing to integrate with Azure DevOps

- packages/server/postgres/migrations/2025-02-18T17:07:41.668Z_increaseTeamMemberIntegrationAuthAccessTokenSize.ts
Azure DevOps was running into our size limit.
I only found some [answer](https://learn.microsoft.com/en-us/answers/questions/1657854/oauth-2-0-refresh-token-and-access-token-max-lengt) that there is no max size because it's a JWT and depends on the claims. I'm only increasing the token size because there is no reason the refresh token should grow in the same manner.
Fixes #10891 
[Please list all the testing scenarios a reviewer has to check before approving the …
> fix: Increase integration OAuth2 access token size

- packages/client/components/Recurrence/RecurrenceSettings.tsx
- packages/client/components/Recurrence/RecurrenceTimePicker.tsx
Fix https://github.com/ParabolInc/parabol/issues/10854
Loom demo: https://www.loom.com/share/ef36d41cac7447b684ae0dba724f2582
> fix: schedule time inaccuracy

- packages/client/components/DiscussionThreadInput.tsx
- packages/client/hooks/useTipTapCommentEditor.ts
Fix https://github.com/ParabolInc/parabol/issues/10223
Demo: https://www.loom.com/share/971e6d96cdd947eb9629fdc7c9672914
This fixes three issues:
1. When replying to yourself, initially, it doesn't prefix the reply with the user's name. Only when replying to a reply does it do this.
2. When replying to yourself, it shouldn't add your name as the prefix.
3. When Bob replies to Susan, prefix Bob's comment with `@Susan` and ensure the cursor starts after `@Susan`. Currently, it's before.
> fix: issues when replying to comments

- packages/mattermost-plugin/components/CreateTaskModal/CreateTaskModal.tsx
- packages/mattermost-plugin/components/InviteToMeetingModal/InviteToMeetingModal.tsx
- packages/mattermost-plugin/components/InviteToTeamModal/InviteToTeamModal.tsx
- packages/mattermost-plugin/components/NoLinkedTeamsModal.tsx
- packages/mattermost-plugin/components/Sidepanel/ActiveMeetings.tsx
- packages/mattermost-plugin/components/Sidepanel/LinkedTeams.tsx
- packages/mattermost-plugin/components/Sidepanel/MeetingRow.tsx
- packages/mattermost-plugin/components/Sidepanel/SidePanel.tsx
- packages/mattermost-plugin/components/Sidepanel/TeamRow.tsx
- packages/mattermost-plugin/components/Sidepanel/index.tsx
- packages/mattermost-plugin/components/StartActivityModal/StartActivityModal.tsx
- packages/mattermost-plugin/hooks/useStartMeeting.tsx
- packages/mattermost-plugin/resolvers.ts
Fixes #10914
Partially fixes #10915 
* if there are no linked teams, show a message in the sidepanel
* show only linked teams in start activity dialog
* correctly show only linked teams in sidepanel
* update active meetings when starting a meeting
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Minor Mattermost Plugin fixes

- packages/server/graphql/private/mutations/loginMattermost.ts
- packages/server/graphql/private/typeDefs/Mutation.graphql
- packages/server/integrations/mattermost/mattermostWebhookHandler.ts
- packages/server/postgres/queries/src/upsertIntegrationProviderQuery.sql
- packages/server/postgres/queries/upsertIntegrationProvider.ts
- scripts/toolboxSrc/primeIntegrations.ts
Add a Mattermost shared secret global provider and use it to verify the login request as well. The logic to verify the request was moved into a private mutation. It now also verifies the content-digest which was missed previously.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: Add loginMattermost private mutation

- packages/server/graphql/public/types/MeetingTemplate.ts
[Previously](https://github.com/ParabolInc/parabol/pull/10902) we enable billing leaders and org admins to delete their templates. However on front end they are not able to see that. This PR addresses that issue.
- User A should be billing leader or org admin for Org 1
- User B is in Org 1
- User B has their own team B, in Org 1 but User A is not on the team
- User B create a template for team B
- User A should be able to edit/delete the template from team B
> feat(templates): allow org admins to access team templates

- codegen.json
- packages/client/mutations/RemoveOrgUsersMutation.ts
- packages/client/subscriptions/NotificationSubscription.ts
- packages/client/subscriptions/OrganizationSubscription.ts
- packages/client/subscriptions/TaskSubscription.ts
- packages/client/subscriptions/TeamSubscription.ts
- packages/server/graphql/public/mutations/removeOrgUsers.ts
- packages/server/graphql/public/typeDefs/Mutation.graphql
- packages/server/graphql/public/typeDefs/NotificationSubscriptionPayload.graphql
- packages/server/graphql/public/typeDefs/OrganizationSubscriptionPayload.graphql
- packages/server/graphql/public/typeDefs/RemoveMultipleOrgUsersPayload.graphql
- packages/server/graphql/public/typeDefs/RemoveOrgUsersPayload.graphql
- packages/server/graphql/public/typeDefs/RemoveOrgUsersSuccess.graphql
- packages/server/graphql/public/typeDefs/TaskSubscriptionPayload.graphql
- packages/server/graphql/public/typeDefs/TeamSubscriptionPayload.graphql
- packages/server/graphql/public/types/RemoveOrgUsersSuccess.ts
Rename the mutation `removeMultipleOrgUsers` to `removeOrgUsers`. Next step is to deprecate `removeOrgUser`.
> chore: rename removeMultipleOrgUsers to removeOrgUsers

- packages/client/modules/teamDashboard/components/TeamSettings/TeamSettings.tsx
Copy says that only team leads can upgrade, but anyone can upgrade an org to the Team tier.
> chore: update copy that says only team leads can upgrade

- packages/client/modules/teamDashboard/components/TeamDashHeader/TeamDashHeader.tsx
Integrations have been moved out of the team settings section. This updates the tooltip to reflect that.
> chore: change settings tooltip copy

- packages/server/graphql/private/mutations/loginSAML.ts
If the customer has email multiple times in their message, we could get an array with multiple of the same email. To work around this, create a set of array attributes.
If they claim multiple emails, then we should still fail, as we don't know which one to choose.
- Step 1
- …
> fix: Handle duplicate SAML attributes

- .github/workflows/test.yml
- .husky/post-checkout
Down migrations should be valid code at least.
I think if we want to explicitly throw in the down migration to prevent accidental runs of it, then we can still bypass the test, but syntax errors like https://github.com/ParabolInc/parabol/pull/11013 should be caught.
- Step 1
- …
> chore: check down migrations are valid

- packages/client/components/DashNavList/DashNavListTeams.tsx
- packages/client/modules/userDashboard/components/OrgBilling/OrgFeatureFlags.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeams.tsx
- packages/client/mutations/fragments/PublicTeamsFrag.ts
- packages/server/graphql/public/types/Organization.ts
- packages/server/postgres/migrations/2025-03-12T15:20:56.255Z_remove-publicTeams.ts
Fix https://github.com/ParabolInc/parabol/issues/10927
> chore: remove public teams feature flag

- packages/client/modules/userDashboard/components/OrgBilling/BillingLeader.tsx
- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
- packages/client/modules/userDashboard/components/OrgUserRow/OrgMemberRow.tsx
- packages/client/modules/userDashboard/components/RemoveFromOrgModal/RemoveFromOrgModal.tsx
- packages/client/mutations/RemoveOrgUsersMutation.ts
- packages/client/utils/constants.ts
1. This is a limited feature for org admins only
2. To simplify the first iteration, other billing leaders or org admins are not selectable.
3. They can not select more than 100 org users
> feat(orgAdmin): UI for mass org user removal

- packages/server/pipeStreamOverResponse.ts
- packages/server/selfHostedHandler.ts
I got a lot of warnings locally about writing without proper corking. It is safe to cork/uncork synchronously.
The gist of it is: [always cork](https://github.com/uNetworking/uWebSockets/blob/master/misc/READMORE.md#corking)
See also #9261 for how we handle corking in the other routes.
- with files served locally (`FILE_STORE_PROVIDER='local'
`) run `yarn dev` and open the activity library
- see no warnings
> chore: Cork serving static files

- packages/client/components/DashNavList/DashNavListTeams.tsx
See conversation in Slack [here](https://parabol.slack.com/archives/C836NA350/p1742833245017449) 🔒 
If a user doesn't belong to any teams within an org, they should still be able to view the public teams
> fix: can see public teams when there are no viewer teams

- packages/server/utils/OpenAIServerManager.ts
> fix: correct meeting link URL in the prompt for generating meeting summaries

- packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
Was peeping font weight 500, saw and yanked the extra `$` character in the help text.
> fix: typo on public team setting help text

- packages/client/components/DashNavList/PublicTeamsModal.tsx
overflow-scroll will always reserve the space for horizontal and vertical scrollbars, looking quite odd.
While at it, I also changed the scrollbar to only scroll the content, not the Dialog header with the close button.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Public Teams Modal Layout on Safari

- packages/server/graphql/private/mutations/assignSAMLIdToOrg.ts
- packages/server/graphql/private/mutations/loginSAML.ts
- packages/server/graphql/private/mutations/updateSAML.ts
- packages/server/graphql/private/typeDefs/AssignSAMLIdToOrgPayload.graphql
- packages/server/graphql/private/typeDefs/AssignSAMLIdToOrgSuccess.graphql
- packages/server/graphql/private/typeDefs/Mutation.graphql
- packages/server/graphql/private/typeDefs/UpdateSAMLPayload.graphql
- packages/server/graphql/private/typeDefs/UpdateSAMLSuccess.graphql
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/typeDefs/SAML.graphql
- packages/server/postgres/migrations/2025-03-25T13:33:26.204Z_addSAMLOrganizationAttributes.ts
Fixes #10921 
This is a special use case where multiple organizations share an IdP and users are provisioned to different orgs based on a SAML claim.Please include a summary of the changes and the related issue]
- configure SAML
- configure the SAML app to add additional attributes to the login response. I found it easiest to map groups to a user defined attribute
- run the following mutations
```graphql
mutation AssignSAMLAttribute {
updateSAML(slug: "parabol", …
```
> feat: User provisioning to different Organization via SAML claim

- packages/client/components/AddTeamDialog.tsx
- packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
- packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
Fix https://github.com/ParabolInc/parabol/issues/11073
See figma feedback [here](https://www.figma.com/board/0M06dFpkcXjKq3aYeQIYbp/Team-Privacy?node-id=1-298&t=ykeYKDhCnYTh5KkY-0).
> feat: team privacy UI updates

- packages/client/modules/userDashboard/components/OrgMembers/OrgMembers.tsx
Small UI changes:
1. After searching, display matched user count instead of always showing the total user count
2. Hide the select all checkbox if there are no matched users
> feat: update OrgMembers component to display matched users in search results

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/SummaryPokerStories.tsx
Fix: https://github.com/ParabolInc/parabol/issues/11080
In prod, if you import GitLab or Azure issues into a Poker meeting, they don't show up in the summary. There's a generic message instead.
Now they do show up:
> fix: gitlab & azure summaries show up

- .github/workflows/ironbank.yml
Removes uploading to S3 for the Iron Bank GH action since we are deprecating.
N/A
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: remove S3 from Iron Bank action

- packages/embedder/WorkflowOrchestrator.ts
- packages/embedder/custom.d.ts
- packages/embedder/workflows/helpers/publishSimilarRetroTopics.ts
- packages/server/hocusPocus.ts
- packages/server/utils/publish.ts
- packages/server/utils/useDatadogTracing.ts
fix #11117 
fix #11115 
fix #11114 
fix #11112
SIGTERM handler was exiting almost immediately because the hocusPocus server, which runs on the same process, was called `process.exit(0)` on SIGTERM when it was finished, which meant that the webserver was exiting before it was able to handle its graceful shutdown.
> fix: bugs found under production load with graphql-yoga

- packages/server/dataloader/RootDataLoader.ts
- packages/server/graphql/private/mutations/disconnectSocket.ts
- packages/server/utils/useDatadogTracing.ts
Turned these off since the server was under heavy load.
Now that we've got a handle on things we can try turning them on again & seeing what happens
> fix: turn on dd resolvers

- packages/server/utils/useDatadogTracing.ts
bugfix for datadog tracing resolvers
> fix: escape hatch for missing datadog context

- packages/server/graphql/public/mutations/toggleAIFeatures.ts
See conversation in [Slack](https://parabol.slack.com/archives/C4JAUUZ9P/p1744203235051599) for more context 🔒 
Currently, the toggle mutation isn't working for Parabol employees because only org admins can use it. This PR enables it for super users too
> fix: super user can toggle ai features

- packages/client/modules/newTeam/components/NewTeamForm/NewTeamForm.tsx
- packages/client/modules/teamDashboard/components/TeamSettings/TeamPrivacyToggle.tsx
- packages/client/shared/UpgradeCTALocationEnumType.d.ts
This PR helps us track when users click to upgrade after discovering Private teams is a premium feature.
> chore: track upgrade clicks from public teams

- packages/server/dataloader/getRedisDataLoader.ts
- packages/server/dataloader/hydrateDataLoader.ts
- packages/server/dataloader/serializeDataLoader.ts
- packages/server/package.json
- packages/server/utils/publish.ts
- yarn.lock
Realized that we probably started seeing these errors because I'm serializing/parsing using JSON, which doesn't support Date types. 
To preserve Date, bigint, etc we can use msgpack, which is usually faster than JSON & definitely a lot smaller, which means less memory used by redis. win/win/win
> fix: serialize using msgpack to preserve Dates for dataloaders

- packages/server/yoga.ts
fixes a vuln where `@whatwg-node/fetch` did not catch errors from busboy, which meant the error would propagate to the top level and crash the server.
Using native undici the error is still reported, but now it gets caught.
> fix: multipart header vuln

- packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
- packages/client/tiptap/extensions/insightsBlock/InsightsBlockResult.tsx
- packages/client/tiptap/extensions/insightsBlock/InsightsBlockView.tsx
lesson learned, never turn contentEditable back on! only turn it off for forms
> fix: listitem updates inside insights

- packages/server/wsHandler.ts
fixes a memory leak where after disposing, we still hung on to the dispose function, which held on to the dataloader, so it didn't really do much disposing.
also calling dipose in `onError` for future proofing because if the query fails validation then onComplete never gets called
> fix: remove referece to dispose fn

- packages/client/tiptap/extensions/insightsBlock/InsightsBlockEditing.tsx
- packages/client/tiptap/extensions/insightsBlock/InsightsBlockPrompt.tsx
fix #11040 
puts initial errors in a snackbar
sets initial prompt on load
> fix: pageInsights set initial prompt on load

- packages/server/billing/helpers/removeTeamsLimitObjects.ts
- packages/server/database/types/processTeamsLimitsJob.ts
- packages/server/graphql/mutations/helpers/generateAIGroupTitle.ts
- packages/server/graphql/mutations/helpers/generateGroups.ts
- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
- packages/server/graphql/mutations/helpers/safeEndTeamPrompt.ts
- packages/server/utils/publish.ts
If publish gets called after the mutation is finished, the dataloader might already be disposed. This can happen either by not sharing it early enough or the operation taking longer than the shared dataloader ttl of 30s.
* Add a `await sleep(40000)` in `generateGroups`: https://github.com/ParabolInc/parabol/blob/057a60cb86d5b874b65189a9834a6f6e2ce1c82d/packages/server/graphql/mutations/helpers/generateGroups.ts#L19
* add reflections and finish the reflect phase …
> fix: Handle publish taking longer than 30s

- packages/server/package.json
- packages/server/yoga.ts
- yarn.lock
Fixes #11243 
We switched previously because of the multipart header vulnerability, but this was fixed in an updated version. So let's switch back because undici fetch caused different issues. Just make sure it's the updated one.
Revert "fix: multipart header vuln (#11181)"
This reverts commit 43ada486b5afebaf39a910253f3dbac7526398a6.
Try crashing the app with sth. like
```
curl 'http://localhost:3000/graphql' \
-H 'accept: application/json' \
-H 'authorization: …
```
> fix: revert back to @whatwg-node/fetch

- packages/server/disconnectAllSockets.ts
- packages/server/server.ts
Last changes in the PR [dump sockets before dumping heap](https://github.com/ParabolInc/parabol/pull/11213/files#diff-9e1fec50a8f6703395e589001a25d389729e6ef1e8a99fed70688afbd9bc2d38L51) removed the use of the app var `RECONNECT_WINDOW` that is used in our non-production environments. This PR adds that option back to the current code.
> fix: disconnectAllSockets accepts an input parameters for the disconnect window

- packages/embedder/ai_models/helpers/fetchWithRetry.ts
- packages/server/fileStorage/GCSManager.ts
- packages/server/graphql/nestedSchema/nestGitLabEndpoint.ts
- packages/server/graphql/public/mutations/embedUserAsset.ts
- packages/server/graphql/public/types/User.ts
- packages/server/hubSpot/backfillHubSpot.ts
- packages/server/hubSpot/hubSpotApi.ts
- packages/server/integrations/helpers/authorizeOAuth2.ts
- packages/server/integrations/jiraServer/JiraServerOAuth1Manager.ts
- packages/server/integrations/jiraServer/JiraServerRestManager.ts
- packages/server/jiraImagesHandler.ts
- packages/server/utils/AtlassianServerManager.ts
- packages/server/utils/AzureDevOpsServerManager.ts
- packages/server/utils/GoogleServerManager.ts
- packages/server/utils/MSTeamsServerManager.ts
- packages/server/utils/MattermostServerManager.ts
- packages/server/utils/MicrosoftServerManager.ts
- packages/server/utils/SlackServerManager.ts
- packages/server/utils/TenorManager.ts
- packages/server/utils/fetchGQL.ts
- packages/server/utils/getSSOMetadataFromURL.ts
Relates to @11243
We don't know if this fixes anything, but we're using @whatwg/fetch in yoga, so there is no reason to use a different fetch in other parts of the server.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: Switch to @whatwg/fetch throughout the server

- packages/server/graphql/private/mutations/helpers/checkSequential.ts
- packages/server/graphql/private/mutations/processRecurrence.ts
Fixes #11261 
Wrap the resolver in a lock function which returns an error if it's already running somewhere.
```
3:21:00 2|Socket Server                  | {"time":"2025-04-30T11:21:00.014Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 4|Socket Server                  | {"time":"2025-04-30T11:21:00.016Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 1|Socket Server                  | {"time":"2025-04-30T11:21:00.017Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"}
13:21:00 1|Socket Server                  | Attempting to acquire lock for processRecurrence
13:21:00 8|Socket Server                  | {"time":"2025-04-30T11:21:00.021Z","level":"info","message":"🌱 Chronos Job processRecurrence: TICK []"} …
```
> fix: ensure process recurrence runs sequentially

- packages/client/Atmosphere.ts
- packages/client/utils/createWSClient.ts
fix #11250
this should improve the websocket connectivity problems. if we do have a case where folks can't connect, it now includes the error event
> fix: improve error handling for websocket connections in safari 

- packages/server/utils/useDatadogTracing.ts
removes resolve-level tracing so we can turn DD trace back on without worrying about introducing another possible culprit
> fix: remove resolver-level tracing for DD debugging

- packages/server/graphql/private/mutations/dumpHeap.ts
now we can do a heapdump by sending a SIGUSR2 to the container
e.g. `kill -SIGUSR2 1337`
> feat: dump on sigusr2

- packages/client/modules/outcomeCard/containers/OutcomeCard/OutcomeCardContainer.tsx
Fix https://github.com/ParabolInc/parabol/issues/11161
In prod, what is happening is:
- A user creates a task card which has no content to start with
- The user types into the task card, but it is not saved until they click out of the task card
- If they click on the buttons to add an integration like GitHub, the content isn't saved because they haven't clicked out of the task card
- There's an error that says the "title can't be blank" 
With this update, the content is saved onBlur, even if the user clicks the integration dropdown or the Due Date button. It does not execute the `UpdateTaskMutation` on every keystroke.
> fix: can push task card to integration

- package.json
- packages/mattermost-plugin/Atmosphere.ts
- packages/server/utils/getReqAuth.ts
While the plugin would work with the bearer token in the authorization header, Mattermost interprets it as its own and spams its logs with warnings.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix(Mattermost): use x-application-authorization header

- package.json
I couldn't run `yarn dev` locally after running `yarn && yarn db:start` for multiple reasons:
- `dev` folder was created by Docker and owned by root. Then, yarn dev couldn't access to it.
- `yarn dev` wouldn't work until I ran `yarn pg:build && yarn relay:build`
This PR fixes the first
> fix: db:start command created the dev folder with the current user

- packages/server/chronos.ts
Fixes #11292
The lock wasn't held while the tick was executed.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: await tick in chronos to not run it in parallel

- packages/mattermost-plugin/Atmosphere.ts
- packages/mattermost-plugin/components/Sidepanel/index.tsx
- packages/mattermost-plugin/index.tsx
Fixes #11227 
When a user tries to execute a slash command, we now showing a more helpful error message if they're not logged in. The sidepanel links in this case now also open in a new window.
https://www.loom.com/share/2cc5dca5c67b43b8b29dfadad13fd9c8?sid=307fe9f5-e72b-40b1-9079-8cced13030d4
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore(Mattermost Plugin): improve not logged in experience

- packages/client/modules/email/components/SummaryEmail/MeetingSummaryEmail/ExportAllTasks.tsx
- packages/client/types/constEnums.ts
Fixes a typo our friends at GitLab caught where we mislabelled "GitLab" as "GitHub" in the meeting summary.
> fix: gitlab name in summary

- packages/server/dataloader/integrationAuthLoaders.ts
- packages/server/graphql/public/types/MSTeamsIntegration.ts
- packages/server/graphql/public/types/User.ts
Fixes https://github.com/ParabolInc/parabol/issues/11258
The issue in #11258 occurs in the `loadActiveProvider` function in `MSTeamsIntegration.ts`, it contains an incorrect service name in the query. The same error also exists in the `isActive` method. Updates the service name from `mattermost` to `msTeams`. 
I'm not sure how to reproduce the bug to test. @Dschoordsch kindly suggested I open a PR anyway and he'll look into testing it. 
Owner: @Dschoordsch 
- Step 1
- Step 2...
- Step 1
- Step 2....
(for visibility) It looks like the precommit hook is failing in `package/server`:
To reproduce run:
```sh
cd package/server
pnpm run typecheck
pnpm run precommit
> parabol-server@10.3.3 precommit /Users/arthur/Documents/arthurgousset/parabol/packages/server
> lint-staged
✔ Preparing...
⚠ …
```
> fix(MSTeamsIntegration.ts): Updates incorrect service name from `mattermost` to `msTeams`

- packages/server/logging.ts
- packages/server/server.ts
- packages/server/utils/useDatadogTracing.ts
- scripts/webpack/prod.servers.config.js
We know there is a circular reference somewhere in the resolver logic flow, but it isn't manifesting itself in dev or staging.
Here are my two best guesses on the culprit. It's most likely the one where the wrapping function is getting rewrapped, so I put a symbol on the function itself to mark it as wrapped.
> fix: mark wrapped resolvers

- packages/client/components/EditableText.tsx
- packages/client/modules/teamDashboard/components/EditTeamName/EditableTeamName.tsx
- packages/client/modules/userDashboard/components/OrgTeams/OrgTeamsRow.tsx
Fixes #10595
- Go to `http://localhost:3000/me/organizations/xxxx/teams` as an org admin
- See pencil icon next to the team name
- Able to rename the team
- See the changes populated to other team views
- Go to `http://localhost:3000/me/organizations/xxxx/teams` as someone not on the team
- See no pencil icon next to the team name
- One cannot change the team name
> feat(orgAdmin): org admin can rename a team in org teams view

- packages/server/dataloader/azureDevOpsLoaders.ts
- packages/server/graphql/public/types/AzureDevOpsIntegration.ts
- packages/server/graphql/queries/helpers/connectionFromTasks.ts
- packages/server/utils/AzureDevOpsServerManager.ts
Fixes #10906 
Limit the number of work items fetched in ADO scoping phase.
Pagination is still not implemented, but seems to be absent for other integrations in scoping.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: limit the Azure DevOps work items fetched

- packages/client/components/JiraServerSVG.tsx
- packages/client/components/LinearProviderLogo.tsx
Relates to #11349 
Fix integration logo sizes. Linear and Jira Server were off.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: integration logo sizing

- packages/client/utils/tiptapEmojiConfig.ts
Fixes #11358 
: is the trigger for the emoji menu, so we omitted the : from the search for matches. This resulted in :) suggesting :disappointment: and :( suggesting :slightly_smiling_face:. Now we include the : in the search if the next character isn't alphanumerical.
- in a new task add various emojis via `:)`, `:dis`, `:(` etc.
> fix: show correct emoji suggestion for :) and :(

- packages/server/graphql/private/queries/suUserCount.ts
`tier` column is deprecate from `User`
Go to `http://localhost:3000/admin/graphql`:
```graphql
query getAllTimeCounts (
$OneWeekAgo: DateTime = "2025-05-26T00:00:00.000Z",
$ThirtyDaysAgo: DateTime = "2025-05-02T00:00:00.000Z",
$AllTimeDate: DateTime = "2016-01-01T00:00:00.000Z",
) {
starterOrgs: suOrgCount(tier: starter)
teamOrgs: suOrgCount(tier: team)
enterpriseOrgs: suOrgCount(tier: enterprise)
starterUsers: suUserCount(tier: starter)
teamUsers: suUserCount(tier: team)
enterpriseUsers: suUserCount(tier: enterprise)
signupsLastWeek: signups(after: $OneWeekAgo, isActive: false) {
total
}
signups30DaysAgo: signups(after: $ThirtyDaysAgo, isActive: false) {
total
}
signupsAllTime: signups(after: $AllTimeDate, isActive: false) {
total
}
}
```
> fix: fix suUserCount after DB schema migration

- packages/client/components/promptResponse/StandardBubbleMenu.tsx
Fix https://github.com/ParabolInc/parabol/issues/10868
Demo: https://www.loom.com/share/5a73efb06aeb4cb69bf1cc17b9b47aba
The `TipTapEditor` was updated here https://github.com/ParabolInc/parabol/pull/10800/files#diff-4f071a6ead07a33aa3809ea02b3d9de303aa1e432a9f866869953b9a915d8e77 to always include `StandardBubbleMenu`. This affects the height calculation in `useDraggableReflectionCard` which makes the reflection have the extra spacing below it as it returns to the kanban. 
Returning early in the `StandardBubbleMenu` causes a `removeChild` error, as indicated by GitHub issue linked in line 23, so using the className to hide the component seems like the cleanest solution to me.
> fix: ungrouped reflection layout issue on kanban

- packages/client/components/BottomControlBarMusic.tsx
- packages/client/hooks/useMeetingMusicSync.ts
Fix https://github.com/ParabolInc/parabol/issues/11389
> feat: background music UI improvements

- packages/client/components/MeetingControlBar.tsx
Now that we've added the background music to the meeting control bar, on mobile, the user can't see the End Meeting button.
As discussed with @ackernaut on Zoom, let's hide the Tips button on mobile so the End Meeting button is clearly visible.
This is a small, low risk change so I'll merge straight to master.
> chore: hide tips on mobile

- packages/client/components/MeetingCard.tsx
- packages/client/components/MeetingsDash.tsx
- packages/client/modules/teamDashboard/components/TeamDashActivityTab/TeamDashActivityTab.tsx
- packages/client/utils/date/relativeDate.ts
- packages/server/dataloader/foreignKeyLoaderMakers.ts
- packages/server/graphql/public/typeDefs/Team.graphql
- packages/server/graphql/public/types/Team.ts
- packages/server/graphql/types/Team.ts
- packages/server/postgres/queries/src/TierEnum.sql
Fixes #11344
Always show active meeting series, even if there is currently no active meeting. We will always show the last meeting in the series, even if it's ended. In that case another bubble with "completed" is added.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: show meeting series without active meetings in dash

- packages/server/utils/MSTeamsServerManager.ts
- scripts/webpack/dev.client.config.js
The server usually replies with 202 which is not an error code, but was logged as such. This cleans up the logs a bit.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: reduce MS Teams error logs

- packages/client/hooks/useMeetingMusicSync.ts
Fix https://github.com/ParabolInc/parabol/issues/11441
This PR ensures that the background music loops on repeat.
The event listener wasn't working properly; there's the native loop property which should be more reliable.
> chore: background music loops

- packages/client/hooks/useNewFeatureSnackbar.ts
- packages/client/mutations/DismissNewFeatureMutation.ts
Fixes #11398
Trying to dismiss the new feature after logout caused some errors which lead relay to return errors for all subsequent fetches, including SSO data.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: ignore dismiss new feature after logout

- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
- packages/server/utils/RecallAIServerManager.ts
Demo: https://www.loom.com/share/9cacc0e110b04911bcd005e5dea48128
There have been lots of updates to the Recall API since our initial implementation. This PR updates the logic so that it works with their new pay-as-you-go API.
This is a proof of concept so that we can submit a Zoom bot application. 
It will be significantly improved before releasing it to customers. For instance:
- Implement live streaming so you can see the transcription during the meeting
- Currently, if you end the Parabol meeting before ending the Zoom meeting it won't work
- Include the transcription in a meeting summary, ideally in a Parabol Page
> feat: zoom transcript proof of concept

- packages/server/graphql/mutations/helpers/createTeamAndLeader.ts
- packages/server/graphql/mutations/helpers/removeTeamMember.ts
- packages/server/graphql/public/mutations/acceptRequestToJoinDomain.ts
- packages/server/postgres/migrations/2025-06-24T13:42:32.158Z_addTMSTriggers.ts
- packages/server/postgres/migrations/2025-06-26T13:51:02.635Z_cleanupUserTMS.ts
- packages/server/safeMutations/acceptTeamInvitation.ts
- packages/server/safeMutations/safeArchiveTeam.ts
Fixes #9932 
We query User.tms quite often to check permissions, so it's useful to be denormalized. To avoid update errors, I added triggers for Team and TeamMember operations which update the array.
There is also some inconsistent data in the database, I've added a migration to clean that up as well.
Nothing should change for the user.
Joining, leaving and archiving teams
> chore: Normalize User.tms

- packages/client/components/DiscussionThreadInput.tsx
- packages/client/components/RetroReflectPhase/PhaseItemEditor.tsx
- packages/client/hooks/useIsEditing.ts
- packages/client/hooks/useTipTapCommentEditor.ts
- packages/client/hooks/useTipTapReflectionEditor.ts
- packages/client/tiptap/extensions/ClearOnSubmit.ts
Fixes #11378 
Added an extension to emit a signal when we clear the editor on submit. This way the `useIsEditing` hook and others can react to this update knowing the intent.
https://www.loom.com/share/5db7cedd76cd41ffb6f354ea76977468?sid=bc3129cd-9a61-4f77-9eaf-758ef7b7fc2a
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: clear typing notification on submit

- packages/client/components/MeetingCard.tsx
- packages/client/components/SelectMeetingDropdownItem.tsx
- packages/client/utils/getMeetingPhase.ts
Fixes #11443 
We're showing the facilitator phase if available, otherwise the last phase with partially completed stages if it exists, otherwise the first non-started stage.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: show correct meeting phase in dashboard

- packages/server/postgres/migrations/2025-07-07T15:47:38.108Z_dropStripeQuantityMismatchOrgUsersNotNull.ts
Fixes #11528 
We do not store the affected org users, let's not fill the column with empty values then.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: drop stripe quantity mismatch logging not null constraint

- .github/dependabot.yml
Forces Dependabot to ignore devDependencies in all packages in the repository
> chore(dependabot): ignore devDependencies

- packages/server/graphql/mutations/helpers/dumpTranscriptToPage.ts
- packages/server/graphql/mutations/helpers/safeEndRetrospective.ts
This PR adds the meeting transcription into a Parabol Page.
> feat: add transcript to Page

- packages/server/package.json
- pnpm-lock.yaml
- scripts/webpack/prod.servers.config.js
sharp version got bumped, which broke the build, so rather than rollback I'm just bumping it in webpack, too.
> chore: bump sharp version in webpack

- pnpm-workspace.yaml
oxide is the rust compiler for tailwindcss. should make builds a little faster & smaller
> fix: approve oxide for tailwindcss builds

- packages/client/components/promptResponse/BubbleMenuButton.tsx
- packages/client/components/promptResponse/StandardBubbleMenu.tsx
- packages/client/tiptap/extensions/imageUpload/ImageSelector.tsx
- packages/client/tiptap/extensions/imageUpload/ImageSelectorSearchTab.tsx
- packages/mattermost-plugin/components/TipTap/Editor.tsx
- packages/mattermost-plugin/types/modules.d.ts
- packages/mattermost-plugin/webpack.config.js
The plugin does not set the object. The easiest way to make client components work anyways is by setting the object to optional. This is done in the mattermost plugin, so only client components which are actually used by mattermost are affected. So far this is only the image selector.
Also fixed the formatting bubble menu to be somewhat presentable.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: window.__ACTION__ is not defined for MattermostPlugin

- package.json
- packages/client/utils/AtlassianManager.ts
- packages/server/fileStorage/GCSManager.ts
- pnpm-lock.yaml
fix #11692
https://app.datadoghq.com/error-tracking?query=&fromUser=true&order=total_count&refresh_mode=sliding&source=all&sp=%5B%7B%22p%22%3A%7B%22issueId%22%3A%2252b61d50-276b-11f0-be4c-da7ad0900002%22%7D%2C%22i%22%3A%22error-tracking-issue%22%7D%5D&from_ts=1753728382763&to_ts=1754333182763&live=true
1660 errors in the last 7 days, let's try this & see if it goes down. if it does, we can apply the fix to all our fetch functions
> fix: always consume stream before abort handler throws

- packages/client/mutations/useUpdatePageAccessMutation.ts
- packages/server/__tests__/createPage.test.ts
- packages/server/graphql/mutations/helpers/summaryPage/getPokerTable.ts
- packages/server/graphql/public/typeDefs/Organization.graphql
- packages/server/graphql/public/typeDefs/OrganizationPartial.graphql
- packages/server/graphql/public/typeDefs/OrganizationPreview.graphql
- packages/server/graphql/public/typeDefs/PageAccessOrganization.graphql
- packages/server/graphql/public/typeDefs/PageAccessTeam.graphql
- packages/server/graphql/public/typeDefs/PageAccessUser.graphql
- packages/server/graphql/public/typeDefs/Team.graphql
- packages/server/graphql/public/typeDefs/TeamPartial.graphql
- packages/server/graphql/public/typeDefs/TeamPreview.graphql
- packages/server/graphql/public/typeDefs/User.graphql
- packages/server/graphql/public/typeDefs/UserPartial.graphql
- packages/server/graphql/public/typeDefs/UserPreview.graphql
- packages/server/graphql/public/types/ActionMeeting.ts
- packages/server/graphql/public/types/PageAccessOrganization.ts
- packages/server/graphql/public/types/PageAccessTeam.ts
- packages/server/graphql/public/types/PageAccessUser.ts
- packages/server/graphql/public/types/PokerMeeting.ts
- packages/server/graphql/public/types/RetrospectiveMeeting.ts
just because you have access to a page does not mean you should be able to view fields on any team or org that has access to that page
fixes #11329
> fix: hide access to teams and orgs

- packages/client/modules/pages/PageBreadCrumbs.tsx
- packages/client/mutations/useUpdatePageMutation.ts
- packages/server/graphql/public/typeDefs/PagePartial.graphql
- packages/server/graphql/public/typeDefs/PagePreview.graphql
- packages/server/graphql/public/types/Page.ts
- packages/server/graphql/public/types/PagePartial.ts
fix #11612
adds the team name to the front of the breadcrumbs for pages (if the page is under a team).
Also fixes a bug where dragging pages around didn't update the breadcrumbs
> fix: prefix breadcrumbs with team name

- packages/client/components/DeleteTeamDialog.tsx
Fixes #10256
This is a simple change that converts any smart quotes within the team name input into regular quotes before comparing it with the actual team name. This has been known to prevent users from deleting a team, because the condition for the button enablement is tied to the team name comparison. This fix should allow users to input smart quotes and still get an accurate comparison of the team name vs input.
Loom coming in a bit!
- Step 1: Create a team instance within the current org (organization -> settings & members -> teams -> add team)
- Step 2: Click the button to delete the newly created team
- Step 3: Type in the team name in order to enable the delete button
- Step 4: Replace the normal quote with the smart quote (copy from here: `’`)
- Step 5: The button should be …
> fix: normalize smart quote to regular quote before comparison

- packages/server/hocusPocus.ts
fixes #11798 (at least the title renaming part)
i probably hit undo before committing this originally :-(.
basically when the title gets changed, we now push that via GQL
> fix: update top-level title updates

- packages/server/graphql/mutations/removePokerTemplateDimension.ts
- packages/server/graphql/types/RemovePokerTemplateDimensionPayload.ts
Fixes #10545, #11708
The mutation payload source contained only the id of the now removed template dimension, which could not be loaded anymore.
> fix: remove poker template dimensions

- packages/server/graphql/public/typeDefs/User.graphql
- packages/server/graphql/public/types/User.ts
- packages/server/postgres/select.ts
fix #11663
Assume Page B is a child of Page A.
If Page A lives under a team & I'm not on the team, then Page A should appear in my shared pages.
If Page B is shared with me but not Page A, Page B should show up in shared pages.
> fix: shared pages include top-level accessible

- packages/client/modules/pages/Page.tsx
- packages/client/modules/pages/StarterActions.tsx
- packages/client/shared/tiptap/extensions/InsightsBlockBase.ts
- packages/client/styles/theme/global.css
- packages/client/tiptap/isCustomNodeSelected.ts
fix #11614 adds an "add insights" button to empty documents.
This PR should make it real obvious why we added pages!
> feat: add starter actions for adding insights

- .env.example
- packages/server/graphql/private/mutations/dumpHeap.ts
Allows to set a custom folder where heap dumps are stored, so we can use some more persistent storage that is not cleared if the pod is restarted like the /tmp is.
Tested through an [on-demand-environment](https://gitlab.com/parabol1/gcp-parabol-development/kubernetes-parabol-saas-development/on-demand-environments/-/merge_requests/14)
> chore(heap-dump): allow customizing the folder where the heap dumps are stored

- packages/client/modules/email/components/PageSharedInvite.tsx
- packages/client/modules/pages/PageNoAccess.tsx
- packages/client/utils/makeAppURL.ts
- packages/server/email/pageSharedEmailCreator.tsx
- packages/server/graphql/public/mutations/updatePageAccess.ts
Fixes #11316
For now we only send emails to external users if they gain access to a page.
For existing users we'll do notifications first until we have the notification setting to disable emails for page sharing.
> feat: send page invites to externals via email

- packages/server/graphql/nestedSchema/nestLinearEndpoint.ts
- packages/server/server.ts
We know the memory leak is undici fetch-related. linear was the only piece of our code using the native undici fetch, so my assumption is that a dependency is using undici fetch, for example, the `FetchTransport` in amplitude.
monkeypatching a global like fetch doesn't feel great, but I'd like to try it for a bit just to see if this fixes it.
Wanna get @Dschoordsch's opinion on this before doing it though
> fix: use watwg-node/fetch for everything on server

- packages/server/graphql/public/mutations/archivePage.ts
Make sure the ancestorIds array is inline with parentPageId
> fix: when restoring child without parent, remove parent from ancestorIds

- package.json
- pnpm-workspace.yaml
we've seen a lot of npm packages get taken over recently. we've been lucky that it hasn't affected us.
pnpm has a clever mitigation for this. since most malicious packages are identified within a few hours, you can tell it to ignore downloading packages that are less than x hours old. https://pnpm.io/settings#minimumreleaseage
I've set the minimum to 2 days & ignored a package that we control as a starting point. This should let us all sleep better
> fix: dont download packages newer than 2 days old by default

- packages/embedder/WorkflowOrchestrator.ts
- packages/server/dataloader/DataLoaderCache.ts
- packages/server/dataloader/__tests__/activeOrganizationUsersCustomLoader.test.ts
- packages/server/dataloader/__tests__/isCompanyDomain.test.ts
- packages/server/dataloader/__tests__/usersCustomRedisQueries.test.ts
- packages/server/dataloader/getNewDataLoader.ts
- packages/server/dataloader/hydrateDataLoader.ts
- packages/server/graphql/getDataLoader.ts
- packages/server/graphql/public/mutations/helpers/__tests__/getIsEmailApprovedByOrg.test.ts
- packages/server/graphql/public/mutations/helpers/movePageToNewParent.ts
- packages/server/hocusPocus.ts
- packages/server/integrations/mattermost/mattermostWebhookHandler.ts
- packages/server/utils/callGQL.ts
- packages/server/utils/tiptap/createChildPage.ts
- packages/server/utils/useDisposeDataloader.ts
- packages/server/wsHandler.ts
Relates to: #11684 
In heap dumps we see that we're retaining dataloaders in the cache which we don't clean up properly. Let's add a field to see who doesn't clean up after themselves.
- Step 1
- Step 2...
- Step 1
- Step 2....
> chore: add dataloader cache debugging field

- .env.example
- packages/server/utils/useAuditLogs.ts
- packages/server/utils/useSOC2AuditLogs.ts
- packages/server/yoga.ts
fix #11555
This PR logs to stdout all the included operations and their sanitized variables.
It'll look like this:
```ts
{
time: '2025-09-15T23:36:08.523Z',
level: 'info',
type: 'audit',
userId: 'google-oauth2|HrMru7cVgI',
ipAddress: '0000:0000:0000:0000:0000:0000:0000:0001',
operation: 'setOrgUserRole',
variables: { orgId: 'HrMruc26tO', userId: 'local|HuUCEsQe4M', role: null }
}
```
Do we want to replace variables with a human-readable message? eh, that seems like a lot of work for little return.
> feat: add audit logs

- packages/client/serviceWorker/sw.ts
- template.html
Relates to #11889
Main objective is to handle the error when Safari decided to close the Service Worker and thus fail all future fetches.
- Step 1
- Step 2...
- Step 1
- Step 2....
> fix: add error handling on initial script load

- packages/client/components/DashNavList/LeftNavPageLink.tsx
- packages/client/components/DashNavList/LeftNavPrivatePagesSection.tsx
- packages/client/components/DashNavList/LeftNavSharedPagesSection.tsx
- packages/client/components/DashNavList/LeftNavTeamLink.tsx
- packages/client/components/DashNavList/LeftNavTeamsSection.tsx
- packages/client/components/DashNavList/PageActions.tsx
- packages/client/components/DashNavList/SubPages.tsx
- packages/client/components/DashNavList/SubPagesRoot.tsx
- packages/client/hooks/useDraggablePage.tsx
- packages/client/schemaExtensions/clientSchema.graphql
- packages/client/tiptap/extensions/pageLinkBlock/PageLinkBlockView.tsx
- packages/server/dataloader/pageLoaderMakers.ts
- packages/server/graphql/mutations/helpers/dumpTranscriptToPage.ts
- packages/server/graphql/public/mutations/helpers/movePageToNewParent.ts
- packages/server/graphql/public/mutations/helpers/movePageToNewTeam.ts
- packages/server/graphql/public/mutations/updatePageAccess.ts
- packages/server/postgres/updatePageAccessTable.ts
- packages/server/utils/tiptap/afterLoadDocument.ts
- packages/server/utils/tiptap/createChildPage.ts
- packages/server/utils/tiptap/createTopLevelPage.ts
- packages/server/utils/tiptap/movePageToNewParent.ts
fixes #12038
column order is important, even when using aliases 😞 
to reproduce:
- User 1 is editor of parent page, User 2 is owner of parent page
- User 1 is editor of page 2, User 2 is owner of page 2
- User 1 drags page 2 to be a child of parent page, it works & User 1 is now owner of that page. 
uncovered 2 more bugs from this:
- you should only be able to change a page's parent if you OWN the child document. if you 're just an editor, you cannot move it to a parent that you have full access to, thus giving you full access. If you are an editor, you can only move pages around in the same parent.
- there should always be an owner of a document. decreasing your role from owner to editor if no one else exists should be disallowed
> fix: sql query column ordering

- packages/client/modules/pages/Page.tsx
starter actions should not be available for viewers
> fix: add insights for editors only

- biome.jsonc
- packages/client/tiptap/providerManager.ts
- packages/client/types/modules.d.ts
- packages/client/utils/createWSClient.ts
- packages/mattermost-plugin/types/modules.d.ts
- packages/server/types/modules.d.ts
- scripts/webpack/dev.client.config.js
Relates to #8364
Instead of having the graphql and hocuspocus websockets on different ports in dev, proxy those. This is closer to production. It is necessary because Safari does not treat localhost special with regards to cookies, meaning localhost:3000 and localhost:3001 appear as 2 different domains to it.
This came up during work on moving the auth token to a cookie. It would block local development on Safari otherwise.
[Please list all the testing scenarios a …
> chore: proxy websockets in local dev

- packages/server/graphql/public/types/User.ts
Fixes #12158 
Normally this would be a user input error, but it can happen naturally in insights when a page is shared with members outside of a team. We could either manually filter an check on the client, or simply allow the meeting query with 0 teams and just return an empty result. The latter seems cleaner and still correct to me.
* share a page with Peter
* add insights
* in edit mode add only teams Peter is not a member of
* Peter will see the error on that page
> fix: allow meeting queries with 0 own teams
